/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 --types --keepnames --keepgroups --keepmeshes --transform --instance --precision 6 public/models/realm-city_13.glb
*/

import * as THREE from 'three'
import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    archer_tower: THREE.Mesh
    barracks: THREE.Mesh
    mage_tower: THREE.Mesh
    castle: THREE.Mesh
    crops: THREE.Mesh
    ocean: THREE.Mesh
    rivers: THREE.Mesh
    ocean_small: THREE.Mesh
    forest: THREE.Mesh
    Cone001: THREE.Mesh
    Cone001_1: THREE.Mesh
    Cone001: THREE.Mesh
    Cone001_1: THREE.Mesh
    Plane007: THREE.Mesh
    Plane007_1: THREE.Mesh
    Plane007_2: THREE.Mesh
    Plane007_3: THREE.Mesh
    Plane007_4: THREE.Mesh
    Plane007_5: THREE.Mesh
    Plane007_6: THREE.Mesh
    tower: THREE.Mesh
    tower_1: THREE.Mesh
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
    Cube003_2: THREE.Mesh
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder002_1: THREE.Mesh
    Cylinder002_2: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    Cylinder003_2: THREE.Mesh
    Cylinder003_3: THREE.Mesh
    Plane004: THREE.Mesh
    Plane004_1: THREE.Mesh
    Cube025: THREE.Mesh
    Cube008: THREE.Mesh
    Cube008_1: THREE.Mesh
    Cube006: THREE.Mesh
    Cube006_1: THREE.Mesh
    Cube006_2: THREE.Mesh
    Cube007: THREE.Mesh
    Cube007_1: THREE.Mesh
    Cube009: THREE.Mesh
    Cube009_1: THREE.Mesh
    Cube009_2: THREE.Mesh
    Cube013: THREE.Mesh
    Cube014: THREE.Mesh
    Cube010: THREE.Mesh
    Cone004: THREE.Mesh
    Cone004_1: THREE.Mesh
    Cube012: THREE.Mesh
    Cube019: THREE.Mesh
    Cube019_1: THREE.Mesh
    Cube019_2: THREE.Mesh
    Cube020: THREE.Mesh
    Cube020_1: THREE.Mesh
    Cube020_2: THREE.Mesh
    Cube022: THREE.Mesh
    Cube022_1: THREE.Mesh
    Cube022_2: THREE.Mesh
    Cube023: THREE.Mesh
    Cube023_1: THREE.Mesh
    Cube024: THREE.Mesh
    Cube024_1: THREE.Mesh
    Cube017: THREE.Mesh
    Cube017_1: THREE.Mesh
    Cube018: THREE.Mesh
    Cube001: THREE.Mesh
    Cube001_1: THREE.Mesh
    mine: THREE.Mesh
    mine_1: THREE.Mesh
    mine_2: THREE.Mesh
    Cone006: THREE.Mesh
    Cone007: THREE.Mesh
    Cone007_1: THREE.Mesh
    ['mine-smoke']: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cone002: THREE.Mesh
    Cone002_1: THREE.Mesh
    Cone: THREE.Mesh
    Cone_1: THREE.Mesh
    Cube002: THREE.Mesh
    Cube002_1: THREE.Mesh
  }
  materials: {
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial013: THREE.MeshStandardMaterial
    PaletteMaterial015: THREE.MeshPhysicalMaterial
    PaletteMaterial016: THREE.MeshStandardMaterial
    PaletteMaterial018: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    PaletteMaterial017: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    PaletteMaterial019: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshStandardMaterial
    PaletteMaterial008: THREE.MeshStandardMaterial
    PaletteMaterial009: THREE.MeshStandardMaterial
    PaletteMaterial010: THREE.MeshStandardMaterial
    PaletteMaterial011: THREE.MeshStandardMaterial
    PaletteMaterial012: THREE.MeshStandardMaterial
    PaletteMaterial014: THREE.MeshPhysicalMaterial
  }
}

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/realm-city_13-transformed.glb') as GLTFResult
  const instances = useMemo(
    () => ({
      Cone: nodes.Cone001,
      Cone1: nodes.Cone001_1,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context)
  const { nodes, materials } = useGLTF('/realm-city_13-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="archer_tower" geometry={nodes.archer_tower.geometry} material={materials.PaletteMaterial004} position={[-62.469486, 39.621521, -24.215282]} rotation={[0.011296, 0.828387, -0.004794]} scale={[35.000004, 35, 35]} />
        <mesh name="barracks" geometry={nodes.barracks.geometry} material={materials.PaletteMaterial004} />
        <mesh name="mage_tower" geometry={nodes.mage_tower.geometry} material={materials.PaletteMaterial004} position={[-8.498649, 27.847218, -229.488235]} scale={31.884161} />
        <mesh name="castle" geometry={nodes.castle.geometry} material={materials.PaletteMaterial004} position={[-25.330475, 32.69627, -113.067566]} />
        <mesh name="crops" geometry={nodes.crops.geometry} material={materials.PaletteMaterial013} position={[-209.282944, 0, -42.59145]} />
        <mesh name="ocean" geometry={nodes.ocean.geometry} material={materials.PaletteMaterial015} scale={[100, 1, 100]} />
        <mesh name="rivers" geometry={nodes.rivers.geometry} material={materials.PaletteMaterial016} position={[2.455429, 1.826893, -3.053192]} scale={35} />
        <mesh name="ocean_small" geometry={nodes.ocean_small.geometry} material={materials.PaletteMaterial015} scale={[1, 0.01, 1]} />
        <mesh name="forest" geometry={nodes.forest.geometry} material={materials.PaletteMaterial018} />
        <group name="deciduous-tree189" position={[494.866547, 4.604025, 284.570831]} rotation={[0, -0.79251, 0]} scale={[0.602762, 0.776755, 0.602762]}>
          <instances.Cone name="Cone001" />
          <instances.Cone1 name="Cone001_1" />
        </group>
        <group name="deciduous-tree190" position={[497.886841, 4.604025, 285.281494]} rotation={[Math.PI, -1.275876, Math.PI]} scale={[0.602762, 0.776755, 0.602762]}>
          <instances.Cone name="Cone001" />
          <instances.Cone1 name="Cone001_1" />
        </group>
        <group name="terrain" position={[0, -0.002192, 0]}>
          <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials.PaletteMaterial017} />
          <mesh name="Plane007_1" geometry={nodes.Plane007_1.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Plane007_2" geometry={nodes.Plane007_2.geometry} material={materials.PaletteMaterial019} />
          <mesh name="Plane007_3" geometry={nodes.Plane007_3.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane007_4" geometry={nodes.Plane007_4.geometry} material={materials.PaletteMaterial003} />
          <mesh name="Plane007_5" geometry={nodes.Plane007_5.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane007_6" geometry={nodes.Plane007_6.geometry} material={materials.PaletteMaterial004} />
        </group>
        <group>
          <instancedMesh args={[nodes.tower.geometry, materials.PaletteMaterial001, 27]} name="tower" instanceMatrix={nodes.tower.instanceMatrix} />
          <instancedMesh args={[nodes.tower_1.geometry, materials.PaletteMaterial002, 27]} name="tower_1" instanceMatrix={nodes.tower_1.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.Cube003.geometry, materials.PaletteMaterial001, 134]} name="Cube003" instanceMatrix={nodes.Cube003.instanceMatrix} />
          <instancedMesh args={[nodes.Cube003_1.geometry, materials.PaletteMaterial002, 134]} name="Cube003_1" instanceMatrix={nodes.Cube003_1.instanceMatrix} />
          <instancedMesh args={[nodes.Cube003_2.geometry, materials.PaletteMaterial003, 134]} name="Cube003_2" instanceMatrix={nodes.Cube003_2.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.Cube005.geometry, materials.PaletteMaterial004, 6]} name="Cube005" instanceMatrix={nodes.Cube005.instanceMatrix} />
          <instancedMesh args={[nodes.Cube005_1.geometry, materials.PaletteMaterial005, 6]} name="Cube005_1" instanceMatrix={nodes.Cube005_1.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.Cylinder002.geometry, materials.PaletteMaterial006, 50]} name="Cylinder002" instanceMatrix={nodes.Cylinder002.instanceMatrix} />
          <instancedMesh args={[nodes.Cylinder002_1.geometry, materials.PaletteMaterial007, 50]} name="Cylinder002_1" instanceMatrix={nodes.Cylinder002_1.instanceMatrix} />
          <instancedMesh args={[nodes.Cylinder002_2.geometry, materials.PaletteMaterial002, 50]} name="Cylinder002_2" instanceMatrix={nodes.Cylinder002_2.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.Cylinder003.geometry, materials.PaletteMaterial002, 6]} name="Cylinder003" instanceMatrix={nodes.Cylinder003.instanceMatrix} />
          <instancedMesh args={[nodes.Cylinder003_1.geometry, materials.PaletteMaterial008, 6]} name="Cylinder003_1" instanceMatrix={nodes.Cylinder003_1.instanceMatrix} />
          <instancedMesh args={[nodes.Cylinder003_2.geometry, materials.PaletteMaterial009, 6]} name="Cylinder003_2" instanceMatrix={nodes.Cylinder003_2.instanceMatrix} />
          <instancedMesh args={[nodes.Cylinder003_3.geometry, materials.PaletteMaterial006, 6]} name="Cylinder003_3" instanceMatrix={nodes.Cylinder003_3.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.Plane004.geometry, materials.PaletteMaterial001, 9]} name="Plane004" instanceMatrix={nodes.Plane004.instanceMatrix} />
          <instancedMesh args={[nodes.Plane004_1.geometry, materials.PaletteMaterial006, 9]} name="Plane004_1" instanceMatrix={nodes.Plane004_1.instanceMatrix} />
        </group>
        <instancedMesh args={[nodes.Cube025.geometry, materials.PaletteMaterial007, 10]} name="Cube025" instanceMatrix={nodes.Cube025.instanceMatrix} />
        <group>
          <instancedMesh args={[nodes.Cube008.geometry, materials.PaletteMaterial006, 96]} name="Cube008" instanceMatrix={nodes.Cube008.instanceMatrix} />
          <instancedMesh args={[nodes.Cube008_1.geometry, materials.PaletteMaterial001, 96]} name="Cube008_1" instanceMatrix={nodes.Cube008_1.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.Cube006.geometry, materials.PaletteMaterial009, 21]} name="Cube006" instanceMatrix={nodes.Cube006.instanceMatrix} />
          <instancedMesh args={[nodes.Cube006_1.geometry, materials.PaletteMaterial010, 21]} name="Cube006_1" instanceMatrix={nodes.Cube006_1.instanceMatrix} />
          <instancedMesh args={[nodes.Cube006_2.geometry, materials.PaletteMaterial006, 21]} name="Cube006_2" instanceMatrix={nodes.Cube006_2.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.Cube007.geometry, materials.PaletteMaterial009, 25]} name="Cube007" instanceMatrix={nodes.Cube007.instanceMatrix} />
          <instancedMesh args={[nodes.Cube007_1.geometry, materials.PaletteMaterial006, 25]} name="Cube007_1" instanceMatrix={nodes.Cube007_1.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.Cube009.geometry, materials.PaletteMaterial009, 11]} name="Cube009" instanceMatrix={nodes.Cube009.instanceMatrix} />
          <instancedMesh args={[nodes.Cube009_1.geometry, materials.PaletteMaterial006, 11]} name="Cube009_1" instanceMatrix={nodes.Cube009_1.instanceMatrix} />
          <instancedMesh args={[nodes.Cube009_2.geometry, materials.PaletteMaterial010, 11]} name="Cube009_2" instanceMatrix={nodes.Cube009_2.instanceMatrix} />
        </group>
        <instancedMesh args={[nodes.Cube013.geometry, materials.PaletteMaterial006, 22]} name="Cube013" instanceMatrix={nodes.Cube013.instanceMatrix} />
        <instancedMesh args={[nodes.Cube014.geometry, materials.PaletteMaterial006, 36]} name="Cube014" instanceMatrix={nodes.Cube014.instanceMatrix} />
        <instancedMesh args={[nodes.Cube010.geometry, materials.PaletteMaterial006, 700]} name="Cube010" instanceMatrix={nodes.Cube010.instanceMatrix} />
        <group>
          <instancedMesh args={[nodes.Cone004.geometry, materials.PaletteMaterial011, 37]} name="Cone004" instanceMatrix={nodes.Cone004.instanceMatrix} />
          <instancedMesh args={[nodes.Cone004_1.geometry, materials.PaletteMaterial012, 37]} name="Cone004_1" instanceMatrix={nodes.Cone004_1.instanceMatrix} />
        </group>
        <instancedMesh args={[nodes.Cube012.geometry, materials.PaletteMaterial013, 54]} name="Cube012" instanceMatrix={nodes.Cube012.instanceMatrix} />
        <group>
          <instancedMesh args={[nodes.Cube019.geometry, materials.PaletteMaterial009, 44]} name="Cube019" instanceMatrix={nodes.Cube019.instanceMatrix} />
          <instancedMesh args={[nodes.Cube019_1.geometry, materials.PaletteMaterial010, 44]} name="Cube019_1" instanceMatrix={nodes.Cube019_1.instanceMatrix} />
          <instancedMesh args={[nodes.Cube019_2.geometry, materials.PaletteMaterial006, 44]} name="Cube019_2" instanceMatrix={nodes.Cube019_2.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.Cube020.geometry, materials.PaletteMaterial009, 14]} name="Cube020" instanceMatrix={nodes.Cube020.instanceMatrix} />
          <instancedMesh args={[nodes.Cube020_1.geometry, materials.PaletteMaterial010, 14]} name="Cube020_1" instanceMatrix={nodes.Cube020_1.instanceMatrix} />
          <instancedMesh args={[nodes.Cube020_2.geometry, materials.PaletteMaterial006, 14]} name="Cube020_2" instanceMatrix={nodes.Cube020_2.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.Cube022.geometry, materials.PaletteMaterial009, 10]} name="Cube022" instanceMatrix={nodes.Cube022.instanceMatrix} />
          <instancedMesh args={[nodes.Cube022_1.geometry, materials.PaletteMaterial010, 10]} name="Cube022_1" instanceMatrix={nodes.Cube022_1.instanceMatrix} />
          <instancedMesh args={[nodes.Cube022_2.geometry, materials.PaletteMaterial006, 10]} name="Cube022_2" instanceMatrix={nodes.Cube022_2.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.Cube023.geometry, materials.PaletteMaterial009, 22]} name="Cube023" instanceMatrix={nodes.Cube023.instanceMatrix} />
          <instancedMesh args={[nodes.Cube023_1.geometry, materials.PaletteMaterial010, 22]} name="Cube023_1" instanceMatrix={nodes.Cube023_1.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.Cube024.geometry, materials.PaletteMaterial009, 44]} name="Cube024" instanceMatrix={nodes.Cube024.instanceMatrix} />
          <instancedMesh args={[nodes.Cube024_1.geometry, materials.PaletteMaterial006, 44]} name="Cube024_1" instanceMatrix={nodes.Cube024_1.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.Cube017.geometry, materials.PaletteMaterial006, 17]} name="Cube017" instanceMatrix={nodes.Cube017.instanceMatrix} />
          <instancedMesh args={[nodes.Cube017_1.geometry, materials.PaletteMaterial002, 17]} name="Cube017_1" instanceMatrix={nodes.Cube017_1.instanceMatrix} />
        </group>
        <instancedMesh args={[nodes.Cube018.geometry, materials.PaletteMaterial006, 22]} name="Cube018" instanceMatrix={nodes.Cube018.instanceMatrix} />
        <group>
          <instancedMesh args={[nodes.Cube001.geometry, materials.PaletteMaterial006, 27]} name="Cube001" instanceMatrix={nodes.Cube001.instanceMatrix} />
          <instancedMesh args={[nodes.Cube001_1.geometry, materials.PaletteMaterial001, 27]} name="Cube001_1" instanceMatrix={nodes.Cube001_1.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.mine.geometry, materials.PaletteMaterial004, 7]} name="mine" instanceMatrix={nodes.mine.instanceMatrix} />
          <instancedMesh args={[nodes.mine_1.geometry, materials.PaletteMaterial005, 7]} name="mine_1" instanceMatrix={nodes.mine_1.instanceMatrix} />
          <instancedMesh args={[nodes.mine_2.geometry, materials.PaletteMaterial006, 7]} name="mine_2" instanceMatrix={nodes.mine_2.instanceMatrix} />
        </group>
        <instancedMesh args={[nodes.Cone006.geometry, materials.PaletteMaterial004, 15]} name="Cone006" instanceMatrix={nodes.Cone006.instanceMatrix} />
        <group>
          <instancedMesh args={[nodes.Cone007.geometry, materials.PaletteMaterial009, 18]} name="Cone007" instanceMatrix={nodes.Cone007.instanceMatrix} />
          <instancedMesh args={[nodes.Cone007_1.geometry, materials.PaletteMaterial006, 18]} name="Cone007_1" instanceMatrix={nodes.Cone007_1.instanceMatrix} />
        </group>
        <instancedMesh args={[nodes['mine-smoke'].geometry, materials.PaletteMaterial014, 18]} name="mine-smoke" instanceMatrix={nodes['mine-smoke'].instanceMatrix} />
        <instancedMesh args={[nodes.Cylinder001.geometry, materials.PaletteMaterial017, 35]} name="Cylinder001" instanceMatrix={nodes.Cylinder001.instanceMatrix} />
        <group>
          <instancedMesh args={[nodes.Cone002.geometry, materials.PaletteMaterial018, 265]} name="Cone002" instanceMatrix={nodes.Cone002.instanceMatrix} />
          <instances.Cone1 name="Cone002_1" />
        </group>
        <group>
          <instancedMesh args={[nodes.Cone.geometry, materials.PaletteMaterial001, 81]} name="Cone" instanceMatrix={nodes.Cone.instanceMatrix} />
          <instancedMesh args={[nodes.Cone_1.geometry, materials.PaletteMaterial006, 81]} name="Cone_1" instanceMatrix={nodes.Cone_1.instanceMatrix} />
        </group>
        <group>
          <instancedMesh args={[nodes.Cube002.geometry, materials.PaletteMaterial004, 181]} name="Cube002" instanceMatrix={nodes.Cube002.instanceMatrix} />
          <instancedMesh args={[nodes.Cube002_1.geometry, materials.PaletteMaterial019, 181]} name="Cube002_1" instanceMatrix={nodes.Cube002_1.instanceMatrix} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/realm-city_13-transformed.glb')
