/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./client/public/models/bank2.glb 
Author: Tunca.Erkal (https://sketchfab.com/Tunca.Erkal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-house-c959349f23f04998b8d9687a4a2c6b50
Title: Medieval House
*/

import { useGetBanks } from "@/hooks/helpers/useBanks";
import { getUIPositionFromColRow, pseudoRandom } from "@/ui/utils/utils";
import { useGLTF } from "@react-three/drei";
import { useMemo } from "react";

export const Banks = () => {
  const banks = useGetBanks();

  return (
    <group>
      {banks.map((bank, index) => {
        const { x, y } = getUIPositionFromColRow(bank.position.x, bank.position.y, false);
        return <BankModel key={index} position={[x, 0.31, -y]} />;
      })}
    </group>
  );
};

export const BankModel = ({ position }: { position: any }) => {
  const bankModel = useGLTF("/models/buildings/castle.glb");
  const clone = useMemo(() => {
    const clone = bankModel.scene.clone();
    return clone;
  }, [bankModel]);

  return <primitive scale={3} object={clone} position={position} />;
};
