/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./client/public/models/bank.glb 
Author: Sergi Trojanski (https://sketchfab.com/nathramn)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-town-hall-2a1c649f403d435b96cffd58662660eb
Title: Low Poly Town Hall
*/

import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: {
      geometry: THREE.BufferGeometry;
      material: THREE.Material;
    };
    Object_3: {
      geometry: THREE.BufferGeometry;
      material: THREE.Material;
    };
    Object_4: {
      geometry: THREE.BufferGeometry;
      material: THREE.Material;
    };
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

export default function Bank1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("models/bank1.glb") as unknown as GLTFResult;
  return (
    <group scale={0.1} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-3.847, -4.71, 0]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.Material} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.Material} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/bank1.glb");
