import type { ConfigPatch } from "../common/merge-config";

const VICTORY_POINTS_MULTIPLIER = 1_000_000;
const VICTORY_POINTS_FOR_WIN = 0n * BigInt(VICTORY_POINTS_MULTIPLIER);
const AWARDED_POINTS_FOR_HYPERSTRUCTURE_HODL_PER_SECOND = 1n * BigInt(VICTORY_POINTS_MULTIPLIER);
const AWARDED_POINTS_FOR_RELIC_CHEST_OPEN = 1_000n * BigInt(VICTORY_POINTS_MULTIPLIER);
const AWARDED_POINTS_FOR_TILE_EXPLORATION = 10n * BigInt(VICTORY_POINTS_MULTIPLIER);
const AWARDED_POINTS_FOR_NON_HYPERSTRUCTURE_CLAIM_AGAINST_BANDITS = 500n * BigInt(VICTORY_POINTS_MULTIPLIER);
const AWARDED_POINTS_FOR_HYPERSTRUCTURE_CLAIM_AGAINST_BANDITS = 3_000n * BigInt(VICTORY_POINTS_MULTIPLIER);

export const blitzVictoryPointConfig: ConfigPatch = {
  victoryPoints: {
    pointsForWin: VICTORY_POINTS_FOR_WIN,
    hyperstructurePointsPerCycle: AWARDED_POINTS_FOR_HYPERSTRUCTURE_HODL_PER_SECOND,
    pointsForHyperstructureClaimAgainstBandits: AWARDED_POINTS_FOR_HYPERSTRUCTURE_CLAIM_AGAINST_BANDITS,
    pointsForNonHyperstructureClaimAgainstBandits: AWARDED_POINTS_FOR_NON_HYPERSTRUCTURE_CLAIM_AGAINST_BANDITS,
    pointsForTileExploration: AWARDED_POINTS_FOR_TILE_EXPLORATION,
    pointsForRelicDiscovery: AWARDED_POINTS_FOR_RELIC_CHEST_OPEN,
  },
};
