// Generated by scripts/settlement/generate-schema-vectors.mjs. Do not edit directly.
use settlement_protocol::economic_interfaces::IEconomicStateSystemDispatcher;
use settlement_protocol::interfaces::{
    IAutoIdMintWithReceiptDispatcher, IChestMetadataCompatibilityDispatcher,
    ICosmeticCollectiblesClaimCompatibilityDispatcher, ICosmeticMintCompatibilityDispatcher,
    ICosmeticOutputLivenessDispatcher, IGameEconomicSettlementCallbacksDispatcher, IGameForcedExitAdapterDispatcher,
    IGameIngressAdapterDispatcher, IHardenedInboxRuntimeDispatcher, ILegacyMmrArchiveQuorumDispatcher,
    ILegacyMmrConfigSystemMigrationDispatcher, ILegacyMmrCutoverFundingDispatcher, ILegacyMmrCutoverGateDispatcher,
    ILegacyMmrFactoryMigrationDispatcher, ILegacyMmrMigrationGuardDispatcher, ILegacyMmrPendingResultSourceDispatcher,
    ILegacyMmrSystemMigrationDispatcher, ILegacyMmrWorldMigrationDispatcher, IMMRSettlementModuleDispatcher,
    IMMRSettlementRouterDispatcher, IMMRSettlementTokenDispatcher, ISealedGameFactoryDispatcher,
    ISealedWorldPolicyDispatcher, ISeasonResourceSettlementTokenDispatcher, IStarknetFinalizedStateRootSourceDispatcher,
};
use starknet::ContractAddress;

pub const PROTOCOL_DISPATCHER_COUNT: u16 = 26;

pub fn protocol_dispatcher_addresses(address: ContractAddress) -> Array<ContractAddress> {
    array![
        ISeasonResourceSettlementTokenDispatcher { contract_address: address }.contract_address,
        IAutoIdMintWithReceiptDispatcher { contract_address: address }.contract_address,
        ICosmeticCollectiblesClaimCompatibilityDispatcher { contract_address: address }.contract_address,
        IChestMetadataCompatibilityDispatcher { contract_address: address }.contract_address,
        ICosmeticMintCompatibilityDispatcher { contract_address: address }.contract_address,
        ICosmeticOutputLivenessDispatcher { contract_address: address }.contract_address,
        ILegacyMmrPendingResultSourceDispatcher { contract_address: address }.contract_address,
        ILegacyMmrWorldMigrationDispatcher { contract_address: address }.contract_address,
        ILegacyMmrSystemMigrationDispatcher { contract_address: address }.contract_address,
        ILegacyMmrFactoryMigrationDispatcher { contract_address: address }.contract_address,
        ILegacyMmrConfigSystemMigrationDispatcher { contract_address: address }.contract_address,
        ILegacyMmrMigrationGuardDispatcher { contract_address: address }.contract_address,
        IStarknetFinalizedStateRootSourceDispatcher { contract_address: address }.contract_address,
        ILegacyMmrCutoverGateDispatcher { contract_address: address }.contract_address,
        ILegacyMmrArchiveQuorumDispatcher { contract_address: address }.contract_address,
        ILegacyMmrCutoverFundingDispatcher { contract_address: address }.contract_address,
        IMMRSettlementTokenDispatcher { contract_address: address }.contract_address,
        IMMRSettlementRouterDispatcher { contract_address: address }.contract_address,
        IMMRSettlementModuleDispatcher { contract_address: address }.contract_address,
        ISealedGameFactoryDispatcher { contract_address: address }.contract_address,
        ISealedWorldPolicyDispatcher { contract_address: address }.contract_address,
        IHardenedInboxRuntimeDispatcher { contract_address: address }.contract_address,
        IGameIngressAdapterDispatcher { contract_address: address }.contract_address,
        IGameEconomicSettlementCallbacksDispatcher { contract_address: address }.contract_address,
        IGameForcedExitAdapterDispatcher { contract_address: address }.contract_address,
        IEconomicStateSystemDispatcher { contract_address: address }.contract_address,
    ]
}
