/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PassesLazyImport = createFileRoute('/passes')()
const BridgeLazyImport = createFileRoute('/bridge')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PassesLazyRoute = PassesLazyImport.update({
  id: '/passes',
  path: '/passes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/passes.lazy').then((d) => d.Route))

const BridgeLazyRoute = BridgeLazyImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bridge.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeLazyImport
      parentRoute: typeof rootRoute
    }
    '/passes': {
      id: '/passes'
      path: '/passes'
      fullPath: '/passes'
      preLoaderRoute: typeof PassesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/bridge': typeof BridgeLazyRoute
  '/passes': typeof PassesLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/bridge': typeof BridgeLazyRoute
  '/passes': typeof PassesLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/bridge': typeof BridgeLazyRoute
  '/passes': typeof PassesLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bridge' | '/passes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bridge' | '/passes'
  id: '__root__' | '/' | '/bridge' | '/passes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BridgeLazyRoute: typeof BridgeLazyRoute
  PassesLazyRoute: typeof PassesLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BridgeLazyRoute: BridgeLazyRoute,
  PassesLazyRoute: PassesLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bridge",
        "/passes"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/bridge": {
      "filePath": "bridge.lazy.tsx"
    },
    "/passes": {
      "filePath": "passes.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
