# db_dir = "./torii-db"

rpc = "https://api.cartridge.gg/x/starknet/mainnet"

[indexing]

events_chunk_size = 1024 # Size of events page to fetch
blocks_chunk_size = 1024 # Blocks to process before DB commit
pending = true # Enable indexing pending blocks
polling_interval = 500 # Polling interval in milliseconds
max_concurrent_tasks = 100 # Maximum concurrent indexing tasks
world_block = 940000
contracts = [
]

[events]
raw = true
historical = ["s0_eternum-TrophyCreation", "s0_eternum-TrophyProgression"]
