import { BuildingType, getProducedResource, ResourcesIds, type ResourceInputs } from "@bibliothecadao/types";

export const BUILDING_CAPACITY: { [key in BuildingType]: number } = {
  [BuildingType.None]: 0,
  [BuildingType.WorkersHut]: 5,
  [BuildingType.Storehouse]: 0,
  [BuildingType.ResourceStone]: 0,
  [BuildingType.ResourceCoal]: 0,
  [BuildingType.ResourceWood]: 0,
  [BuildingType.ResourceCopper]: 0,
  [BuildingType.ResourceIronwood]: 0,
  [BuildingType.ResourceObsidian]: 0,
  [BuildingType.ResourceGold]: 0,
  [BuildingType.ResourceSilver]: 0,
  [BuildingType.ResourceMithral]: 0,
  [BuildingType.ResourceAlchemicalSilver]: 0,
  [BuildingType.ResourceColdIron]: 0,
  [BuildingType.ResourceDeepCrystal]: 0,
  [BuildingType.ResourceRuby]: 0,
  [BuildingType.ResourceDiamonds]: 0,
  [BuildingType.ResourceHartwood]: 0,
  [BuildingType.ResourceIgnium]: 0,
  [BuildingType.ResourceTwilightQuartz]: 0,
  [BuildingType.ResourceTrueIce]: 0,
  [BuildingType.ResourceAdamantine]: 0,
  [BuildingType.ResourceSapphire]: 0,
  [BuildingType.ResourceEtherealSilica]: 0,
  [BuildingType.ResourceDragonhide]: 0,
  [BuildingType.ResourceLabor]: 0,
  [BuildingType.ResourceAncientFragment]: 0,
  [BuildingType.ResourceDonkey]: 0,
  [BuildingType.ResourceKnightT1]: 0,
  [BuildingType.ResourceKnightT2]: 0,
  [BuildingType.ResourceKnightT3]: 0,
  [BuildingType.ResourceCrossbowmanT1]: 0,
  [BuildingType.ResourceCrossbowmanT2]: 0,
  [BuildingType.ResourceCrossbowmanT3]: 0,
  [BuildingType.ResourcePaladinT1]: 0,
  [BuildingType.ResourcePaladinT2]: 0,
  [BuildingType.ResourcePaladinT3]: 0,
  [BuildingType.ResourceWheat]: 0,
  [BuildingType.ResourceFish]: 0,
};

export const BUILDING_POPULATION: { [key in BuildingType]: number } = {
  [BuildingType.None]: 0,
  [BuildingType.WorkersHut]: 0,
  [BuildingType.Storehouse]: 2,
  [BuildingType.ResourceStone]: 2,
  [BuildingType.ResourceCoal]: 2,
  [BuildingType.ResourceWood]: 2,
  [BuildingType.ResourceCopper]: 2,
  [BuildingType.ResourceIronwood]: 2,
  [BuildingType.ResourceObsidian]: 2,
  [BuildingType.ResourceGold]: 2,
  [BuildingType.ResourceSilver]: 2,
  [BuildingType.ResourceMithral]: 2,
  [BuildingType.ResourceAlchemicalSilver]: 2,
  [BuildingType.ResourceColdIron]: 2,
  [BuildingType.ResourceDeepCrystal]: 2,
  [BuildingType.ResourceRuby]: 2,
  [BuildingType.ResourceDiamonds]: 2,
  [BuildingType.ResourceHartwood]: 2,
  [BuildingType.ResourceIgnium]: 2,
  [BuildingType.ResourceTwilightQuartz]: 2,
  [BuildingType.ResourceTrueIce]: 2,
  [BuildingType.ResourceAdamantine]: 2,
  [BuildingType.ResourceSapphire]: 2,
  [BuildingType.ResourceEtherealSilica]: 2,
  [BuildingType.ResourceDragonhide]: 2,
  [BuildingType.ResourceLabor]: 0,
  [BuildingType.ResourceAncientFragment]: 2,
  [BuildingType.ResourceDonkey]: 3,
  [BuildingType.ResourceKnightT1]: 3,
  [BuildingType.ResourceKnightT2]: 3,
  [BuildingType.ResourceKnightT3]: 3,
  [BuildingType.ResourceCrossbowmanT1]: 3,
  [BuildingType.ResourceCrossbowmanT2]: 3,
  [BuildingType.ResourceCrossbowmanT3]: 3,
  [BuildingType.ResourcePaladinT1]: 3,
  [BuildingType.ResourcePaladinT2]: 3,
  [BuildingType.ResourcePaladinT3]: 3,
  [BuildingType.ResourceWheat]: 1,
  [BuildingType.ResourceFish]: 1,
};

export const BUILDING_RESOURCE_PRODUCED: { [key in BuildingType]: number } = {
  [BuildingType.None]: getProducedResource(BuildingType.None) ?? 0,
  [BuildingType.WorkersHut]: getProducedResource(BuildingType.WorkersHut) ?? 0,
  [BuildingType.Storehouse]: getProducedResource(BuildingType.Storehouse) ?? 0,
  [BuildingType.ResourceStone]: getProducedResource(BuildingType.ResourceStone) ?? 0,
  [BuildingType.ResourceCoal]: getProducedResource(BuildingType.ResourceCoal) ?? 0,
  [BuildingType.ResourceWood]: getProducedResource(BuildingType.ResourceWood) ?? 0,
  [BuildingType.ResourceCopper]: getProducedResource(BuildingType.ResourceCopper) ?? 0,
  [BuildingType.ResourceIronwood]: getProducedResource(BuildingType.ResourceIronwood) ?? 0,
  [BuildingType.ResourceObsidian]: getProducedResource(BuildingType.ResourceObsidian) ?? 0,
  [BuildingType.ResourceGold]: getProducedResource(BuildingType.ResourceGold) ?? 0,
  [BuildingType.ResourceSilver]: getProducedResource(BuildingType.ResourceSilver) ?? 0,
  [BuildingType.ResourceMithral]: getProducedResource(BuildingType.ResourceMithral) ?? 0,
  [BuildingType.ResourceAlchemicalSilver]: getProducedResource(BuildingType.ResourceAlchemicalSilver) ?? 0,
  [BuildingType.ResourceColdIron]: getProducedResource(BuildingType.ResourceColdIron) ?? 0,
  [BuildingType.ResourceDeepCrystal]: getProducedResource(BuildingType.ResourceDeepCrystal) ?? 0,
  [BuildingType.ResourceRuby]: getProducedResource(BuildingType.ResourceRuby) ?? 0,
  [BuildingType.ResourceDiamonds]: getProducedResource(BuildingType.ResourceDiamonds) ?? 0,
  [BuildingType.ResourceHartwood]: getProducedResource(BuildingType.ResourceHartwood) ?? 0,
  [BuildingType.ResourceIgnium]: getProducedResource(BuildingType.ResourceIgnium) ?? 0,
  [BuildingType.ResourceTwilightQuartz]: getProducedResource(BuildingType.ResourceTwilightQuartz) ?? 0,
  [BuildingType.ResourceTrueIce]: getProducedResource(BuildingType.ResourceTrueIce) ?? 0,
  [BuildingType.ResourceAdamantine]: getProducedResource(BuildingType.ResourceAdamantine) ?? 0,
  [BuildingType.ResourceSapphire]: getProducedResource(BuildingType.ResourceSapphire) ?? 0,
  [BuildingType.ResourceEtherealSilica]: getProducedResource(BuildingType.ResourceEtherealSilica) ?? 0,
  [BuildingType.ResourceDragonhide]: getProducedResource(BuildingType.ResourceDragonhide) ?? 0,
  [BuildingType.ResourceLabor]: getProducedResource(BuildingType.ResourceLabor) ?? 0,
  [BuildingType.ResourceAncientFragment]: getProducedResource(BuildingType.ResourceAncientFragment) ?? 0,
  [BuildingType.ResourceDonkey]: getProducedResource(BuildingType.ResourceDonkey) ?? 0,
  [BuildingType.ResourceKnightT1]: getProducedResource(BuildingType.ResourceKnightT1) ?? 0,
  [BuildingType.ResourceKnightT2]: getProducedResource(BuildingType.ResourceKnightT2) ?? 0,
  [BuildingType.ResourceKnightT3]: getProducedResource(BuildingType.ResourceKnightT3) ?? 0,
  [BuildingType.ResourceCrossbowmanT1]: getProducedResource(BuildingType.ResourceCrossbowmanT1) ?? 0,
  [BuildingType.ResourceCrossbowmanT2]: getProducedResource(BuildingType.ResourceCrossbowmanT2) ?? 0,
  [BuildingType.ResourceCrossbowmanT3]: getProducedResource(BuildingType.ResourceCrossbowmanT3) ?? 0,
  [BuildingType.ResourcePaladinT1]: getProducedResource(BuildingType.ResourcePaladinT1) ?? 0,
  [BuildingType.ResourcePaladinT2]: getProducedResource(BuildingType.ResourcePaladinT2) ?? 0,
  [BuildingType.ResourcePaladinT3]: getProducedResource(BuildingType.ResourcePaladinT3) ?? 0,
  [BuildingType.ResourceWheat]: getProducedResource(BuildingType.ResourceWheat) ?? 0,
  [BuildingType.ResourceFish]: getProducedResource(BuildingType.ResourceFish) ?? 0,
};

export const COMPLEX_BUILDING_COSTS: ResourceInputs = {
  [BuildingType.None]: [],
  [BuildingType.ResourceLabor]: [],
  [BuildingType.ResourceAncientFragment]: [],
  // Basic Buildings - primarily Common resources
  [BuildingType.ResourceWheat]: [{ resource: ResourcesIds.Fish, amount: 500_000 }],
  [BuildingType.ResourceFish]: [{ resource: ResourcesIds.Wheat, amount: 500_000 }],
  [BuildingType.ResourceWood]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceStone]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceCoal]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceCopper]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceObsidian]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceSilver]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceIronwood]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceColdIron]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceGold]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceHartwood]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceDiamonds]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceSapphire]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceRuby]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceDeepCrystal]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceIgnium]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceEtherealSilica]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceTrueIce]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceTwilightQuartz]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceAlchemicalSilver]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceAdamantine]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceMithral]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceDragonhide]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  // T1 Military Buildings - primarily Uncommon resources
  [BuildingType.ResourceKnightT1]: [
    { resource: ResourcesIds.Labor, amount: 75_000 },
    { resource: ResourcesIds.Stone, amount: 75_000 },
    { resource: ResourcesIds.Coal, amount: 75_000 },
    { resource: ResourcesIds.Copper, amount: 25_000 },
    { resource: ResourcesIds.Obsidian, amount: 50_000 },
    { resource: ResourcesIds.ColdIron, amount: 25_000 },
  ],
  [BuildingType.ResourceCrossbowmanT1]: [
    { resource: ResourcesIds.Labor, amount: 75_000 },
    { resource: ResourcesIds.Wood, amount: 75_000 },
    { resource: ResourcesIds.Coal, amount: 75_000 },
    { resource: ResourcesIds.Obsidian, amount: 25_000 },
    { resource: ResourcesIds.Silver, amount: 50_000 },
    { resource: ResourcesIds.Ironwood, amount: 25_000 },
  ],
  [BuildingType.ResourcePaladinT1]: [
    { resource: ResourcesIds.Labor, amount: 75_000 },
    { resource: ResourcesIds.Wood, amount: 75_000 },
    { resource: ResourcesIds.Stone, amount: 75_000 },
    { resource: ResourcesIds.Copper, amount: 50_000 },
    { resource: ResourcesIds.Silver, amount: 25_000 },
    { resource: ResourcesIds.Gold, amount: 25_000 },
  ],

  // T2 Military Buildings - include Rare resources
  [BuildingType.ResourceKnightT2]: [
    { resource: ResourcesIds.Labor, amount: 250_000 },
    { resource: ResourcesIds.Stone, amount: 250_000 },
    { resource: ResourcesIds.Coal, amount: 250_000 },
    { resource: ResourcesIds.Hartwood, amount: 100_000 },
    { resource: ResourcesIds.Ruby, amount: 75_000 },
    { resource: ResourcesIds.DeepCrystal, amount: 50_000 },
  ],
  [BuildingType.ResourceCrossbowmanT2]: [
    { resource: ResourcesIds.Labor, amount: 250_000 },
    { resource: ResourcesIds.Wood, amount: 250_000 },
    { resource: ResourcesIds.Coal, amount: 250_000 },
    { resource: ResourcesIds.Hartwood, amount: 100_000 },
    { resource: ResourcesIds.Diamonds, amount: 75_000 },
    { resource: ResourcesIds.EtherealSilica, amount: 50_000 },
  ],
  [BuildingType.ResourcePaladinT2]: [
    { resource: ResourcesIds.Labor, amount: 250_000 },
    { resource: ResourcesIds.Wood, amount: 250_000 },
    { resource: ResourcesIds.Stone, amount: 250_000 },
    { resource: ResourcesIds.Hartwood, amount: 100_000 },
    { resource: ResourcesIds.Sapphire, amount: 75_000 },
    { resource: ResourcesIds.Ignium, amount: 50_000 },
  ],

  // T3 Military Buildings - include Epic and Legendary resources
  [BuildingType.ResourceKnightT3]: [
    { resource: ResourcesIds.Labor, amount: 750_000 },
    { resource: ResourcesIds.Stone, amount: 500_000 },
    { resource: ResourcesIds.Coal, amount: 500_000 },
    { resource: ResourcesIds.Hartwood, amount: 250_000 },
    { resource: ResourcesIds.TwilightQuartz, amount: 100_000 },
    { resource: ResourcesIds.Mithral, amount: 50_000 },
  ],
  [BuildingType.ResourceCrossbowmanT3]: [
    { resource: ResourcesIds.Labor, amount: 750_000 },
    { resource: ResourcesIds.Wood, amount: 500_000 },
    { resource: ResourcesIds.Coal, amount: 500_000 },
    { resource: ResourcesIds.Hartwood, amount: 250_000 },
    { resource: ResourcesIds.TrueIce, amount: 100_000 },
    { resource: ResourcesIds.Dragonhide, amount: 50_000 },
  ],
  [BuildingType.ResourcePaladinT3]: [
    { resource: ResourcesIds.Labor, amount: 750_000 },
    { resource: ResourcesIds.Wood, amount: 500_000 },
    { resource: ResourcesIds.Stone, amount: 500_000 },
    { resource: ResourcesIds.Hartwood, amount: 250_000 },
    { resource: ResourcesIds.AlchemicalSilver, amount: 100_000 },
    { resource: ResourcesIds.Adamantine, amount: 50_000 },
  ],

  // Specialist Buildings - mix of resources across tiers
  [BuildingType.ResourceDonkey]: [
    { resource: ResourcesIds.Labor, amount: 50_000 },
    { resource: ResourcesIds.Silver, amount: 50_000 },
    { resource: ResourcesIds.Hartwood, amount: 25_000 },
    { resource: ResourcesIds.Sapphire, amount: 5_000 },
    { resource: ResourcesIds.Ruby, amount: 5_000 },
  ],
  [BuildingType.WorkersHut]: [
    { resource: ResourcesIds.Labor, amount: 25_000 },
    { resource: ResourcesIds.Wood, amount: 50_000 },
    { resource: ResourcesIds.Stone, amount: 50_000 },
    { resource: ResourcesIds.Coal, amount: 50_000 },
    { resource: ResourcesIds.Copper, amount: 25_000 },
  ],
  [BuildingType.Storehouse]: [
    { resource: ResourcesIds.Labor, amount: 25_000 },
    { resource: ResourcesIds.Obsidian, amount: 50_000 },
    { resource: ResourcesIds.Hartwood, amount: 10_000 },
    { resource: ResourcesIds.Diamonds, amount: 5_000 },
  ],
};

export const SIMPLE_BUILDING_COSTS: ResourceInputs = {
  [BuildingType.None]: [],
  [BuildingType.ResourceLabor]: [],
  [BuildingType.ResourceAncientFragment]: [],
  // Basic Buildings - primarily Common resources
  [BuildingType.ResourceWheat]: [{ resource: ResourcesIds.Fish, amount: 500_000 }],
  [BuildingType.ResourceFish]: [{ resource: ResourcesIds.Wheat, amount: 500_000 }],
  [BuildingType.ResourceWood]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceStone]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceCoal]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceCopper]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceObsidian]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceSilver]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceIronwood]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceColdIron]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceGold]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceHartwood]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceDiamonds]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceSapphire]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceRuby]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceDeepCrystal]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceIgnium]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceEtherealSilica]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceTrueIce]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceTwilightQuartz]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceAlchemicalSilver]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceAdamantine]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  [BuildingType.ResourceMithral]: [{ resource: ResourcesIds.Wheat, amount: 750_000 }],
  [BuildingType.ResourceDragonhide]: [{ resource: ResourcesIds.Fish, amount: 750_000 }],
  // T1 Military Buildings - primarily Uncommon resources
  [BuildingType.ResourceKnightT1]: [{ resource: ResourcesIds.Labor, amount: 560_000 }],
  [BuildingType.ResourceCrossbowmanT1]: [{ resource: ResourcesIds.Labor, amount: 590_000 }],
  [BuildingType.ResourcePaladinT1]: [{ resource: ResourcesIds.Labor, amount: 590_000 }],

  // T2 Military Buildings - include Rare resources
  [BuildingType.ResourceKnightT2]: [],
  [BuildingType.ResourceCrossbowmanT2]: [],
  [BuildingType.ResourcePaladinT2]: [],

  // T3 Military Buildings - include Epic and Legendary resources
  [BuildingType.ResourceKnightT3]: [],
  [BuildingType.ResourceCrossbowmanT3]: [],
  [BuildingType.ResourcePaladinT3]: [],

  // Specialist Buildings - mix of resources across tiers
  [BuildingType.ResourceDonkey]: [{ resource: ResourcesIds.Labor, amount: 600_000 }],
  [BuildingType.WorkersHut]: [{ resource: ResourcesIds.Labor, amount: 250_000 }],
  [BuildingType.Storehouse]: [{ resource: ResourcesIds.Labor, amount: 300_000 }],
};
