export const VICTORY_POINTS_MULTIPLIER = 1_000_000;
export const VICTORY_POINTS_FOR_WIN = 0n * BigInt(VICTORY_POINTS_MULTIPLIER);
export const AWARDED_POINTS_FOR_HYPERSTRUCTURE_HODL_PER_SECOND = 1n * BigInt(VICTORY_POINTS_MULTIPLIER);
export const AWARDED_POINTS_FOR_TILE_EXPLORATION = 5n * BigInt(VICTORY_POINTS_MULTIPLIER);
export const AWARDED_POINTS_FOR_NON_HYPERSTRUCTURE_CLAIM_AGAINST_BANDITS = 200n * BigInt(VICTORY_POINTS_MULTIPLIER);
export const AWARDED_POINTS_FOR_HYPERSTRUCTURE_CLAIM_AGAINST_BANDITS = 500n * BigInt(VICTORY_POINTS_MULTIPLIER);

// export const VICTORY_POINTS_FOR_WIN = 9_620_000n * BigInt(VICTORY_POINTS_MULTIPLIER);
// export const AWARDED_POINTS_FOR_HYPERSTRUCTURE_HODL_PER_SECOND = 7n * BigInt(VICTORY_POINTS_MULTIPLIER);