import {
  ResourcesIds,
  type ProductionByLaborParams,
  type ResourceCost,
  type ResourceInputs,
  type ResourceOutputs,
} from "@bibliothecadao/eternum";

// weight in kg
export const RESOURCES_WEIGHTS_GRAM: { [key in ResourcesIds]: number } = {
  [ResourcesIds.Wood]: 1000,
  [ResourcesIds.Stone]: 1000,
  [ResourcesIds.Coal]: 1000,
  [ResourcesIds.Copper]: 1000,
  [ResourcesIds.Obsidian]: 1000,
  [ResourcesIds.Silver]: 1000,
  [ResourcesIds.Ironwood]: 1000,
  [ResourcesIds.ColdIron]: 1000,
  [ResourcesIds.Gold]: 1000,
  [ResourcesIds.Hartwood]: 1000,
  [ResourcesIds.Diamonds]: 1000,
  [ResourcesIds.Sapphire]: 1000,
  [ResourcesIds.Ruby]: 1000,
  [ResourcesIds.DeepCrystal]: 1000,
  [ResourcesIds.Ignium]: 1000,
  [ResourcesIds.EtherealSilica]: 1000,
  [ResourcesIds.TrueIce]: 1000,
  [ResourcesIds.TwilightQuartz]: 1000,
  [ResourcesIds.AlchemicalSilver]: 1000,
  [ResourcesIds.Adamantine]: 1000,
  [ResourcesIds.Mithral]: 1000,
  [ResourcesIds.Dragonhide]: 1000,
  [ResourcesIds.Labor]: 1000,
  [ResourcesIds.AncientFragment]: 1000,
  [ResourcesIds.Donkey]: 0,
  [ResourcesIds.Knight]: 5000,
  [ResourcesIds.KnightT2]: 5000,
  [ResourcesIds.KnightT3]: 5000,
  [ResourcesIds.Crossbowman]: 3000,
  [ResourcesIds.CrossbowmanT2]: 3000,
  [ResourcesIds.CrossbowmanT3]: 3000,
  [ResourcesIds.Paladin]: 5000,
  [ResourcesIds.PaladinT2]: 5000,
  [ResourcesIds.PaladinT3]: 5000,
  [ResourcesIds.Lords]: 0,
  [ResourcesIds.Wheat]: 100,
  [ResourcesIds.Fish]: 100,
};

export const RESOURCE_PRODUCTION_OUTPUT_AMOUNTS: ResourceOutputs = {
  [ResourcesIds.Wood]: 30,
  [ResourcesIds.Stone]: 30,
  [ResourcesIds.Coal]: 30,
  [ResourcesIds.Copper]: 30,
  [ResourcesIds.Obsidian]: 30,
  [ResourcesIds.Silver]: 30,
  [ResourcesIds.Ironwood]: 30,
  [ResourcesIds.ColdIron]: 30,
  [ResourcesIds.Gold]: 30,
  [ResourcesIds.Hartwood]: 30,
  [ResourcesIds.Diamonds]: 30,
  [ResourcesIds.Sapphire]: 30,
  [ResourcesIds.Ruby]: 30,
  [ResourcesIds.DeepCrystal]: 30,
  [ResourcesIds.Ignium]: 30,
  [ResourcesIds.EtherealSilica]: 30,
  [ResourcesIds.TrueIce]: 30,
  [ResourcesIds.TwilightQuartz]: 30,
  [ResourcesIds.AlchemicalSilver]: 30,
  [ResourcesIds.Adamantine]: 30,
  [ResourcesIds.Mithral]: 30,
  [ResourcesIds.Dragonhide]: 30,
  [ResourcesIds.Donkey]: 0.5,
  [ResourcesIds.Knight]: 0.04,
  [ResourcesIds.KnightT2]: 0.04,
  [ResourcesIds.KnightT3]: 0.04,
  [ResourcesIds.Crossbowman]: 0.04,
  [ResourcesIds.CrossbowmanT2]: 0.04,
  [ResourcesIds.CrossbowmanT3]: 0.04,
  [ResourcesIds.Paladin]: 0.04,
  [ResourcesIds.PaladinT2]: 0.04,
  [ResourcesIds.PaladinT3]: 0.04,
  [ResourcesIds.Lords]: 0,
  [ResourcesIds.Wheat]: 50,
  [ResourcesIds.Fish]: 50,
  [ResourcesIds.AncientFragment]: 1,
  [ResourcesIds.Labor]: 30,
};

export const RESOURCE_PRODUCTION_THROUGH_LABOR: ProductionByLaborParams = {
  [ResourcesIds.Wood]: {
    resource_rarity: 1,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Stone]: {
    resource_rarity: 1,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Coal]: {
    resource_rarity: 1,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Copper]: {
    resource_rarity: 2,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Obsidian]: {
    resource_rarity: 2,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Silver]: {
    resource_rarity: 3,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Ironwood]: {
    resource_rarity: 4,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.ColdIron]: {
    resource_rarity: 5,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Gold]: {
    resource_rarity: 5,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Hartwood]: {
    resource_rarity: 8,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Diamonds]: {
    resource_rarity: 17,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Sapphire]: {
    resource_rarity: 20,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Ruby]: {
    resource_rarity: 21,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.DeepCrystal]: {
    resource_rarity: 21,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Ignium]: {
    resource_rarity: 29,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.EtherealSilica]: {
    resource_rarity: 31,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.TrueIce]: {
    resource_rarity: 36,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.TwilightQuartz]: {
    resource_rarity: 45,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.AlchemicalSilver]: {
    resource_rarity: 54,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Adamantine]: {
    resource_rarity: 91,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Mithral]: {
    resource_rarity: 136,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Dragonhide]: {
    resource_rarity: 218,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.AncientFragment]: {
    resource_rarity: 21,
    depreciation_percent_num: 10,
    depreciation_percent_denom: 100,
    wheat_burn_per_labor: 25,
    fish_burn_per_labor: 30,
  },
  [ResourcesIds.Donkey]: {
    resource_rarity: 0,
    depreciation_percent_num: 0,
    depreciation_percent_denom: 0,
    wheat_burn_per_labor: 0,
    fish_burn_per_labor: 0,
  },
  [ResourcesIds.Knight]: {
    resource_rarity: 0,
    depreciation_percent_num: 0,
    depreciation_percent_denom: 0,
    wheat_burn_per_labor: 0,
    fish_burn_per_labor: 0,
  },
  [ResourcesIds.KnightT2]: {
    resource_rarity: 0,
    depreciation_percent_num: 0,
    depreciation_percent_denom: 0,
    wheat_burn_per_labor: 0,
    fish_burn_per_labor: 0,
  },
  [ResourcesIds.KnightT3]: {
    resource_rarity: 0,
    depreciation_percent_num: 0,
    depreciation_percent_denom: 0,
    wheat_burn_per_labor: 0,
    fish_burn_per_labor: 0,
  },
  [ResourcesIds.Crossbowman]: {
    resource_rarity: 0,
    depreciation_percent_num: 0,
    depreciation_percent_denom: 0,
    wheat_burn_per_labor: 0,
    fish_burn_per_labor: 0,
  },
  [ResourcesIds.CrossbowmanT2]: {
    resource_rarity: 0,
    depreciation_percent_num: 0,
    depreciation_percent_denom: 0,
    wheat_burn_per_labor: 0,
    fish_burn_per_labor: 0,
  },
  [ResourcesIds.CrossbowmanT3]: {
    resource_rarity: 0,
    depreciation_percent_num: 0,
    depreciation_percent_denom: 0,
    wheat_burn_per_labor: 0,
    fish_burn_per_labor: 0,
  },
  [ResourcesIds.Paladin]: {
    resource_rarity: 0,
    depreciation_percent_num: 0,
    depreciation_percent_denom: 0,
    wheat_burn_per_labor: 0,
    fish_burn_per_labor: 0,
  },
  [ResourcesIds.PaladinT2]: {
    resource_rarity: 0,
    depreciation_percent_num: 0,
    depreciation_percent_denom: 0,
    wheat_burn_per_labor: 0,
    fish_burn_per_labor: 0,
  },
  [ResourcesIds.PaladinT3]: {
    resource_rarity: 0,
    depreciation_percent_num: 0,
    depreciation_percent_denom: 0,
    wheat_burn_per_labor: 0,
    fish_burn_per_labor: 0,
  },
  [ResourcesIds.Wheat]: {
    resource_rarity: 0,
    depreciation_percent_num: 0,
    depreciation_percent_denom: 0,
    wheat_burn_per_labor: 0,
    fish_burn_per_labor: 0,
  },
  [ResourcesIds.Fish]: {
    resource_rarity: 0,
    depreciation_percent_num: 0,
    depreciation_percent_denom: 0,
    wheat_burn_per_labor: 0,
    fish_burn_per_labor: 0,
  },
  [ResourcesIds.Lords]: {
    resource_rarity: 0,
    depreciation_percent_num: 0,
    depreciation_percent_denom: 0,
    wheat_burn_per_labor: 0,
    fish_burn_per_labor: 0,
  },
  [ResourcesIds.Labor]: {
    resource_rarity: 0,
    depreciation_percent_num: 0,
    depreciation_percent_denom: 0,
    wheat_burn_per_labor: 0,
    fish_burn_per_labor: 0,
  },
};
export const RESOURCE_PRODUCTION_INPUT_RESOURCES: ResourceInputs = {
  [ResourcesIds.Wood]: [
    { resource: ResourcesIds.Stone, amount: 3 },
    { resource: ResourcesIds.Coal, amount: 3.2 },
    { resource: ResourcesIds.Wheat, amount: 5 },
  ],
  [ResourcesIds.Stone]: [
    { resource: ResourcesIds.Wood, amount: 5 },
    { resource: ResourcesIds.Coal, amount: 3.8 },
    { resource: ResourcesIds.Wheat, amount: 5 },
  ],
  [ResourcesIds.Coal]: [
    { resource: ResourcesIds.Stone, amount: 4.2 },
    { resource: ResourcesIds.Copper, amount: 2.8 },
    { resource: ResourcesIds.Wheat, amount: 5 },
  ],
  [ResourcesIds.Copper]: [
    { resource: ResourcesIds.Coal, amount: 5.8 },
    { resource: ResourcesIds.Obsidian, amount: 3.4 },
    { resource: ResourcesIds.Wheat, amount: 5 },
  ],
  [ResourcesIds.Obsidian]: [
    { resource: ResourcesIds.Copper, amount: 4.8 },
    { resource: ResourcesIds.Silver, amount: 3.2 },
    { resource: ResourcesIds.Wheat, amount: 5 },
  ],
  [ResourcesIds.Silver]: [
    { resource: ResourcesIds.Obsidian, amount: 5 },
    { resource: ResourcesIds.Ironwood, amount: 2.8 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.Ironwood]: [
    { resource: ResourcesIds.Silver, amount: 6 },
    { resource: ResourcesIds.ColdIron, amount: 3.2 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.ColdIron]: [
    { resource: ResourcesIds.Ironwood, amount: 5 },
    { resource: ResourcesIds.Gold, amount: 3.8 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.Gold]: [
    { resource: ResourcesIds.ColdIron, amount: 4.2 },
    { resource: ResourcesIds.Hartwood, amount: 2.6 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.Hartwood]: [
    { resource: ResourcesIds.Gold, amount: 6.2 },
    { resource: ResourcesIds.Diamonds, amount: 2 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.Diamonds]: [
    { resource: ResourcesIds.Hartwood, amount: 8 },
    { resource: ResourcesIds.Sapphire, amount: 3.2 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.Sapphire]: [
    { resource: ResourcesIds.Diamonds, amount: 4.8 },
    { resource: ResourcesIds.Ruby, amount: 3.8 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.Ruby]: [
    { resource: ResourcesIds.Sapphire, amount: 4.2 },
    { resource: ResourcesIds.DeepCrystal, amount: 4 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.DeepCrystal]: [
    { resource: ResourcesIds.Ruby, amount: 4 },
    { resource: ResourcesIds.Ignium, amount: 4.2 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.Ignium]: [
    { resource: ResourcesIds.DeepCrystal, amount: 5.6 },
    { resource: ResourcesIds.EtherealSilica, amount: 3.8 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.EtherealSilica]: [
    { resource: ResourcesIds.Ignium, amount: 4.2 },
    { resource: ResourcesIds.TrueIce, amount: 3.4 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.TrueIce]: [
    { resource: ResourcesIds.EtherealSilica, amount: 4.6 },
    { resource: ResourcesIds.TwilightQuartz, amount: 3.2 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.TwilightQuartz]: [
    { resource: ResourcesIds.TrueIce, amount: 5 },
    { resource: ResourcesIds.AlchemicalSilver, amount: 3.4 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.AlchemicalSilver]: [
    { resource: ResourcesIds.TwilightQuartz, amount: 4.8 },
    { resource: ResourcesIds.Adamantine, amount: 2.4 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.Adamantine]: [
    { resource: ResourcesIds.AlchemicalSilver, amount: 6.8 },
    { resource: ResourcesIds.Mithral, amount: 2.6 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.Mithral]: [
    { resource: ResourcesIds.Adamantine, amount: 6 },
    { resource: ResourcesIds.Dragonhide, amount: 2.4 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.Dragonhide]: [
    { resource: ResourcesIds.Mithral, amount: 6.4 },
    { resource: ResourcesIds.Adamantine, amount: 4 },
    { resource: ResourcesIds.Fish, amount: 4 },
  ],
  [ResourcesIds.Donkey]: [
    { resource: ResourcesIds.Wheat, amount: 25 },
    { resource: ResourcesIds.Lords, amount: 0.01 },
  ],
  [ResourcesIds.Knight]: [
    { resource: ResourcesIds.Wheat, amount: 50 },
    { resource: ResourcesIds.Fish, amount: 50 },
    { resource: ResourcesIds.Silver, amount: 2 },
    { resource: ResourcesIds.Ironwood, amount: 5 },
  ],
  [ResourcesIds.Crossbowman]: [
    { resource: ResourcesIds.Wheat, amount: 50 },
    { resource: ResourcesIds.Fish, amount: 50 },
    { resource: ResourcesIds.Obsidian, amount: 2 },
    { resource: ResourcesIds.ColdIron, amount: 5 },
  ],
  [ResourcesIds.Paladin]: [
    { resource: ResourcesIds.Wheat, amount: 50 },
    { resource: ResourcesIds.Fish, amount: 50 },
    { resource: ResourcesIds.Copper, amount: 2 },
    { resource: ResourcesIds.Gold, amount: 5 },
  ],
  [ResourcesIds.Wheat]: [],
  [ResourcesIds.Fish]: [],
  [ResourcesIds.Lords]: [],
  [ResourcesIds.AncientFragment]: [],
  [ResourcesIds.Labor]: [],
  [ResourcesIds.KnightT2]: [],
  [ResourcesIds.KnightT3]: [],
  [ResourcesIds.CrossbowmanT2]: [],
  [ResourcesIds.CrossbowmanT3]: [],
  [ResourcesIds.PaladinT2]: [],
  [ResourcesIds.PaladinT3]: [],
};

export const STARTING_RESOURCES: ResourceCost[] = [
  { resource: ResourcesIds.Wheat, amount: 1_200_000 },
  { resource: ResourcesIds.Fish, amount: 1_200_000 },
  { resource: ResourcesIds.Wood, amount: 5_000 },
  { resource: ResourcesIds.Stone, amount: 5_000 },
  { resource: ResourcesIds.Coal, amount: 5_000 },
  { resource: ResourcesIds.Copper, amount: 5_000 },
  { resource: ResourcesIds.Obsidian, amount: 5_000 },
  { resource: ResourcesIds.Silver, amount: 5_000 },
  { resource: ResourcesIds.Ironwood, amount: 5_000 },
  { resource: ResourcesIds.ColdIron, amount: 5_000 },
  { resource: ResourcesIds.Gold, amount: 5_000 },
  { resource: ResourcesIds.Hartwood, amount: 5_000 },
  { resource: ResourcesIds.Diamonds, amount: 5_000 },
  { resource: ResourcesIds.Sapphire, amount: 5_000 },
  { resource: ResourcesIds.Ruby, amount: 5_000 },
  { resource: ResourcesIds.DeepCrystal, amount: 5_000 },
  { resource: ResourcesIds.Ignium, amount: 5_000 },
  { resource: ResourcesIds.EtherealSilica, amount: 5_000 },
  { resource: ResourcesIds.TrueIce, amount: 5_000 },
  { resource: ResourcesIds.TwilightQuartz, amount: 5_000 },
  { resource: ResourcesIds.AlchemicalSilver, amount: 5_000 },
  { resource: ResourcesIds.Adamantine, amount: 5_000 },
  { resource: ResourcesIds.Mithral, amount: 5_000 },
  { resource: ResourcesIds.Dragonhide, amount: 5_000 },
  { resource: ResourcesIds.Donkey, amount: 800 },
  { resource: ResourcesIds.Knight, amount: 1200 },
  { resource: ResourcesIds.Crossbowman, amount: 1200 },
  { resource: ResourcesIds.Paladin, amount: 1200 },
  { resource: ResourcesIds.AncientFragment, amount: 200 },
];

export const multiplyStartingResources = (multiplier: number): ResourceCost[] => {
  return STARTING_RESOURCES.map(resource => ({
    resource: resource.resource,
    amount: resource.amount * multiplier
  }));
};