import { RESOURCE_PRECISION, RESOURCE_RARITY, ResourcesIds } from "../../../packages/types/src/constants";
import type { ResourceCost, ResourceMinMax } from "../../../packages/types/src/types/common";
import type { ConfigPatch } from "../common/merge-config";

type ResourceInputsById = Record<number, ResourceCost[]>;
type ResourceOutputsById = Record<number, number>;

// weight in kg
// grams / 10^9
const RESOURCES_WEIGHTS_NANOGRAM: Record<number, number> = {
  [ResourcesIds.Wood]: 1000,
  [ResourcesIds.Stone]: 1000,
  [ResourcesIds.Coal]: 1000,
  [ResourcesIds.Copper]: 1000,
  [ResourcesIds.Obsidian]: 1000,
  [ResourcesIds.Silver]: 1000,
  [ResourcesIds.Ironwood]: 1000,
  [ResourcesIds.ColdIron]: 1000,
  [ResourcesIds.Gold]: 1000,
  [ResourcesIds.Hartwood]: 1000,
  [ResourcesIds.Diamonds]: 1000,
  [ResourcesIds.Sapphire]: 1000,
  [ResourcesIds.Ruby]: 1000,
  [ResourcesIds.DeepCrystal]: 1000,
  [ResourcesIds.Ignium]: 1000,
  [ResourcesIds.EtherealSilica]: 1000,
  [ResourcesIds.TrueIce]: 1000,
  [ResourcesIds.TwilightQuartz]: 1000,
  [ResourcesIds.AlchemicalSilver]: 1000,
  [ResourcesIds.Adamantine]: 1000,
  [ResourcesIds.Mithral]: 1000,
  [ResourcesIds.Dragonhide]: 1000,
  [ResourcesIds.Labor]: 1000,
  [ResourcesIds.AncientFragment]: 100, // 0.1 kg
  [ResourcesIds.Essence]: 100, // 0.1 kg
  [ResourcesIds.Donkey]: 0,
  [ResourcesIds.Knight]: 5000,
  [ResourcesIds.KnightT2]: 5000,
  [ResourcesIds.KnightT3]: 5000,
  [ResourcesIds.Crossbowman]: 5000,
  [ResourcesIds.CrossbowmanT2]: 5000,
  [ResourcesIds.CrossbowmanT3]: 5000,
  [ResourcesIds.Paladin]: 5000,
  [ResourcesIds.PaladinT2]: 5000,
  [ResourcesIds.PaladinT3]: 5000,
  [ResourcesIds.Lords]: 0,
  [ResourcesIds.Wheat]: 100,
  [ResourcesIds.Fish]: 100,
  [ResourcesIds.Research]: 0, // Weightless
};

const RESOURCE_PRODUCTION_OUTPUT_AMOUNTS: ResourceOutputsById = {
  [ResourcesIds.Wood]: 1,
  [ResourcesIds.Stone]: 1,
  [ResourcesIds.Coal]: 1,
  [ResourcesIds.Copper]: 1,
  [ResourcesIds.Obsidian]: 1,
  [ResourcesIds.Silver]: 1,
  [ResourcesIds.Ironwood]: 1,
  [ResourcesIds.ColdIron]: 1,
  [ResourcesIds.Gold]: 1,
  [ResourcesIds.Hartwood]: 1,
  [ResourcesIds.Diamonds]: 1,
  [ResourcesIds.Sapphire]: 1,
  [ResourcesIds.Ruby]: 1,
  [ResourcesIds.DeepCrystal]: 1,
  [ResourcesIds.Ignium]: 1,
  [ResourcesIds.EtherealSilica]: 1,
  [ResourcesIds.TrueIce]: 1,
  [ResourcesIds.TwilightQuartz]: 1,
  [ResourcesIds.AlchemicalSilver]: 1,
  [ResourcesIds.Adamantine]: 1,
  [ResourcesIds.Mithral]: 1,
  [ResourcesIds.Dragonhide]: 1,
  [ResourcesIds.Donkey]: 3,
  [ResourcesIds.Knight]: 5,
  [ResourcesIds.KnightT2]: 5,
  [ResourcesIds.KnightT3]: 5,
  [ResourcesIds.Crossbowman]: 5,
  [ResourcesIds.CrossbowmanT2]: 5,
  [ResourcesIds.CrossbowmanT3]: 5,
  [ResourcesIds.Paladin]: 5,
  [ResourcesIds.PaladinT2]: 5,
  [ResourcesIds.PaladinT3]: 5,
  [ResourcesIds.Lords]: 0,
  [ResourcesIds.Wheat]: 6,
  [ResourcesIds.Fish]: 6,
  [ResourcesIds.AncientFragment]: 3,
  [ResourcesIds.Essence]: 10,
  [ResourcesIds.Labor]: 1,
  [ResourcesIds.Research]: 1, // Placeholder - TBD from balance sheet
};

const RESOURCE_PRODUCTION_INPUT_RESOURCES: ResourceInputsById = {
  [ResourcesIds.Wood]: [
    { resource: ResourcesIds.Wheat, amount: 1 },
    { resource: ResourcesIds.Fish, amount: 1 },
    { resource: ResourcesIds.Coal, amount: 0.2 },
    { resource: ResourcesIds.Copper, amount: 0.2 },
  ],
  [ResourcesIds.Coal]: [
    { resource: ResourcesIds.Wheat, amount: 1 },
    { resource: ResourcesIds.Fish, amount: 1 },
    { resource: ResourcesIds.Wood, amount: 0.3 },
    { resource: ResourcesIds.Copper, amount: 0.2 },
  ],
  [ResourcesIds.Copper]: [
    { resource: ResourcesIds.Wheat, amount: 1 },
    { resource: ResourcesIds.Fish, amount: 1 },
    { resource: ResourcesIds.Wood, amount: 0.3 },
    { resource: ResourcesIds.Coal, amount: 0.2 },
  ],
  [ResourcesIds.Ironwood]: [
    { resource: ResourcesIds.Wheat, amount: 2 },
    { resource: ResourcesIds.Fish, amount: 2 },
    { resource: ResourcesIds.Coal, amount: 0.6 },
    { resource: ResourcesIds.Copper, amount: 0.4 },
  ],
  [ResourcesIds.ColdIron]: [
    { resource: ResourcesIds.Wheat, amount: 2 },
    { resource: ResourcesIds.Fish, amount: 2 },
    { resource: ResourcesIds.Coal, amount: 0.6 },
    { resource: ResourcesIds.Copper, amount: 0.4 },
  ],
  [ResourcesIds.Gold]: [
    { resource: ResourcesIds.Wheat, amount: 2 },
    { resource: ResourcesIds.Fish, amount: 2 },
    { resource: ResourcesIds.Coal, amount: 0.6 },
    { resource: ResourcesIds.Copper, amount: 0.4 },
  ],
  [ResourcesIds.Adamantine]: [
    { resource: ResourcesIds.Wheat, amount: 3 },
    { resource: ResourcesIds.Fish, amount: 3 },
    { resource: ResourcesIds.Coal, amount: 0.9 },
    { resource: ResourcesIds.Ironwood, amount: 0.6 },
  ],
  [ResourcesIds.Mithral]: [
    { resource: ResourcesIds.Wheat, amount: 3 },
    { resource: ResourcesIds.Fish, amount: 3 },
    { resource: ResourcesIds.Coal, amount: 0.9 },
    { resource: ResourcesIds.ColdIron, amount: 0.6 },
  ],
  [ResourcesIds.Dragonhide]: [
    { resource: ResourcesIds.Wheat, amount: 3 },
    { resource: ResourcesIds.Fish, amount: 3 },
    { resource: ResourcesIds.Coal, amount: 0.9 },
    { resource: ResourcesIds.Gold, amount: 0.6 },
  ],
  // All other resources not in the provided list have empty input arrays
  [ResourcesIds.Stone]: [],
  [ResourcesIds.Obsidian]: [],
  [ResourcesIds.Silver]: [],
  [ResourcesIds.Hartwood]: [],
  [ResourcesIds.Diamonds]: [],
  [ResourcesIds.Sapphire]: [],
  [ResourcesIds.Ruby]: [],
  [ResourcesIds.DeepCrystal]: [],
  [ResourcesIds.Ignium]: [],
  [ResourcesIds.EtherealSilica]: [],
  [ResourcesIds.TrueIce]: [],
  [ResourcesIds.TwilightQuartz]: [],
  [ResourcesIds.AlchemicalSilver]: [],
  [ResourcesIds.Donkey]: [
    { resource: ResourcesIds.Wheat, amount: 3 },
    { resource: ResourcesIds.Fish, amount: 3 },
  ],
  [ResourcesIds.Knight]: [
    { resource: ResourcesIds.Wheat, amount: 2 },
    { resource: ResourcesIds.Fish, amount: 2 },
    { resource: ResourcesIds.Copper, amount: 0.4 },
  ],
  [ResourcesIds.KnightT2]: [
    { resource: ResourcesIds.Wheat, amount: 3 },
    { resource: ResourcesIds.Fish, amount: 3 },
    { resource: ResourcesIds.Knight, amount: 10 },
    { resource: ResourcesIds.Copper, amount: 0.2 },
    { resource: ResourcesIds.ColdIron, amount: 0.6 },
    { resource: ResourcesIds.Essence, amount: 1 },
  ],
  [ResourcesIds.KnightT3]: [
    { resource: ResourcesIds.Wheat, amount: 4 },
    { resource: ResourcesIds.Fish, amount: 4 },
    { resource: ResourcesIds.KnightT2, amount: 10 },
    { resource: ResourcesIds.ColdIron, amount: 0.4 },
    { resource: ResourcesIds.Mithral, amount: 0.8 },
    { resource: ResourcesIds.Essence, amount: 3 },
  ],
  [ResourcesIds.Crossbowman]: [
    { resource: ResourcesIds.Wheat, amount: 2 },
    { resource: ResourcesIds.Fish, amount: 2 },
    { resource: ResourcesIds.Copper, amount: 0.4 },
  ],
  [ResourcesIds.CrossbowmanT2]: [
    { resource: ResourcesIds.Wheat, amount: 3 },
    { resource: ResourcesIds.Fish, amount: 3 },
    { resource: ResourcesIds.Crossbowman, amount: 10 },
    { resource: ResourcesIds.Copper, amount: 0.2 },
    { resource: ResourcesIds.Ironwood, amount: 0.6 },
    { resource: ResourcesIds.Essence, amount: 1 },
  ],
  [ResourcesIds.CrossbowmanT3]: [
    { resource: ResourcesIds.Wheat, amount: 4 },
    { resource: ResourcesIds.Fish, amount: 4 },
    { resource: ResourcesIds.CrossbowmanT2, amount: 10 },
    { resource: ResourcesIds.Ironwood, amount: 0.4 },
    { resource: ResourcesIds.Adamantine, amount: 0.8 },
    { resource: ResourcesIds.Essence, amount: 3 },
  ],
  [ResourcesIds.Paladin]: [
    { resource: ResourcesIds.Wheat, amount: 2 },
    { resource: ResourcesIds.Fish, amount: 2 },
    { resource: ResourcesIds.Copper, amount: 0.4 },
  ],
  [ResourcesIds.PaladinT2]: [
    { resource: ResourcesIds.Wheat, amount: 3 },
    { resource: ResourcesIds.Fish, amount: 3 },
    { resource: ResourcesIds.Paladin, amount: 10 },
    { resource: ResourcesIds.Copper, amount: 0.2 },
    { resource: ResourcesIds.Gold, amount: 0.6 },
    { resource: ResourcesIds.Essence, amount: 1 },
  ],
  [ResourcesIds.PaladinT3]: [
    { resource: ResourcesIds.Wheat, amount: 4 },
    { resource: ResourcesIds.Fish, amount: 4 },
    { resource: ResourcesIds.PaladinT2, amount: 10 },
    { resource: ResourcesIds.Gold, amount: 0.4 },
    { resource: ResourcesIds.Dragonhide, amount: 0.8 },
    { resource: ResourcesIds.Essence, amount: 3 },
  ],
  [ResourcesIds.Wheat]: [],
  [ResourcesIds.Fish]: [],
  [ResourcesIds.Lords]: [],
  [ResourcesIds.AncientFragment]: [],
  [ResourcesIds.Essence]: [],
  [ResourcesIds.Labor]: [],
  [ResourcesIds.Research]: [
    { resource: ResourcesIds.Fish, amount: 15 },
    { resource: ResourcesIds.Lords, amount: 0.001 },
    { resource: ResourcesIds.Essence, amount: 0.5 },
  ],
};

const STARTING_RESOURCES: ResourceCost[] = [
  { resource: ResourcesIds.Wheat, amount: 1_000 },
  { resource: ResourcesIds.Fish, amount: 1_000 },
  { resource: ResourcesIds.Labor, amount: 1_200 },
  { resource: ResourcesIds.Wood, amount: 180 },
  { resource: ResourcesIds.Coal, amount: 120 },
  { resource: ResourcesIds.Copper, amount: 60 },
  { resource: ResourcesIds.Donkey, amount: 200 },
  // 3,000, tokenized troops. Only one troop type will be selected
  { resource: ResourcesIds.Knight, amount: 1_500 },
  { resource: ResourcesIds.Crossbowman, amount: 1_500 },
  { resource: ResourcesIds.Paladin, amount: 1_500 },
];

const VILLAGE_STARTING_RESOURCES: ResourceCost[] = [
  { resource: ResourcesIds.Knight, amount: 500 },
  { resource: ResourcesIds.Crossbowman, amount: 500 },
  { resource: ResourcesIds.Paladin, amount: 500 },
];

const DISCOVERABLE_VILLAGE_STARTING_RESOURCES: ResourceMinMax[] = [
  { resource: ResourcesIds.Wheat, min_amount: 500, max_amount: 500 },
  { resource: ResourcesIds.Fish, min_amount: 500, max_amount: 500 },
  { resource: ResourcesIds.Labor, min_amount: 2_500, max_amount: 2_500 },
  { resource: ResourcesIds.Donkey, min_amount: 200, max_amount: 200 },
];

const LABOR_PRODUCTION_OUTPUT_AMOUNTS_THROUGH_RESOURCES: ResourceOutputsById = {
  [ResourcesIds.Wood]: 0,
  [ResourcesIds.Stone]: 0,
  [ResourcesIds.Coal]: 0,
  [ResourcesIds.Copper]: 0,
  [ResourcesIds.Obsidian]: 0,
  [ResourcesIds.Silver]: 0,
  [ResourcesIds.Ironwood]: 0,
  [ResourcesIds.ColdIron]: 0,
  [ResourcesIds.Gold]: 0,
  [ResourcesIds.Hartwood]: 0,
  [ResourcesIds.Diamonds]: 0,
  [ResourcesIds.Sapphire]: 0,
  [ResourcesIds.Ruby]: 0,
  [ResourcesIds.DeepCrystal]: 0,
  [ResourcesIds.Ignium]: 0,
  [ResourcesIds.EtherealSilica]: 0,
  [ResourcesIds.TrueIce]: 0,
  [ResourcesIds.TwilightQuartz]: 0,
  [ResourcesIds.AlchemicalSilver]: 0,
  [ResourcesIds.Adamantine]: 0,
  [ResourcesIds.Mithral]: 0,
  [ResourcesIds.Dragonhide]: 0,
  [ResourcesIds.Donkey]: 0,
  [ResourcesIds.Knight]: 0,
  [ResourcesIds.KnightT2]: 0,
  [ResourcesIds.KnightT3]: 0,
  [ResourcesIds.Crossbowman]: 0,
  [ResourcesIds.CrossbowmanT2]: 0,
  [ResourcesIds.CrossbowmanT3]: 0,
  [ResourcesIds.Paladin]: 0,
  [ResourcesIds.PaladinT2]: 0,
  [ResourcesIds.PaladinT3]: 0,
  [ResourcesIds.Lords]: 0,
  [ResourcesIds.Wheat]: 0,
  [ResourcesIds.Fish]: 0,
  [ResourcesIds.AncientFragment]: 0,
  [ResourcesIds.Essence]: 0,
  [ResourcesIds.Labor]: 0,
  [ResourcesIds.Research]: 0, // Cannot be converted to labor
};
const RESOURCE_PRODUCTION_OUTPUT_AMOUNTS_SIMPLE_SYSTEM: ResourceOutputsById = RESOURCE_PRODUCTION_OUTPUT_AMOUNTS;

const RESOURCE_PRODUCTION_INPUT_RESOURCES_SIMPLE_SYSTEM: ResourceInputsById = {
  [ResourcesIds.Wood]: [
    { resource: ResourcesIds.Wheat, amount: 1 },
    { resource: ResourcesIds.Fish, amount: 1 },
    { resource: ResourcesIds.Labor, amount: 0.5 },
  ],
  [ResourcesIds.Stone]: [],
  [ResourcesIds.Coal]: [
    { resource: ResourcesIds.Wheat, amount: 1 },
    { resource: ResourcesIds.Fish, amount: 1 },
    { resource: ResourcesIds.Labor, amount: 1 },
  ],
  [ResourcesIds.Copper]: [
    { resource: ResourcesIds.Wheat, amount: 1 },
    { resource: ResourcesIds.Fish, amount: 1 },
    { resource: ResourcesIds.Labor, amount: 1 },
  ],
  [ResourcesIds.Obsidian]: [],
  [ResourcesIds.Silver]: [],
  [ResourcesIds.Ironwood]: [
    { resource: ResourcesIds.Wheat, amount: 2 },
    { resource: ResourcesIds.Fish, amount: 2 },
    { resource: ResourcesIds.Labor, amount: 2.5 },
  ],
  [ResourcesIds.ColdIron]: [
    { resource: ResourcesIds.Wheat, amount: 2 },
    { resource: ResourcesIds.Fish, amount: 2 },
    { resource: ResourcesIds.Labor, amount: 2.5 },
  ],
  [ResourcesIds.Gold]: [
    { resource: ResourcesIds.Wheat, amount: 2 },
    { resource: ResourcesIds.Fish, amount: 2 },
    { resource: ResourcesIds.Labor, amount: 2.5 },
  ],
  [ResourcesIds.Hartwood]: [],
  [ResourcesIds.Diamonds]: [],
  [ResourcesIds.Sapphire]: [],
  [ResourcesIds.Ruby]: [],
  [ResourcesIds.DeepCrystal]: [],
  [ResourcesIds.Ignium]: [],
  [ResourcesIds.EtherealSilica]: [],
  [ResourcesIds.TrueIce]: [],
  [ResourcesIds.TwilightQuartz]: [],
  [ResourcesIds.AlchemicalSilver]: [],
  [ResourcesIds.Adamantine]: [
    { resource: ResourcesIds.Wheat, amount: 4 },
    { resource: ResourcesIds.Fish, amount: 4 },
    { resource: ResourcesIds.Labor, amount: 10 },
  ],
  [ResourcesIds.Mithral]: [
    { resource: ResourcesIds.Wheat, amount: 4 },
    { resource: ResourcesIds.Fish, amount: 4 },
    { resource: ResourcesIds.Labor, amount: 10 },
  ],
  [ResourcesIds.Dragonhide]: [
    { resource: ResourcesIds.Wheat, amount: 4 },
    { resource: ResourcesIds.Fish, amount: 4 },
    { resource: ResourcesIds.Labor, amount: 10 },
  ],
  [ResourcesIds.Donkey]: [],
  [ResourcesIds.Knight]: [
    { resource: ResourcesIds.Wheat, amount: 2 },
    { resource: ResourcesIds.Fish, amount: 2 },
    { resource: ResourcesIds.Labor, amount: 0.5 },
  ],
  [ResourcesIds.KnightT2]: [],
  [ResourcesIds.KnightT3]: [],
  [ResourcesIds.Crossbowman]: [
    { resource: ResourcesIds.Wheat, amount: 2 },
    { resource: ResourcesIds.Fish, amount: 2 },
    { resource: ResourcesIds.Labor, amount: 0.5 },
  ],
  [ResourcesIds.CrossbowmanT2]: [],
  [ResourcesIds.CrossbowmanT3]: [],
  [ResourcesIds.Paladin]: [
    { resource: ResourcesIds.Wheat, amount: 2 },
    { resource: ResourcesIds.Fish, amount: 2 },
    { resource: ResourcesIds.Labor, amount: 0.5 },
  ],
  [ResourcesIds.PaladinT2]: [],
  [ResourcesIds.PaladinT3]: [],
  [ResourcesIds.Wheat]: [],
  [ResourcesIds.Fish]: [],
  [ResourcesIds.Lords]: [],
  [ResourcesIds.AncientFragment]: [],
  [ResourcesIds.Essence]: [],
  [ResourcesIds.Labor]: [],
  [ResourcesIds.Research]: [], // No simple recipe
};

export const eternumResourceConfig: ConfigPatch = {
  resources: {
    resourcePrecision: RESOURCE_PRECISION,
    productionByComplexRecipe: RESOURCE_PRODUCTION_INPUT_RESOURCES,
    productionByComplexRecipeOutputs: RESOURCE_PRODUCTION_OUTPUT_AMOUNTS,
    productionBySimpleRecipe: RESOURCE_PRODUCTION_INPUT_RESOURCES_SIMPLE_SYSTEM,
    productionBySimpleRecipeOutputs: RESOURCE_PRODUCTION_OUTPUT_AMOUNTS_SIMPLE_SYSTEM,
    laborOutputPerResource: LABOR_PRODUCTION_OUTPUT_AMOUNTS_THROUGH_RESOURCES,
    resourceWeightsGrams: RESOURCES_WEIGHTS_NANOGRAM,
    resourceRarity: RESOURCE_RARITY,
  },
  startingResources: STARTING_RESOURCES,
  villageStartingResources: VILLAGE_STARTING_RESOURCES,
  discoverableVillageStartingResources: DISCOVERABLE_VILLAGE_STARTING_RESOURCES,
};
