packages:
  - "client"
  - "client/apps/landing"
  - "client/apps/game"
  - "client/apps/balancing"
  - "client/apps/game-docs"
  - "client/apps/heavy-load"
  - "client/apps/eternum-mobile"
  - "config"
  - "packages/*"
  - "contracts/season_pass/scripts/deployment"
  - "contracts/season_resources/scripts/deployment"
