packages:
  - "client/sdk/packages/*"
  - "client"
  - "client/apps/*"
  - "client/config"
  - "client/balancing"
  - "contracts/season_pass/scripts/deployment"
  - "contracts/season_resources/scripts/deployment"
