packages:
  - "client"
  - "client/apps/landing"
  - "client/apps/game"
  - "client/apps/balancing"
  - "client/apps/game-docs"
  - "client/apps/torii-client"
  - "client/apps/heavy-load"
  - "client/apps/eternum-mobile"
  - "config"
  - "packages/*"
  - "contracts/season_pass/scripts/deployment"
  - "contracts/season_resources/scripts/deployment"

catalog:
  starknet: 6.23.1
  starknetkit: ^2.6.1
  "@cartridge/controller": ^0.7.14-alpha.3
  "@cartridge/connector": ^0.7.14-alpha.3
  "@starknet-react/core": 3.7.2
  "@starknet-react/chains": 3.1.2
  "@metamask/sdk": ^0.32.1
  "@solana/web3.js": ^1.98.0
  open: ^10.1.0
  react: ^18
  react-dom: ^18
  "@types/react": ^18
  "@types/react-dom": ^18
  "@dojoengine/react": 1.5.3
  "@dojoengine/core": 1.5.3
  "@dojoengine/sdk": 1.5.3
  "@dojoengine/predeployed-connector": 1.5.3
  "@dojoengine/recs": ^2.0.13
  "@dojoengine/state": 1.5.3
  "@dojoengine/torii-client": 1.5.3
  "@dojoengine/torii-wasm": 1.5.3
  "@dojoengine/utils": 1.5.3
