kind = "DojoContract"
class_hash = "0x6afb6b57ca88a9a6582e66b844fa6ea594067dfa9e22ee03516af67ef9ec573"
original_class_hash = "0x6afb6b57ca88a9a6582e66b844fa6ea594067dfa9e22ee03516af67ef9ec573"
base_class_hash = "0x0"
abi = "manifests/prod/base/abis/contracts/eternum-swap_systems-216e8d44.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-swap_systems"
systems = []
manifest_name = "eternum-swap_systems-216e8d44"
