kind = "DojoContract"
class_hash = "0x54ee2d1b8ccb8f74c200d1d43656a27906cc1488d7a762b61d94baa09a473cf"
original_class_hash = "0x54ee2d1b8ccb8f74c200d1d43656a27906cc1488d7a762b61d94baa09a473cf"
base_class_hash = "0x0"
abi = "manifests/prod/base/abis/contracts/eternum-travel_systems-4ec72d4c.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-travel_systems"
systems = [
    "travel",
    "travel_hex",
]
manifest_name = "eternum-travel_systems-4ec72d4c"
