kind = "DojoContract"
class_hash = "0x22d788f4a836d88ac5eb219aab1fc066a8567100053f28ca8580384fc700438"
original_class_hash = "0x22d788f4a836d88ac5eb219aab1fc066a8567100053f28ca8580384fc700438"
base_class_hash = "0x0"
abi = "manifests/prod/base/abis/contracts/eternum-guild_systems-38e127d4.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-guild_systems"
systems = [
    "join_guild",
    "whitelist_player",
    "leave_guild",
    "transfer_guild_ownership",
    "remove_guild_member",
    "remove_player_from_whitelist",
]
manifest_name = "eternum-guild_systems-38e127d4"
