kind = "DojoContract"
class_hash = "0x3d34c4f65b2d71321a673540732c9854209b2585535656f9c3a292f3fe73eee"
original_class_hash = "0x3d34c4f65b2d71321a673540732c9854209b2585535656f9c3a292f3fe73eee"
base_class_hash = "0x0"
abi = "manifests/prod/base/abis/contracts/eternum-dev_bank_systems-7a630ec9.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-dev_bank_systems"
systems = []
manifest_name = "eternum-dev_bank_systems-7a630ec9"
