kind = "DojoContract"
class_hash = "0x244001a404ca3863c67421bfc75333c080ffb381cde1d083388431d4e2865b4"
original_class_hash = "0x244001a404ca3863c67421bfc75333c080ffb381cde1d083388431d4e2865b4"
base_class_hash = "0x0"
abi = "manifests/prod/base/abis/contracts/eternum-hyperstructure_systems-3660009a.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-hyperstructure_systems"
systems = [
    "contribute_to_construction",
    "set_co_owners",
]
manifest_name = "eternum-hyperstructure_systems-3660009a"
