kind = "DojoContract"
class_hash = "0x574732996ab5073ff265b7d1bdf6f0cff168007270439c9ff9e3845c3275d2a"
original_class_hash = "0x574732996ab5073ff265b7d1bdf6f0cff168007270439c9ff9e3845c3275d2a"
base_class_hash = "0x0"
abi = "manifests/prod/base/abis/contracts/eternum-building_systems-4b0f3026.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-building_systems"
systems = [
    "create",
    "pause_production",
    "resume_production",
    "destroy",
]
manifest_name = "eternum-building_systems-4b0f3026"
