kind = "DojoContract"
class_hash = "0x52fa112fe7ba8911c5f4cd0d6ba3ba612c1fe6fdfd0a16ab1f2dd75963c9a17"
original_class_hash = "0x52fa112fe7ba8911c5f4cd0d6ba3ba612c1fe6fdfd0a16ab1f2dd75963c9a17"
base_class_hash = "0x0"
abi = "manifests/prod/base/abis/contracts/eternum-config_systems-5f8c7cdc.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-config_systems"
systems = [
    "set_world_config",
    "set_mint_config",
    "set_map_config",
    "set_capacity_config",
    "set_travel_stamina_cost_config",
    "set_weight_config",
    "set_battle_config",
    "set_tick_config",
    "set_stamina_config",
    "set_stamina_refill_config",
    "set_leveling_config",
    "set_production_config",
    "set_speed_config",
    "set_hyperstructure_config",
    "set_bank_config",
    "set_troop_config",
    "set_building_category_pop_config",
    "set_population_config",
    "set_building_config",
    "set_mercenaries_config",
]
manifest_name = "eternum-config_systems-5f8c7cdc"
