kind = "DojoContract"
class_hash = "0x71eb3d17fa699da80155d87501ea9d683de1dea2a02661ee1d6547b5d1cd1ab"
original_class_hash = "0x71eb3d17fa699da80155d87501ea9d683de1dea2a02661ee1d6547b5d1cd1ab"
base_class_hash = "0x0"
abi = "manifests/prod/base/abis/contracts/eternum-name_systems-bbb2e543.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-name_systems"
systems = [
    "set_address_name",
    "set_entity_name",
]
manifest_name = "eternum-name_systems-bbb2e543"
