kind = "DojoContract"
class_hash = "0x38e8b0892ad3133ad0f7cdfa106455ca7ae4b58a803a311ad160221101dce7d"
original_class_hash = "0x38e8b0892ad3133ad0f7cdfa106455ca7ae4b58a803a311ad160221101dce7d"
base_class_hash = "0x0"
abi = "manifests/prod/base/abis/contracts/eternum-combat_systems-27f37676.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-combat_systems"
systems = [
    "army_delete",
    "army_buy_troops",
    "army_merge_troops",
    "battle_force_start",
    "battle_join",
    "battle_leave",
    "battle_claim",
    "battle_pillage",
]
manifest_name = "eternum-combat_systems-27f37676"
