kind = "DojoContract"
class_hash = "0x7fb8ee85e15a3438d6bd9af1fd0455a4db860427800dbd5b1468badaee56de4"
original_class_hash = "0x7fb8ee85e15a3438d6bd9af1fd0455a4db860427800dbd5b1468badaee56de4"
base_class_hash = "0x0"
abi = "manifests/prod/base/abis/contracts/eternum-resource_systems-59b73d5a.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-resource_systems"
systems = [
    "approve",
    "send",
    "pickup",
]
manifest_name = "eternum-resource_systems-59b73d5a"
