/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, type World } from "@dojoengine/recs";

export type ContractComponents = ReturnType<typeof defineContractComponents>;

export function defineContractComponents(world: World) {
  return {
    AddressName: (() => {
      return defineComponent(
        world,
        { address: RecsType.BigInt, name: RecsType.BigInt },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "AddressName",
            types: ["felt252", "felt252"],
            customTypes: [],
          },
        },
      );
    })(),
    Army: (() => {
      return defineComponent(
        world,
        {
          entity_id: RecsType.Number,
          troops: { knight_count: RecsType.BigInt, paladin_count: RecsType.BigInt, crossbowman_count: RecsType.BigInt },
          battle_id: RecsType.Number,
          battle_side: RecsType.String,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Army",
            types: ["u32", "u64", "u64", "u64", "u32", "enum"],
            customTypes: ["Troops", "BattleSide"],
          },
        },
      );
    })(),
    ArrivalTime: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, arrives_at: RecsType.BigInt },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "ArrivalTime",
            types: ["u32", "u64"],
            customTypes: [],
          },
        },
      );
    })(),
    Bank: (() => {
      return defineComponent(
        world,
        {
          entity_id: RecsType.Number,
          owner_fee_num: RecsType.BigInt,
          owner_fee_denom: RecsType.BigInt,
          owner_bridge_fee_dpt_percent: RecsType.Number,
          owner_bridge_fee_wtdr_percent: RecsType.Number,
          exists: RecsType.Boolean,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Bank",
            types: ["u32", "u128", "u128", "u16", "u16", "bool"],
            customTypes: [],
          },
        },
      );
    })(),
    Battle: (() => {
      return defineComponent(
        world,
        {
          entity_id: RecsType.Number,
          attack_army: {
            troops: {
              knight_count: RecsType.BigInt,
              paladin_count: RecsType.BigInt,
              crossbowman_count: RecsType.BigInt,
            },
            battle_id: RecsType.Number,
            battle_side: RecsType.String,
          },
          attack_army_lifetime: {
            troops: {
              knight_count: RecsType.BigInt,
              paladin_count: RecsType.BigInt,
              crossbowman_count: RecsType.BigInt,
            },
            battle_id: RecsType.Number,
            battle_side: RecsType.String,
          },
          defence_army: {
            troops: {
              knight_count: RecsType.BigInt,
              paladin_count: RecsType.BigInt,
              crossbowman_count: RecsType.BigInt,
            },
            battle_id: RecsType.Number,
            battle_side: RecsType.String,
          },
          defence_army_lifetime: {
            troops: {
              knight_count: RecsType.BigInt,
              paladin_count: RecsType.BigInt,
              crossbowman_count: RecsType.BigInt,
            },
            battle_id: RecsType.Number,
            battle_side: RecsType.String,
          },
          attackers_resources_escrow_id: RecsType.Number,
          defenders_resources_escrow_id: RecsType.Number,
          attack_army_health: { current: RecsType.BigInt, lifetime: RecsType.BigInt },
          defence_army_health: { current: RecsType.BigInt, lifetime: RecsType.BigInt },
          attack_delta: RecsType.BigInt,
          defence_delta: RecsType.BigInt,
          last_updated: RecsType.BigInt,
          duration_left: RecsType.BigInt,
          start_at: RecsType.BigInt,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Battle",
            types: [
              "u32",
              "u64",
              "u64",
              "u64",
              "u32",
              "enum",
              "u64",
              "u64",
              "u64",
              "u32",
              "enum",
              "u64",
              "u64",
              "u64",
              "u32",
              "enum",
              "u64",
              "u64",
              "u64",
              "u32",
              "enum",
              "u32",
              "u32",
              "u128",
              "u128",
              "u128",
              "u128",
              "u64",
              "u64",
              "u64",
              "u64",
              "u64",
            ],
            customTypes: [
              "BattleArmy",
              "Troops",
              "BattleSide",
              "BattleArmy",
              "Troops",
              "BattleSide",
              "BattleArmy",
              "Troops",
              "BattleSide",
              "BattleArmy",
              "Troops",
              "BattleSide",
              "BattleHealth",
              "BattleHealth",
            ],
          },
        },
      );
    })(),
    BattleConfig: (() => {
      return defineComponent(
        world,
        {
          config_id: RecsType.Number,
          regular_immunity_ticks: RecsType.Number,
          hyperstructure_immunity_ticks: RecsType.Number,
          battle_delay_seconds: RecsType.Number,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "BattleConfig",
            types: ["u32", "u8", "u8", "u64"],
            customTypes: [],
          },
        },
      );
    })(),
    Building: (() => {
      return defineComponent(
        world,
        {
          outer_col: RecsType.Number,
          outer_row: RecsType.Number,
          inner_col: RecsType.Number,
          inner_row: RecsType.Number,
          category: RecsType.String,
          produced_resource_type: RecsType.Number,
          bonus_percent: RecsType.Number,
          entity_id: RecsType.Number,
          outer_entity_id: RecsType.Number,
          paused: RecsType.Boolean,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Building",
            types: ["u32", "u32", "u32", "u32", "enum", "u8", "u32", "u32", "u32", "bool"],
            customTypes: ["BuildingCategory"],
          },
        },
      );
    })(),
    BuildingCategoryPopConfig: (() => {
      return defineComponent(
        world,
        {
          config_id: RecsType.Number,
          building_category: RecsType.String,
          population: RecsType.Number,
          capacity: RecsType.Number,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "BuildingCategoryPopConfig",
            types: ["u32", "enum", "u32", "u32"],
            customTypes: ["BuildingCategory"],
          },
        },
      );
    })(),
    BuildingConfig: (() => {
      return defineComponent(
        world,
        {
          config_id: RecsType.Number,
          category: RecsType.String,
          resource_type: RecsType.Number,
          resource_cost_id: RecsType.Number,
          resource_cost_count: RecsType.Number,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "BuildingConfig",
            types: ["u32", "enum", "u8", "u32", "u32"],
            customTypes: ["BuildingCategory"],
          },
        },
      );
    })(),
    BuildingQuantityv2: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, category: RecsType.String, value: RecsType.Number },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "BuildingQuantityv2",
            types: ["u32", "enum", "u8"],
            customTypes: ["BuildingCategory"],
          },
        },
      );
    })(),
    CapacityConfig: (() => {
      return defineComponent(
        world,
        {
          category: RecsType.String,
          weight_gram: RecsType.BigInt,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "CapacityConfig",
            types: ["enum", "u128"],
            customTypes: ["CapacityConfig"],
          },
        },
      );
    })(),
    Contribution: (() => {
      return defineComponent(
        world,
        {
          hyperstructure_entity_id: RecsType.Number,
          player_address: RecsType.BigInt,
          resource_type: RecsType.Number,
          amount: RecsType.BigInt,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Contribution",
            types: ["u32", "contractaddress", "u8", "u128"],
            customTypes: [],
          },
        },
      );
    })(),
    DetachedResource: (() => {
      return defineComponent(
        world,
        {
          entity_id: RecsType.Number,
          index: RecsType.Number,
          resource_type: RecsType.Number,
          resource_amount: RecsType.BigInt,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "DetachedResource",
            types: ["u32", "u32", "u8", "u128"],
            customTypes: [],
          },
        },
      );
    })(),
    EntityName: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, name: RecsType.BigInt },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "EntityName",
            types: ["u32", "felt252"],
            customTypes: [],
          },
        },
      );
    })(),
    EntityOwner: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, entity_owner_id: RecsType.Number },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "EntityOwner",
            types: ["u32", "u32"],
            customTypes: [],
          },
        },
      );
    })(),
    Epoch: (() => {
      return defineComponent(
        world,
        {
          hyperstructure_entity_id: RecsType.Number,
          index: RecsType.Number,
          start_timestamp: RecsType.BigInt,
          owners: RecsType.BigIntArray,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Epoch",
            types: ["u32", "u16", "u64", "array"],
            customTypes: [],
          },
        },
      );
    })(),
    Guild: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, is_public: RecsType.Boolean, member_count: RecsType.Number },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Guild",
            types: ["u32", "bool", "u16"],
            customTypes: [],
          },
        },
      );
    })(),
    GuildMember: (() => {
      return defineComponent(
        world,
        { address: RecsType.BigInt, guild_entity_id: RecsType.Number },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "GuildMember",
            types: ["contractaddress", "u32"],
            customTypes: [],
          },
        },
      );
    })(),
    GuildWhitelist: (() => {
      return defineComponent(
        world,
        { address: RecsType.BigInt, guild_entity_id: RecsType.Number, is_whitelisted: RecsType.Boolean },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "GuildWhitelist",
            types: ["contractaddress", "u32", "bool"],
            customTypes: [],
          },
        },
      );
    })(),
    Health: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, current: RecsType.BigInt, lifetime: RecsType.BigInt },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Health",
            types: ["u32", "u128", "u128"],
            customTypes: [],
          },
        },
      );
    })(),
    Hyperstructure: (() => {
      return defineComponent(
        world,
        {
          entity_id: RecsType.Number,
          current_epoch: RecsType.Number,
          completed: RecsType.Boolean,
          last_updated_by: RecsType.BigInt,
          last_updated_timestamp: RecsType.Number,
          access: RecsType.String,
          randomness: RecsType.BigInt,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Hyperstructure",
            types: ["u32", "u16", "bool", "contractaddress", "u64", "enum", "felt252"],
            customTypes: ["Access"],
          },
        },
      );
    })(),
    HyperstructureResourceConfig: (() => {
      return defineComponent(
        world,
        {
          config_id: RecsType.Number,
          resource_tier: RecsType.Number,
          min_amount: RecsType.BigInt,
          max_amount: RecsType.BigInt,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "HyperstructureResourceConfig",
            types: ["u32", "u8", "u128", "u128"],
            customTypes: [],
          },
        },
      );
    })(),
    Leaderboard: (() => {
      return defineComponent(
        world,
        {
          config_id: RecsType.Number,
          registration_end_timestamp: RecsType.Number,
          total_points: RecsType.BigInt,
          total_price_pool: RecsType.OptionalBigInt,
          distribution_started: RecsType.Boolean,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Leaderboard",
            types: ["u32", "u64", "u128", "u256", "bool"],
            customTypes: [],
          },
        },
      );
    })(),

    LeaderboardEntry: (() => {
      return defineComponent(
        world,
        {
          address: RecsType.BigInt,
          points: RecsType.BigInt,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "LeaderboardEntry",
            types: ["contractaddress", "u128"],
            customTypes: [],
          },
        },
      );
    })(),

    LeaderboardRewardClaimed: (() => {
      return defineComponent(
        world,
        {
          address: RecsType.BigInt,
          claimed: RecsType.Boolean,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "LeaderboardRewardClaimed",
            types: ["contractaddress", "bool"],
            customTypes: [],
          },
        },
      );
    })(),

    LeaderboardRegistered: (() => {
      return defineComponent(
        world,
        {
          address: RecsType.BigInt,
          registered: RecsType.Boolean,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "LeaderboardRegistered",
            types: ["contractaddress", "bool"],
            customTypes: [],
          },
        },
      );
    })(),

    LeaderboardRegisterContribution: (() => {
      return defineComponent(
        world,
        {
          address: RecsType.BigInt,
          hyperstructure_entity_id: RecsType.Number,
          registered: RecsType.Boolean,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "LeaderboardRegisterContribution",
            types: ["contractaddress", "u32", "bool"],
            customTypes: [],
          },
        },
      );
    })(),

    LeaderboardRegisterShare: (() => {
      return defineComponent(
        world,
        {
          address: RecsType.BigInt,
          hyperstructure_entity_id: RecsType.Number,
          epoch: RecsType.Number,
          registered: RecsType.Boolean,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "LeaderboardRegisterShare",
            types: ["contractaddress", "u32", "u16", "bool"],
            customTypes: [],
          },
        },
      );
    })(),

    Liquidity: (() => {
      return defineComponent(
        world,
        {
          bank_entity_id: RecsType.Number,
          player: RecsType.BigInt,
          resource_type: RecsType.Number,
          shares: { mag: RecsType.BigInt, sign: RecsType.Boolean },
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Liquidity",
            types: ["u32", "contractaddress", "u8", "u128", "bool"],
            customTypes: ["Fixed"],
          },
        },
      );
    })(),
    Market: (() => {
      return defineComponent(
        world,
        {
          bank_entity_id: RecsType.Number,
          resource_type: RecsType.Number,
          lords_amount: RecsType.BigInt,
          resource_amount: RecsType.BigInt,
          total_shares: { mag: RecsType.BigInt, sign: RecsType.Boolean },
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Market",
            types: ["u32", "u8", "u128", "u128", "u128", "bool"],
            customTypes: ["Fixed"],
          },
        },
      );
    })(),
    Message: (() => {
      return defineComponent(
        world,
        {
          identity: RecsType.BigInt,
          channel: RecsType.BigInt,
          content: RecsType.String,
          salt: RecsType.BigInt,
          timestamp: RecsType.Number,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Message",
            types: ["felt252", "felt252", "BytesArray", "felt252", "u64"],
            customTypes: [],
          },
        },
      );
    })(),
    Movable: (() => {
      return defineComponent(
        world,
        {
          entity_id: RecsType.Number,
          entity_type: RecsType.Number,
          blocked: RecsType.Boolean,
          round_trip: RecsType.Boolean,
          start_coord_x: RecsType.Number,
          start_coord_y: RecsType.Number,
          intermediate_coord_x: RecsType.Number,
          intermediate_coord_y: RecsType.Number,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Movable",
            types: ["u32", "u32", "bool", "bool", "u32", "u32", "u32", "u32"],
            customTypes: [],
          },
        },
      );
    })(),
    Orders: (() => {
      return defineComponent(
        world,
        { order_id: RecsType.Number, hyperstructure_count: RecsType.Number },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Orders",
            types: ["u32", "u32"],
            customTypes: [],
          },
        },
      );
    })(),
    OwnedResourcesTracker: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, resource_types: RecsType.BigInt },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "OwnedResourcesTracker",
            types: ["u32", "u256"],
            customTypes: [],
          },
        },
      );
    })(),
    Owner: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, address: RecsType.BigInt },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Owner",
            types: ["u32", "contractaddress"],
            customTypes: [],
          },
        },
      );
    })(),
    Population: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, population: RecsType.Number, capacity: RecsType.Number },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Population",
            types: ["u32", "u32", "u32"],
            customTypes: [],
          },
        },
      );
    })(),
    Position: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, x: RecsType.Number, y: RecsType.Number },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Position",
            types: ["u32", "u32", "u32"],
            customTypes: [],
          },
        },
      );
    })(),
    ProductionConfig: (() => {
      return defineComponent(
        world,
        {
          resource_type: RecsType.Number,
          amount_per_building_per_tick: RecsType.BigInt,
          labor_burn_strategy: {
            resource_rarity: RecsType.BigInt,
            depreciation_percent_num: RecsType.Number,
            depreciation_percent_denom: RecsType.Number,
            wheat_burn_per_labor: RecsType.BigInt,
            fish_burn_per_labor: RecsType.BigInt,
          },
          multiple_resource_burn_strategy: {
            required_resources_id: RecsType.Number,
            required_resources_count: RecsType.Number,
          },
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "ProductionConfig",
            types: ["u8", "u128", "u128", "u16", "u16", "u128", "u128", "u32", "u8"],
            customTypes: ["LaborBurnPrStrategy", "MultipleResourceBurnPrStrategy"],
          },
        },
      );
    })(),
    Progress: (() => {
      return defineComponent(
        world,
        { hyperstructure_entity_id: RecsType.Number, resource_type: RecsType.Number, amount: RecsType.BigInt },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Progress",
            types: ["u32", "u8", "u128"],
            customTypes: [],
          },
        },
      );
    })(),
    Protectee: (() => {
      return defineComponent(
        world,
        { army_id: RecsType.Number, protectee_id: RecsType.Number },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Protectee",
            types: ["u32", "u32"],
            customTypes: [],
          },
        },
      );
    })(),
    Protector: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, army_id: RecsType.Number },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Protector",
            types: ["u32", "u32"],
            customTypes: [],
          },
        },
      );
    })(),
    Quantity: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, value: RecsType.BigInt },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Quantity",
            types: ["u32", "u128"],
            customTypes: [],
          },
        },
      );
    })(),
    QuantityTracker: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.BigInt, count: RecsType.BigInt },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "QuantityTracker",
            types: ["felt252", "u128"],
            customTypes: [],
          },
        },
      );
    })(),
    Quest: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, config_id: RecsType.Number, completed: RecsType.Boolean },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Quest",
            types: ["u32", "u32", "bool"],
            customTypes: [],
          },
        },
      );
    })(),
    QuestRewardConfig: (() => {
      return defineComponent(
        world,
        { quest_id: RecsType.Number, detached_resource_id: RecsType.Number, detached_resource_count: RecsType.Number },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "QuestRewardConfig",
            types: ["u32", "u32", "u32"],
            customTypes: [],
          },
        },
      );
    })(),
    Realm: (() => {
      return defineComponent(
        world,
        {
          entity_id: RecsType.Number,
          realm_id: RecsType.Number,
          produced_resources: RecsType.BigInt,
          order: RecsType.Number,
          level: RecsType.Number,
          has_wonder: RecsType.Boolean,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Realm",
            types: ["u32", "u32", "u128", "u8", "u8", "bool"],
            customTypes: [],
          },
        },
      );
    })(),
    RealmLevelConfig: (() => {
      return defineComponent(
        world,
        { level: RecsType.Number, required_resources_id: RecsType.Number, required_resource_count: RecsType.Number },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "RealmLevelConfig",
            types: ["u8", "u32", "u8"],
            customTypes: [],
          },
        },
      );
    })(),
    Resource: (() => {
      return defineComponent(
        world,
        {
          entity_id: RecsType.Number,
          resource_type: RecsType.Number,
          balance: RecsType.BigInt,
          production: {
            building_count: RecsType.Number,
            production_rate: RecsType.BigInt,
            output_amount_left: RecsType.BigInt,
            last_updated_at: RecsType.Number,
          },
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Resource",
            types: ["u32", "u8", "u128", "u8", "u64", "u128", "u32"],
            customTypes: [],
          },
        },
      );
    })(),
    ResourceAllowance: (() => {
      return defineComponent(
        world,
        {
          owner_entity_id: RecsType.Number,
          approved_entity_id: RecsType.Number,
          resource_type: RecsType.Number,
          amount: RecsType.BigInt,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "ResourceAllowance",
            types: ["u32", "u32", "u8", "u128"],
            customTypes: [],
          },
        },
      );
    })(),
    ResourceBridgeWhitelistConfig: (() => {
      return defineComponent(
        world,
        {
          token: RecsType.BigInt,
          resource_type: RecsType.Number,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "ResourceBridgeWhitelistConfig",
            types: ["ContractAddress", "u8"],
            customTypes: [],
          },
        },
      );
    })(),
    ResourceCost: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, index: RecsType.Number, resource_type: RecsType.Number, amount: RecsType.BigInt },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "ResourceCost",
            types: ["u32", "u32", "u8", "u128"],
            customTypes: [],
          },
        },
      );
    })(),
    ResourceTransferLock: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, start_at: RecsType.BigInt, release_at: RecsType.BigInt },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "ResourceTransferLock",
            types: ["u32", "u64", "u64"],
            customTypes: [],
          },
        },
      );
    })(),
    Season: (() => {
      return defineComponent(
        world,
        {
          config_id: RecsType.Number,
          start_at: RecsType.BigInt,
          is_over: RecsType.Boolean,
          ended_at: RecsType.BigInt,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Season",
            types: ["u32", "u64", "bool", "u64"],
            customTypes: [],
          },
        },
      );
    })(),
    Stamina: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, amount: RecsType.Number, last_refill_tick: RecsType.BigInt },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Stamina",
            types: ["u32", "u16", "u64"],
            customTypes: [],
          },
        },
      );
    })(),
    StaminaConfig: (() => {
      return defineComponent(
        world,
        { config_id: RecsType.Number, unit_type: RecsType.Number, max_stamina: RecsType.Number },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "StaminaConfig",
            types: ["u32", "u8", "u16"],
            customTypes: [],
          },
        },
      );
    })(),
    Status: (() => {
      return defineComponent(
        world,
        { trade_id: RecsType.Number, value: RecsType.BigInt },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Status",
            types: ["u32", "u128"],
            customTypes: [],
          },
        },
      );
    })(),
    Structure: (() => {
      return defineComponent(
        world,
        {
          entity_id: RecsType.Number,
          category: RecsType.String,
          owner: RecsType.BigInt,
          coord: { x: RecsType.Number, y: RecsType.Number },
          guards: {
            delta: {
              category: RecsType.String,
              tier: RecsType.String,
              count: RecsType.BigInt,
              stamina: {
                amount: RecsType.BigInt,
                updated_tick: RecsType.BigInt,
              },
            },
            charlie: {
              category: RecsType.String,
              tier: RecsType.String,
              count: RecsType.BigInt,
              stamina: {
                amount: RecsType.BigInt,
                updated_tick: RecsType.BigInt,
              },
            },
            bravo: {
              category: RecsType.String,
              tier: RecsType.String,
              count: RecsType.BigInt,
              stamina: {
                amount: RecsType.BigInt,
                updated_tick: RecsType.BigInt,
              },
            },
            alpha: {
              category: RecsType.String,
              tier: RecsType.String,
              count: RecsType.BigInt,
              stamina: {
                amount: RecsType.BigInt,
                updated_tick: RecsType.BigInt,
              },
            },
            delta_destroyed_tick: RecsType.Number,
            charlie_destroyed_tick: RecsType.Number,
            bravo_destroyed_tick: RecsType.Number,
            alpha_destroyed_tick: RecsType.Number,
          },
          limits: {
            max_explorer_count: RecsType.Number,
            max_guard_count: RecsType.Number,
          },
          created_at: RecsType.BigInt,
          guard_count: RecsType.Number,
          explorers: RecsType.NumberArray,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Structure",
            types: [
              "u32",
              "enum",
              "ContractAddress",
              "u32",
              "u32",
              //delta
              "enum",
              "enum",
              "u128",
              "u64",
              "u64",
              //charlie
              "enum",
              "enum",
              "u128",
              "u64",
              "u64",
              //bravo
              "enum",
              "enum",
              "u128",
              "u64",
              "u64",
              //alpha
              "enum",
              "enum",
              "u128",
              "u64",
              "u64",
              //destroyed_ticks
              "u32",
              "u32",
              "u32",
              "u32",
              //limits
              "u32",
              "u32",
              //created_at
              "u64",
              //guard_count
              "u32",
              //explorers
              "Span<u32>",
            ],
            customTypes: ["StructureCategory", "Coord", "GuardTroops","Troops",  "TroopType","TroopTier", "Stamina", "Limits"],
          },
        },
      );
    })(),
    Tile: (() => {
      return defineComponent(
        world,
        {
          col: RecsType.Number,
          row: RecsType.Number,
          biome: RecsType.String,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Tile",
            types: ["u32", "u32", "enum"],
            customTypes: ["Biome"],
          },
        },
      );
    })(),
    Trade: (() => {
      return defineComponent(
        world,
        {
          trade_id: RecsType.Number,
          maker_id: RecsType.Number,
          maker_gives_resources_origin_id: RecsType.Number,
          maker_gives_resources_id: RecsType.Number,
          maker_gives_resources_hash: RecsType.BigInt,
          maker_gives_resources_weight: RecsType.BigInt,
          taker_id: RecsType.Number,
          taker_gives_resources_origin_id: RecsType.Number,
          taker_gives_resources_id: RecsType.Number,
          taker_gives_resources_hash: RecsType.BigInt,
          taker_gives_resources_weight: RecsType.BigInt,
          expires_at: RecsType.BigInt,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Trade",
            types: ["u32", "u32", "u32", "u32", "felt252", "u128", "u32", "u32", "u32", "felt252", "u128", "u64"],
            customTypes: [],
          },
        },
      );
    })(),
    TravelFoodCostConfig: (() => {
      return defineComponent(
        world,
        {
          config_id: RecsType.Number,
          unit_type: RecsType.Number,
          explore_wheat_burn_amount: RecsType.BigInt,
          explore_fish_burn_amount: RecsType.BigInt,
          travel_wheat_burn_amount: RecsType.BigInt,
          travel_fish_burn_amount: RecsType.BigInt,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "TravelFoodCostConfig",
            types: ["u32", "u8", "u128", "u128", "u128", "u128"],
            customTypes: [],
          },
        },
      );
    })(),
    TravelStaminaCostConfig: (() => {
      return defineComponent(
        world,
        {
          config_id: RecsType.Number,
          travel_type: RecsType.Number,
          cost: RecsType.Number,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "TravelStaminaCostConfig",
            types: ["u32", "u8", "u16"],
            customTypes: [],
          },
        },
      );
    })(),
    TroopConfig: (() => {
      return defineComponent(
        world,
        {
          config_id: RecsType.Number,
          health: RecsType.Number,
          knight_strength: RecsType.Number,
          paladin_strength: RecsType.Number,
          crossbowman_strength: RecsType.Number,
          advantage_percent: RecsType.Number,
          disadvantage_percent: RecsType.Number,
          max_troop_count: RecsType.Number,
          pillage_health_divisor: RecsType.Number,
          army_free_per_structure: RecsType.Number,
          army_extra_per_building: RecsType.Number,
          army_max_per_structure: RecsType.Number,
          battle_leave_slash_num: RecsType.Number,
          battle_leave_slash_denom: RecsType.Number,
          battle_time_scale: RecsType.Number,
          battle_max_time_seconds: RecsType.Number,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "TroopConfig",
            types: [
              "u32",
              "u32",
              "u8",
              "u8",
              "u16",
              "u16",
              "u16",
              "u64",
              "u8",
              "u8",
              "u8",
              "u8",
              "u8",
              "u8",
              "u16",
              "u64",
            ],
            customTypes: [],
          },
        },
      );
    })(),
    Weight: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.Number, value: RecsType.BigInt, capacity_category: RecsType.String },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "Weight",
            types: ["u32", "u128", "enum"],
            customTypes: ["CapacityCategory"],
          },
        },
      );
    })(),
    WeightConfig: (() => {
      return defineComponent(
        world,
        {
          config_id: RecsType.Number,
          weight_config_id: RecsType.Number,
          entity_type: RecsType.Number,
          weight_gram: RecsType.BigInt,
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "WeightConfig",
            types: ["u32", "u32", "u32", "u128"],
            customTypes: [],
          },
        },
      );
    })(),
    WorldConfig: (() => {
      return defineComponent(
        world,
        {
          config_id: RecsType.Number,
          admin_address: RecsType.BigInt,
          vrf_provider_address: RecsType.BigInt,
          season_addresses_config: {
            season_pass_address: RecsType.BigInt,
            realms_address: RecsType.BigInt,
            lords_address: RecsType.BigInt,
          },
          season_bridge_config: {
            close_after_end_seconds: RecsType.Number,
          },
          hyperstructure_config: {
            points_per_cycle: RecsType.Number,
            points_for_win: RecsType.Number,
            points_on_completion: RecsType.Number,
            time_between_shares_change: RecsType.Number,
          },
          stamina_cost_config: {
            travel_cost: RecsType.Number,
            explore_cost: RecsType.Number,
          },
          speed_config: {
            donkey_sec_per_km: RecsType.Number,
            army_sec_per_km: RecsType.Number,
          },
          map_config: {
            reward_resource_amount: RecsType.Number,
            shards_mines_fail_probability: RecsType.Number,
          },
          settlement_config: {
            center: RecsType.Number,
            base_distance: RecsType.Number,
            min_first_layer_distance: RecsType.Number,
            points_placed: RecsType.Number,
            current_layer: RecsType.Number,
            current_side: RecsType.Number,
            current_point_on_side: RecsType.Number,
          },
          tick_config: {
            default_tick_in_seconds: RecsType.Number,
            armies_tick_in_seconds: RecsType.Number,
          },
          mercenaries_config: {
            knights_lower_bound: RecsType.Number,
            knights_upper_bound: RecsType.Number,
            paladins_lower_bound: RecsType.Number,
            paladins_upper_bound: RecsType.Number,
            crossbowmen_lower_bound: RecsType.Number,
            crossbowmen_upper_bound: RecsType.Number,
            rewards: RecsType.StringArray,
          },
          bank_config: {
            lords_cost: RecsType.Number,
            lp_fee_num: RecsType.Number,
            lp_fee_denom: RecsType.Number,
          },
          population_config: {
            base_population: RecsType.Number,
          },
          resource_bridge_config: {
            deposit_paused: RecsType.Number,
            withdraw_paused: RecsType.Number,
          },
          res_bridge_fee_split_config: {
            velords_fee_on_dpt_percent: RecsType.Number,
            velords_fee_on_wtdr_percent: RecsType.Number,
            season_pool_fee_on_dpt_percent: RecsType.Number,
            season_pool_fee_on_wtdr_percent: RecsType.Number,
            client_fee_on_dpt_percent: RecsType.Number,
            client_fee_on_wtdr_percent: RecsType.Number,
            max_bank_fee_dpt_percent: RecsType.Number,
            max_bank_fee_wtdr_percent: RecsType.Number,
            velords_fee_recipient: RecsType.BigInt,
            season_pool_fee_recipient: RecsType.BigInt,
          },
          realm_max_level_config: {
            max_level: RecsType.Number,
          },
          stamina_refill_config: {
            amount_per_tick: RecsType.Number,
            start_boost_tick_count: RecsType.Number,
          },
          building_general_config: {
            base_cost_percent_increase: RecsType.Number,
          },
        },
        {
          metadata: {
            namespace: "s1_eternum",
            name: "WorldConfig",
            types: [
              "u32", // config_id
              "ContractAddress", // admin_address
              "ContractAddress", // vrf_provider_address
              "ContractAddress", // season_pass_address
              "ContractAddress", // realms_address
              "ContractAddress", // lords_address
              "u64", // SeasonBridgeConfig close_after_end_seconds
              "u128", // HyperstructureConfig points_per_cycle
              "u128", // HyperstructureConfig points_for_win
              "u128", // HyperstructureConfig points_on_completion
              "u64", // HyperstructureConfig time_between_shares_change
              "u16", // SpeedConfig donkey_sec_per_km
              "u128", // MapConfig reward_resource_amount
              "u128", // MapConfig shards_mines_fail_probability
              "u128", // MapConfig mine_wheat_grant_amount
              "u128", // MapConfig mine_fish_grant_amount
              "u32", // SettlementConfig center
              "u32", // SettlementConfig base_distance
              "u32", // SettlementConfig min_first_layer_distance
              "u32", // SettlementConfig points_placed
              "u32", // SettlementConfig current_layer
              "u32", // SettlementConfig current_side
              "u32", // SettlementConfig current_point_on_side
              "u64", // TickConfig armies_tick_in_seconds
              "u128", // BankConfig lords_cost
              "u128", // BankConfig lp_fee_num
              "u128", // BankConfig lp_fee_denom
              "u32", // PopulationConfig base_population
              "bool", // ResourceBridgeConfig deposit_paused
              "bool", // ResourceBridgeConfig withdraw_paused
              "u16", // ResourceBridgeFeeSplitConfig velords_fee_on_dpt_percent
              "u16", // ResourceBridgeFeeSplitConfig velords_fee_on_wtdr_percent
              "u16", // ResourceBridgeFeeSplitConfig season_pool_fee_on_dpt_percent
              "u16", // ResourceBridgeFeeSplitConfig season_pool_fee_on_wtdr_percent
              "u16", // ResourceBridgeFeeSplitConfig client_fee_on_dpt_percent
              "u16", // ResourceBridgeFeeSplitConfig client_fee_on_wtdr_percent
              "u16", // ResourceBridgeFeeSplitConfig max_bank_fee_dpt_percent
              "u16", // ResourceBridgeFeeSplitConfig max_bank_fee_wtdr_percent
              "ContractAddress", // ResourceBridgeFeeSplitConfig velords_fee_recipient
              "ContractAddress", // ResourceBridgeFeeSplitConfig season_pool_fee_recipient
              "u8", // RealmMaxLevelConfig max_level
              "u16", // BuildingGeneralConfig base_cost_percent_increase
              "u16", // TroopDamageConfig damage_biome_bonus_num
              "u64", // TroopDamageConfig damage_beta_small
              "u64", // TroopDamageConfig damage_beta_large
              "u128", // TroopDamageConfig damage_scaling_factor
              "u128", // TroopDamageConfig damage_c0
              "u128", // TroopDamageConfig damage_delta
              "u128", // TroopDamageConfig t1_damage_value
              "u128", // TroopDamageConfig t2_damage_multiplier
              "u16", // TroopDamageConfig t3_damage_multiplier
              "u16", // TroopStaminaConfig stamina_gain_per_tick
              "u16", // TroopStaminaConfig stamina_initial
              "u16", // TroopStaminaConfig stamina_bonus_value
              "u16", // TroopStaminaConfig stamina_knight_max
              "u16", // TroopStaminaConfig stamina_paladin_max
              "u16", // TroopStaminaConfig stamina_crossbowman_max
              "u16", // TroopStaminaConfig stamina_attack_req
              "u16", // TroopStaminaConfig stamina_attack_max
              "u16", // TroopStaminaConfig stamina_explore_wheat_cost
              "u16", // TroopStaminaConfig stamina_explore_fish_cost
              "u16", // TroopStaminaConfig stamina_explore_stamina_cost
              "u16", // TroopStaminaConfig stamina_travel_wheat_cost
              "u16", // TroopStaminaConfig stamina_travel_fish_cost
              "u16", // TroopStaminaConfig stamina_travel_stamina_cost
              "u8", // TroopLimitConfig explorer_max_party_count
              "u32", // TroopLimitConfig explorer_max_troop_count
              "u32", // TroopLimitConfig guard_resurrection_delay
              "u64", // TroopLimitConfig mercenaries_troop_lower_bound
              "u64", // TroopLimitConfig mercenaries_troop_upper_bound
              "u32", // CapacityConfig structure_capacity
              "u32", // CapacityConfig troop_capacity
              "u32", // CapacityConfig donkey_capacity
              "u32", // CapacityConfig storehouse_boost_capacity
              "u8", // TradeCountConfig max_count
            ],
            customTypes: [],
          },
        },
      );
    })(),
    ...eventsComponents(world),
  };
}

const eventsComponents = (world: World) => {
  return {
    events: {
      AcceptOrder: (() => {
        return defineComponent(
          world,
          {
            taker_id: RecsType.Number,
            maker_id: RecsType.Number,
            id: RecsType.Number,
            trade_id: RecsType.Number,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "AcceptOrder",
              types: ["u32", "u32", "u32", "u32", "u64"],
              customTypes: [],
            },
          },
        );
      })(),

      BattleClaimData: (() => {
        return defineComponent(
          world,
          {
            id: RecsType.Number,
            event_id: RecsType.String,
            structure_entity_id: RecsType.Number,
            claimer: RecsType.BigInt,
            claimer_name: RecsType.BigInt,
            claimer_army_entity_id: RecsType.Number,
            claimee_address: RecsType.BigInt,
            claimee_name: RecsType.BigInt,
            x: RecsType.Number,
            y: RecsType.Number,
            structure_type: RecsType.String,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "BattleClaimData",
              types: [
                "u32",
                "EventType",
                "u32",
                "ContractAddress",
                "felt252",
                "u32",
                "ContractAddress",
                "felt252",
                "u32",
                "u32",
                "StructureCategory",
                "u64",
              ],
              customTypes: [],
            },
          },
        );
      })(),

      BattleJoinData: (() => {
        return defineComponent(
          world,
          {
            id: RecsType.Number,
            event_id: RecsType.String,
            battle_entity_id: RecsType.Number,
            joiner: RecsType.BigInt,
            joiner_name: RecsType.BigInt,
            joiner_army_entity_id: RecsType.Number,
            joiner_side: RecsType.String,
            duration_left: RecsType.Number,
            x: RecsType.Number,
            y: RecsType.Number,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "BattleJoinData",
              types: [
                "u32",
                "EventType",
                "u32",
                "ContractAddress",
                "felt252",
                "u32",
                "BattleSide",
                "u64",
                "u32",
                "u32",
                "u64",
              ],
              customTypes: [],
            },
          },
        );
      })(),

      BattleLeaveData: (() => {
        return defineComponent(
          world,
          {
            id: RecsType.Number,
            event_id: RecsType.String,
            battle_entity_id: RecsType.Number,
            leaver: RecsType.BigInt,
            leaver_name: RecsType.BigInt,
            leaver_army_entity_id: RecsType.Number,
            leaver_side: RecsType.String,
            duration_left: RecsType.Number,
            x: RecsType.Number,
            y: RecsType.Number,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "BattleLeaveData",
              types: [
                "u32",
                "EventType",
                "u32",
                "ContractAddress",
                "felt252",
                "u32",
                "BattleSide",
                "u64",
                "u32",
                "u32",
                "u64",
              ],
              customTypes: [],
            },
          },
        );
      })(),

      BattlePillageData: (() => {
        return defineComponent(
          world,
          {
            id: RecsType.Number,
            event_id: RecsType.String,
            pillager: RecsType.BigInt,
            pillager_name: RecsType.BigInt,
            pillager_realm_entity_id: RecsType.Number,
            pillager_army_entity_id: RecsType.Number,
            pillaged_structure_owner: RecsType.BigInt,
            pillaged_structure_entity_id: RecsType.Number,
            attacker_lost_troops: {
              knight_count: RecsType.BigInt,
              paladin_count: RecsType.BigInt,
              crossbowman_count: RecsType.BigInt,
            },
            structure_lost_troops: {
              knight_count: RecsType.BigInt,
              paladin_count: RecsType.BigInt,
              crossbowman_count: RecsType.BigInt,
            },
            pillaged_structure_owner_name: RecsType.BigInt,
            winner: RecsType.String,
            x: RecsType.Number,
            y: RecsType.Number,
            structure_type: RecsType.String,
            pillaged_resources: RecsType.StringArray,
            destroyed_building_category: RecsType.String,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "BattlePillageData",
              types: [
                "u32",
                "EventType",
                "ContractAddress",
                "felt252",
                "u32",
                "u32",
                "ContractAddress",
                "u32",
                // attacking troops
                "u64",
                "u64",
                "u64",
                // structure troops
                "u64",
                "u64",
                "u64",
                "felt252",
                "BattleSide",
                "u32",
                "u32",
                "StructureCategory",
                "array",
                "enum",
                "u64",
              ],
              customTypes: ["Troops", "BuildingCategory"],
            },
          },
        );
      })(),

      BattleStartData: (() => {
        return defineComponent(
          world,
          {
            id: RecsType.Number,
            event_id: RecsType.String,
            battle_entity_id: RecsType.Number,
            attacker: RecsType.BigInt,
            attacker_name: RecsType.BigInt,
            attacker_army_entity_id: RecsType.Number,
            defender_name: RecsType.BigInt,
            defender: RecsType.BigInt,
            defender_army_entity_id: RecsType.Number,
            duration_left: RecsType.Number,
            x: RecsType.Number,
            y: RecsType.Number,
            structure_type: RecsType.String,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "BattleStartData",
              types: [
                "u32",
                "EventType",
                "u32",
                "ContractAddress",
                "felt252",
                "u32",
                "felt252",
                "ContractAddress",
                "u32",
                "u64",
                "u32",
                "u32",
                "StructureCategory",
                "u64",
              ],
              customTypes: [],
            },
          },
        );
      })(),

      BurnDonkey: (() => {
        return defineComponent(
          world,
          {
            player_address: RecsType.BigInt,
            entity_id: RecsType.Number,
            amount: RecsType.BigInt,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "BurnDonkey",
              types: ["ContractAddress", "u32", "u128", "u64"],
              customTypes: [],
            },
          },
        );
      })(),

      CreateGuild: (() => {
        return defineComponent(
          world,
          {
            guild_entity_id: RecsType.Number,
            guild_name: RecsType.BigInt,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "CreateGuild",
              types: ["u32", "felt252", "u64"],
              customTypes: [],
            },
          },
        );
      })(),

      GameEnded: (() => {
        return defineComponent(
          world,
          {
            winner_address: RecsType.BigInt,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "GameEnded",
              types: ["ContractAddress", "u64"],
              customTypes: [],
            },
          },
        );
      })(),

      HyperstructureContribution: (() => {
        return defineComponent(
          world,
          {
            id: RecsType.Number,
            hyperstructure_entity_id: RecsType.Number,
            contributor_entity_id: RecsType.Number,
            contributions: RecsType.StringArray,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "HyperstructureContribution",
              types: ["u32", "u32", "u32", "array", "u64"],
              customTypes: [],
            },
          },
        );
      })(),

      HyperstructureFinished: (() => {
        return defineComponent(
          world,
          {
            id: RecsType.Number,
            hyperstructure_entity_id: RecsType.Number,
            contributor_entity_id: RecsType.Number,
            timestamp: RecsType.Number,
            hyperstructure_owner_name: RecsType.BigInt,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "HyperstructureFinished",
              types: ["u32", "u32", "u32", "felt252", "u64"],
              customTypes: [],
            },
          },
        );
      })(),

      JoinGuild: (() => {
        return defineComponent(
          world,
          {
            guild_entity_id: RecsType.Number,
            address: RecsType.BigInt,
            guild_name: RecsType.BigInt,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "JoinGuild",
              types: ["u32", "ContractAddress", "felt252", "u64"],
              customTypes: [],
            },
          },
        );
      })(),

      LiquidityEvent: (() => {
        return defineComponent(
          world,
          {
            bank_entity_id: RecsType.Number,
            entity_id: RecsType.Number,
            resource_type: RecsType.Number,
            lords_amount: RecsType.BigInt,
            resource_amount: RecsType.BigInt,
            resource_price: RecsType.BigInt,
            add: RecsType.Boolean,
            timestamp: RecsType.BigInt,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "LiquidityEvent",
              types: ["u32", "u32", "u8", "u128", "u128", "u128", "bool", "u64"],
              customTypes: [],
            },
          },
        );
      })(),

      MapExplored: (() => {
        return defineComponent(
          world,
          {
            entity_id: RecsType.Number,
            col: RecsType.Number,
            row: RecsType.Number,
            id: RecsType.Number,
            entity_owner_id: RecsType.Number,
            biome: RecsType.String,
            reward: RecsType.StringArray,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "MapExplored",
              types: ["u32", "u32", "u32", "u32", "u32", "Biome", "array", "u64"],
              customTypes: [],
            },
          },
        );
      })(),

      SwapEvent: (() => {
        return defineComponent(
          world,
          {
            bank_entity_id: RecsType.Number,
            entity_id: RecsType.Number,
            id: RecsType.Number,
            resource_type: RecsType.Number,
            lords_amount: RecsType.BigInt,
            resource_amount: RecsType.BigInt,
            bank_owner_fees: RecsType.BigInt,
            lp_fees: RecsType.BigInt,
            resource_price: RecsType.BigInt,
            buy: RecsType.Boolean,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "SwapEvent",
              types: ["u32", "u32", "u32", "u8", "u128", "u128", "u128", "u128", "u128", "bool", "u64"],
              customTypes: [],
            },
          },
        );
      })(),

      SettleRealmData: (() => {
        return defineComponent(
          world,
          {
            id: RecsType.Number,
            event_id: RecsType.String,
            entity_id: RecsType.Number,
            owner_address: RecsType.BigInt,
            owner_name: RecsType.BigInt,
            realm_name: RecsType.BigInt,
            produced_resources: RecsType.BigInt,
            cities: RecsType.Number,
            harbors: RecsType.Number,
            rivers: RecsType.Number,
            regions: RecsType.Number,
            wonder: RecsType.Number,
            order: RecsType.Number,
            x: RecsType.Number,
            y: RecsType.Number,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "SettleRealmData",
              types: [
                "u32",
                "EventType",
                "u32",
                "ContractAddress",
                "felt252",
                "felt252",
                "u128",
                "u8",
                "u8",
                "u8",
                "u8",
                "u8",
                "u8",
                "u32",
                "u32",
                "u64",
              ],
              customTypes: [],
            },
          },
        );
      })(),

      Transfer: (() => {
        return defineComponent(
          world,
          {
            recipient_entity_id: RecsType.Number,
            sending_realm_id: RecsType.Number,
            sender_entity_id: RecsType.Number,
            resources: RecsType.StringArray,
            timestamp: RecsType.BigInt,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "Transfer",
              types: ["u32", "u32", "u32", "array", "u64"],
              customTypes: ["Coord"],
            },
          },
        );
      })(),

      Travel: (() => {
        return defineComponent(
          world,
          {
            destination_coord_x: RecsType.Number,
            destination_coord_y: RecsType.Number,
            owner: RecsType.BigInt,
            entity_id: RecsType.Number,
            travel_time: RecsType.BigInt,
            travel_path: RecsType.StringArray,
            timestamp: RecsType.BigInt,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "Travel",
              types: ["u32", "u32", "ContractAddress", "u32", "array", "u64"],
              customTypes: ["Coord"],
            },
          },
        );
      })(),

      TrophyProgression: (() => {
        return defineComponent(
          world,
          {
            player_id: RecsType.BigInt,
            task_id: RecsType.BigInt,
            count: RecsType.Number,
            time: RecsType.BigInt,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "TrophyProgression",
              types: ["felt252", "felt252", "u32", "u64"],
              customTypes: [],
            },
          },
        );
      })(),
      HyperstructureCoOwnersChange: (() => {
        return defineComponent(
          world,
          {
            id: RecsType.Number,
            hyperstructure_entity_id: RecsType.Number,
            co_owners: RecsType.StringArray,
            timestamp: RecsType.Number,
          },
          {
            metadata: {
              namespace: "s1_eternum",
              name: "HyperstructureCoOwnersChange",
              types: ["u32", "u32", "array", "u64"],
              customTypes: [],
            },
          },
        );
      })(),
    },
  };
};
