import { fal } from "@fal-ai/client";

fal.config({
  credentials: process.env.FAL_KEY ?? process.env.FAL_API_KEY,
});

export interface AvatarGenerationResult {
  imageUrls: string[];
  jobId: string;
}

export interface AvatarGenerationOptions {
  prompt: string;
  style?: string;
}

const AVATAR_LORA_PATH =
  "https://v3b.fal.media/files/b/0a8a72d0/2fIFu-A-H48Vv1lcMyiao_pytorch_lora_weights.safetensors";

export async function generateAvatar(options: AvatarGenerationOptions): Promise<AvatarGenerationResult> {
  const { prompt, style } = options;

  const enhancedPrompt = style
    ? `${style} style, ${prompt}, professional game avatar, portrait, clean background`
    : `professional game avatar, ${prompt}, portrait style, clean background, high quality`;

  try {
    const result = (await fal.subscribe("fal-ai/flux-2/lora", {
      input: {
        prompt: enhancedPrompt,
        image_size: "square_hd",
        num_inference_steps: 28,
        num_images: 4,
        loras: [
          {
            path: AVATAR_LORA_PATH,
            scale: 1,
          },
        ],
      },
      logs: true,
      onQueueUpdate: (update) => {
        if (update.status === "IN_PROGRESS") {
          update.logs?.forEach((log) => {
            console.log(log.message);
          });
        }
      },
    })) as any;

    if (!result.data?.images || result.data.images.length === 0) {
      throw new Error("No images generated by Fal AI");
    }

    return {
      imageUrls: result.data.images.map((image: any) => image.url),
      jobId: result.requestId || crypto.randomUUID(),
    };
  } catch (error) {
    console.error("Fal AI generation error:", error);
    throw new Error(`Failed to generate avatar: ${error instanceof Error ? error.message : "Unknown error"}`);
  }
}

export async function getGenerationStatus(jobId: string): Promise<{
  status: "pending" | "processing" | "completed" | "failed";
  imageUrls?: string[];
  error?: string;
}> {
  try {
    const result = await fal.queue.status("fal-ai/flux-2/lora", {
      requestId: jobId,
      logs: false,
    });

    if (result.status === "COMPLETED") {
      const response = await fal.queue.result("fal-ai/flux-2/lora", {
        requestId: jobId,
      });
      return {
        status: "completed",
        imageUrls: response.data?.images?.map((image) => image.url),
      };
    }

    if (result.status === "IN_PROGRESS") {
      return { status: "processing" };
    }

    if (result.status === "IN_QUEUE") {
      return { status: "pending" };
    }

    return {
      status: "failed",
      error: "Generation failed",
    };
  } catch (error) {
    console.error("Failed to check generation status:", error);
    return {
      status: "failed",
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}
