/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScrollIndexRouteImport } from './routes/scroll/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as ScrollSlugRouteImport } from './routes/scroll/$slug'
import { Route as GamesSlugRouteImport } from './routes/games/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrollIndexRoute = ScrollIndexRouteImport.update({
  id: '/scroll/',
  path: '/scroll/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrollSlugRoute = ScrollSlugRouteImport.update({
  id: '/scroll/$slug',
  path: '/scroll/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/$slug': typeof GamesSlugRoute
  '/scroll/$slug': typeof ScrollSlugRoute
  '/games/': typeof GamesIndexRoute
  '/scroll/': typeof ScrollIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/$slug': typeof GamesSlugRoute
  '/scroll/$slug': typeof ScrollSlugRoute
  '/games': typeof GamesIndexRoute
  '/scroll': typeof ScrollIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/$slug': typeof GamesSlugRoute
  '/scroll/$slug': typeof ScrollSlugRoute
  '/games/': typeof GamesIndexRoute
  '/scroll/': typeof ScrollIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/$slug' | '/scroll/$slug' | '/games/' | '/scroll/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/$slug' | '/scroll/$slug' | '/games' | '/scroll'
  id:
    | '__root__'
    | '/'
    | '/games/$slug'
    | '/scroll/$slug'
    | '/games/'
    | '/scroll/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesSlugRoute: typeof GamesSlugRoute
  ScrollSlugRoute: typeof ScrollSlugRoute
  GamesIndexRoute: typeof GamesIndexRoute
  ScrollIndexRoute: typeof ScrollIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scroll/': {
      id: '/scroll/'
      path: '/scroll'
      fullPath: '/scroll/'
      preLoaderRoute: typeof ScrollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scroll/$slug': {
      id: '/scroll/$slug'
      path: '/scroll/$slug'
      fullPath: '/scroll/$slug'
      preLoaderRoute: typeof ScrollSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesSlugRoute: GamesSlugRoute,
  ScrollSlugRoute: ScrollSlugRoute,
  GamesIndexRoute: GamesIndexRoute,
  ScrollIndexRoute: ScrollIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
