/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as VelordsIndexImport } from './routes/velords.index'
import { Route as RealmsIndexImport } from './routes/realms.index'
import { Route as DelegatesIndexImport } from './routes/delegates.index'
import { Route as VelordsClaimImport } from './routes/velords.claim'
import { Route as RealmsClaimsImport } from './routes/realms.claims'
import { Route as RealmsBridgeImport } from './routes/realms.bridge'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VelordsIndexRoute = VelordsIndexImport.update({
  id: '/velords/',
  path: '/velords/',
  getParentRoute: () => rootRoute,
} as any)

const RealmsIndexRoute = RealmsIndexImport.update({
  id: '/realms/',
  path: '/realms/',
  getParentRoute: () => rootRoute,
} as any)

const DelegatesIndexRoute = DelegatesIndexImport.update({
  id: '/delegates/',
  path: '/delegates/',
  getParentRoute: () => rootRoute,
} as any)

const VelordsClaimRoute = VelordsClaimImport.update({
  id: '/velords/claim',
  path: '/velords/claim',
  getParentRoute: () => rootRoute,
} as any)

const RealmsClaimsRoute = RealmsClaimsImport.update({
  id: '/realms/claims',
  path: '/realms/claims',
  getParentRoute: () => rootRoute,
} as any)

const RealmsBridgeRoute = RealmsBridgeImport.update({
  id: '/realms/bridge',
  path: '/realms/bridge',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/realms/bridge': {
      id: '/realms/bridge'
      path: '/realms/bridge'
      fullPath: '/realms/bridge'
      preLoaderRoute: typeof RealmsBridgeImport
      parentRoute: typeof rootRoute
    }
    '/realms/claims': {
      id: '/realms/claims'
      path: '/realms/claims'
      fullPath: '/realms/claims'
      preLoaderRoute: typeof RealmsClaimsImport
      parentRoute: typeof rootRoute
    }
    '/velords/claim': {
      id: '/velords/claim'
      path: '/velords/claim'
      fullPath: '/velords/claim'
      preLoaderRoute: typeof VelordsClaimImport
      parentRoute: typeof rootRoute
    }
    '/delegates/': {
      id: '/delegates/'
      path: '/delegates'
      fullPath: '/delegates'
      preLoaderRoute: typeof DelegatesIndexImport
      parentRoute: typeof rootRoute
    }
    '/realms/': {
      id: '/realms/'
      path: '/realms'
      fullPath: '/realms'
      preLoaderRoute: typeof RealmsIndexImport
      parentRoute: typeof rootRoute
    }
    '/velords/': {
      id: '/velords/'
      path: '/velords'
      fullPath: '/velords'
      preLoaderRoute: typeof VelordsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/realms/bridge': typeof RealmsBridgeRoute
  '/realms/claims': typeof RealmsClaimsRoute
  '/velords/claim': typeof VelordsClaimRoute
  '/delegates': typeof DelegatesIndexRoute
  '/realms': typeof RealmsIndexRoute
  '/velords': typeof VelordsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/realms/bridge': typeof RealmsBridgeRoute
  '/realms/claims': typeof RealmsClaimsRoute
  '/velords/claim': typeof VelordsClaimRoute
  '/delegates': typeof DelegatesIndexRoute
  '/realms': typeof RealmsIndexRoute
  '/velords': typeof VelordsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/realms/bridge': typeof RealmsBridgeRoute
  '/realms/claims': typeof RealmsClaimsRoute
  '/velords/claim': typeof VelordsClaimRoute
  '/delegates/': typeof DelegatesIndexRoute
  '/realms/': typeof RealmsIndexRoute
  '/velords/': typeof VelordsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/realms/bridge'
    | '/realms/claims'
    | '/velords/claim'
    | '/delegates'
    | '/realms'
    | '/velords'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/realms/bridge'
    | '/realms/claims'
    | '/velords/claim'
    | '/delegates'
    | '/realms'
    | '/velords'
  id:
    | '__root__'
    | '/'
    | '/realms/bridge'
    | '/realms/claims'
    | '/velords/claim'
    | '/delegates/'
    | '/realms/'
    | '/velords/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RealmsBridgeRoute: typeof RealmsBridgeRoute
  RealmsClaimsRoute: typeof RealmsClaimsRoute
  VelordsClaimRoute: typeof VelordsClaimRoute
  DelegatesIndexRoute: typeof DelegatesIndexRoute
  RealmsIndexRoute: typeof RealmsIndexRoute
  VelordsIndexRoute: typeof VelordsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RealmsBridgeRoute: RealmsBridgeRoute,
  RealmsClaimsRoute: RealmsClaimsRoute,
  VelordsClaimRoute: VelordsClaimRoute,
  DelegatesIndexRoute: DelegatesIndexRoute,
  RealmsIndexRoute: RealmsIndexRoute,
  VelordsIndexRoute: VelordsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/realms/bridge",
        "/realms/claims",
        "/velords/claim",
        "/delegates/",
        "/realms/",
        "/velords/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/realms/bridge": {
      "filePath": "realms.bridge.tsx"
    },
    "/realms/claims": {
      "filePath": "realms.claims.tsx"
    },
    "/velords/claim": {
      "filePath": "velords.claim.tsx"
    },
    "/delegates/": {
      "filePath": "delegates.index.tsx"
    },
    "/realms/": {
      "filePath": "realms.index.tsx"
    },
    "/velords/": {
      "filePath": "velords.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
