import Button from "@/ui/elements/Button";
import CircleButton from "@/ui/elements/CircleButton";
import { Headline } from "@/ui/elements/Headline";
import { BuildingThumbs } from "@/ui/modules/navigation/LeftNavigationModule";
import { EternumGlobalConfig } from "@bibliothecadao/eternum";

export const GettingStarted = () => {
  const concepts = [
    {
      name: "The Time Cycle",
      content: `Everything in this world revolves around an Eternum Day. A day in Eternum is ${
        EternumGlobalConfig.tick.armiesTickIntervalInSeconds / 60
      } minute. This determines how far you can move your armies.`,
    },
    {
      name: "Resources",
      content:
        "Everything in this world is fungible. Resources, Troops, Donkeys. All of these are generated by buildings which have a cost to production.",
    },
    {
      name: "Cost of Production",
      content:
        "Every resource has a cost to production. You must maintain these balances in order to keep production going. If you do not have enough resources, production stops.",
    },
    {
      name: "Trading + Donkeys",
      content: (
        <div className="flex">
          Trading is done via Donkeys at the Marketplace. You must have Donkeys in your balance in order to trade. You
          can generate these with a market. You can also trade donkeys like any other resource.
        </div>
      ),
    },
  ];

  return (
    <div>
      <Headline>Key Concepts</Headline>

      {concepts.map((concept) => (
        <div key={concept.name} className="my-4">
          <h2>{concept.name}</h2>
          <p>{concept.content}</p>
        </div>
      ))}
    </div>
  );
};
