import { ModalContainer } from "../ModalContainer";
import { useState } from "react";

export const HintModal = () => {
  const sections = [
    {
      name: "Getting Started",
      content: <GettingStarted />,
    },
    {
      name: "Resources",
      content: <Resources />,
    },
    {
      name: "Trading & Banking",
      content: <Banking />,
    },
    {
      name: "Combat",
      content: <Combat />,
    },
  ];
  const [activeSection, setActiveSection] = useState(sections[0]);

  return (
    <ModalContainer>
      <div className="grid grid-cols-12 container mx-auto gap-8">
        <div className="col-span-4 border p-1 space-y-1">
          {sections.map((section) => (
            <div
              className={`p-4 hover:bg-gold hover:text-brown ${
                activeSection.name === section.name ? "bg-gold text-brown" : ""
              }`}
              key={section.name}
              onClick={() => setActiveSection(section)}
            >
              <h4>{section.name}</h4>
            </div>
          ))}
        </div>
        <div className="col-span-8 border p-4">{activeSection.content}</div>
      </div>
    </ModalContainer>
  );
};

export const GettingStarted = () => {
  const concepts = [
    {
      name: "The World",
      content:
        "Eternum World is made up of hexagons within hexagons, hexception if you will. Each hexagon is a buildable space. You can travel around the hexes explore and expand.",
    },
    {
      name: "The Time Cycle",
      content:
        "Everything in this world revolves around the time cycle. Currently, a day in Eternum is 15 minutes. This determines your production, movement, and everything else.",
    },
    {
      name: "Resources",
      content:
        "Everything in this world is fungible. Resources, Troops, Donkeys. All of these are generated by buildings which you then consume",
    },
    {
      name: "Cost of Production",
      content:
        "Every resource has a cost to production. You must maintain these balances in order to keep production going. If you do not have enough resources, production stops.",
    },
    {
      name: "Trading + Donkeys",
      content:
        "Trading is done through Donkeys. You must have Donkeys in your balance in order to trade. You can generate these with a market. You can also trade donkeys as they are fungible.",
    },
  ];

  return (
    <div>
      <h4>Key Concepts</h4>

      {concepts.map((concept) => (
        <div key={concept.name} className="my-4">
          <h5>{concept.name}</h5>
          <p>{concept.content}</p>
        </div>
      ))}
    </div>
  );
};

export const Resources = () => {
  return (
    <div>
      <h4>Resources & Food</h4>
      <p>
        All resources except for Food have a resource input cost associated. You must have these resources in your
        balance otherwise production stops. Trade with others or banks in order to keep your balances in check.
      </p>
      <h4>Storage of Food</h4>
      <p>
        You can only store a certain capacity of resources per your storehouses. Each storehouse grants you 10k per
        resource. You can build more storehouses to increase your capacity.
      </p>
    </div>
  );
};

export const Banking = () => {
  return (
    <div>
      <h4>Trading</h4>
      <p>
        Trading is done through Donkeys. You must have Donkeys in your balance in order to trade. You can generate these
        with a market. You can also trade donkeys as they are fungible.
      </p>

      <h5>Banking</h5>
      <p>
        Banks exist around the map. You can trade with them or deposit resources. You can even provide liquidity. If you
        have enough money you can create your own bank and set fees.
      </p>
    </div>
  );
};

export const Combat = () => {
  return (
    <div>
      <h4>Armies</h4>
      <p>
        Armies can be created using your balance of Troops. Remember, everything is fungible so you must generate troops
        in order to build an Army.
      </p>

      <h4>Protecting your Base</h4>
      <p>To protect your Base you must build a defensive Army. This Army will help protect from raiders.</p>
    </div>
  );
};
