/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VelordsIndexRouteImport } from './routes/velords.index'
import { Route as RealmsIndexRouteImport } from './routes/realms.index'
import { Route as ComingSoonIndexRouteImport } from './routes/coming-soon.index'
import { Route as RealmsClaimsRouteImport } from './routes/realms.claims'
import { Route as RealmsBridgeRouteImport } from './routes/realms.bridge'
import { Route as ProposalListRouteImport } from './routes/proposal.list'
import { Route as ProposalIdRouteImport } from './routes/proposal.$id'
import { Route as DelegateProfileRouteImport } from './routes/delegate.profile'
import { Route as DelegateListRouteImport } from './routes/delegate.list'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VelordsIndexRoute = VelordsIndexRouteImport.update({
  id: '/velords/',
  path: '/velords/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmsIndexRoute = RealmsIndexRouteImport.update({
  id: '/realms/',
  path: '/realms/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonIndexRoute = ComingSoonIndexRouteImport.update({
  id: '/coming-soon/',
  path: '/coming-soon/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmsClaimsRoute = RealmsClaimsRouteImport.update({
  id: '/realms/claims',
  path: '/realms/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmsBridgeRoute = RealmsBridgeRouteImport.update({
  id: '/realms/bridge',
  path: '/realms/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalListRoute = ProposalListRouteImport.update({
  id: '/proposal/list',
  path: '/proposal/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalIdRoute = ProposalIdRouteImport.update({
  id: '/proposal/$id',
  path: '/proposal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegateProfileRoute = DelegateProfileRouteImport.update({
  id: '/delegate/profile',
  path: '/delegate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegateListRoute = DelegateListRouteImport.update({
  id: '/delegate/list',
  path: '/delegate/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delegate/list': typeof DelegateListRoute
  '/delegate/profile': typeof DelegateProfileRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/proposal/list': typeof ProposalListRoute
  '/realms/bridge': typeof RealmsBridgeRoute
  '/realms/claims': typeof RealmsClaimsRoute
  '/coming-soon/': typeof ComingSoonIndexRoute
  '/realms/': typeof RealmsIndexRoute
  '/velords/': typeof VelordsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delegate/list': typeof DelegateListRoute
  '/delegate/profile': typeof DelegateProfileRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/proposal/list': typeof ProposalListRoute
  '/realms/bridge': typeof RealmsBridgeRoute
  '/realms/claims': typeof RealmsClaimsRoute
  '/coming-soon': typeof ComingSoonIndexRoute
  '/realms': typeof RealmsIndexRoute
  '/velords': typeof VelordsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/delegate/list': typeof DelegateListRoute
  '/delegate/profile': typeof DelegateProfileRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/proposal/list': typeof ProposalListRoute
  '/realms/bridge': typeof RealmsBridgeRoute
  '/realms/claims': typeof RealmsClaimsRoute
  '/coming-soon/': typeof ComingSoonIndexRoute
  '/realms/': typeof RealmsIndexRoute
  '/velords/': typeof VelordsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/delegate/list'
    | '/delegate/profile'
    | '/proposal/$id'
    | '/proposal/list'
    | '/realms/bridge'
    | '/realms/claims'
    | '/coming-soon/'
    | '/realms/'
    | '/velords/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/delegate/list'
    | '/delegate/profile'
    | '/proposal/$id'
    | '/proposal/list'
    | '/realms/bridge'
    | '/realms/claims'
    | '/coming-soon'
    | '/realms'
    | '/velords'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/delegate/list'
    | '/delegate/profile'
    | '/proposal/$id'
    | '/proposal/list'
    | '/realms/bridge'
    | '/realms/claims'
    | '/coming-soon/'
    | '/realms/'
    | '/velords/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DelegateListRoute: typeof DelegateListRoute
  DelegateProfileRoute: typeof DelegateProfileRoute
  ProposalIdRoute: typeof ProposalIdRoute
  ProposalListRoute: typeof ProposalListRoute
  RealmsBridgeRoute: typeof RealmsBridgeRoute
  RealmsClaimsRoute: typeof RealmsClaimsRoute
  ComingSoonIndexRoute: typeof ComingSoonIndexRoute
  RealmsIndexRoute: typeof RealmsIndexRoute
  VelordsIndexRoute: typeof VelordsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/velords/': {
      id: '/velords/'
      path: '/velords'
      fullPath: '/velords/'
      preLoaderRoute: typeof VelordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realms/': {
      id: '/realms/'
      path: '/realms'
      fullPath: '/realms/'
      preLoaderRoute: typeof RealmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon/': {
      id: '/coming-soon/'
      path: '/coming-soon'
      fullPath: '/coming-soon/'
      preLoaderRoute: typeof ComingSoonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realms/claims': {
      id: '/realms/claims'
      path: '/realms/claims'
      fullPath: '/realms/claims'
      preLoaderRoute: typeof RealmsClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realms/bridge': {
      id: '/realms/bridge'
      path: '/realms/bridge'
      fullPath: '/realms/bridge'
      preLoaderRoute: typeof RealmsBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/list': {
      id: '/proposal/list'
      path: '/proposal/list'
      fullPath: '/proposal/list'
      preLoaderRoute: typeof ProposalListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$id': {
      id: '/proposal/$id'
      path: '/proposal/$id'
      fullPath: '/proposal/$id'
      preLoaderRoute: typeof ProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegate/profile': {
      id: '/delegate/profile'
      path: '/delegate/profile'
      fullPath: '/delegate/profile'
      preLoaderRoute: typeof DelegateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegate/list': {
      id: '/delegate/list'
      path: '/delegate/list'
      fullPath: '/delegate/list'
      preLoaderRoute: typeof DelegateListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DelegateListRoute: DelegateListRoute,
  DelegateProfileRoute: DelegateProfileRoute,
  ProposalIdRoute: ProposalIdRoute,
  ProposalListRoute: ProposalListRoute,
  RealmsBridgeRoute: RealmsBridgeRoute,
  RealmsClaimsRoute: RealmsClaimsRoute,
  ComingSoonIndexRoute: ComingSoonIndexRoute,
  RealmsIndexRoute: RealmsIndexRoute,
  VelordsIndexRoute: VelordsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
