# Start from the Ubuntu 22.04 base image
FROM ubuntu:22.04

ARG PERSISTENT_STATE
ENV PERSISTENT_STATE=$PERSISTENT_STATE

ARG RESET_STATE
ENV RESET_STATE=$RESET_STATE

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

ENV PATH="${PATH}:/root/.local/bin"

ADD Dockers/config/litefs.static-lease.yml /etc/litefs.yml

# Update and install some common packages
RUN apt-get update && apt-get install -y \
    ca-certificates \
    libsqlite3-mod-spatialite \
    curl \
    fuse3 \
    sqlite \
    git \
    vim \
    wget \
	jq \
	bc \
	python3.9 \
	make \
    && rm -rf /var/lib/apt/lists/* && \
	git clone --depth 1 https://github.com/The-Overlore/lore-machine.git && \
	curl -sSL https://install.python-poetry.org | python3 -

COPY --from=flyio/litefs:0.5 /usr/local/bin/litefs /usr/local/bin/litefs

COPY ./Dockers/lore-machine.sh /lore-machine

EXPOSE 8765

WORKDIR /lore-machine
