world_address = "0x50ed913cc4b5fb11f50b5e1118d2999ee3e7917a7349bc34900fd76b307b5d"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"

[server]
http_cors_origins = ["*"]

[indexing]
controllers = true
index_pending = false
polling_interval = 500
max_concurrent_tasks = 32
events_chunk_size = 1024
contracts = [
    "ERC20:0x00d5a3c8c5ebcacf3279aafd2de3eb0c4736afc11be6f41c84880080fa7a1aaf",    # mmr token
]
namespaces = ["pm"]

[sql]
historical = [
    "pm-MarketBuy",
    "pm-PayoutRedemption",
    "pm-VaultNumerator",
    "pm-VaultDenominator",
    "pm-VaultNumeratorEvent",
    "pm-VaultDenominatorEvent",
]
all_model_indices = false

hooks = [
    { event = { ModelRegistered = { model_tag = "pm-Market" } }, statement = "CREATE INDEX IF NOT EXISTS [idx_events_mmr_player_latest] ON events (lower(substr(lower(keys), instr(lower(keys), '/') + 1, instr(substr(lower(keys), instr(lower(keys), '/') + 1), '/') - 1)), executed_at DESC, id DESC) WHERE ltrim(substr(lower(keys), 1, instr(lower(keys), '/') - 1), '0x') = ltrim('0x16f4294f4d138f6ce05f6157837f2607fdb74f7f25e8d8f4be4e933309f4d37', '0x') AND lower(substr(substr(id, instr(id, ':') + 1), instr(substr(id, instr(id, ':') + 1), ':') + 1, instr(substr(substr(id, instr(id, ':') + 1), instr(substr(id, instr(id, ':') + 1), ':') + 1), ':') - 1)) = '0x00d5a3c8c5ebcacf3279aafd2de3eb0c4736afc11be6f41c84880080fa7a1aaf'" },
    { event = { ModelRegistered = { model_tag = "pm-Market" } }, statement = "CREATE INDEX IF NOT EXISTS [idx_events_mmr_latest_time] ON events (executed_at DESC, id DESC) WHERE ltrim(substr(lower(keys), 1, instr(lower(keys), '/') - 1), '0x') = ltrim('0x16f4294f4d138f6ce05f6157837f2607fdb74f7f25e8d8f4be4e933309f4d37', '0x') AND lower(substr(substr(id, instr(id, ':') + 1), instr(substr(id, instr(id, ':') + 1), ':') + 1, instr(substr(substr(id, instr(id, ':') + 1), instr(substr(id, instr(id, ':') + 1), ':') + 1), ':') - 1)) = '0x00d5a3c8c5ebcacf3279aafd2de3eb0c4736afc11be6f41c84880080fa7a1aaf'" },
]

[[sql.model_indices]]
model_tag = "pm-Market"
fields = ["start_at", "resolve_at", "resolved_at", "oracle"]

[[sql.model_indices]]
model_tag = "pm-MarketCreated"
fields = ["market_id"]

[[sql.model_indices]]
model_tag = "pm-VaultDenominator"
fields = ["market_id"]

[[sql.model_indices]]
model_tag = "pm-VaultNumerator"
fields = ["market_id", "index"]

[[sql.model_indices]]
model_tag = "pm-MarketBuy"
fields = ["market_id"]

[[sql.model_indices]]
model_tag = "pm-PayoutRedemption"
fields = ["condition_id"]

[events]
raw = true
