[namespace]
default = "world_0"

[env]
account_address = ""
private_key = ""
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x06a9e4c6f0799160ea8ddc43ff982a5f83d7f633e9732ce42701de1288ff705f"

[world]
seed = "s0_eternum"
name = "Realms World"
description = "The world of Realms"
cover_uri = "file://assets/bg.webp"
website = "https://realms.world/"
