import type { NativePreset } from "../common/native-preset";
import {
  nativeResearchConstants as research,
  nativeRuleConstants as rule,
} from "../../../contracts/l3/world-native/schema/client.gen";
import { nativeCommandBits } from "../../../contracts/l3/world-native/schema/commands.gen";
import { FRONTIER_PRESET_ID } from "../common/native-preset-modes";

// A building row's tier, uncommon to legendary, costs its base times this ladder, in Essence and in labor.
const essenceLadder = [1, 4, 12, 30];
const laborLadder = [1, 3, 8, 20];
const buildingRows = [
  { row: research.ROW_FARM, essence: 1000, labor: 1000 },
  { row: research.ROW_WORKSHOP, essence: 2000, labor: 2000 },
  { row: research.ROW_BARRACKS, essence: 4000, labor: 3000 },
  { row: research.ROW_HUT, essence: 500, labor: 500 },
  ...[research.ROW_WAR_HALL, research.ROW_SUPPLY_YARD, research.ROW_SCOUTS_LODGE, research.ROW_HEARTH].map((row) => ({
    row,
    essence: 12000,
    labor: 3000,
  })),
];

export const frontierPreset: NativePreset = {
  ledger: {
    entryFee: 0,
    protocolCutBps: 0,
    swordPrice: 0,
    shieldPrice: 0,
    mmrEnabled: false,
    predictionFeeBps: 0,
    liabilityCap: 0,
    seed: 0,
  },
  bitcoinEnabled: false,
  startingTroops: Array.from({ length: 17 }, () => "Knight" as const),
  realmResources: [],
  relics: [],
  supplies: [],
  bridgeResources: [],
  id: FRONTIER_PRESET_ID,
  gameType: "frontier",
  environmentGameType: "frontier",
  settlementMode: "Single",
  modeRules: rule.HOME_REWARDS | rule.UNOWNED_TARGETS | rule.DEPTH_CONTENTS | rule.REVEAL_SUPPLIES | rule.SEASON_CLOSE,
  entryRule: rule.ENTRY_OPEN,
  commandMask: (
    [
      "SettleSeason",
      "CreateExplorer",
      "ManageTroops",
      "Explore",
      "Move",
      "BattleGuard",
      "CreateBuilding",
      "DestroyBuilding",
      "LevelUp",
      "Research",
      "EnterDepth",
      "BuyTier",
      "OpenRelicChest",
      "InteractSite",
      "SetEntityName",
      "MarkGameSettled",
    ] satisfies Array<keyof typeof nativeCommandBits>
  ).reduce((mask, command) => mask | BigInt(nativeCommandBits[command]), 0n),
  spacing: 100,
  epochSeconds: 86400,
  board: {
    demolitionRefundBps: 5000,
    workshopRate: 0.056,
    outputStepBps: 2500,
    storageStepBps: 5000,
    populationStepBps: 2500,
    rationStep: 0.25,
    trainingGateTier: 2,
    castleStoreDeploys: 2,
  },
  research: [
    ...buildingRows.flatMap(({ row, essence, labor }) =>
      essenceLadder.map((factor, index) => ({
        row,
        tier: index + 1,
        essenceCost: essence * factor,
        laborCost: labor * laborLadder[index]!,
      })),
    ),
    { row: research.ROW_SHRINE, tier: 1, essenceCost: 2000, laborCost: 0 },
    { row: research.ROW_WELL, tier: 1, essenceCost: 6000, laborCost: 0 },
    ...[160000, 400000, 900000].map((essenceCost, index) => ({
      row: research.ROW_DEPTH,
      tier: index + 1,
      essenceCost,
      laborCost: 0,
    })),
  ],
  discovery: {
    campBps: 400,
    riftBps: 400,
    fallenRealmBps: 200,
    looseChestBps: 200,
    shrineBps: 300,
    wellBps: 300,
    emptyRevealLimit: 7,
  },
  progression: { revealXp: 2, fixedXp: 200, uncommonXp: 100, rareXp: 200, epicXp: 400, legendaryXp: 800 },
  chests: {
    relicProbability: 9000,
    tokenCap: 1,
    lordsAmounts: { common: 100, uncommon: 400, rare: 1500, epic: 6000 },
    lordsPool: 1000000,
    seasonEpochs: 70,
  },
  depths: [
    {
      revealPercent: 10,
      guardLower: 1000,
      guardUpper: 1600,
      fallenGuardLower: 2000,
      fallenGuardUpper: 4000,
      guardStep: 100,
      fallenGuardTier: "T1",
      revealSiteNeighbors: false,
      entryStamina: 0,
      chest: { common: 7800, uncommon: 1800, rare: 350, pity: 400 },
    },
    {
      revealPercent: 15,
      guardLower: 3000,
      guardUpper: 5000,
      fallenGuardLower: 2000,
      fallenGuardUpper: 3500,
      guardStep: 100,
      fallenGuardTier: "T2",
      revealSiteNeighbors: false,
      entryStamina: 30,
      chest: { common: 6000, uncommon: 3000, rare: 800, pity: 100 },
    },
    {
      revealPercent: 20,
      guardLower: 8000,
      guardUpper: 12000,
      fallenGuardLower: 2000,
      fallenGuardUpper: 2500,
      guardStep: 100,
      fallenGuardTier: "T3",
      revealSiteNeighbors: false,
      entryStamina: 40,
      chest: { common: 4200, uncommon: 3800, rare: 1500, pity: 40 },
    },
    {
      revealPercent: 25,
      guardLower: 20000,
      guardUpper: 30000,
      // The ruin beasts grow x1.3 for +100% Battle; a step of 50 keeps both ends exact.
      fallenGuardLower: 5850,
      fallenGuardUpper: 8450,
      guardStep: 50,
      fallenGuardTier: "T3",
      revealSiteNeighbors: false,
      entryStamina: 50,
      chest: { common: 2500, uncommon: 4300, rare: 2300, pity: 20 },
    },
  ],
};
