import type { NativePreset } from "../common/native-preset";
import { nativeRuleConstants as rule } from "../../../contracts/l3/world-native/schema/client.gen";
import { nativeCommandBits } from "../../../contracts/l3/world-native/schema/commands.gen";
import { FRONTIER_PRESET_ID } from "../common/native-preset-modes";

export const frontierPreset: NativePreset = {
  ledger: {
    entryFee: 0,
    protocolCutBps: 0,
    swordPrice: 0,
    shieldPrice: 0,
    mmrEnabled: false,
    predictionFeeBps: 0,
    liabilityCap: 0,
    seed: 0,
  },
  bitcoinEnabled: false,
  startingTroops: Array.from({ length: 17 }, () => "Knight" as const),
  realmResources: [],
  relics: [],
  supplies: [],
  bridgeResources: [],
  id: FRONTIER_PRESET_ID,
  gameType: "frontier",
  environmentGameType: "frontier",
  settlementMode: "Single",
  modeRules: rule.HOME_REWARDS | rule.UNOWNED_TARGETS | rule.DEPTH_CONTENTS | rule.REVEAL_SUPPLIES | rule.SEASON_CLOSE,
  entryRule: rule.ENTRY_OPEN,
  commandMask: (
    [
      "SettleSeason",
      "CreateExplorer",
      "ManageTroops",
      "Explore",
      "Move",
      "BattleGuard",
      "CreateBuilding",
      "DestroyBuilding",
      "LevelUp",
      "Research",
      "UpgradeBuilding",
      "EnterDepth",
      "ChooseAttribute",
      "OpenRelicChest",
      "InteractSite",
      "SetEntityName",
      "MarkGameSettled",
    ] satisfies Array<keyof typeof nativeCommandBits>
  ).reduce((mask, command) => mask | BigInt(nativeCommandBits[command]), 0n),
  spacing: 100,
  epochSeconds: 86400,
  board: {
    demolitionRefundBps: 5000,
    workshopRate: 200 / 3600,
  },
  research: [
    { node: 0, prerequisites: 0, essenceCost: 150, effect: { kind: "BuildingTier", category: 37, tier: 2 } },
    { node: 1, prerequisites: 1 << 0, essenceCost: 12000, effect: { kind: "BuildingTier", category: 37, tier: 3 } },
    { node: 2, prerequisites: 0, essenceCost: 3000, effect: { kind: "BuildingTier", category: 28, tier: 2 } },
    { node: 3, prerequisites: 1 << 2, essenceCost: 40000, effect: { kind: "BuildingTier", category: 28, tier: 3 } },
    { node: 4, prerequisites: 0, essenceCost: 1000, effect: { kind: "BuildingTier", category: 2, tier: 2 } },
    { node: 5, prerequisites: 1 << 4, essenceCost: 15000, effect: { kind: "BuildingTier", category: 2, tier: 3 } },
    { node: 6, prerequisites: 0, essenceCost: 400, effect: { kind: "BuildingTier", category: 1, tier: 2 } },
    { node: 7, prerequisites: 1 << 6, essenceCost: 12000, effect: { kind: "BuildingTier", category: 1, tier: 3 } },
    { node: 8, prerequisites: 0, essenceCost: 2000, effect: { kind: "MapContent", content: "Shrine" } },
    { node: 9, prerequisites: 0, essenceCost: 6000, effect: { kind: "MapContent", content: "Well" } },
    { node: 10, prerequisites: 0, essenceCost: 80000, effect: { kind: "Depth", depth: 1 } },
    { node: 11, prerequisites: 1 << 10, essenceCost: 200000, effect: { kind: "Depth", depth: 2 } },
    { node: 12, prerequisites: 1 << 11, essenceCost: 450000, effect: { kind: "Depth", depth: 3 } },
  ],
  buildingTiers: [
    {
      category: 37,
      tier: 2,
      laborUpgradeCost: 200,
      outputMultiplierBps: 20000,
      capacityMultiplierBps: 10000,
      populationMultiplierBps: 10000,
    },
    {
      category: 37,
      tier: 3,
      laborUpgradeCost: 400,
      outputMultiplierBps: 40000,
      capacityMultiplierBps: 10000,
      populationMultiplierBps: 10000,
    },
    {
      category: 28,
      tier: 2,
      laborUpgradeCost: 2400,
      outputMultiplierBps: 10000,
      capacityMultiplierBps: 10000,
      populationMultiplierBps: 10000,
    },
    {
      category: 28,
      tier: 3,
      laborUpgradeCost: 4800,
      outputMultiplierBps: 10000,
      capacityMultiplierBps: 10000,
      populationMultiplierBps: 10000,
    },
    {
      category: 2,
      tier: 2,
      laborUpgradeCost: 2000,
      outputMultiplierBps: 10000,
      capacityMultiplierBps: 20000,
      populationMultiplierBps: 10000,
    },
    {
      category: 2,
      tier: 3,
      laborUpgradeCost: 4000,
      outputMultiplierBps: 10000,
      capacityMultiplierBps: 40000,
      populationMultiplierBps: 10000,
    },
    {
      category: 1,
      tier: 2,
      laborUpgradeCost: 600,
      outputMultiplierBps: 10000,
      capacityMultiplierBps: 10000,
      populationMultiplierBps: 20000,
    },
    {
      category: 1,
      tier: 3,
      laborUpgradeCost: 1200,
      outputMultiplierBps: 10000,
      capacityMultiplierBps: 10000,
      populationMultiplierBps: 40000,
    },
  ],
  discovery: {
    campBps: 400,
    riftBps: 400,
    fallenRealmBps: 200,
    looseChestBps: 200,
    shrineBps: 300,
    wellBps: 300,
    emptyRevealLimit: 7,
  },
  progression: { revealXp: 10, clearXp: 25, levelStepXp: 20 },
  chests: {
    relicProbability: 9000,
    tokenCap: 1,
    lordsAmounts: { common: 100, uncommon: 400, rare: 1500, epic: 6000 },
    lordsPool: 1000000,
    seasonEpochs: 70,
  },
  depths: [
    {
      revealPercent: 10,
      guardLower: 1000,
      guardUpper: 1600,
      fallenGuardLower: 2000,
      fallenGuardUpper: 4000,
      guardStep: 100,
      fallenGuardTier: "T1",
      revealSiteNeighbors: false,
      entryStamina: 0,
      chest: { common: 7800, uncommon: 1800, rare: 350, pity: 400 },
    },
    {
      revealPercent: 15,
      guardLower: 3000,
      guardUpper: 5000,
      fallenGuardLower: 2000,
      fallenGuardUpper: 3500,
      guardStep: 100,
      fallenGuardTier: "T2",
      revealSiteNeighbors: false,
      entryStamina: 30,
      chest: { common: 6000, uncommon: 3000, rare: 800, pity: 100 },
    },
    {
      revealPercent: 20,
      guardLower: 8000,
      guardUpper: 12000,
      fallenGuardLower: 2000,
      fallenGuardUpper: 2500,
      guardStep: 100,
      fallenGuardTier: "T3",
      revealSiteNeighbors: false,
      entryStamina: 40,
      chest: { common: 4200, uncommon: 3800, rare: 1500, pity: 40 },
    },
    {
      revealPercent: 25,
      guardLower: 20000,
      guardUpper: 30000,
      fallenGuardLower: 4500,
      fallenGuardUpper: 6500,
      guardStep: 100,
      fallenGuardTier: "T3",
      revealSiteNeighbors: false,
      entryStamina: 50,
      chest: { common: 2500, uncommon: 4300, rare: 2300, pity: 20 },
    },
  ],
};
