import type { NativePreset } from "../common/native-preset";
import { nativeRuleConstants as rule } from "../../../contracts/l3/world-native/schema/client.gen";
import { nativeCommandBits } from "../../../contracts/l3/world-native/schema/commands.gen";
import { FRONTIER_PRESET_ID } from "../common/native-preset-modes";

export const frontierPreset: NativePreset = {
  ledger: {
    entryFee: 0,
    protocolCutBps: 0,
    swordPrice: 0,
    shieldPrice: 0,
    mmrEnabled: false,
    predictionFeeBps: 0,
    liabilityCap: 0,
    seed: 0,
  },
  bitcoinEnabled: false,
  startingTroops: Array.from({ length: 17 }, () => "Knight" as const),
  realmResources: [],
  relics: [],
  supplies: [],
  bridgeResources: [],
  id: FRONTIER_PRESET_ID,
  gameType: "frontier",
  environmentGameType: "frontier",
  settlementMode: "Single",
  modeRules: rule.HOME_REWARDS | rule.UNOWNED_TARGETS | rule.DEPTH_CONTENTS | rule.REVEAL_SUPPLIES | rule.SEASON_CLOSE,
  entryRule: rule.ENTRY_OPEN,
  commandMask: (
    [
      "SettleSeason",
      "CreateExplorer",
      "ManageTroops",
      "Explore",
      "Move",
      "BattleGuard",
      "CreateBuilding",
      "DestroyBuilding",
      "LevelUp",
      "BuyRealmUpgrade",
      "EnterDepth",
      "ChooseAttribute",
      "OpenRelicChest",
      "SetEntityName",
      "MarkGameSettled",
    ] satisfies Array<keyof typeof nativeCommandBits>
  ).reduce((mask, command) => mask | BigInt(nativeCommandBits[command]), 0n),
  spacing: 100,
  epochSeconds: 86400,
  board: {
    demolitionRefundBps: 5000,
    workshopRate: 200 / 3600,
    barracksIICost: 8000,
    barracksIIICost: 45000,
    neighbors: [],
  },
  discovery: {
    campBps: 400,
    riftBps: 400,
    fallenRealmBps: 200,
    looseChestBps: 200,
    shrineBps: 300,
    wellBps: 300,
    emptyRevealLimit: 7,
  },
  progression: { revealXp: 10, clearXp: 25, levelStepXp: 20 },
  chests: { relicProbability: 9000, cosmeticProbability: 900, tokenCap: 1 },
  depths: [
    {
      revealPercent: 10,
      guardLower: 1000,
      guardUpper: 1600,
      fallenGuardLower: 2000,
      fallenGuardUpper: 4000,
      revealSiteNeighbors: false,
      entryStamina: 0,
      attunementCost: 0,
      chest: { common: 7800, uncommon: 1800, rare: 350, pity: 400 },
    },
    {
      revealPercent: 15,
      guardLower: 3000,
      guardUpper: 5000,
      fallenGuardLower: 6000,
      fallenGuardUpper: 10000,
      revealSiteNeighbors: false,
      entryStamina: 30,
      attunementCost: 150000,
      chest: { common: 6000, uncommon: 3000, rare: 800, pity: 100 },
    },
    {
      revealPercent: 20,
      guardLower: 8000,
      guardUpper: 12000,
      fallenGuardLower: 16000,
      fallenGuardUpper: 24000,
      revealSiteNeighbors: false,
      entryStamina: 40,
      attunementCost: 330000,
      chest: { common: 4200, uncommon: 3800, rare: 1500, pity: 40 },
    },
    {
      revealPercent: 25,
      guardLower: 20000,
      guardUpper: 30000,
      fallenGuardLower: 40000,
      fallenGuardUpper: 60000,
      revealSiteNeighbors: false,
      entryStamina: 50,
      attunementCost: 850000,
      chest: { common: 2500, uncommon: 4300, rare: 2300, pity: 20 },
    },
  ],
};
