[package]
cairo-version = "2.13.1"
name = "realms_player_account"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.13.1"
openzeppelin_account = "=2.0.0"
openzeppelin_introspection = "=2.0.0"

[dev-dependencies]
snforge_std = "0.51.2"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.fmt]
sort-module-level-items = true
max-line-length = 120
