import type { HorseRigAdapter } from "./horse-rig-adapter";

const QUATERNIUS_HORSE_BONES = {
  root: "Body",
  pelvis: "Back",
  spine: "Torso",
  chest: "Torso2",
  withers: "Torso3",
  neck1: "Neck1",
  neck2: "Neck2",
  neck3: "Neck3",
  head: "Head",
  frontShoulderLeft: "FrontShoulderL",
  frontUpperLeft: "FrontUpperLegL",
  frontLowerLeft: "FrontLowerLegL",
  frontTargetLeft: "IKFrontLegL",
  frontHoofLeft: "FFL",
  frontShoulderRight: "FrontShoulderR",
  frontUpperRight: "FrontUpperLegR",
  frontLowerRight: "FrontLowerLegR",
  frontTargetRight: "IKFrontLegR",
  frontHoofRight: "FFR",
  hindShoulderLeft: "BackShoulderL",
  hindUpperLeft: "BackLegL",
  hindMiddleLeft: "BackUpperLegL",
  hindLowerLeft: "BackLowerLegL",
  hindTargetLeft: "IKBackLegL",
  hindHoofLeft: "FFBL",
  hindShoulderRight: "BackShoulderR",
  hindUpperRight: "BackLegR",
  hindMiddleRight: "BackUpperLegR",
  hindLowerRight: "BackLowerLegR",
  hindTargetRight: "IKBackLegR",
  hindHoofRight: "FFBR",
  tail1: "Tail1",
  tail2: "Tail2",
  tail3: "Tail3",
  tail4: "Tail4",
  tail5: "Tail5",
  tail6: "Tail6",
  tail7: "Tail7",
} as const;

export const QUATERNIUS_HORSE_RIG_ADAPTER = {
  axialBones: {
    chest: QUATERNIUS_HORSE_BONES.chest,
    head: QUATERNIUS_HORSE_BONES.head,
    pelvis: QUATERNIUS_HORSE_BONES.pelvis,
    root: QUATERNIUS_HORSE_BONES.root,
    spine: QUATERNIUS_HORSE_BONES.spine,
    withers: QUATERNIUS_HORSE_BONES.withers,
  },
  id: "quaternius-horse",
  label: "Quaternius horse rig",
  legs: {
    frontLeft: {
      bones: [
        QUATERNIUS_HORSE_BONES.frontShoulderLeft,
        QUATERNIUS_HORSE_BONES.frontUpperLeft,
        QUATERNIUS_HORSE_BONES.frontLowerLeft,
      ],
      hoof: QUATERNIUS_HORSE_BONES.frontHoofLeft,
      segments: ["frontShoulderLeft", "frontUpperLeft", "frontLowerLeft"],
      target: QUATERNIUS_HORSE_BONES.frontTargetLeft,
    },
    frontRight: {
      bones: [
        QUATERNIUS_HORSE_BONES.frontShoulderRight,
        QUATERNIUS_HORSE_BONES.frontUpperRight,
        QUATERNIUS_HORSE_BONES.frontLowerRight,
      ],
      hoof: QUATERNIUS_HORSE_BONES.frontHoofRight,
      segments: ["frontShoulderRight", "frontUpperRight", "frontLowerRight"],
      target: QUATERNIUS_HORSE_BONES.frontTargetRight,
    },
    hindLeft: {
      bones: [
        QUATERNIUS_HORSE_BONES.hindShoulderLeft,
        QUATERNIUS_HORSE_BONES.hindUpperLeft,
        QUATERNIUS_HORSE_BONES.hindMiddleLeft,
        QUATERNIUS_HORSE_BONES.hindLowerLeft,
      ],
      hoof: QUATERNIUS_HORSE_BONES.hindHoofLeft,
      segments: ["hindShoulderLeft", "hindUpperLeft", "hindMiddleLeft", "hindLowerLeft"],
      target: QUATERNIUS_HORSE_BONES.hindTargetLeft,
    },
    hindRight: {
      bones: [
        QUATERNIUS_HORSE_BONES.hindShoulderRight,
        QUATERNIUS_HORSE_BONES.hindUpperRight,
        QUATERNIUS_HORSE_BONES.hindMiddleRight,
        QUATERNIUS_HORSE_BONES.hindLowerRight,
      ],
      hoof: QUATERNIUS_HORSE_BONES.hindHoofRight,
      segments: ["hindShoulderRight", "hindUpperRight", "hindMiddleRight", "hindLowerRight"],
      target: QUATERNIUS_HORSE_BONES.hindTargetRight,
    },
  },
  neck: [QUATERNIUS_HORSE_BONES.neck1, QUATERNIUS_HORSE_BONES.neck2, QUATERNIUS_HORSE_BONES.neck3],
  saddle: {
    offset: [0, 0.34, -0.12],
    pelvisToWithers: 0.42,
  },
  tail: [
    QUATERNIUS_HORSE_BONES.tail1,
    QUATERNIUS_HORSE_BONES.tail2,
    QUATERNIUS_HORSE_BONES.tail3,
    QUATERNIUS_HORSE_BONES.tail4,
    QUATERNIUS_HORSE_BONES.tail5,
    QUATERNIUS_HORSE_BONES.tail6,
    QUATERNIUS_HORSE_BONES.tail7,
  ],
} as const satisfies HorseRigAdapter;
