use starknet::ContractAddress;
use starknet::storage::Map;
use crate::release::Release;

#[starknet::storage_node]
pub struct GamesStorage<
    TResourceAmount,
    TPhase,
    TContribution,
    TMineFunding,
    TPlayerResult,
    TDepositRules,
    TBuilding,
    TStructureBuildings,
    TBoardTerms,
    TNeighborBonus,
    TBuildingTerms,
    TWonderFaith,
    TFaithfulStructure,
    TPlayerFaithPoints,
    TFaithRules,
    TGameRegistry,
    TSliceRules,
    TGuard,
    TGuild,
    THyperstructure,
    TConstructionResource,
    TShare,
    TSpireLayout,
    TExplorationReward,
    TMarket,
    TBankRules,
    TMineKindConfig,
    TMineWeight,
    TRecipeTerms,
    TProductionBonus,
    TRosterPlayer,
    TRelicRule,
    TChestRules,
    TChestReward,
    TProduction,
    TProductionReceiver,
    TWeight,
    TSettlementRules,
    TSettlementProgress,
    TPlayerEntry,
    TTroopType,
    TEntryEntitlement,
    TDepthRules,
    TStructureRecord,
    TTradeOrder,
    TTradeRules,
    TExplorerTroops,
    TUpgradeLimits,
    TVillageResource,
    TVillagePass,
    TWithdrawalTerms,
    TRetention,
> {
    pub authority: ContractAddress,
    pub releases: Map<u32, Release>,
    pub game_releases: Map<u32, u32>,
    pub current_release: u32,
    pub arrivals: crate::arrivals::ArrivalStateStorage<TResourceAmount>,
    pub bitcoin: crate::bitcoin::BitcoinStateStorage<TPhase, TContribution, TMineFunding>,
    pub blitz_results: crate::blitz_results::BlitzResultStateStorage<TPlayerResult>,
    pub bridge: crate::bridge::BridgeStateStorage<TDepositRules>,
    pub buildings: crate::buildings::BuildingStateStorage<
        TBuilding, TStructureBuildings, TBoardTerms, TNeighborBonus, TBuildingTerms, TResourceAmount,
    >,
    pub combat_domain: crate::combat_domain::CombatDomainStorage,
    pub entry: crate::entry::EntryAdministrationStorage,
    pub faith: crate::faith::FaithStateStorage<TWonderFaith, TFaithfulStructure, TPlayerFaithPoints, TFaithRules>,
    pub games: crate::game::GameStateStorage<TGameRegistry, TSliceRules>,
    pub guards: crate::guards::GuardStateStorage<TGuard>,
    pub guilds: crate::guilds::GuildStateStorage<TGuild>,
    pub hyperstructures: crate::hyperstructures::HyperstructureStateStorage<
        THyperstructure, TConstructionResource, TShare,
    >,
    pub map: crate::map::MapStateStorage,
    pub map_rules: crate::map::MapDomainStorage<TSpireLayout, TExplorationReward>,
    pub market: crate::market::MarketStateStorage<TMarket, TBankRules>,
    pub mines: crate::mines::MineStateStorage<TMineKindConfig, TMineWeight>,
    pub production: crate::production::ProductionStateStorage<TRecipeTerms, TResourceAmount, TProductionBonus>,
    pub realms: crate::realms::RealmStateStorage,
    pub registrar: crate::registrar::RegistrarStateStorage<TRosterPlayer>,
    pub relics: crate::relics::RelicStateStorage<TRelicRule, TChestRules, TChestReward>,
    pub resources: crate::resources::ResourceStateStorage<TProduction, TProductionReceiver, TWeight>,
    pub season: crate::season::SeasonPointsStorage,
    pub settlement_pool: crate::settlement::SettlementPoolStateStorage,
    pub settlements: crate::settlement::SettlementStateStorage<
        TSettlementRules, TResourceAmount, TSettlementProgress, TPlayerEntry, TTroopType, TEntryEntitlement,
    >,
    pub depths: crate::settlement_domain::SettlementDomainStorage<TDepthRules>,
    pub structures: crate::structures::StructureStateStorage<TStructureRecord>,
    pub structure_rules: crate::structures::StructuresDomainStorage<TResourceAmount>,
    pub trade: crate::trade::TradeStateStorage<TTradeOrder, TTradeRules>,
    pub troops: crate::troops::TroopStateStorage<TExplorerTroops>,
    pub upgrades: crate::upgrades::UpgradeStateStorage<TUpgradeLimits, TResourceAmount>,
    pub village: crate::village::VillageStateStorage<TResourceAmount, TVillageResource, TVillagePass>,
    pub withdrawals: crate::withdrawals::WithdrawalStateStorage<TWithdrawalTerms, TRetention>,
}
