use starknet::ContractAddress;
use starknet::storage::Map;
use crate::release::Release;

#[starknet::storage_node]
pub struct GamesStorage<
    TPreset,
    TResourceAmount,
    TPhase,
    TContribution,
    TMineFunding,
    TPlayerResult,
    TBuilding,
    TStructureBuildings,
    TWonderFaith,
    TFaithfulStructure,
    TPlayerFaithPoints,
    TGameRegistry,
    TGameOverrides,
    TGuard,
    TGuild,
    THyperstructure,
    TShare,
    TMarket,
    TProductionBonus,
    TRosterPlayer,
    TChestReward,
    TProduction,
    TWeight,
    TSettlementProgress,
    TPlayerEntry,
    TEntryEntitlement,
    TStructureRecord,
    TExpeditionSite,
    TTradeOrder,
    TExplorerTroops,
    TArmySlot,
    TArmyProgress,
    TVillagePass,
> {
    pub authority: ContractAddress,
    pub presets: Map<felt252, TPreset>,
    pub releases: Map<u32, Release>,
    pub game_releases: Map<u32, u32>,
    pub current_release: u32,
    pub arrivals: crate::arrivals::ArrivalStateStorage<TResourceAmount>,
    pub bitcoin: crate::bitcoin::BitcoinStateStorage<TPhase, TContribution, TMineFunding>,
    pub blitz_results: crate::blitz_results::BlitzResultStateStorage<TPlayerResult>,
    pub buildings: crate::buildings::BuildingStateStorage<TBuilding, TStructureBuildings>,
    pub combat_domain: crate::combat_domain::CombatDomainStorage,
    pub entry: crate::entry::EntryAdministrationStorage,
    pub faith: crate::faith::FaithStateStorage<TWonderFaith, TFaithfulStructure, TPlayerFaithPoints>,
    pub games: crate::game::GameStateStorage<TGameRegistry, TGameOverrides>,
    pub guards: crate::guards::GuardStateStorage<TGuard>,
    pub guilds: crate::guilds::GuildStateStorage<TGuild>,
    pub hyperstructures: crate::hyperstructures::HyperstructureStateStorage<THyperstructure, TShare>,
    pub map: crate::map::MapStateStorage,
    pub map_rules: crate::map::MapDomainStorage,
    pub market: crate::market::MarketStateStorage<TMarket>,
    pub production: crate::production::ProductionStateStorage<TProductionBonus>,
    pub realms: crate::realms::RealmStateStorage,
    pub registrar: crate::registrar::RegistrarStateStorage<TRosterPlayer>,
    pub relics: crate::relics::RelicStateStorage<TChestReward>,
    pub resources: crate::resources::ResourceStateStorage<TProduction, TWeight>,
    pub season: crate::season::SeasonPointsStorage,
    pub settlement_pool: crate::settlement::SettlementPoolStateStorage,
    pub settlements: crate::settlement::SettlementStateStorage<TSettlementProgress, TPlayerEntry, TEntryEntitlement>,
    pub structures: crate::structures::StructureStateStorage<TStructureRecord, TExpeditionSite>,
    pub structure_rules: crate::structures::StructuresDomainStorage,
    pub trade: crate::trade::TradeStateStorage<TTradeOrder>,
    pub troops: crate::troops::TroopStateStorage<TExplorerTroops, TArmySlot, TArmyProgress>,
    pub village: crate::village::VillageStateStorage<TVillagePass>,
}
