use starknet::ContractAddress;
use starknet::storage::Map;

/// Shared immutable configuration. Games store only their preset id and launch overrides.
#[starknet::storage_node]
pub struct PresetStorage<
    TSliceRules,
    TResourceAmount,
    TRecipeTerms,
    TMineKindConfig,
    TMineWeight,
    TBoardTerms,
    TNeighborBonus,
    TBuildingTerms,
    TFaithRules,
    TUpgradeLimits,
    TSettlementMode,
    TTroopType,
    TDepthRules,
    TVillageResource,
    TSpireLayout,
    TTradeRules,
    TBankRules,
    TConstructionResource,
    TRelicRule,
    TChestRules,
    TArmyProgressionRules,
    TFrontierDiscoveryRules,
    TDepositRules,
    TWithdrawalTerms,
    TRetention,
    TExplorationReward,
> {
    pub rules: TSliceRules,
    pub resource_rules: Map<u8, (u128, u128)>,
    pub production_terms: Map<u8, TRecipeTerms>,
    pub production_inputs: Map<(u8, bool, u8), TResourceAmount>,
    pub mine_kind_count: u32,
    pub mine_kind_ids: Map<u32, u8>,
    pub mine_kinds: Map<u8, TMineKindConfig>,
    pub mine_pool_count: u8,
    pub mine_weights: Map<u8, TMineWeight>,
    pub board_terms: Option<TBoardTerms>,
    pub board_neighbors: Map<u8, TNeighborBonus>,
    pub building_terms: Map<u8, TBuildingTerms>,
    pub building_costs: Map<(u8, bool, u8), TResourceAmount>,
    pub camp_resource_count: u32,
    pub camp_grants: Map<u32, TResourceAmount>,
    pub faith_rules: TFaithRules,
    pub upgrade_limits: TUpgradeLimits,
    pub upgrade_cost_counts: Map<u8, u32>,
    pub upgrade_costs: Map<(u8, u32), TResourceAmount>,
    pub settlement_mode: TSettlementMode,
    pub settlement_spacing: u32,
    pub depth_count: u32,
    pub depth_rules: Map<u8, Option<TDepthRules>>,
    pub realm_grant_count: u32,
    pub realm_grants: Map<u32, TResourceAmount>,
    pub starting_troops: Map<u8, TTroopType>,
    pub realm_resource_count: u8,
    pub realm_resources: Map<u8, u8>,
    pub village_delay: u16,
    pub village_grant_count: u32,
    pub village_grants: Map<u32, TResourceAmount>,
    pub village_pool: Map<u8, TVillageResource>,
    pub spires: Option<TSpireLayout>,
    pub trade_rules: TTradeRules,
    pub bank_rules: TBankRules,
    pub hyper_cost_count: u32,
    pub hyper_shards: u128,
    pub hyper_costs: Map<u32, TConstructionResource>,
    pub relic_rules: Map<u8, TRelicRule>,
    pub chest_rules: Option<TChestRules>,
    pub discovery_rules: Option<TFrontierDiscoveryRules>,
    pub progression_rules: Option<TArmyProgressionRules>,
    pub artificer_cost: u128,
    pub deposit_rules: Option<TDepositRules>,
    pub withdrawal_terms: TWithdrawalTerms,
    pub withdrawal_retention: Map<u32, TRetention>,
    pub withdrawal_tokens: Map<u8, ContractAddress>,
    pub exploration_reward_count: u32,
    pub exploration_rewards: Map<u32, TExplorationReward>,
    pub season_win_points: u128,
}
