[package]
name = "collectibles_claim"
version = "1.0.0"
cairo-version = "2.13.1"
edition = "2023_11"

[lib]

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.13.1"
cartridge_vrf = { git = "https://github.com/cartridge-gg/vrf", rev = "6d1c0f60a53558f19618b2bff81c3da0849db270" }
openzeppelin = "=2.0.0"
openzeppelin_utils = "=2.0.0"
stark_vrf = "0.1.1"

[dev-dependencies]
snforge_std = "0.51.2"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.fmt]
sort-module-level-items = true
max-line-length = 120
