import { BuildingThumbs } from "@/ui/config";
import { RealmInfo as RealmInfoType, ResourcesIds } from "@bibliothecadao/types";
import { useState } from "react";
import { BuildingsList } from "./buildings-list";
import { ProductionControls } from "./production-controls";
import { RealmInfo } from "./realm-info";

export const ProductionBody = ({
  realm,
  preSelectedResource,
}: {
  realm: RealmInfoType;
  preSelectedResource?: ResourcesIds;
}) => {
  const [selectedResource, setSelectedResource] = useState<ResourcesIds | null>(preSelectedResource || null);

  return (
    <>
      <div className="space-y-2">
        <RealmInfo realm={realm} />
        <div className="mb-4 p-3 border border-gray-700 bg-gray-900 rounded-md text-sm opacity-80 flex gap-2">
          <img src={BuildingThumbs.question} alt="hint" className="w-14 h-14" />
          <div className="flex flex-col">
            <p className="text-amber-400 font-semibold mb-1">Greetings, noble Lord!</p>
            <p>
              Resources can be produced in two ways in your land - by spending labor or by consuming raw materials.
              Using raw resources could be cheaper, but requires careful management of your supply chains. Labor can be
              generated by spending any resource you desire and food.
            </p>
          </div>
        </div>
        <BuildingsList realm={realm} onSelectProduction={setSelectedResource} selectedResource={selectedResource} />
        {selectedResource && <ProductionControls selectedResource={selectedResource} realm={realm} />}
      </div>
    </>
  );
};
