use starknet::ContractAddress;
use crate::alias::ID;
use crate::models::hyperstructure::ConstructionAccess;

/// # Hyperstructure Systems Interface
///
/// This interface defines the core functions for managing hyperstructures in the Eternum game.
/// Hyperstructures are large-scale collaborative buildings that players can contribute resources
/// to, earn points from, and share ownership of through a shareholder system.
///
/// ## Key Formulas
///
/// * Construction Points Calculation:
///   `generated_construction_points
///     = (contributed_resource_amount_contributed / total_resource_amount) *
///     total_points_generated_for_that_particular_resource's_completion`
///
///
/// * Share Points Generation:
///   `generated_share_points = (shareholder_percentage / 100) * time_elapsed * points_per_second `
///
#[starknet::interface]
trait IHyperstructureSystems<T> {
    /// Initializes a hyperstructure, making it ready to receive contributions.
    ///
    /// This function must be called by the hyperstructure owner before any contributions can be
    /// made.
    /// It spends a specified amount of Earthen Shards from the hyperstructure's balance to activate
    /// it.
    ///
    /// # Arguments
    /// * `hyperstructure_id` - The ID of the hyperstructure to initialize
    ///
    /// # Requirements
    /// * Caller must own the structure
    /// * Structure must be of hyperstructure category
    /// * Hyperstructure must not already be initialized
    /// * Hyperstructure must have sufficient Earthen Shards for initialization
    ///
    /// # Effects
    /// * Sets the hyperstructure as initialized
    /// * Calculates and records total resources needed for construction
    /// * Spends Earthen Shards from the hyperstructure's balance

    fn initialize(ref self: T, game_id: u32, hyperstructure_id: ID);

    /// Contributes resources to a hyperstructure's construction.
    ///
    /// Players can contribute multiple resource types in a single transaction. Resources are taken
    /// from the specified structure and added to the hyperstructure's construction progress. The
    /// player earns construction points proportional to their contribution.
    ///
    /// # Arguments
    /// * `hyperstructure_id` - The ID of the hyperstructure to contribute to
    /// * `from_structure_id` - The ID of the structure providing the resources
    /// * `contribution` - A list of (resource_type, amount) pairs to contribute
    ///
    /// # Requirements
    /// * Caller must own the contributing structure
    /// * Hyperstructure must be initialized and not completed
    /// * Contributor must have access to the hyperstructure (based on access control settings)
    /// * Contributed amounts must be positive and not exceed remaining requirements
    /// * Contributed amounts must be multiples of RESOURCE_PRECISION
    ///
    /// # Effects
    /// * Burns resources from the contributing structure
    /// * Updates hyperstructure construction progress
    /// * Awards unregistered construction points to the contributor using the formula:
    ///   `points = (resource_amount / RESOURCE_PRECISION) * resource_point_value / (needed_amount /
    ///   RESOURCE_PRECISION)`
    /// * Marks hyperstructure as completed if all requirements are met
    /// * Automatically sets up initial shareholding for the hyperstructure owner when completed

    fn contribute(
        ref self: T, game_id: u32, hyperstructure_id: ID, from_structure_id: ID, contribution: Span<(u8, u128)>,
    );

    /// Allocates shares of a completed hyperstructure to a list of shareholders.
    ///
    /// Shares determine what percentage of points generated by the hyperstructure each player
    /// receives.
    /// The hyperstructure owner can redistribute shares at any time, which takes effect
    /// immediately.
    ///
    /// # Arguments
    /// * `hyperstructure_id` - The ID of the hyperstructure
    /// * `shareholders` - A list of (address, percentage) pairs, where percentage is in basis
    /// points (0-10000)
    ///
    /// # Requirements
    /// * Caller must own the hyperstructure
    /// * Hyperstructure must be initialized and completed
    /// * Total percentage allocated must equal exactly 100% (10000 basis points)
    /// * Maximum of 20 shareholders allowed
    /// * All shareholder addresses must be non-zero
    ///
    /// # Effects
    /// * Claims all pending share points for current shareholders before reallocation
    /// * Sets new shareholders with specified percentages
    /// * Updates the timestamp for point calculation
    fn allocate_shares(ref self: T, game_id: u32, hyperstructure_id: ID, shareholders: Span<(ContractAddress, u16)>);

    /// Updates the construction access control for a hyperstructure.
    ///
    /// The owner can control who is allowed to contribute resources to the hyperstructure:
    /// - Public: Anyone can contribute
    /// - GuildOnly: Only members of the owner's guild can contribute
    /// - OwnerOnly: Only the owner can contribute
    ///
    /// # Arguments
    /// * `hyperstructure_id` - The ID of the hyperstructure
    /// * `access` - The new access control setting
    ///
    /// # Requirements
    /// * Caller must own the hyperstructure
    /// * Hyperstructure must be initialized
    /// * If setting GuildOnly access, the owner must be a member of a guild
    ///
    /// # Effects
    /// * Updates the hyperstructure's access control setting
    fn update_construction_access(ref self: T, game_id: u32, hyperstructure_id: ID, access: ConstructionAccess);
}


#[dojo::contract]
pub mod hyperstructure_systems {
    use core::num::traits::zero::Zero;
    use dojo::model::ModelStorage;
    use dojo::world::WorldStorage;
    use starknet::ContractAddress;
    use crate::alias::ID;
    use crate::constants::{DEFAULT_NS, RESOURCE_PRECISION, ResourceTypes};
    use crate::models::config::{HyperstructureConfig, HyperstructureCostConfig, SeasonConfigImpl, WorldConfigUtilImpl};
    use crate::models::guild::GuildMember;
    use crate::models::hyperstructure::{
        CompletedHyperstructureImpl, ConstructionAccess, Hyperstructure, HyperstructureConstructionAccessImpl,
        HyperstructureRequirementsImpl, HyperstructureShareholders, PlayerRegisteredPoints,
    };
    use crate::models::map::{Tile, TileImpl};
    use crate::models::map2::TileOpt;
    use crate::models::owner::{OwnerAddressImpl, OwnerAddressTrait};
    use crate::models::position::Coord;
    use crate::models::resource::resource::{
        ResourceWeightImpl, SingleResource, SingleResourceImpl, SingleResourceStoreImpl, WeightStoreImpl,
    };
    use crate::models::season::SeasonPrize;
    use crate::models::structure::{StructureBase, StructureBaseStoreImpl, StructureCategory, StructureOwnerStoreImpl};
    use crate::models::weight::{Weight, WeightImpl};
    use crate::systems::utils::hyperstructure::resolve_points_multiplier;
    use crate::systems::utils::map::IMapImpl;
    use crate::systems::utils::share_points::settle_hyperstructure_shares;
    use crate::systems::utils::structure::iStructureImpl;
    use crate::utils::math::PercentageValueImpl;
    use crate::utils::random::VRFImpl;


    const HYPERSTRUCTURE_POINT_MULTIPLIER: u128 = 1_000_000;

    #[abi(embed_v0)]
    impl HyperstructureSystemsImpl of super::IHyperstructureSystems<ContractState> {
        fn initialize(ref self: ContractState, game_id: u32, hyperstructure_id: ID) {
            let mut world: WorldStorage = self.world(DEFAULT_NS());
            SeasonConfigImpl::get(world, game_id).assert_started_and_not_over();

            // ensure caller owns the structure
            let mut structure_owner: ContractAddress = StructureOwnerStoreImpl::retrieve(
                ref world, game_id, hyperstructure_id,
            );
            structure_owner.assert_caller_owner();

            // ensure structure is a hyperstructure
            let structure: StructureBase = StructureBaseStoreImpl::retrieve(ref world, game_id, hyperstructure_id);
            assert!(structure.category == StructureCategory::Hyperstructure.into(), "not a hyperstructure");

            // ensure hyperstructure has not been initialized
            let mut hyperstructure: Hyperstructure = world.read_model((game_id, hyperstructure_id));
            assert!(hyperstructure.initialized == false, "hyperstructure is already initialized");

            // spend shards from hyperstructure's balance
            let hyperstructure_config: HyperstructureConfig = WorldConfigUtilImpl::get_member(
                world, game_id, selector!("hyperstructure_config"),
            );
            let required_shards_amount = hyperstructure_config.initialize_shards_amount;
            let mut hyperstructure_weight: Weight = WeightStoreImpl::retrieve(ref world, game_id, hyperstructure_id);
            let shards_resource_weight_grams: u128 = ResourceWeightImpl::grams(
                ref world, game_id, ResourceTypes::EARTHEN_SHARD,
            );
            let mut hyperstructure_shard_resource: SingleResource = SingleResourceStoreImpl::retrieve(
                ref world,
                game_id,
                hyperstructure_id,
                ResourceTypes::EARTHEN_SHARD,
                ref hyperstructure_weight,
                shards_resource_weight_grams,
                true,
            );

            // spend required shards amount for initialization
            hyperstructure_shard_resource
                .spend(required_shards_amount, ref hyperstructure_weight, shards_resource_weight_grams);
            hyperstructure_shard_resource.store(ref world);
            hyperstructure_weight.store(ref world, game_id, hyperstructure_id);

            // set total needed amount
            let mut construction_total_needed_amount = 0;
            let hyperstructure_cost_config: HyperstructureCostConfig = WorldConfigUtilImpl::get_member(
                world, game_id, selector!("hyperstructure_cost_config"),
            );
            for i in 0..hyperstructure_cost_config.construction_resources_ids.len() {
                let resource_type = *hyperstructure_cost_config.construction_resources_ids.at(i);
                construction_total_needed_amount +=
                    HyperstructureRequirementsImpl::get_amount_needed(ref world, hyperstructure, resource_type);
            }
            HyperstructureRequirementsImpl::initialize(ref world, game_id, hyperstructure_id);
            HyperstructureRequirementsImpl::write_needed_resource_total(
                ref world, game_id, hyperstructure_id, construction_total_needed_amount,
            );

            // set hyperstructure as initialized
            hyperstructure.initialized = true;
            world.write_model(@hyperstructure);

            // update structure tile
            let hyperstructure_coord = Coord { alt: false, x: structure.coord_x, y: structure.coord_y };
            let hyperstructure_tile_opt: TileOpt = world
                .read_model((game_id, hyperstructure_coord.alt, hyperstructure_coord.x, hyperstructure_coord.y));
            let mut hyperstructure_tile: Tile = hyperstructure_tile_opt.into();
            let hyperstructure_tile_occupier = IMapImpl::get_hyperstructure_occupier(1);
            IMapImpl::occupy(ref world, ref hyperstructure_tile, hyperstructure_tile_occupier, hyperstructure_id);
        }

        fn contribute(
            ref self: ContractState,
            game_id: u32,
            hyperstructure_id: ID,
            from_structure_id: ID,
            contribution: Span<(u8, u128)>,
        ) {
            let mut world: WorldStorage = self.world(DEFAULT_NS());
            SeasonConfigImpl::get(world, game_id).assert_started_and_not_over();

            // ensure caller structure is owned by caller
            let from_structure_owner: ContractAddress = StructureOwnerStoreImpl::retrieve(
                ref world, game_id, from_structure_id,
            );
            from_structure_owner.assert_caller_owner();

            // ensure structure is a hyperstructure
            let structure_base: StructureBase = StructureBaseStoreImpl::retrieve(ref world, game_id, hyperstructure_id);
            assert!(structure_base.category == StructureCategory::Hyperstructure.into(), "not a hyperstructure");

            // ensure hyperstructure is initialized and not completed
            let mut hyperstructure: Hyperstructure = world.read_model((game_id, hyperstructure_id));
            assert!(hyperstructure.initialized, "hyperstructure has not been initialized");
            assert!(hyperstructure.completed == false, "hyperstructure has been completed");

            // ensure contributor has access to contribute to the hyperstructure
            let hyperstructure_owner: ContractAddress = StructureOwnerStoreImpl::retrieve(
                ref world, game_id, hyperstructure_id,
            );
            hyperstructure.assert_caller_construction_access(ref world, hyperstructure_owner);

            // contribute to hyperstructure
            let mut total_resource_amount_contributed_by_structure = 0;
            let mut from_structure_weight: Weight = WeightStoreImpl::retrieve(ref world, game_id, from_structure_id);
            for (resource_type, resource_amount) in contribution {
                let (resource_type, resource_amount) = (*resource_type, *resource_amount);
                assert!(resource_amount.is_non_zero(), "contributed amount must be greater than zero");

                // ensure that resource amount does not exceed max contributable
                let current_contributed_amount = HyperstructureRequirementsImpl::read_current_amount(
                    ref world, game_id, hyperstructure_id, resource_type,
                );
                let needed_contribution_amount = HyperstructureRequirementsImpl::get_amount_needed(
                    ref world, hyperstructure, resource_type,
                );
                let max_contributable_amount = needed_contribution_amount - current_contributed_amount;
                assert!(
                    max_contributable_amount.is_non_zero(), "contribution for resource ({})is complete", resource_type,
                );

                // ensure resource amount is a multiplier of RESOURCE_PRECISION
                let resource_amount = core::cmp::min(max_contributable_amount, resource_amount);
                assert!(resource_amount % RESOURCE_PRECISION == 0, "amount not multiplier of RESOURCE_PRECISION");

                // burn caller structure's resource
                let resource_weight_grams: u128 = ResourceWeightImpl::grams(ref world, game_id, resource_type);
                let mut from_structure_resource: SingleResource = SingleResourceStoreImpl::retrieve(
                    ref world,
                    game_id,
                    from_structure_id,
                    resource_type,
                    ref from_structure_weight,
                    resource_weight_grams,
                    true,
                );
                from_structure_resource.spend(resource_amount, ref from_structure_weight, resource_weight_grams);
                from_structure_resource.store(ref world);

                // update current contributable amount
                HyperstructureRequirementsImpl::write_current_amount(
                    ref world, game_id, hyperstructure_id, resource_type, current_contributed_amount + resource_amount,
                );
                total_resource_amount_contributed_by_structure += resource_amount;

                // add points to player's registered points and update global total registered
                // points
                let generated_points = (resource_amount / RESOURCE_PRECISION)
                    * HyperstructureRequirementsImpl::get_resource_points(ref world, game_id, resource_type)
                    / (needed_contribution_amount / RESOURCE_PRECISION);

                let mut player_points: PlayerRegisteredPoints = world.read_model((game_id, from_structure_owner));
                let mut season_prize: SeasonPrize = world.read_model(game_id);
                player_points.registered_points += generated_points;
                season_prize.total_registered_points += generated_points;

                world.write_model(@player_points);
                world.write_model(@season_prize);
            }

            // update structure weight
            from_structure_weight.store(ref world, game_id, from_structure_id);

            assert!(total_resource_amount_contributed_by_structure.is_non_zero(), "no resources contributed");

            // update resource amount contributed by all
            let total_resource_amount_contributed_by_all = HyperstructureRequirementsImpl::read_current_resource_total(
                ref world, game_id, hyperstructure_id,
            );
            let new_total_resource_amount_contributed_by_all = (total_resource_amount_contributed_by_all
                + total_resource_amount_contributed_by_structure);
            HyperstructureRequirementsImpl::write_current_resource_total(
                ref world, game_id, hyperstructure_id, new_total_resource_amount_contributed_by_all,
            );
            let needed_total_resource_amount_contributed_by_all =
                HyperstructureRequirementsImpl::read_needed_resource_total(
                ref world, game_id, hyperstructure_id,
            );

            // mark hyperstructure as completed, if completed
            if new_total_resource_amount_contributed_by_all == needed_total_resource_amount_contributed_by_all {
                hyperstructure.completed = true;
                hyperstructure.points_multiplier = resolve_points_multiplier(ref world, game_id, hyperstructure_id);
                world.write_model(@hyperstructure);

                // increase hyperstructure completed count
                CompletedHyperstructureImpl::record(ref world, game_id, hyperstructure_id);

                // make hyperstructure owner start receiving points
                world
                    .write_model(
                        @HyperstructureShareholders {
                            game_id,
                            hyperstructure_id,
                            start_at: starknet::get_block_timestamp(),
                            shareholders: array![
                                (hyperstructure_owner, PercentageValueImpl::_100().try_into().unwrap()),
                            ]
                                .span(),
                        },
                    );

                // update structure tile
                let hyperstructure_coord = Coord { alt: false, x: structure_base.coord_x, y: structure_base.coord_y };
                let hyperstructure_tile_opt: TileOpt = world
                    .read_model((game_id, hyperstructure_coord.alt, hyperstructure_coord.x, hyperstructure_coord.y));
                let mut hyperstructure_tile: Tile = hyperstructure_tile_opt.into();
                let hyperstructure_tile_occupier = IMapImpl::get_hyperstructure_occupier(2);
                IMapImpl::occupy(ref world, ref hyperstructure_tile, hyperstructure_tile_occupier, hyperstructure_id);
            }
        }

        fn allocate_shares(
            ref self: ContractState, game_id: u32, hyperstructure_id: ID, shareholders: Span<(ContractAddress, u16)>,
        ) {
            let mut world: WorldStorage = self.world(DEFAULT_NS());
            SeasonConfigImpl::get(world, game_id).assert_started_and_not_over();

            // ensure the structure is owned by caller
            let structure_owner: ContractAddress = StructureOwnerStoreImpl::retrieve(
                ref world, game_id, hyperstructure_id,
            );
            structure_owner.assert_caller_owner();

            // ensure the structure is a hyperstructure
            let structure: StructureBase = StructureBaseStoreImpl::retrieve(ref world, game_id, hyperstructure_id);
            assert!(structure.category == StructureCategory::Hyperstructure.into(), "not a hyperstructure");

            // ensure hyperstructure is initialized and completed
            let mut hyperstructure: Hyperstructure = world.read_model((game_id, hyperstructure_id));
            assert!(hyperstructure.initialized, "hyperstructure has not been initialized");
            assert!(hyperstructure.completed, "hyperstructure has not been completed");

            let blitz_mode_on: bool = WorldConfigUtilImpl::get_member(world, game_id, selector!("blitz_mode_on"));
            match blitz_mode_on {
                true => {
                    assert!(shareholders.len() == 1, "too many shareholders, maximum of 1");
                    let (address, percentage) = *shareholders.at(0);
                    assert!(percentage.into() == PercentageValueImpl::_100(), "percentage must be 100%");
                    assert!(address.is_non_zero(), "shareholder must be set");
                    assert!(address == structure_owner, "shareholder must be the structure owner");
                },
                false => {
                    assert!( // 20 is the max for non-blitz mode
                        shareholders.len() <= 20, "too many shareholders, maximum of 20",
                    );
                },
            }

            // ensure the allocated percentage does not exceed 100%
            let mut allocated_percentage: u16 = 0;
            for i in 0..shareholders.len() {
                let (address, percentage) = *shareholders.at(i);
                assert!(address.is_non_zero(), "zero address shareholders");
                allocated_percentage += percentage;

                // ensure the min percentage is 1% to ensure that no one's
                // generated points round out to zero
                assert!(percentage.into() >= PercentageValueImpl::_1(), "minimum percentage is 1%");

                // initialize the player registered points model in the indexer
                // if not present
                let player_points_initializer: PlayerRegisteredPoints = world.read_model((game_id, address));
                world.write_model(@player_points_initializer);
            }
            assert!(
                allocated_percentage.into() == PercentageValueImpl::_100(),
                "total allocated percentage must be {}",
                PercentageValueImpl::_100(),
            );

            // todo check no adverse effect of duplicated shareholder address

            // claim points for current shareholders
            settle_hyperstructure_shares(ref world, game_id, hyperstructure_id);
            hyperstructure.points_multiplier = resolve_points_multiplier(ref world, game_id, hyperstructure_id);
            world.write_model(@hyperstructure);

            let hyperstructure_shareholders = HyperstructureShareholders {
                game_id, hyperstructure_id, start_at: starknet::get_block_timestamp(), shareholders,
            };
            world.write_model(@hyperstructure_shareholders);
        }

        fn update_construction_access(
            ref self: ContractState, game_id: u32, hyperstructure_id: ID, access: ConstructionAccess,
        ) {
            let mut world: WorldStorage = self.world(DEFAULT_NS());
            SeasonConfigImpl::get(world, game_id).assert_started_and_not_over();

            // ensure the structure is a hyperstructure
            let structure_owner: ContractAddress = StructureOwnerStoreImpl::retrieve(
                ref world, game_id, hyperstructure_id,
            );
            structure_owner.assert_caller_owner();

            let structure_base: StructureBase = StructureBaseStoreImpl::retrieve(ref world, game_id, hyperstructure_id);
            assert!(structure_base.category == StructureCategory::Hyperstructure.into(), "not a hyperstructure");

            // ensure hyperstructure is initialized
            let mut hyperstructure: Hyperstructure = world.read_model((game_id, hyperstructure_id));
            assert!(hyperstructure.initialized, "hyperstructure has not been initialized");

            // ensure owner has a guild if set to guild only
            if (access == ConstructionAccess::GuildOnly) {
                let structure_owner_guild_member: GuildMember = world.read_model((game_id, structure_owner));
                assert!(structure_owner_guild_member.guild_id.is_non_zero(), "you are not a member of any guild");
            }

            // update construction access
            hyperstructure.access = access;
            world.write_model(@hyperstructure);
        }
    }
}
