[package]
name = "esp"
version = "1.0.0"
cairo-version = "2.13.1"
edition = "2023_11"

[lib]

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.13.1"
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "v0.5.2" }
openzeppelin = "=2.0.0"
openzeppelin_utils = "=2.0.0"
graffiti = { git = "https://github.com/ponderingdemocritus/graffiti", rev = "bc569531791dbc71c6cd8d9bc154c34eedad31fe" }

[dev-dependencies]
snforge_std = "0.51.2"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.fmt]
sort-module-level-items = true
max-line-length = 120
