import { shortString } from "starknet";
import type { NativeCommandPayloads, NativeCommand } from "../../../contracts/l3/world-native/schema/commands.gen";

// Typed missing-state probes follow the integrator's roll_independence.cairo vectors. These exercise domain rollback,
// not disabled masks or invalid calldata. Happy paths in the fixture replace these for state that can be prepared.
export const MISSING_ENTITY = 999999n;
const missing = MISSING_ENTITY;
const other = missing - 1n;
const coord = { alt: false, x: 2000000, y: 2000000 };
const resources = [{ resource_type: 1, amount: 1n }];
const transfer = { from_entity_id: missing, to_entity_id: other, resources };
const swap = { bank_id: missing, structure_id: other, resource_type: 1, amount: 1n };
const building = { structure_id: missing, coord };
const guard = { structure_id: missing, slot: 0 };
const address = "0x3e7";

const routePayloads = {
  CreateExplorer: { structure_id: missing, category: 0, tier: 0, amount: 1n, direction: 0 },
  Explore: { explorer_id: missing, direction: 0 },
  Battle: { attacker_id: missing, defender_id: other, steal_resources: resources },
  Move: { explorer_id: missing, directions: [0] },
  ToggleAlternate: { explorer_id: missing, spire_direction: 0 },
  TransferStructureOwnership: { entity_id: missing, new_owner: address },
  LevelUp: missing,
  SettleBlitzRoster: undefined,
  ProvisionRealm: missing,
  CreateReservedHyperstructure: coord,
  SettleSeason: { name: shortString.encodeShortString("route"), selected_realm: { kind: "None", value: undefined } },
  SettleVillage: { pass_id: 1, connected_realm_entity_id: missing },
  ReceiveVillageArmy: missing,
  BurnStructureResources: { entity_id: missing, resources },
  TransferExplorerResources: transfer,
  TransferStructureResourcesToExplorer: transfer,
  OffloadArrival: { entity_id: missing, day: 0, slot: 0, resource_count: 1 },
  SendResources: transfer,
  TransferExplorerResourcesToStructure: transfer,
  BurnLaborForResourceProduction: { structure_id: missing, resource_types: [1], amounts: [1n] },
  BurnResourceForResourceProduction: { structure_id: missing, resource_types: [1], amounts: [1n] },
  CreateBuilding: { structure_id: missing, directions: [0], category: 0, use_simple: false },
  DestroyBuilding: building,
  PauseBuildingProduction: building,
  ResumeBuildingProduction: building,
  ContributeBitcoinLabor: { structure_id: missing, amount: 0n },
  CloseBitcoinPhase: 0,
  BindBitcoinPhase: 0,
  ClaimBitcoinPhase: { phase: 0, mine_ids: [missing] },
  BattleGuard: { attacker_id: missing, defender_id: other },
  CreateTradeOrder: {
    maker_id: missing,
    taker_id: other,
    offered_resource: 1,
    requested_resource: 2,
    offered_per_lot: 1n,
    requested_per_lot: 1n,
    lots: 1,
    expires_at: 0,
  },
  AcceptTradeOrder: { trade_id: missing, taker_id: other, lots: 1 },
  CancelTradeOrder: missing,
  CreateBanks: Array.from({ length: 6 }, (_, index) => ({
    name: shortString.encodeShortString(`check-bank-${index}`),
    coord: { ...coord, x: coord.x + index * 10 },
  })),
  BuyFromBank: swap,
  SellToBank: swap,
  AddBankLiquidity: { bank_id: missing, structure_id: other, resource_type: 1, resource_amount: 1n, lords_amount: 1n },
  RemoveBankLiquidity: { bank_id: missing, structure_id: other, resource_type: 1, shares: 1n },
  InitializeHyperstructure: missing,
  ContributeHyperstructure: { hyperstructure_id: missing, from_structure_id: other, resources },
  AllocateHyperstructureShares: { hyperstructure_id: missing, shareholders: [{ player: address, bps: 10000 }] },
  SetConstructionAccess: { hyperstructure_id: missing, access: { kind: "Public", value: undefined } },
  OpenRelicChest: { explorer_id: missing, coord },
  ApplyRelic: { entity_id: missing, relic_id: 39, recipient: { kind: "Explorer", value: undefined } },
  CloseSeason: undefined,
  PledgeFaith: { structure_id: missing, wonder_id: other },
  RemoveFaith: missing,
  UpdateWonderOwnership: missing,
  UpdateFaithfulOwnership: missing,
  ClaimWonderPoints: missing,
  ClaimPlayerFaithPoints: { player: address, wonder_id: missing },
  RecordBlitzResults: { start: 0, players: [{ wallet: address, rank: 1 }] },
  CraftRelic: missing,
  CreateGuild: { owned_structure_id: missing, public: false, name: shortString.encodeShortString("route") },
  JoinGuild: { owned_structure_id: missing, guild_id: address },
  LeaveGuild: undefined,
  SetGuildWhitelist: { player: address, owned_structure_id: missing, allowed: false },
  RemoveGuildMember: address,
  MarkGameSettled: undefined,
  ManageTroops: {
    kind: "RecruitGuard",
    value: {
      guard,
      category: { kind: "Knight", value: undefined },
      tier: { kind: "T1", value: undefined },
      amount: 1n,
    },
  },
  GuardAttack: { guard, explorer_id: other },
  Raid: { explorer_id: missing, structure_id: other, steal_resources: resources },
  DepositResource: { structure_id: missing, resource_type: 1, amount: 1n, client_fee_recipient: address },
  WithdrawResource: {
    structure_id: missing,
    recipient: address,
    resource_type: 1,
    amount: 1n,
    client_fee_recipient: address,
  },
  ProvisionAndUpgradeRealm: missing,
  SetEntityName: { entity_id: missing, name: shortString.encodeShortString("route") },
  EnterDepth: { explorer_id: missing, depth: 1 },
  Research: { structure_id: missing, row: 0, choice: 0 },
  BuyTier: {
    explorer_id: missing,
    attribute: { kind: "Battle", value: undefined },
    kind: { kind: "None", value: undefined },
  },
  InteractSite: { explorer_id: missing, coord },
  RefillStamina: { explorer_id: missing },
  WithdrawLords: { structure_id: missing, amount: 1n },
} satisfies NativeCommandPayloads;

// Every refusal pins a route's actual first domain guard. A generic revert, disabled mask, missing stamp or wrong
// library cannot satisfy these expectations. undefined is an applied case; the fixture must assert its effect/no-op.
export const routeReasons: Record<NativeCommand["kind"], string | undefined> = {
  CreateExplorer: "missing home structure",
  Explore: "missing explorer",
  Battle: "missing explorer",
  Move: "missing explorer",
  ToggleAlternate: "missing explorer",
  TransferStructureOwnership: "missing structure",
  LevelUp: "missing structure",
  SettleBlitzRoster: "not a Blitz game",
  ProvisionRealm: "missing structure",
  CreateReservedHyperstructure: "reserved hyperstructures disabled",
  SettleSeason: undefined,
  SettleVillage: "missing structure",
  ReceiveVillageArmy: "missing structure",
  BurnStructureResources: "actor does not own structure",
  TransferExplorerResources: "missing explorer",
  TransferStructureResourcesToExplorer: "actor does not own structure",
  OffloadArrival: "actor does not own structure",
  SendResources: "actor does not own sender",
  TransferExplorerResourcesToStructure: "missing explorer",
  BurnLaborForResourceProduction: "missing producer structure",
  BurnResourceForResourceProduction: "missing producer structure",
  CreateBuilding: "actor does not own structure",
  DestroyBuilding: "actor does not own structure",
  PauseBuildingProduction: "actor does not own structure",
  ResumeBuildingProduction: "actor does not own structure",
  ContributeBitcoinLabor: "Bitcoin labor below minimum",
  CloseBitcoinPhase: "Bitcoin phase outside game",
  BindBitcoinPhase: "Bitcoin phase outside game",
  ClaimBitcoinPhase: "Bitcoin phase outside game",
  BattleGuard: "missing explorer",
  CreateTradeOrder: "missing trade structure",
  AcceptTradeOrder: "trade does not exist",
  CancelTradeOrder: "trade does not exist",
  CreateBanks: undefined,
  BuyFromBank: "missing trade structure",
  SellToBank: "missing trade structure",
  AddBankLiquidity: "missing trade structure",
  RemoveBankLiquidity: "missing trade structure",
  InitializeHyperstructure: "structure does not exist",
  ContributeHyperstructure: "structure does not exist",
  AllocateHyperstructureShares: "structure does not exist",
  SetConstructionAccess: "structure does not exist",
  OpenRelicChest: "missing explorer",
  ApplyRelic: "missing explorer",
  CloseSeason: undefined,
  PledgeFaith: "missing structure",
  RemoveFaith: "structure is not faithful",
  UpdateWonderOwnership: "missing structure",
  UpdateFaithfulOwnership: undefined,
  ClaimWonderPoints: "missing structure",
  ClaimPlayerFaithPoints: "missing structure",
  RecordBlitzResults: "result finalisation is disabled",
  CraftRelic: "missing structure",
  CreateGuild: "player does not own this structure",
  JoinGuild: "player does not own this structure",
  LeaveGuild: "not a guild member",
  SetGuildWhitelist: "guild does not exist",
  RemoveGuildMember: "not a member of this guild",
  MarkGameSettled: "game has not ended",
  ManageTroops: "missing home structure",
  GuardAttack: "missing home structure",
  Raid: "missing explorer",
  DepositResource: "structure does not exist",
  WithdrawResource: "structure does not exist",
  ProvisionAndUpgradeRealm: "missing structure",
  SetEntityName: "missing explorer",
  EnterDepth: "depth entry requires expeditions",
  Research: "actor does not own structure",
  BuyTier: "missing explorer",
  InteractSite: "site requires expedition",
  RefillStamina: "missing explorer",
  WithdrawLords: "actor does not own structure",
};

export function commandForRoute<K extends NativeCommand["kind"]>(route: K): NativeCommand {
  return { kind: route, value: routePayloads[route] } as NativeCommand;
}
