// Generated by scripts/settlement/generate-config-setter-inventory.mjs. Do not edit directly.
pub const CONFIG_SETTER_COUNT: usize = 45;

pub fn config_setter_selectors() -> Array<felt252> {
    array![
        0x31c3405166cebed0e5a059ef4e007e3d9cf62d66110c2c952c38732eef418a5, // factory:set_factory_config
        0x3c49cf5cb90dfd97fe7acfd30b311a755438c639b6e77f66ad5d30635b0e89d, // factory:set_factory_config_contracts
        0x1bf830ddcca34d1d5220557584ceae2981bf35881494b9aaa38c8e729628dcf, // factory:set_factory_config_events
        0x35669b0ffc77a27dc7022187bd3689f27c6c38f5f8c5b8f7b0ff488c2e13c57, // factory:set_factory_config_libraries
        0x38b56126fcd08e3f319210114b4db862d100f952791b95e14d4e7a18cb5e930, // factory:set_factory_config_models
        0x3358b5030ae1c774bc0bfbe8de9e483d0a25c93c222b9f5b53d78d1dd03e677, // factory:set_series_config
        0xb9b9a249b45402e76dd60ab333391beb014be202cabf481278d958b227e9f4, // world:set_agent_config
        0x3d21bac97e33fbc2aa999b1d98b4602a62d5cd7d4d7a410b1a5b461184ed817, // world:set_artificer_config
        0x3f5bb4de84fcd87a041588566879ee248a9cf0e23ae28329b223db245c27036, // world:set_bank_config
        0x3d10087741021673089ea4860bff353f76a5733cf0832fc9b27e2965c3c74ed, // world:set_battle_config
        0x165a252d6c591fd29c9773b03ac0cb75c37db199db736c4d6abe90937c78664, // world:set_biome_climate_config
        0x2c2b763bc5e3f1e541c6f297838efb63b9c8bda04b9901d4f14acfad3bbc084, // world:set_bitcoin_mine_config
        0x122ed795770b597914a8992c2e0abcdd8ae693df76dcc7fc3f6cfdb49a12bc8, // world:set_blitz_exploration_config
        0x7b4c6986e1f0200f58f1804e1bebe594c51e5e84586397ba17f382e244ba52, // world:set_blitz_registration_config
        0x1877b84efd5260fa9f20641ce09db80eeef827f6cf379cbc67880912a3c7c77, // world:set_building_category_config
        0x293b44b705569856c7433bac9a61a35c7d0c093f00c5f8d3fb14e27accdc42d, // world:set_building_config
        0x3498ae84c06601c439fdfb1431b4a2079fe4f9e4bf73731c38be7fa4bff7e48, // world:set_capacity_config
        0x20743412fa2bc13f30efa62f73c10bfdfaf213073ef14e335695326f1cd78ab, // world:set_donkey_speed_config
        0x1d7f08ce804bee81637e1ea41ce0dc68a3d25caeca1c0b7dfcb14dd39dbe894, // world:set_factory_address
        0xdb1edd97baa98b0a5f36de056abe2e0ca078fa301579f1ad3e090dcc1b7448, // world:set_faith_config
        0x26e35916b168ecce44d5a4d5b3bad169c04da6af41764f55db45c8e04900b9e, // world:set_game_mode_config
        0x16f4ece8614e3a5c84810106f6b95a6a17336d2bdaebbb88c67c054d1804405, // world:set_hyperstructure_config
        0x3c63168d455b22b51f3af866aabf73593dcd62f88462f1b2708130c65f8cffa, // world:set_map_config
        0x3b70c7dbb26a5e2b238d893a2cd4cb319cfbf9eed17132cafa70661bf15b90a, // world:set_mercenaries_name_config
        0x148a838124692abe8685fdab742fde583bfdc05cd87d287115b9eaf5aa716ca, // world:set_mmr_config
        0x1b8fbb836067297b4827db67b9c661724264e1e4b196fd77de5439e95039ce8, // world:set_quest_config
        0x278df23e0a150dd779a682fcf28d5545e5414a7670a03e6e18852b2b76d5cc, // world:set_resource_bridge_config
        0x3792840527af50a5b9b640f89dd93777cc9db0ec506516802e3544f57a1f62d, // world:set_resource_bridge_fee_split_config
        0x1b905659ec34a6395e6e2ceebbcb444a6af152095674251c8c90403e3e75cad, // world:set_resource_bridge_whitelist_config
        0x2bd9f6cc0105e294c0f585a1fe4064242618122c351876c76149f81cc1fc3ae, // world:set_resource_factory_config
        0x1ef8e5e2088b6937ce67a9f735aa1964b4f988bc2dd0a40ab027125b3adffa7, // world:set_resource_weight_config
        0x22b0c8998dbe5dbc57533c98005413bb40a30090d932d2c376be13a8965d239, // world:set_season_config
        0x274e1b8a332bff8a9b2293997706eec2cdafa4326f2aff9bc6ce8eb12dcaec0, // world:set_settlement_config
        0x259fe4040d959f2fae1cae1a499b2748169614d85682e7a537711dec5cb5a7e, // world:set_starting_resources_config
        0x17b1020e7525c63aebc51521e073b585515cfd574e12ca93874d57b7ccfd93f, // world:set_structure_level_config
        0x1e3a2239cc2c67adce73e8d22a86fd3dedd0aac09251b77464b51195d29cbd3, // world:set_structure_max_level_config
        0xce7487c0fb8b6793528608e371dffd9ac0164c264d3a3e800896af6bde14d7, // world:set_tick_config
        0x1e1092d1e199ecc1a2ab540648e77cb694b007d80a062c7f5918a1b393abf33, // world:set_trade_config
        0x23f5dae4f4fea662b737f0dad938f37c46f415fe2c467bf81bec8e976aa7187, // world:set_troop_config
        0x112178849fa01e884a18722b37506e5f0db4ac68760a7e8fe64316737a4139b, // world:set_victory_points_grant_config
        0x237099d1d8a8ae7836498b8f3b99e3528db47ea2a4119c1624cd7d087956fb3, // world:set_victory_points_win_config
        0x10f26b5e2fa6bd1be7029095be28bcf3d7a6f73d1a10b2848b91ea5f30c1a33, // world:set_village_found_resources_config
        0x47b10a3b5669ffd123031f2e4cd4c9079993e0fbceff2c125c4a6f35ff4233, // world:set_village_token_config
        0x1a44089d1d8978247edb884b5dd13488849fd56edbf3a64ff234ecb0cd5dde5, // world:set_vrf_config
        0x306288504bb3eb83a8dd64bc727c3d3e83b4e026a71acc0c3d2e0e4d69aac43 // world:set_world_config
    ]
}
