// Generated by scripts/settlement/generate-schema-vectors.mjs. Do not edit directly.
use starknet::ContractAddress;

pub type DeploymentId = felt252;

pub type SeasonId = felt252;

pub type GameId = felt252;

pub type MessageId = felt252;

pub type IngressId = felt252;

pub type LiabilityId = felt252;

pub type BatchId = u64;

#[derive(Drop, Serde)]
pub struct ProtocolEnvelope {
    pub magic: felt252,
    pub version: u16,
    pub source_chain_id: felt252,
    pub destination_chain_id: felt252,
    pub deployment_id: DeploymentId,
    pub season_id: SeasonId,
    pub game_id: GameId,
    pub action: u16,
    pub transport_nonce: u64,
    pub message_id: MessageId,
}

#[derive(Drop, Serde)]
pub struct ClaimLeg {
    pub asset_mode: u8,
    pub asset_id: u32,
    pub backing_pool_id: felt252,
    pub recipient: ContractAddress,
    pub amount_or_token_id: u256,
    pub policy_key: felt252,
}

#[derive(Drop, Serde)]
pub struct ClaimLeaf {
    pub version: u16,
    pub deployment_id: DeploymentId,
    pub season_id: SeasonId,
    pub game_id: GameId,
    pub batch_id: BatchId,
    pub leaf_index: u8,
    pub claim_kind: u16,
    pub liability_id: LiabilityId,
    pub claimant_l2: ContractAddress,
    pub recipient_l1: ContractAddress,
    pub legs_hash: felt252,
    pub aux_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct AbortRefundAux {
    pub source_ingress_or_pool_id: felt252,
    pub funding_source_id: felt252,
    pub disposition_epoch: u32,
    pub refund_kind: u16,
    pub refund_policy_hash: felt252,
    pub unused_amount: u256,
}

#[derive(Drop, Serde)]
pub struct LiabilityTotal {
    pub game_id: GameId,
    pub asset_mode: u8,
    pub asset_id: u32,
    pub backing_pool_id: felt252,
    pub payout_purpose: felt252,
    pub amount_or_count: u256,
}

#[derive(Drop, Serde)]
pub struct CapacityAllocation {
    pub game_id: GameId,
    pub asset_mode: u8,
    pub asset_id: u32,
    pub backing_pool_id: felt252,
    pub amount_or_quota: u256,
}

#[derive(Drop, Serde)]
pub struct BackingKey {
    pub deployment_id: DeploymentId,
    pub game_id: GameId,
    pub asset_mode: u8,
    pub asset_id: u32,
    pub backing_pool_id: felt252,
}

#[derive(Drop, Serde)]
pub struct BackingTotal {
    pub key: BackingKey,
    pub amount_or_quota: u256,
}

#[derive(Drop, Serde)]
pub struct GameBackingLot {
    pub game_id: GameId,
    pub parent_key_hash: felt252,
    pub lot_index: u8,
    pub lot_class: u8,
    pub source_index: u16,
    pub source_id: felt252,
    pub allocated_total: u256,
    pub active_committed_total: u256,
    pub cumulative_outbox_total: u256,
    pub returned_unused_total: u256,
}

#[derive(Drop, Serde)]
pub struct LotSharePromotion {
    pub game_id: GameId,
    pub parent_key_hash: felt252,
    pub lot_index: u8,
    pub amount: u256,
}

#[derive(Drop, Serde)]
pub enum HubBatchSealState {
    Unknown,
    Open,
    Sealed,
}

#[derive(Drop, Serde)]
pub struct HubBackingAggregate {
    pub game_id: GameId,
    pub parent_key_hash: felt252,
    pub active_committed_total: u256,
    pub cumulative_outbox_total: u256,
}

#[derive(Drop, Serde)]
pub struct HubLotAggregate {
    pub game_id: GameId,
    pub parent_key_hash: felt252,
    pub lot_index: u8,
    pub active_committed_total: u256,
    pub cumulative_outbox_total: u256,
}

#[derive(Drop, Serde)]
pub struct BackingPolicy {
    pub asset_mode: u8,
    pub asset_id: u32,
    pub backing_pool_id: felt252,
    pub allowed_payout_purposes_hash: felt252,
    pub retag_policy_hash: felt252,
    pub adapter_kind: u8,
    pub custody_class_hash: felt252,
    pub custody_address_recipe_hash: felt252,
    pub lifetime_cap_or_quota: u256,
}

#[derive(Drop, Serde)]
pub struct PayoutPurposePolicy {
    pub asset_mode: u8,
    pub asset_id: u32,
    pub backing_pool_id: felt252,
    pub payout_purpose: felt252,
    pub recipient_rule: u16,
    pub allowed_claim_kind_index_bitmap: u256,
    pub retag_rule_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct CapacityCommitmentEntry {
    pub asset_mode: u8,
    pub asset_id: u32,
    pub backing_pool_id: felt252,
    pub committed_amount_or_quota: u256,
    pub custody_or_authority: ContractAddress,
    pub backing_policy_hash: felt252,
    pub has_provisioning_refund_source: bool,
    pub provisioning_funding_source_id: felt252,
    pub provisioning_funder_l1: ContractAddress,
    pub provisioning_refund_recipient_l1: ContractAddress,
    pub provisioning_refund_policy_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct ProvisioningInventoryReceipt {
    pub capacity_entry_hash: felt252,
    pub adapter: ContractAddress,
    pub token_or_collection: ContractAddress,
    pub physical_amount: u256,
    pub mint_or_quota_allowance: u256,
    pub funding_source_id: felt252,
    pub funder_l1: ContractAddress,
    pub refund_source: ContractAddress,
    pub refund_policy_hash: felt252,
    pub entry_state_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct DeploymentRefundSource {
    pub source_index: u16,
    pub parent_key: BackingKey,
    pub source_ingress_or_pool_id: felt252,
    pub funding_source_id: felt252,
    pub refund_recipient_l1: ContractAddress,
    pub refund_policy_hash: felt252,
    pub provisioned_physical_total: u256,
    pub committed_lifetime_total: u256,
    pub unallocated_total: u256,
    pub returned_unused_from_games_total: u256,
    pub refundable_total: u256,
    pub disposition_epoch: u32,
    pub refund_kind: u16,
    pub emitted: bool,
}

#[derive(Drop, Serde)]
pub struct DeploymentRefundCommitment {
    pub source_count: u16,
    pub physical_refund_source_count: u16,
    pub sources_hash: felt252,
    pub sources_root: felt252,
    pub game_return_count: u16,
    pub game_returns_hash: felt252,
    pub source_cursor: u16,
    pub disposition_count: u16,
    pub refund_liability_count: u16,
    pub refund_liabilities_hash: felt252,
    pub refund_liabilities_root: felt252,
}

#[derive(Drop, Serde)]
pub struct DeploymentRefundDisposition {
    pub source_index: u16,
    pub source_leaf_hash: felt252,
    pub has_liability: bool,
    pub liability_id: LiabilityId,
    pub legs_hash: felt252,
    pub aux_hash: felt252,
    pub has_batch_assignment: bool,
    pub batch_id: BatchId,
    pub leaf_index: u8,
}

#[derive(Drop, Serde)]
pub struct GameDraftPlan {
    pub game_id: GameId,
    pub game_creation_nonce: u64,
    pub draft_salt: felt252,
    pub world_salt: felt252,
    pub component_recipe_hash: felt252,
    pub component_count: u16,
    pub game_config_root: felt252,
    pub game_config_count: u16,
    pub game_config_hash: felt252,
    pub capacity_root: felt252,
    pub capacity_count: u8,
    pub writer_graph_hash: felt252,
    pub writer_count: u16,
    pub series_id: felt252,
    pub game_number: u8,
    pub predecessor_result_hash: felt252,
    pub completion_deadline: u64,
}

#[derive(Drop, Serde)]
pub struct GameConfigEntry {
    pub config_key: u16,
    pub value_hash: felt252,
    pub value: Span<felt252>,
}

#[derive(Drop, Serde)]
pub struct GameDraft {
    pub plan_hash: felt252,
    pub state: u8,
    pub config_cursor: u16,
    pub capacity_cursor: u8,
    pub component_cursor: u16,
    pub writer_cursor: u16,
    pub world: ContractAddress,
    pub adapter_set_hash: felt252,
    pub deadline: u64,
}

#[derive(Drop, Serde)]
pub struct RootSummary {
    pub batch_id: BatchId,
    pub previous_batch_hash: felt252,
    pub leaf_count: u8,
    pub root: felt252,
    pub asset_totals_hash: felt252,
    pub ingress_activation_count: u8,
    pub ingress_activations_hash: felt252,
    pub nft_reservation_count: u8,
    pub nft_reservations_hash: felt252,
    pub deployment_refund_count: u8,
    pub deployment_refunds_hash: felt252,
    pub lot_share_promotion_count: u16,
    pub lot_share_promotions_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct IngressActivation {
    pub ingress_id: IngressId,
    pub source_message_id: MessageId,
    pub applied_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct IngressClaimAppend {
    pub claim_kind: u16,
    pub liability_id: LiabilityId,
    pub claimant_l2: ContractAddress,
    pub recipient_l1: ContractAddress,
    pub legs: Span<ClaimLeg>,
    pub aux: Span<felt252>,
}

#[derive(Drop, Serde)]
pub struct NftReservation {
    pub game_id: GameId,
    pub reservation_kind: u8,
    pub asset_mode: u8,
    pub asset_id: u32,
    pub purpose: felt252,
    pub token_or_claim_id: u256,
    pub source_id: felt252,
    pub attributes_raw: u128,
    pub attributes_hash: felt252,
    pub metadata_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct CheckpointJournal {
    pub deployment_id: DeploymentId,
    pub chain_id: felt252,
    pub protocol_version: u16,
    pub ruleset_hash: felt252,
    pub genesis_hash: felt252,
    pub production_manifest_hash: felt252,
    pub previous_block_number: u64,
    pub previous_block_hash: felt252,
    pub previous_state_root: felt252,
    pub new_block_number: u64,
    pub new_block_hash: felt252,
    pub new_state_root: felt252,
    pub previous_inbox_cursor: u64,
    pub new_inbox_cursor: u64,
    pub inbox_commitment: felt252,
    pub previous_outbox_cursor: u64,
    pub new_outbox_cursor: u64,
    pub outbox_commitment: felt252,
    pub lifecycle_state: u8,
    pub lifecycle_commitment: felt252,
    pub has_final_outbox_batch: bool,
    pub final_outbox_batch_id: BatchId,
    pub cumulative_outbox_totals_hash: felt252,
    pub active_exit_totals_hash: felt252,
    pub index_high_watermarks_hash: felt252,
    pub remaining_quotas_hash: felt252,
    pub unsealed_ingress_activations_hash: felt252,
    pub unsealed_ingress_activation_count: u8,
    pub unsealed_control_acks_hash: felt252,
    pub unsealed_control_ack_count: u8,
    pub archive_manifest_hash: felt252,
    pub attestation_revocation_root: felt252,
    pub measurement: Measurement384,
    pub checkpoint_challenge_nonce: felt252,
    pub economic_timestamp: u64,
    pub report_timestamp: u64,
}

#[derive(Drop, Serde)]
pub struct CheckpointChallenge {
    pub deployment_id: DeploymentId,
    pub previous_checkpoint_hash: felt252,
    pub previous_block_number: u64,
    pub previous_inbox_cursor: u64,
    pub previous_outbox_cursor: u64,
    pub entropy_block_number: u64,
    pub entropy_block_hash: felt252,
    pub issued_at: u64,
    pub expires_at: u64,
    pub nonce: felt252,
    pub consumed: bool,
}

#[derive(Drop, Serde)]
pub struct Measurement384 {
    pub limb_0: u128,
    pub limb_1: u128,
    pub limb_2: u128,
}

#[derive(Drop, Serde)]
pub struct ArchiveReceipt {
    pub protocol_version: u16,
    pub receipt_kind: u8,
    pub deployment_id: DeploymentId,
    pub checkpoint_hash: felt252,
    pub block_number: u64,
    pub state_root: felt252,
    pub inbox_cursor: u64,
    pub outbox_cursor: u64,
    pub has_final_outbox_batch: bool,
    pub final_outbox_batch_id: BatchId,
    pub manifest_or_bundle_hash: felt252,
    pub game_id: GameId,
    pub index_family: u16,
    pub chunk_index: u64,
    pub signer_set_epoch: u32,
    pub signer_id: u8,
    pub failure_domain_id: u8,
    pub signature_r: felt252,
    pub signature_s: felt252,
}

#[derive(Drop, Serde)]
pub struct ArchiveSigner {
    pub signer_id: u8,
    pub failure_domain_id: u8,
    pub public_key: felt252,
}

#[derive(Drop, Serde)]
pub struct ArchiveRetrievalDescriptor {
    pub signer_set_epoch: u32,
    pub descriptor_id: u8,
    pub failure_domain_id: u8,
    pub scheme: u8,
    pub endpoint_byte_length: u16,
    pub endpoint_word_0: felt252,
    pub endpoint_word_1: felt252,
    pub endpoint_word_2: felt252,
    pub endpoint_word_3: felt252,
    pub content_namespace_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct ArchiveRouteIdentity {
    pub signer_set_epoch: u32,
    pub descriptor_id: u8,
    pub failure_domain_id: u8,
    pub scheme: u8,
    pub content_namespace_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct ArchiveEndpointApproval {
    pub signer_id: u8,
    pub failure_domain_id: u8,
    pub signature_r: felt252,
    pub signature_s: felt252,
}

#[derive(Drop, Serde)]
pub struct ArchiveEndpointUpdate {
    pub protocol_version: u16,
    pub deployment_id: DeploymentId,
    pub signer_set_epoch: u32,
    pub descriptor_id: u8,
    pub route_identity_hash: felt252,
    pub current_endpoint_metadata_hash: felt252,
    pub proposed_endpoint_byte_length: u16,
    pub proposed_endpoint_words_hash: felt252,
    pub update_nonce: u64,
    pub expires_at: u64,
}

#[derive(Drop, Serde)]
pub struct ArchiveHandover {
    pub protocol_version: u16,
    pub deployment_id: DeploymentId,
    pub prior_signer_set_epoch: u32,
    pub new_signer_set_epoch: u32,
    pub prior_signer_set_hash: felt252,
    pub new_signer_set_hash: felt252,
    pub prior_route_identity_set_hash: felt252,
    pub new_route_identity_set_hash: felt252,
    pub copied_archive_manifest_hash: felt252,
    pub effective_at: u64,
}

#[derive(Drop, Serde)]
pub struct ExitClaim {
    pub deployment_id: DeploymentId,
    pub game_id: GameId,
    pub frozen_block_number: u64,
    pub world: ContractAddress,
    pub class_hash: felt252,
    pub schema_hash: felt252,
    pub position_family: u16,
    pub position_id: u64,
    pub position_generation: u64,
    pub source_state: u8,
    pub liability_id: LiabilityId,
    pub owner_l2: ContractAddress,
    pub recipient_l1: ContractAddress,
    pub recovery_policy_hash: felt252,
    pub payout_legs_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct EmergencySealedClaim {
    pub deployment_id: DeploymentId,
    pub frozen_checkpoint_hash: felt252,
    pub game_id: GameId,
    pub batch_id: BatchId,
    pub leaf_index: u8,
    pub original_leaf_hash: felt252,
    pub liability_id: LiabilityId,
    pub disposition_kind: u16,
    pub enabling_outbox_fact_hash: felt252,
    pub original_legs_hash: felt252,
    pub settlement_legs_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct IndexHighWatermark {
    pub game_id: GameId,
    pub index_family: u16,
    pub exclusive_high_watermark: u64,
    pub schema_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct UnsealedControlAck {
    pub claim_kind: u16,
    pub liability_id: LiabilityId,
    pub source_message_id: MessageId,
    pub player_l2: ContractAddress,
    pub recipient_l1: ContractAddress,
    pub aux_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct GameLifecycleEntry {
    pub game_id: GameId,
    pub registration_index: u8,
    pub lifecycle_state: u8,
    pub ingress_cutoff_nonce: u64,
    pub freeze_id: felt252,
    pub finalizer_state_hash: felt252,
    pub game_result_hash: felt252,
    pub series_result_hash: felt252,
    pub has_game_activation_ack: bool,
    pub game_activation_ack_nonce: u64,
    pub has_series_advance_ack: bool,
    pub series_advance_ack_nonce: u64,
}

#[derive(Drop, Serde)]
pub struct LifecycleSnapshot {
    pub deployment_id: DeploymentId,
    pub deployment_state: u8,
    pub registered_game_count: u8,
    pub registered_game_list_hash: felt252,
    pub registration_close_outbox_cursor: u64,
    pub ingress_close_job_cursor: u8,
    pub game_freeze_job_cursor: u8,
    pub has_finalization_barrier: bool,
    pub finalization_barrier_nonce: u64,
    pub forced_exit_cutoff_transport_nonce: u64,
    pub season_finalizer_state_hash: felt252,
    pub deployment_refunds: DeploymentRefundCommitment,
    pub game_entries_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct GameCheckpointCommitment {
    pub game_id: GameId,
    pub cumulative_backing_count: u8,
    pub cumulative_backing_root: felt252,
    pub active_backing_count: u8,
    pub active_backing_root: felt252,
    pub index_high_watermark_count: u8,
    pub index_high_watermark_root: felt252,
    pub remaining_quota_count: u8,
    pub remaining_quota_root: felt252,
    pub backing_lot_count: u16,
    pub backing_lot_root: felt252,
}

#[derive(Drop, Serde)]
pub struct CheckpointVectors {
    pub game_commitments: Span<GameCheckpointCommitment>,
    pub unsealed_ingress_activations: Span<IngressActivation>,
    pub unsealed_control_acks: Span<UnsealedControlAck>,
    pub lifecycle: LifecycleSnapshot,
    pub game_lifecycle_entries: Span<GameLifecycleEntry>,
}

#[derive(Drop, Serde)]
pub struct FrozenReservationChunk {
    pub checkpoint_hash: felt252,
    pub game_id: GameId,
    pub vector_kind: u8,
    pub start_index: u16,
    pub item_count: u8,
    pub items_hash: felt252,
    pub items: Span<felt252>,
    pub multiproof: Span<felt252>,
    pub secondary_multiproof: Span<felt252>,
}

#[derive(Drop, Serde)]
pub struct FrozenRecoverySummary {
    pub deployment_id: DeploymentId,
    pub frozen_checkpoint_hash: felt252,
    pub final_inbox_cursor: u64,
    pub final_outbox_cursor: u64,
    pub has_final_outbox_batch: bool,
    pub final_outbox_batch_id: BatchId,
    pub cumulative_outbox_totals_hash: felt252,
    pub active_exit_totals_hash: felt252,
    pub index_high_watermarks_hash: felt252,
    pub remaining_quotas_hash: felt252,
    pub unsealed_ingress_activations_hash: felt252,
    pub unsealed_ingress_activation_count: u8,
    pub unsealed_control_acks_hash: felt252,
    pub unsealed_control_ack_count: u8,
    pub lifecycle_commitment: felt252,
    pub deployment_refunds: DeploymentRefundCommitment,
}

#[derive(Drop, Serde)]
pub struct FrozenDeploymentRefundClaim {
    pub deployment_id: DeploymentId,
    pub frozen_checkpoint_hash: felt252,
    pub terminal_refund_source_hash: felt252,
    pub source_index: u16,
    pub liability_id: LiabilityId,
    pub recipient_l1: ContractAddress,
    pub legs_hash: felt252,
    pub aux_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct FinalSettlementSummary {
    pub aggregate_result_hash: felt252,
    pub valid_game_count: u8,
    pub aborted_game_count: u8,
    pub final_inbox_cursor: u64,
    pub final_outbox_cursor: u64,
    pub has_final_outbox_batch: bool,
    pub final_outbox_batch_id: BatchId,
    pub game_result_count: u8,
    pub game_results_hash: felt252,
    pub ranking_ids: Span<felt252>,
    pub series_result_count: u8,
    pub series_results_hash: felt252,
    pub index_high_watermarks_hash: felt252,
    pub cumulative_outbox_totals_hash: felt252,
    pub active_exit_totals_hash: felt252,
    pub remaining_quotas_hash: felt252,
    pub deployment_refunds: DeploymentRefundCommitment,
    pub finalization_state_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct GameActivationAck {
    pub game_id: GameId,
    pub game_registration_hash: felt252,
    pub registration_outbox_nonce: u64,
    pub capacity_count: u8,
    pub capacity_hash: felt252,
    pub activation_disposition: u8,
}

#[derive(Drop, Serde)]
pub struct SeriesLease {
    pub series_id: felt252,
    pub deployment_id: DeploymentId,
    pub expected_head_hash: felt252,
    pub expected_accumulator_hash: felt252,
    pub state: u8,
    pub acquired_at: u64,
}

#[derive(Drop, Serde)]
pub struct EnqueuedMessage {
    pub transport_nonce: u64,
    pub message_id: MessageId,
}

#[derive(Drop, Serde)]
pub struct EnqueuedControlMessage {
    pub transport_nonce: u64,
    pub message_id: MessageId,
    pub typed_body_hash: felt252,
    pub effective_cutoff_transport_nonce: u64,
}

#[derive(Drop, Serde)]
pub enum TransportMessageState {
    Enqueued,
    CancellationPending: u64,
    ConsumedFinal: felt252,
    RejectedFinal: felt252,
    Cancelled: u64,
    EmergencyOrphaned: felt252,
}

#[derive(Drop, Serde)]
pub struct InboxSlotCommitment {
    pub transport_nonce: u64,
    pub message_id: MessageId,
    pub terminal_state: u8,
    pub terminal_evidence_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct OutboxSlotCommitment {
    pub transport_nonce: u64,
    pub message_id: MessageId,
    pub envelope_hash: felt252,
    pub typed_body_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct InboxExecutionReceipt {
    pub transport_nonce: u64,
    pub message_id: MessageId,
    pub action: u16,
    pub typed_body_hash: felt252,
    pub execution_outcome: u8,
    pub action_receipt_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct IngressRejectionReceipt {
    pub ingress_id: IngressId,
    pub source_message_id: MessageId,
    pub rejection_code: u16,
    pub immutable_input_hash: felt252,
    pub observed_domain_state_hash: felt252,
    pub refund_policy_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct CancelledInboxMarker {
    pub protocol_version: u16,
    pub deployment_id: DeploymentId,
    pub transport_nonce: u64,
    pub message_id: MessageId,
    pub typed_body_hash: felt252,
    pub cancellation_finalized_at_l1: u64,
}

#[derive(Drop, Serde)]
pub enum IngressCloseEvidence {
    ScheduledEnd: u64,
    BudgetFloor: felt252,
    GuardianClose: felt252,
    AttestationRevoked: felt252,
    BlockedOutbox: (felt252, u64),
}

#[derive(Drop, Serde)]
pub enum EmergencyEvidence {
    CheckpointStall: (felt252, u64),
    FinalRegistrationStall: (felt252, u64, u64),
    ForcedExitDeadline: (felt252, u64),
    BlockedOutboxDeadline: (felt252, u64),
    AttestationRevoked: felt252,
}

#[derive(Drop, Serde)]
pub enum SlashEvidence {
    AcceptanceDeadline: (DeploymentId, felt252, u16, u16, u64),
    ProvisioningDeadline: (DeploymentId, u64),
    CheckpointDeadline: (felt252, u64),
    ForcedExitDeadline: (felt252, u64),
    CapacityInvariant: (felt252, felt252),
}

#[derive(Drop, Serde)]
pub struct ReservationCheck {
    pub ok: bool,
    pub reason: u16,
    pub required: u256,
    pub available: u256,
}

#[derive(Drop, Serde)]
pub struct BlockedOutboxHead {
    pub deployment_id: DeploymentId,
    pub transport_nonce: u64,
    pub action: u16,
    pub subject_id: felt252,
    pub body_hash: felt252,
    pub reason: u16,
    pub blocked_at: u64,
    pub retry_deadline: u64,
}

#[derive(Drop, Serde)]
pub enum RootRegistrationResult {
    Registered: BatchId,
    Blocked: BlockedOutboxHead,
    ReservationNotReady: BackingKey,
    FrozenRegisteredUnderfunded: (BatchId, felt252),
}

#[derive(Drop, Serde)]
pub enum SeriesApplicationResult {
    Advanced: MessageId,
    Aborted,
    FrozenAdvancedNoAck: felt252,
    FrozenAbortedNoAck: felt252,
}

#[derive(Drop, Serde)]
pub enum GameRegistrationResult {
    AckEnqueued: MessageId,
    FrozenClosedNoAck: felt252,
}

#[derive(Drop, Serde)]
pub struct FrozenOutboxDisposition {
    pub deployment_id: DeploymentId,
    pub transport_nonce: u64,
    pub action: u16,
    pub subject_id: felt252,
    pub body_hash: felt252,
    pub effect_kind: u16,
    pub effect_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct SettlementBudgetKey {
    pub deployment_id: DeploymentId,
    pub source_mode: u8,
    pub batch_or_budget_kind: u64,
    pub source_sub_id: felt252,
    pub game_id: GameId,
    pub asset_mode: u8,
    pub asset_id: u32,
    pub backing_pool_id: felt252,
    pub has_payout_purpose: bool,
    pub payout_purpose: felt252,
    pub token_or_claim_id: u256,
}

#[derive(Drop, Serde)]
pub struct DeficiencySourceKey {
    pub deployment_id: DeploymentId,
    pub source_kind: u8,
    pub source_id: felt252,
    pub source_sub_id: felt252,
    pub key: BackingKey,
}

#[derive(Drop, Serde)]
pub struct BudgetExport {
    pub key: SettlementBudgetKey,
    pub remaining_budget: u256,
    pub has_remaining_deficiency: bool,
    pub deficiency_source: DeficiencySourceKey,
    pub remaining_deficiency: u256,
    pub custody_amount: u256,
    pub mint_headroom: u256,
    pub quota_headroom: u256,
    pub state_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct MigrationInventory {
    pub adapter: ContractAddress,
    pub frozen_count: u64,
    pub cursor: u64,
    pub key_list_hash: felt252,
    pub exported_totals_hash: felt252,
    pub imported_totals_hash: felt252,
}

#[derive(Drop, Serde)]
pub enum SyncResult {
    Applied: IngressId,
    AlreadyApplied: IngressId,
    RejectedRefunded: IngressId,
    AlreadyRejected: IngressId,
}

#[derive(Drop, Serde)]
pub struct AppchainMessageView {
    pub transport_nonce: u64,
    pub message_id: MessageId,
    pub typed_body_hash: felt252,
    pub accepted_checkpoint_hash: felt252,
}

#[derive(Drop, Serde)]
pub enum RouteState {
    ActiveAdapters,
    Migrating,
    DormantReserve,
}

#[derive(Drop, Serde)]
pub enum RecoverySource {
    NormalFinal: (felt252, felt252),
    EmergencyFrozen: (FrozenRecoverySummary, Span<felt252>),
}

#[derive(Drop, Serde)]
pub struct ReleaseBundleBodyV1 {
    pub protocol_version: u16,
    pub source_tree_root: felt252,
    pub cairo_artifact_count: u16,
    pub cairo_artifacts_hash: felt252,
    pub runtime_artifact_count: u16,
    pub runtime_artifacts_hash: felt252,
    pub dojo_recipe_artifacts_hash: felt252,
    pub sp1_artifact_count: u16,
    pub sp1_artifacts_hash: felt252,
    pub codec_vector_artifacts_hash: felt252,
    pub vrf_artifacts_hash: felt252,
    pub archive_tool_artifacts_hash: felt252,
    pub deployer_artifacts_hash: felt252,
    pub authoritative_address_inputs_hash: felt252,
    pub privileged_mutation_paths_hash: felt252,
    pub benchmark_evidence_hash: felt252,
    pub audit_evidence_hash: felt252,
    pub ruleset_config_without_release_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct ProductionReleaseCandidateBodyV1 {
    pub protocol_version: u16,
    pub release_bundle_hash: felt252,
    pub deployment_activation_bundle_hash: felt252,
    pub authoritative_address_inputs_hash: felt252,
    pub privileged_mutation_paths_hash: felt252,
    pub expected_roles_hash: felt252,
    pub capacity_and_provenance_hash: felt252,
    pub package_lock_matrix_hash: felt252,
    pub maximum_bound_evidence_hash: felt252,
    pub real_tee_recovery_evidence_hash: felt252,
    pub audit_closure_hash: felt252,
    pub legacy_liability_manifest_hash: felt252,
    pub legacy_mmr_static_config_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct ArchivePolicy {
    pub archive_format_version: u16,
    pub signer_count: u8,
    pub receipt_quorum: u8,
    pub failure_domain_quorum: u8,
    pub minimum_retrieval_descriptor_count: u8,
    pub maximum_retrieval_descriptor_count: u8,
    pub endpoint_word_count: u8,
    pub maximum_endpoint_byte_length: u16,
    pub signature_scheme: u8,
    pub content_hash_scheme: u8,
    pub checkpoint_receipt_kind: u8,
    pub dormant_bundle_receipt_kind: u8,
    pub handover_receipt_kind: u8,
    pub legacy_mmr_import_receipt_kind: u8,
    pub legacy_mmr_pre_freeze_receipt_kind: u8,
}

#[derive(Drop, Serde)]
pub struct ClassBinding {
    pub binding_index: u16,
    pub component_kind: felt252,
    pub execution_layer: u8,
    pub deployment_scope: u8,
    pub class_hash: felt252,
    pub interface_hash: felt252,
    pub constructor_schema_hash: felt252,
    pub storage_layout_hash: felt252,
    pub role_schema_hash: felt252,
    pub expected_deploy_from_zero: bool,
}

#[derive(Drop, Serde)]
pub struct WriterCapability {
    pub capability_index: u16,
    pub writer_component_kind: felt252,
    pub writer_class_hash: felt252,
    pub operation: u16,
    pub model_selector: felt252,
    pub member_selector: felt252,
    pub permission_kind: u8,
    pub game_scope: u8,
    pub allowed_game_lifecycle_bitmap: u256,
}

#[derive(Drop, Serde)]
pub struct EmitterCapability {
    pub emitter_index: u8,
    pub emitter_kind: u8,
    pub emitter: ContractAddress,
    pub emitter_class_hash: felt252,
    pub operation_bitmap: u256,
    pub claim_kind_index_bitmap: u256,
}

#[derive(Drop, Serde)]
pub struct MerkleProof {
    pub leaf_index: u32,
    pub sibling_0: felt252,
    pub sibling_1: felt252,
    pub sibling_2: felt252,
    pub sibling_3: felt252,
    pub sibling_4: felt252,
    pub sibling_5: felt252,
    pub sibling_6: felt252,
    pub sibling_7: felt252,
    pub sibling_8: felt252,
    pub sibling_9: felt252,
    pub sibling_10: felt252,
    pub sibling_11: felt252,
    pub sibling_12: felt252,
    pub sibling_13: felt252,
    pub sibling_14: felt252,
    pub sibling_15: felt252,
    pub sibling_16: felt252,
    pub sibling_17: felt252,
    pub sibling_18: felt252,
    pub sibling_19: felt252,
    pub sibling_20: felt252,
    pub sibling_21: felt252,
    pub sibling_22: felt252,
    pub sibling_23: felt252,
    pub sibling_24: felt252,
    pub sibling_25: felt252,
    pub sibling_26: felt252,
    pub sibling_27: felt252,
    pub sibling_28: felt252,
    pub sibling_29: felt252,
    pub sibling_30: felt252,
    pub sibling_31: felt252,
}

#[derive(Drop, Serde)]
pub struct RulesetConfig {
    pub protocol_version: u16,
    pub release_bundle_hash: felt252,
    pub schema_registry_hash: felt252,
    pub hash_domains_hash: felt252,
    pub vector_bounds_hash: felt252,
    pub mainnet_class_bundle_hash: felt252,
    pub appchain_class_bundle_hash: felt252,
    pub proof_policy_hash: felt252,
    pub attestation_policy_hash: felt252,
    pub genesis_recipe_hash: felt252,
    pub asset_policies_hash: felt252,
    pub asset_policy_count: u16,
    pub backing_policies_hash: felt252,
    pub backing_policy_count: u16,
    pub payout_purpose_policies_hash: felt252,
    pub payout_purpose_policy_count: u16,
    pub class_bindings_hash: felt252,
    pub class_binding_count: u16,
    pub writer_capabilities_hash: felt252,
    pub writer_capability_count: u16,
    pub archive_policy_hash: felt252,
    pub timing_policy_hash: felt252,
    pub economics_policy_hash: felt252,
    pub mmr_policy_hash: felt252,
    pub vrf_policy_hash: felt252,
    pub recovery_policy_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct AssetPolicy {
    pub asset_mode: u8,
    pub asset_id: u32,
    pub l1_token: ContractAddress,
    pub token_standard: u8,
    pub decimals: u8,
    pub transfer_semantics: u8,
    pub ingress_allowed: bool,
    pub escrow_only: bool,
    pub mint_shortfall_allowed: bool,
    pub burn_surplus_allowed: bool,
    pub lifetime_mint_cap: u256,
    pub per_period_mint_cap: u256,
    pub period_seconds: u64,
    pub purpose_policy_hash: felt252,
    pub metadata_policy_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct SeasonIntentParams {
    pub season_id: SeasonId,
    pub ruleset_id: felt252,
    pub creator_salt: felt252,
    pub intended_start: u64,
    pub intended_end: u64,
    pub max_games: u8,
    pub operator_acceptance_deadline: u64,
    pub lifecycle_bond: u256,
    pub operating_budget: u256,
    pub protected_recovery_budget: u256,
    pub sponsor_commitment_hash: felt252,
    pub archive_set_hash: felt252,
    pub series_id: felt252,
    pub series_predecessor_hash: felt252,
    pub series_accumulator_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct AddressSourceRecord {
    pub chain_id: felt252,
    pub semantic_key: felt252,
    pub source_kind: u8,
    pub source_path_hash: felt252,
    pub source_key_hash: felt252,
    pub value: felt252,
    pub is_authoritative: bool,
    pub allowed_profile_bitmap: u256,
}

#[derive(Drop, Serde)]
pub struct AddressAliasRecord {
    pub chain_id: felt252,
    pub semantic_key: felt252,
    pub alias_path_hash: felt252,
    pub alias_key_hash: felt252,
    pub disposition: u8,
    pub expected_value: felt252,
}

#[derive(Drop, Serde)]
pub struct PrivilegedMutationPathRecord {
    pub path_hash: felt252,
    pub operation_kind: u16,
    pub target_semantic_key: felt252,
    pub production_disposition: u8,
    pub replacement_path_hash: felt252,
    pub evidence_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct DeploymentAddressRecipe {
    pub protocol_version: u16,
    pub deployment_id: DeploymentId,
    pub ruleset_id: felt252,
    pub l1_chain_id: felt252,
    pub appchain_chain_id: felt252,
    pub l1_deployer: ContractAddress,
    pub l1_deploy_from_zero: bool,
    pub l1_deployment_primitive_hash: felt252,
    pub l2_deployer: felt252,
    pub l2_deploy_from_zero: bool,
    pub l2_deployment_primitive_hash: felt252,
    pub l1_component_count: u8,
    pub l1_component_classes_hash: felt252,
    pub l1_component_salts_hash: felt252,
    pub l2_component_count: u8,
    pub l2_component_classes_hash: felt252,
    pub l2_component_salts_hash: felt252,
    pub shell_constructor_schema_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct DeploymentManifest {
    pub protocol_version: u16,
    pub deployment_id: DeploymentId,
    pub ruleset_id: felt252,
    pub release_bundle_hash: felt252,
    pub address_recipe_hash: felt252,
    pub l1_chain_id: felt252,
    pub appchain_chain_id: felt252,
    pub hardened_piltover: ContractAddress,
    pub coordinator: ContractAddress,
    pub funding_vault: ContractAddress,
    pub root_inbox: ContractAddress,
    pub claim_router: ContractAddress,
    pub resource_gateway: ContractAddress,
    pub scarce_bridge: ContractAddress,
    pub entitlement_vault: ContractAddress,
    pub outcome_portal: ContractAddress,
    pub settlement_route_registry: ContractAddress,
    pub archive_quorum: ContractAddress,
    pub mmr_settlement_router: ContractAddress,
    pub mmr_settlement_module: ContractAddress,
    pub attestation_revocation_registry: ContractAddress,
    pub exit_verifier: ContractAddress,
    pub dormant_reserve: ContractAddress,
    pub settlement_config_l2: felt252,
    pub settlement_ingress_l2: felt252,
    pub settlement_hub_l2: felt252,
    pub hardened_inbox_runtime_l2: felt252,
    pub forced_exit_coordinator_l2: felt252,
    pub season_finalizer_l2: felt252,
    pub sealed_factory_l2: felt252,
    pub world_policy_l2: felt252,
    pub vrf_l2: felt252,
    pub world_class_hash: felt252,
    pub class_bundle_hash: felt252,
    pub schema_bundle_hash: felt252,
    pub authoritative_address_inputs_hash: felt252,
    pub external_counterpart_count: u16,
    pub external_counterparts_hash: felt252,
    pub privileged_mutation_paths_hash: felt252,
    pub expected_role_count: u16,
    pub expected_roles_hash: felt252,
    pub writer_graph_hash: felt252,
    pub config_snapshot_hash: felt252,
    pub genesis_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct AppchainSettlementConfig {
    pub protocol_version: u16,
    pub deployment_id: DeploymentId,
    pub season_id: SeasonId,
    pub ruleset_id: felt252,
    pub release_bundle_hash: felt252,
    pub starknet_chain_id: felt252,
    pub appchain_chain_id: felt252,
    pub hardened_piltover_l1: ContractAddress,
    pub coordinator_l1: ContractAddress,
    pub funding_vault_l1: ContractAddress,
    pub root_inbox_l1: ContractAddress,
    pub claim_router_l1: ContractAddress,
    pub resource_gateway_l1: ContractAddress,
    pub scarce_bridge_l1: ContractAddress,
    pub entitlement_vault_l1: ContractAddress,
    pub outcome_portal_l1: ContractAddress,
    pub settlement_route_registry_l1: ContractAddress,
    pub archive_quorum_l1: ContractAddress,
    pub attestation_revocation_registry_l1: ContractAddress,
    pub hardened_inbox_runtime_l2: ContractAddress,
    pub season_ingress_l2: ContractAddress,
    pub season_settlement_hub_l2: ContractAddress,
    pub forced_exit_coordinator_l2: ContractAddress,
    pub season_finalizer_l2: ContractAddress,
    pub sealed_factory_l2: ContractAddress,
    pub sealed_world_policy_l2: ContractAddress,
    pub vrf_provider_l2: ContractAddress,
    pub vrf_public_key_hash: felt252,
    pub appchain_component_classes_hash: felt252,
    pub class_binding_count: u16,
    pub class_bindings_hash: felt252,
    pub schema_bundle_hash: felt252,
    pub asset_policy_count: u16,
    pub asset_policies_hash: felt252,
    pub backing_policy_count: u16,
    pub backing_policies_hash: felt252,
    pub payout_purpose_policy_count: u16,
    pub payout_purpose_policies_hash: felt252,
    pub writer_capability_count: u16,
    pub writer_capabilities_hash: felt252,
    pub capacity_entry_count: u16,
    pub capacity_root: felt252,
    pub sealed_game_recipe_hash: felt252,
    pub intended_start: u64,
    pub intended_end: u64,
    pub max_games: u8,
    pub initial_inbox_cursor: u64,
    pub initial_outbox_cursor: u64,
    pub timing_policy_hash: felt252,
    pub economics_policy_hash: felt252,
    pub vrf_policy_hash: felt252,
    pub recovery_policy_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct SealedGameConfig {
    pub game_id: GameId,
    pub game_creation_nonce: u64,
    pub world: ContractAddress,
    pub game_config_hash: felt252,
    pub world_config_snapshot_hash: felt252,
    pub game_ingress_adapter: ContractAddress,
    pub economic_state_system: ContractAddress,
    pub outcome_settlement: ContractAddress,
    pub forced_exit_adapter: ContractAddress,
    pub class_bundle_hash: felt252,
    pub schema_bundle_hash: felt252,
    pub writer_capability_count: u16,
    pub writer_capabilities_hash: felt252,
    pub emitter_capability_count: u8,
    pub emitter_capabilities_hash: felt252,
    pub capacity_count: u8,
    pub capacity_hash: felt252,
    pub series_id: felt252,
    pub game_number: u8,
    pub predecessor_result_hash: felt252,
    pub series_accumulator_seed_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct SeasonRecord {
    pub deployment_id: DeploymentId,
    pub season_id: SeasonId,
    pub ruleset_id: felt252,
    pub creator: ContractAddress,
    pub operator: ContractAddress,
    pub lifecycle_state: u8,
    pub manifest_hash: felt252,
    pub genesis_checkpoint_hash: felt252,
    pub latest_checkpoint_hash: felt252,
    pub ingress_cutoff_nonce: u64,
    pub final_outbox_cursor: u64,
    pub has_final_outbox_batch: bool,
    pub final_outbox_batch_id: BatchId,
    pub final_summary_hash: felt252,
    pub frozen_checkpoint_hash: felt252,
    pub aggregate_result_hash: felt252,
    pub valid_game_count: u8,
    pub aborted_game_count: u8,
    pub activated_at: u64,
    pub claims_opened_at: u64,
    pub emergency_frozen_at: u64,
    pub retirement_route: ContractAddress,
}

#[derive(Drop, Serde)]
pub struct RankingCommitment {
    pub game_id: GameId,
    pub root: felt252,
    pub participant_count: u16,
    pub result_hash: felt252,
    pub first_rank: u16,
    pub last_rank: u16,
    pub tie_break_policy_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct RankingEntry {
    pub game_id: GameId,
    pub player_l2: ContractAddress,
    pub recipient_l1: ContractAddress,
    pub participation_id: felt252,
    pub rank: u16,
    pub score: u256,
    pub result_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct MmrSnapshotEntry {
    pub ranking_entry_hash: felt252,
    pub mmr_identity: ContractAddress,
    pub starting_mmr_scaled: u256,
    pub starting_mmr_logical: u128,
}

#[derive(Drop, Serde)]
pub struct MmrPlanEntry {
    pub ranking_entry_hash: felt252,
    pub mmr_identity: ContractAddress,
    pub starting_mmr_logical: u128,
    pub new_mmr_logical: u128,
}

#[derive(Drop, Serde)]
pub struct GameResult {
    pub game_id: GameId,
    pub winner_l2: ContractAddress,
    pub ended_at: u64,
    pub result_hash: felt252,
    pub valid_result: bool,
    pub abort_reason: u16,
    pub participant_root: felt252,
    pub ranking_id: felt252,
}

#[derive(Drop, Serde)]
pub struct SeriesAccumulator {
    pub game_index: u32,
    pub ema_players_scaled: u128,
    pub recent_len: u8,
    pub recent_0: u128,
    pub recent_1: u128,
    pub recent_2: u128,
    pub recent_sum: u128,
    pub anchor_len: u8,
    pub anchor_0: u128,
    pub anchor_1: u128,
    pub anchor_sum: u128,
    pub has_last_rate: bool,
    pub last_rate_bps: u128,
    pub soft_supply: u128,
    pub overspend_remaining: u128,
}

#[derive(Drop, Serde)]
pub struct FrozenCheckpoint {
    pub deployment_id: DeploymentId,
    pub checkpoint_hash: felt252,
    pub block_number: u64,
    pub block_hash: felt252,
    pub state_root: felt252,
    pub economic_timestamp: u64,
    pub archive_manifest_hash: felt252,
    pub inbox_cursor: u64,
    pub outbox_cursor: u64,
    pub has_final_outbox_batch: bool,
    pub final_outbox_batch_id: BatchId,
    pub cumulative_outbox_totals_hash: felt252,
    pub active_exit_totals_hash: felt252,
    pub index_high_watermarks_hash: felt252,
    pub remaining_quotas_hash: felt252,
    pub unsealed_ingress_activations_hash: felt252,
    pub unsealed_ingress_activation_count: u8,
    pub unsealed_control_acks_hash: felt252,
    pub unsealed_control_ack_count: u8,
    pub lifecycle_commitment: felt252,
    pub deployment_refunds: DeploymentRefundCommitment,
}

#[derive(Drop, Serde)]
pub struct MaterializationChunk {
    pub deployment_id: DeploymentId,
    pub frozen_checkpoint_hash: felt252,
    pub game_id: GameId,
    pub index_family: u16,
    pub chunk_index: u64,
    pub start_index: u64,
    pub item_count: u8,
    pub items_hash: felt252,
    pub chunk_root: felt252,
    pub live_liability_count: u8,
    pub live_preimages_hash: felt252,
    pub live_totals_hash: felt252,
    pub bundle_objects_root: felt252,
    pub permanent_bundle_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct VerifiedMaterializationOutput {
    pub deployment_id: DeploymentId,
    pub frozen_checkpoint_hash: felt252,
    pub game_id: GameId,
    pub index_family: u16,
    pub chunk_index: u64,
    pub item_count: u8,
    pub items_hash: felt252,
    pub chunk_root: felt252,
    pub live_liability_count: u8,
    pub live_preimages_hash: felt252,
    pub live_totals_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct DormantExitLeaf {
    pub deployment_id: DeploymentId,
    pub frozen_checkpoint_hash: felt252,
    pub game_id: GameId,
    pub index_family: u16,
    pub source_index: u64,
    pub chunk_index: u64,
    pub leaf_index: u8,
    pub tombstone: bool,
    pub exit_claim_hash: felt252,
    pub legs_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct DormantDeploymentRefundLeaf {
    pub deployment_id: DeploymentId,
    pub frozen_checkpoint_hash: felt252,
    pub terminal_refund_source_hash: felt252,
    pub source_index: u16,
    pub chunk_index: u8,
    pub leaf_index: u8,
    pub tombstone: bool,
    pub refund_claim_hash: felt252,
    pub source_hash: felt252,
    pub legs_hash: felt252,
    pub aux_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct QuotaBalance {
    pub game_id: GameId,
    pub outcome_id: u32,
    pub backing_pool_id: felt252,
    pub remaining: u256,
}

#[derive(Drop, Serde)]
pub struct AutoIdMintRequest {
    pub deployment_id: DeploymentId,
    pub game_id: GameId,
    pub collection_id: felt252,
    pub reservation_id: felt252,
    pub recipient: ContractAddress,
    pub metadata_policy_hash: felt252,
    pub attributes_raw: u128,
}

#[derive(Drop, Serde)]
pub struct EffectiveMmr {
    pub initialized: bool,
    pub scaled_value: u256,
    pub logical_value: u128,
}

#[derive(Drop, Serde)]
pub struct MmrTokenUpdate {
    pub identity: ContractAddress,
    pub expected_starting_scaled: u256,
    pub new_scaled: u256,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrCutoverCommitment {
    pub production_candidate_hash: felt252,
    pub target_router: ContractAddress,
    pub target_router_class_hash: felt252,
    pub router_legacy_binding_hash: felt252,
    pub static_config_hash: felt252,
    pub mmr_token: ContractAddress,
    pub mmr_token_class_hash: felt252,
    pub mmr_token_storage_layout_hash: felt252,
    pub mmr_token_migration_init_hash: felt252,
    pub cutover_component_class_bindings_hash: felt252,
    pub cutover_component_authority_state_hash: felt252,
    pub admission_gate: ContractAddress,
    pub admission_registry_hash: felt252,
    pub instrumentation_complete_marker_hash: felt252,
    pub pending_import_baseline_hash: felt252,
    pub quiescence_marker_hash: felt252,
    pub pre_freeze_witness_manifest_hash: felt252,
    pub proved_source_inventory_hash: felt252,
    pub pre_freeze_verified_bundle_hash: felt252,
    pub admission_freeze_marker_hash: felt252,
    pub router_reservation_hash: felt252,
    pub finalized_state_root_source: ContractAddress,
    pub finalized_header_policy_hash: felt252,
    pub finalized_header_codec_hash: felt252,
    pub minimum_finality_blocks: u16,
    pub inventory_finalized_state_root_anchor_hash: felt252,
    pub inventory_program_id: felt252,
    pub inventory_verification_key_hash: felt252,
    pub derivation_program_id: felt252,
    pub derivation_verification_key_hash: felt252,
    pub freeze_marker_hash: felt252,
    pub inventory_block_number: u64,
    pub inventory_block_hash: felt252,
    pub inventory_state_root: felt252,
    pub factory_count: u16,
    pub factories_hash: felt252,
    pub factory_event_range_count: u16,
    pub factory_event_ranges_hash: felt252,
    pub partial_creation_count: u32,
    pub partial_creations_root: felt252,
    pub world_count: u32,
    pub worlds_root: felt252,
    pub disposition_count: u32,
    pub dispositions_root: felt252,
    pub imported_job_count: u32,
    pub imported_jobs_root: felt252,
    pub legacy_synthetic_deployment_id: DeploymentId,
    pub legacy_module_protocol_version: u16,
    pub legacy_module_ruleset_id: felt252,
    pub legacy_module: ContractAddress,
    pub legacy_program_id: felt252,
    pub legacy_verification_key_hash: felt252,
    pub legacy_mmr_policy_hash: felt252,
    pub legacy_release_bundle_hash: felt252,
    pub legacy_settlement_chunk_size: u8,
    pub legacy_writer_count: u32,
    pub legacy_writers_root: felt252,
    pub legacy_factory_tuple_hash: felt252,
    pub token_state_hash: felt252,
    pub frozen_pending_import_bound_hash: felt252,
    pub frozen_pending_import_job_count: u32,
    pub frozen_pending_import_reward_units: u64,
    pub prefunded_escrow_hash: felt252,
    pub legacy_migration_funding_scope_id: felt252,
    pub funding_vault: ContractAddress,
    pub funding_account: ContractAddress,
    pub funding_owner: ContractAddress,
    pub reward_unit_amount: u256,
    pub max_reward_units: u32,
    pub reward_budget: u256,
    pub excess_refund_recipient: ContractAddress,
    pub excess_return_policy_hash: felt252,
    pub funding_reservations_hash: felt252,
    pub archive_registry: ContractAddress,
    pub archive_policy_hash: felt252,
    pub archive_signer_set_epoch: u32,
    pub archive_signer_set_hash: felt252,
    pub archive_route_identity_set_hash: felt252,
    pub import_data_manifest_hash: felt252,
    pub import_data_item_count: u32,
    pub import_data_total_entry_count: u64,
    pub import_data_items_root: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrWorldDisposition {
    pub disposition_index: u32,
    pub factory: ContractAddress,
    pub factory_event_index: u64,
    pub world: ContractAddress,
    pub mmr_system: ContractAddress,
    pub game_or_trial_id: felt252,
    pub game_meta_hash: felt252,
    pub claimed_hash: felt252,
    pub status: u8,
    pub imported_job_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrApprovedFactoryVersion {
    pub factory_index: u16,
    pub version_index: u16,
    pub factory: ContractAddress,
    pub factory_version: felt252,
    pub config_revision: u64,
    pub parent_world_binding_hash: felt252,
    pub child_system_bindings_hash: felt252,
    pub effective_recipe_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrFactoryInventoryLeaf {
    pub factory_index: u16,
    pub factory: ContractAddress,
    pub factory_class_hash: felt252,
    pub approved_versions_hash: felt252,
    pub creation_highwater_hash: felt252,
    pub reverse_lookup_root: felt252,
    pub writer_registry_root: felt252,
    pub event_range_index: u16,
    pub completed_world_count: u32,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrFactoryBindingLeaf {
    pub factory_index: u16,
    pub factory: ContractAddress,
    pub factory_class_hash: felt252,
    pub approved_versions_hash: felt252,
    pub factory_migration_init_hash: felt252,
    pub controller_authority_closure_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrFactoryCreationHighwaterLeaf {
    pub factory_index: u16,
    pub factory: ContractAddress,
    pub next_creation_nonce: u64,
    pub completed_world_count: u32,
    pub partial_sparse_root: felt252,
    pub creation_transition_accumulator: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrCanonicalHeaderLeaf {
    pub range_index: u16,
    pub block_offset: u64,
    pub block_number: u64,
    pub block_hash: felt252,
    pub parent_hash: felt252,
    pub state_root: felt252,
    pub transaction_count: u32,
    pub transactions_commitment: felt252,
    pub receipt_count: u32,
    pub receipts_commitment: felt252,
    pub events_commitment: felt252,
    pub canonical_header_preimage_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrBlockTransactionCommitment {
    pub range_index: u16,
    pub block_offset: u64,
    pub block_number: u64,
    pub block_hash: felt252,
    pub transaction_count: u32,
    pub transactions_commitment: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrBlockReceiptCommitment {
    pub range_index: u16,
    pub block_offset: u64,
    pub block_number: u64,
    pub block_hash: felt252,
    pub receipt_count: u32,
    pub receipts_commitment: felt252,
    pub events_commitment: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrFactorySelectedEvent {
    pub selected_event_index: u64,
    pub block_offset: u64,
    pub block_number: u64,
    pub block_hash: felt252,
    pub transaction_index: u32,
    pub transaction_hash: felt252,
    pub event_index_in_receipt: u32,
    pub emitter: ContractAddress,
    pub keys_hash: felt252,
    pub data_hash: felt252,
    pub decoded_fact_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrFactoryEventLayoutEntry {
    pub layout_index: u16,
    pub fact_kind: u8,
    pub emitter: ContractAddress,
    pub selector: felt252,
    pub keys_schema_hash: felt252,
    pub data_schema_hash: felt252,
    pub decoder_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrFactoryEventRange {
    pub range_index: u16,
    pub factory_index: u16,
    pub factory: ContractAddress,
    pub deployment_block_number: u64,
    pub deployment_block_hash: felt252,
    pub first_block_number: u64,
    pub last_block_number: u64,
    pub header_chain_root: felt252,
    pub transaction_commitments_root: felt252,
    pub receipt_commitments_root: felt252,
    pub first_event_index: u64,
    pub last_event_index: u64,
    pub event_count: u64,
    pub events_accumulator: felt252,
    pub event_layout_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrWorldInventoryLeaf {
    pub disposition_index: u32,
    pub factory_index: u16,
    pub factory: ContractAddress,
    pub factory_event_index: u64,
    pub world: ContractAddress,
    pub world_class_hash: felt252,
    pub world_config_hash: felt252,
    pub mmr_system: ContractAddress,
    pub game_or_trial_id: felt252,
    pub game_meta_hash: felt252,
    pub claimed_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrWriterInventoryLeaf {
    pub writer_index: u32,
    pub factory: ContractAddress,
    pub factory_version: felt252,
    pub factory_class_hash: felt252,
    pub writer_status: u8,
    pub world: ContractAddress,
    pub world_class_hash: felt252,
    pub mmr_system: ContractAddress,
    pub mmr_system_class_hash: felt252,
    pub game_or_trial_id: felt252,
    pub result_selector: felt252,
    pub claim_selector: felt252,
    pub token_update_selector: felt252,
    pub token_batch_update_selector: felt252,
    pub config_selector_set_hash: felt252,
    pub source_projection_interface_hash: felt252,
    pub instrumented_class_hash: felt252,
    pub locked_formula_config_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrRegistryBootstrapCommitment {
    pub bootstrap_id: felt252,
    pub finalized_state_root_anchor_hash: felt252,
    pub inventory_program_id: felt252,
    pub inventory_verification_key_hash: felt252,
    pub bridge_token_class_hash: felt252,
    pub bridge_token_storage_layout_hash: felt252,
    pub token_bridge_init_hash: felt252,
    pub old_factory_tuple_hash: felt252,
    pub factory_count: u16,
    pub factory_bindings_hash: felt252,
    pub factory_creation_highwater_hash: felt252,
    pub factory_event_range_count: u16,
    pub factory_event_ranges_hash: felt252,
    pub historical_event_chain_root: felt252,
    pub writer_count: u32,
    pub writers_root: felt252,
    pub completed_writer_count: u32,
    pub partial_writer_count: u32,
    pub partial_creation_count: u32,
    pub partial_creations_root: felt252,
    pub formula_configs_root: felt252,
    pub bootstrap_deadline: u64,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrCreationTransition {
    pub sequence: u64,
    pub factory: ContractAddress,
    pub creation_nonce: u64,
    pub transition_kind: u8,
    pub previous_cursor: u16,
    pub new_cursor: u16,
    pub previous_partial_leaf_hash: felt252,
    pub new_partial_leaf_hash: felt252,
    pub previous_writer_leaf_hash: felt252,
    pub new_writer_leaf_hash: felt252,
    pub previous_creation_highwater_state_hash: felt252,
    pub new_creation_highwater_state_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrRegistryTransition {
    pub sequence: u64,
    pub registry_bootstrap_commitment_hash: felt252,
    pub transition_kind: u8,
    pub source_creation_transition_hash: felt252,
    pub writer_update_kind: u8,
    pub writer_index: u32,
    pub previous_writer_leaf_hash: felt252,
    pub new_writer_leaf_hash: felt252,
    pub previous_writers_root: felt252,
    pub new_writers_root: felt252,
    pub previous_formula_configs_root: felt252,
    pub new_formula_configs_root: felt252,
    pub previous_partial_creation_count: u32,
    pub new_partial_creation_count: u32,
    pub previous_partial_creations_root: felt252,
    pub new_partial_creations_root: felt252,
    pub previous_factory_creation_highwater_hash: felt252,
    pub new_factory_creation_highwater_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyImportedMmrJob {
    pub disposition_index: u32,
    pub import_index: u32,
    pub factory: ContractAddress,
    pub factory_event_index: u64,
    pub world: ContractAddress,
    pub mmr_system: ContractAddress,
    pub game_or_trial_id: felt252,
    pub game_meta_hash: felt252,
    pub claimed_hash: felt252,
    pub legacy_source_projection_hash: felt252,
    pub legacy_source_participants_root: felt252,
    pub legacy_game_median: u128,
    pub legacy_formula_inputs_root: felt252,
    pub legacy_formula_policy_hash: felt252,
    pub settlement_chunk_size: u8,
    pub legacy_synthetic_deployment_id: DeploymentId,
    pub imported_game_id: GameId,
    pub ranking_id: felt252,
    pub ranking: RankingCommitment,
    pub result: GameResult,
    pub module_binding_hash: felt252,
    pub module_aux_hash: felt252,
    pub funding_job_id: felt252,
    pub maximum_reward_units: u32,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrPendingImportBound {
    pub baseline_hash: felt252,
    pub state_sequence: u64,
    pub pending_job_count: u32,
    pub reward_units_upper_bound: u64,
    pub pending_jobs_accumulator: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrInstrumentationCompleteMarker {
    pub admission_gate: ContractAddress,
    pub admission_registry_hash: felt252,
    pub writer_count: u32,
    pub writers_root: felt252,
    pub factory_creation_highwater_hash: felt252,
    pub partial_creation_count: u32,
    pub partial_creations_root: felt252,
    pub marked_at_block_number: u64,
    pub gate_state_sequence: u64,
    pub gate_transition_accumulator: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrPendingImportBaseline {
    pub instrumentation_complete_marker_hash: felt252,
    pub finalized_state_root_anchor_hash: felt252,
    pub baseline_block_number: u64,
    pub baseline_block_hash: felt252,
    pub baseline_state_root: felt252,
    pub gate_state_sequence: u64,
    pub gate_transition_accumulator: felt252,
    pub cumulative_added_count: u64,
    pub cumulative_added_reward_units: u64,
    pub cumulative_resolved_count: u64,
    pub cumulative_resolved_reward_units: u64,
    pub pending_job_count: u32,
    pub pending_reward_units: u64,
    pub pending_jobs_root: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrPendingResultProjection {
    pub result_key: felt252,
    pub factory: ContractAddress,
    pub factory_event_index: u64,
    pub world: ContractAddress,
    pub mmr_system: ContractAddress,
    pub game_or_trial_id: felt252,
    pub game_meta_hash: felt252,
    pub pre_application_claimed_hash: felt252,
    pub current_claimed_hash: felt252,
    pub legacy_result_state_hash: felt252,
    pub legacy_ranking_layout_hash: felt252,
    pub legacy_ranking_highwater: u32,
    pub legacy_game_median: u128,
    pub legacy_formula_policy_hash: felt252,
    pub settlement_chunk_size: u8,
    pub participant_count: u16,
    pub first_rank: u16,
    pub last_rank: u16,
    pub winner_l2: ContractAddress,
    pub ended_at: u64,
    pub valid_result: bool,
    pub abort_reason: u16,
    pub application_mode: u8,
    pub application_nonce: u64,
    pub application_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrSourceParticipant {
    pub source_index: u32,
    pub factory: ContractAddress,
    pub factory_event_index: u64,
    pub world: ContractAddress,
    pub game_or_trial_id: felt252,
    pub player_l2: ContractAddress,
    pub legacy_player_key: ContractAddress,
    pub recipient_l1: ContractAddress,
    pub legacy_participation_key: felt252,
    pub formula_rank: u16,
    pub score: u256,
}

#[derive(Drop, Serde)]
pub struct MmrFormulaInput {
    pub ordinal_index: u16,
    pub ranking_entry_hash: felt252,
    pub formula_rank: u16,
}

#[derive(Drop, Serde)]
pub struct MmrCurrentFormulaAux {
    pub median_source: u8,
    pub game_median: u128,
    pub participant_count: u16,
    pub formula_inputs_root: felt252,
    pub formula_policy_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrPendingTransition {
    pub sequence: u64,
    pub transition_kind: u8,
    pub result_key: felt252,
    pub pending_projection_hash: felt252,
    pub observed_projection_hash: felt252,
    pub prior_add_transition_hash: felt252,
    pub application_hash: felt252,
    pub participant_count: u16,
    pub reward_units: u32,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrTokenValueChange {
    pub change_index: u16,
    pub player: ContractAddress,
    pub was_initialized: bool,
    pub old_scaled_value: u256,
    pub new_scaled_value: u256,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrTokenMutation {
    pub sequence: u64,
    pub caller: ContractAddress,
    pub mutation_kind: u8,
    pub result_key: felt252,
    pub application_nonce: u64,
    pub mutation_index: u16,
    pub mutation_count: u16,
    pub value_change_count: u16,
    pub value_changes_root: felt252,
    pub old_total_supply: u256,
    pub new_total_supply: u256,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrApplicationContext {
    pub result_key: felt252,
    pub application_nonce: u64,
    pub writer_leaf_hash: felt252,
    pub pending_projection_hash: felt252,
    pub pre_application_claimed_hash: felt252,
    pub participant_count: u16,
    pub total_update_count: u16,
    pub settlement_chunk_size: u8,
    pub chunk_index: u16,
    pub chunk_count: u16,
    pub start_index: u16,
    pub application_precommit_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrMutationReceipt {
    pub result_key: felt252,
    pub application_nonce: u64,
    pub first_mutation_sequence: u64,
    pub last_mutation_sequence: u64,
    pub completed_chunk_count: u16,
    pub mutation_hashes_accumulator: felt252,
    pub resulting_total_supply: u256,
    pub complete: bool,
    pub sealed: bool,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrPartialCreationDisposition {
    pub factory: ContractAddress,
    pub creation_nonce: u64,
    pub factory_version: felt252,
    pub game_name: felt252,
    pub draft_world: ContractAddress,
    pub mmr_system: ContractAddress,
    pub has_mmr_registration: bool,
    pub mmr_registration_hash: felt252,
    pub creation_cursor: u16,
    pub creation_highwater: u16,
    pub creation_state_hash: felt252,
    pub disposition: u8,
}

#[derive(Drop, Serde)]
pub struct StarknetFinalizedStateRootAnchor {
    pub source: ContractAddress,
    pub policy_hash: felt252,
    pub header_codec_hash: felt252,
    pub minimum_finality_blocks: u16,
    pub block_number: u64,
    pub block_hash: felt252,
    pub state_root: felt252,
    pub authenticated_at_block_number: u64,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrPreFreezeWitnessManifest {
    pub cutover_id: felt252,
    pub production_candidate_hash: felt252,
    pub static_config_hash: felt252,
    pub finalized_state_root_anchor_hash: felt252,
    pub instrumentation_complete_marker_hash: felt252,
    pub pending_import_baseline_hash: felt252,
    pub quiescence_generation: u32,
    pub quiescence_marker_hash: felt252,
    pub admission_registry_hash: felt252,
    pub factory_bindings_hash: felt252,
    pub writer_count: u32,
    pub writers_root: felt252,
    pub formula_configs_root: felt252,
    pub registry_transition_accumulator: felt252,
    pub factory_creation_highwater_hash: felt252,
    pub partial_creation_count: u32,
    pub partial_creations_root: felt252,
    pub factory_count: u16,
    pub factories_hash: felt252,
    pub factory_event_range_count: u16,
    pub factory_event_ranges_hash: felt252,
    pub historical_event_chain_root: felt252,
    pub world_count: u32,
    pub worlds_root: felt252,
    pub pending_import_bound_hash: felt252,
    pub gate_state_sequence: u64,
    pub gate_transition_accumulator: felt252,
    pub initial_token_state_hash: felt252,
    pub final_token_state_hash: felt252,
    pub token_mutation_accumulator: felt252,
    pub legacy_factory_tuple_hash: felt252,
    pub raw_projection_count: u32,
    pub raw_projections_root: felt252,
    pub source_participant_count: u64,
    pub source_participants_root: felt252,
    pub witness_object_count: u32,
    pub witness_objects_root: felt252,
    pub prefunded_escrow_hash: felt252,
    pub signer_set_epoch: u32,
    pub signer_set_hash: felt252,
    pub route_identity_set_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrProvedSourceInventory {
    pub cutover_id: felt252,
    pub production_candidate_hash: felt252,
    pub static_config_hash: felt252,
    pub finalized_state_root_anchor_hash: felt252,
    pub inventory_program_id: felt252,
    pub inventory_verification_key_hash: felt252,
    pub quiescence_generation: u32,
    pub quiescence_marker_hash: felt252,
    pub pre_freeze_witness_manifest_hash: felt252,
    pub instrumentation_complete_marker_hash: felt252,
    pub pending_import_baseline_hash: felt252,
    pub admission_registry_hash: felt252,
    pub factory_bindings_hash: felt252,
    pub writer_count: u32,
    pub writers_root: felt252,
    pub formula_configs_root: felt252,
    pub registry_transition_accumulator: felt252,
    pub factory_creation_highwater_hash: felt252,
    pub partial_creation_count: u32,
    pub partial_creations_root: felt252,
    pub factory_count: u16,
    pub factories_hash: felt252,
    pub factory_event_range_count: u16,
    pub factory_event_ranges_hash: felt252,
    pub historical_event_chain_root: felt252,
    pub world_count: u32,
    pub worlds_root: felt252,
    pub pending_import_bound_hash: felt252,
    pub pending_import_job_count: u32,
    pub pending_import_reward_units: u64,
    pub gate_state_sequence: u64,
    pub gate_transition_accumulator: felt252,
    pub initial_token_state_hash: felt252,
    pub final_token_state_hash: felt252,
    pub token_mutation_accumulator: felt252,
    pub legacy_factory_tuple_hash: felt252,
    pub raw_projection_count: u32,
    pub raw_projections_root: felt252,
    pub source_participant_count: u64,
    pub source_participants_root: felt252,
    pub witness_object_count: u32,
    pub witness_objects_root: felt252,
    pub prefunded_escrow_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrQuiescenceMarker {
    pub cutover_id: felt252,
    pub quiescence_generation: u32,
    pub started_at: u64,
    pub expires_at: u64,
    pub admission_registry_hash: felt252,
    pub pending_import_bound_hash: felt252,
    pub gate_state_sequence: u64,
    pub gate_transition_accumulator: felt252,
    pub token_mutation_accumulator: felt252,
    pub legacy_factory_tuple_hash: felt252,
    pub prefunded_escrow_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrAdmissionFreezeMarker {
    pub admission_gate: ContractAddress,
    pub cutover_id: felt252,
    pub frozen_at_block_number: u64,
    pub quiescence_generation: u32,
    pub quiescence_marker_hash: felt252,
    pub instrumentation_complete_marker_hash: felt252,
    pub pending_import_baseline_hash: felt252,
    pub admission_registry_hash: felt252,
    pub pending_import_bound_hash: felt252,
    pub proved_source_inventory_hash: felt252,
    pub pre_freeze_verified_bundle_hash: felt252,
    pub router_reservation_hash: felt252,
    pub gate_state_sequence: u64,
    pub gate_transition_accumulator: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrTokenMigrationPauseMarker {
    pub admission_gate: ContractAddress,
    pub migration_generation: u32,
    pub started_at: u64,
    pub expires_at: u64,
    pub registry_bootstrap_commitment_hash: felt252,
    pub writer_count: u32,
    pub writers_root: felt252,
    pub factory_creation_highwater_hash: felt252,
    pub partial_creation_count: u32,
    pub partial_creations_root: felt252,
    pub formula_configs_root: felt252,
    pub registry_transition_accumulator: felt252,
    pub token_bridge_init_hash: felt252,
    pub token_class_hash: felt252,
    pub token_storage_layout_hash: felt252,
    pub factory_tuple_hash: felt252,
    pub pre_pause_token_state_hash: felt252,
    pub pre_pause_component_authority_state_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrImportArchiveItem {
    pub import_index: u32,
    pub imported_job_hash: felt252,
    pub legacy_source_projection_hash: felt252,
    pub legacy_source_participants_root: felt252,
    pub legacy_formula_inputs_root: felt252,
    pub legacy_formula_inputs_content_hash: felt252,
    pub ranking_root: felt252,
    pub participant_count: u16,
    pub ranking_entries_content_hash: felt252,
    pub merkle_material_content_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrImportDataManifest {
    pub cutover_id: felt252,
    pub freeze_marker_hash: felt252,
    pub proved_source_inventory_hash: felt252,
    pub legacy_synthetic_deployment_id: DeploymentId,
    pub imported_job_count: u32,
    pub imported_jobs_root: felt252,
    pub total_ranking_entry_count: u64,
    pub archive_item_count: u32,
    pub archive_items_root: felt252,
    pub module_binding_hash: felt252,
    pub funding_reservations_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrFundingReservation {
    pub cutover_id: felt252,
    pub funding_scope_id: felt252,
    pub import_index: u32,
    pub funding_job_id: felt252,
    pub unit_amount: u256,
    pub maximum_reward_units: u32,
    pub reserved_amount: u256,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrCutoverEscrow {
    pub cutover_id: felt252,
    pub production_candidate_hash: felt252,
    pub static_config_hash: felt252,
    pub target_router: ContractAddress,
    pub mmr_token: ContractAddress,
    pub funding_vault: ContractAddress,
    pub funding_account: ContractAddress,
    pub funding_owner: ContractAddress,
    pub reward_unit_amount: u256,
    pub max_reward_units: u32,
    pub reward_budget: u256,
    pub excess_refund_recipient: ContractAddress,
    pub excess_return_policy_hash: felt252,
    pub state: u8,
    pub derived_funding_scope_id: felt252,
    pub imported_jobs_root: felt252,
    pub expected_imported_job_count: u32,
    pub reserved_job_count: u32,
    pub terminal_job_count: u32,
    pub expected_funding_reservations_hash: felt252,
    pub actual_funding_reservations_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct MmrSettlementLock {
    pub active: bool,
    pub sequence: u64,
    pub has_snapshot_commitment: bool,
    pub snapshot_commitment: felt252,
    pub expected_count: u16,
    pub applied_count: u16,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrFreezeMarker {
    pub cutover_id: felt252,
    pub production_candidate_hash: felt252,
    pub target_router: ContractAddress,
    pub router_legacy_binding_hash: felt252,
    pub static_config_hash: felt252,
    pub frozen_at_block_number: u64,
    pub admission_gate: ContractAddress,
    pub admission_registry_hash: felt252,
    pub instrumentation_complete_marker_hash: felt252,
    pub pending_import_baseline_hash: felt252,
    pub quiescence_marker_hash: felt252,
    pub pre_freeze_witness_manifest_hash: felt252,
    pub proved_source_inventory_hash: felt252,
    pub pre_freeze_verified_bundle_hash: felt252,
    pub admission_freeze_marker_hash: felt252,
    pub router_reservation_hash: felt252,
    pub legacy_factory_tuple_hash: felt252,
    pub token_mutation_accumulator: felt252,
    pub frozen_pending_import_bound_hash: felt252,
    pub frozen_pending_import_job_count: u32,
    pub frozen_pending_import_reward_units: u64,
    pub prefunded_escrow_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct MmrModuleBinding {
    pub protocol_version: u16,
    pub ruleset_id: felt252,
    pub module: ContractAddress,
    pub program_id: felt252,
    pub verification_key_hash: felt252,
    pub mmr_policy_hash: felt252,
    pub release_bundle_hash: felt252,
    pub settlement_chunk_size: u8,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrRouterBinding {
    pub protocol_version: u16,
    pub router: ContractAddress,
    pub router_class_hash: felt252,
    pub canonical_mmr_token: ContractAddress,
    pub funding_vault: ContractAddress,
    pub archive_registry: ContractAddress,
    pub finalized_state_root_source: ContractAddress,
    pub inventory_verifier: ContractAddress,
    pub inventory_verifier_class_hash: felt252,
    pub inventory_program_id: felt252,
    pub inventory_verification_key_hash: felt252,
    pub derivation_program_id: felt252,
    pub derivation_verification_key_hash: felt252,
    pub release_bundle_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrRouterReservation {
    pub router_legacy_binding_hash: felt252,
    pub cutover_id: felt252,
    pub production_candidate_hash: felt252,
    pub static_config_hash: felt252,
    pub canonical_mmr_token: ContractAddress,
    pub admission_gate: ContractAddress,
    pub quiescence_generation: u32,
    pub quiescence_marker_hash: felt252,
    pub pre_freeze_witness_manifest_hash: felt252,
    pub proved_source_inventory_hash: felt252,
    pub pre_freeze_verified_bundle_hash: felt252,
    pub prefunded_escrow_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrCutoverStaticConfig {
    pub production_candidate_hash: felt252,
    pub target_router: ContractAddress,
    pub target_router_class_hash: felt252,
    pub router_legacy_binding_hash: felt252,
    pub mmr_token: ContractAddress,
    pub mmr_token_class_hash: felt252,
    pub mmr_token_storage_layout_hash: felt252,
    pub mmr_token_migration_init_hash: felt252,
    pub cutover_component_class_bindings_hash: felt252,
    pub cutover_component_authority_state_hash: felt252,
    pub admission_gate: ContractAddress,
    pub admission_registry_hash: felt252,
    pub instrumentation_complete_marker_hash: felt252,
    pub pending_import_baseline_hash: felt252,
    pub finalized_state_root_source: ContractAddress,
    pub finalized_header_policy_hash: felt252,
    pub finalized_header_codec_hash: felt252,
    pub minimum_finality_blocks: u16,
    pub quiescence_duration_seconds: u32,
    pub expected_legacy_factory_tuple_hash: felt252,
    pub inventory_program_id: felt252,
    pub inventory_verification_key_hash: felt252,
    pub derivation_program_id: felt252,
    pub derivation_verification_key_hash: felt252,
    pub legacy_module_binding: MmrModuleBinding,
    pub funding_vault: ContractAddress,
    pub funding_account: ContractAddress,
    pub funding_owner: ContractAddress,
    pub reward_unit_amount: u256,
    pub max_reward_units: u32,
    pub excess_refund_recipient: ContractAddress,
    pub excess_return_policy_hash: felt252,
    pub archive_registry: ContractAddress,
    pub archive_policy_hash: felt252,
    pub archive_signer_set_epoch: u32,
    pub archive_signer_set_hash: felt252,
    pub archive_route_identity_set_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrTokenBridgeInit {
    pub protocol_version: u16,
    pub migration_release_bundle_hash: felt252,
    pub migration_guard: ContractAddress,
    pub expected_old_token_class_hash: felt252,
    pub expected_old_storage_layout_hash: felt252,
    pub expected_old_factory_tuple_hash: felt252,
    pub new_token_class_hash: felt252,
    pub new_token_storage_layout_hash: felt252,
    pub admission_gate: ContractAddress,
    pub admission_gate_class_hash: felt252,
    pub finalized_state_root_source: ContractAddress,
    pub finalized_state_root_source_class_hash: felt252,
    pub finalized_header_policy_hash: felt252,
    pub finalized_header_codec_hash: felt252,
    pub minimum_finality_blocks: u16,
    pub inventory_program_id: felt252,
    pub inventory_verification_key_hash: felt252,
    pub legacy_cutover_authority: ContractAddress,
    pub expected_pre_init_role_state_hash: felt252,
    pub bridge_role_state_hash: felt252,
    pub post_activation_role_closure_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrTokenContextActivation {
    pub protocol_version: u16,
    pub migration_release_bundle_hash: felt252,
    pub migration_guard: ContractAddress,
    pub admission_gate: ContractAddress,
    pub migration_generation: u32,
    pub migration_pause_marker_hash: felt252,
    pub initial_token_state_hash: felt252,
    pub finalized_state_root_anchor_hash: felt252,
    pub registry_bootstrap_commitment_hash: felt252,
    pub writer_count: u32,
    pub writers_root: felt252,
    pub factory_creation_highwater_hash: felt252,
    pub partial_creation_count: u32,
    pub partial_creations_root: felt252,
    pub formula_configs_root: felt252,
    pub registry_transition_accumulator: felt252,
    pub expected_token_class_hash: felt252,
    pub expected_token_storage_layout_hash: felt252,
    pub expected_factory_tuple_hash: felt252,
    pub post_activation_role_closure_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrWorldMigrationInit {
    pub protocol_version: u16,
    pub migration_release_bundle_hash: felt252,
    pub migration_guard: ContractAddress,
    pub factory: ContractAddress,
    pub factory_version: felt252,
    pub factory_event_index: u64,
    pub game_or_trial_id: felt252,
    pub source_identity_hash: felt252,
    pub world: ContractAddress,
    pub expected_old_world_class_hash: felt252,
    pub expected_old_world_storage_layout_hash: felt252,
    pub new_world_class_hash: felt252,
    pub new_world_storage_layout_hash: felt252,
    pub proved_upgrade_controller: ContractAddress,
    pub world_upgrade_route_hash: felt252,
    pub child_component_plan_set_hash: felt252,
    pub admission_gate: ContractAddress,
    pub migration_executor_state_hash: felt252,
    pub post_rollout_authority_closure_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrSystemMigrationInit {
    pub protocol_version: u16,
    pub migration_release_bundle_hash: felt252,
    pub migration_guard: ContractAddress,
    pub factory: ContractAddress,
    pub factory_version: felt252,
    pub factory_event_index: u64,
    pub game_or_trial_id: felt252,
    pub source_identity_hash: felt252,
    pub world: ContractAddress,
    pub mmr_system: ContractAddress,
    pub expected_mmr_system_class_hash: felt252,
    pub expected_mmr_system_storage_layout_hash: felt252,
    pub new_mmr_system_class_hash: felt252,
    pub new_mmr_system_storage_layout_hash: felt252,
    pub proved_upgrade_controller: ContractAddress,
    pub system_upgrade_route_hash: felt252,
    pub admission_gate: ContractAddress,
    pub source_projection_interface_hash: felt252,
    pub instrumented_selector_set_hash: felt252,
    pub post_rollout_authority_closure_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrFactoryMigrationInit {
    pub protocol_version: u16,
    pub migration_release_bundle_hash: felt252,
    pub migration_guard: ContractAddress,
    pub factory: ContractAddress,
    pub expected_old_factory_class_hash: felt252,
    pub expected_old_factory_storage_layout_hash: felt252,
    pub new_factory_class_hash: felt252,
    pub new_factory_storage_layout_hash: felt252,
    pub factory_dojo_world: ContractAddress,
    pub proved_upgrade_controller: ContractAddress,
    pub upgrade_controller_class_hash: felt252,
    pub old_owner_config_authority_state_hash: felt252,
    pub admission_gate: ContractAddress,
    pub create_resume_sync_selector_set_hash: felt252,
    pub config_selector_set_hash: felt252,
    pub initial_creation_highwater_state_hash: felt252,
    pub child_world_upgrade_route_hash: felt252,
    pub instrumented_recipe_binding_hash: felt252,
    pub first_instrumented_creation_nonce: u64,
    pub pre_migration_partial_creation_count: u32,
    pub pre_migration_partial_creations_root: felt252,
    pub migration_executor_state_hash: felt252,
    pub post_rollout_authority_closure_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrConfigSystemMigrationInit {
    pub protocol_version: u16,
    pub migration_release_bundle_hash: felt252,
    pub migration_guard: ContractAddress,
    pub world: ContractAddress,
    pub config_system: ContractAddress,
    pub expected_old_config_system_class_hash: felt252,
    pub expected_old_config_storage_layout_hash: felt252,
    pub new_config_system_class_hash: felt252,
    pub new_config_storage_layout_hash: felt252,
    pub proved_upgrade_controller: ContractAddress,
    pub config_system_upgrade_route_hash: felt252,
    pub set_mmr_config_selector: felt252,
    pub other_mmr_config_writer_selectors_hash: felt252,
    pub world_admin_writer_authority_state_hash: felt252,
    pub admission_gate: ContractAddress,
    pub post_rollout_authority_closure_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrMigrationPlan {
    pub component_kind: u8,
    pub proxy: ContractAddress,
    pub upgrade_executor: ContractAddress,
    pub upgrade_route_hash: felt252,
    pub expected_old_class_hash: felt252,
    pub expected_old_storage_layout_hash: felt252,
    pub expected_old_state_hash: felt252,
    pub expected_new_class_hash: felt252,
    pub expected_new_storage_layout_hash: felt252,
    pub migration_init_hash: felt252,
    pub migration_release_bundle_hash: felt252,
    pub execute_before: u64,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrInitialTokenState {
    pub finalized_state_root_anchor_hash: felt252,
    pub admission_gate: ContractAddress,
    pub migration_generation: u32,
    pub migration_pause_marker_hash: felt252,
    pub mmr_token: ContractAddress,
    pub token_class_hash: felt252,
    pub token_storage_layout_hash: felt252,
    pub token_contract_storage_root: felt252,
    pub factory_tuple_hash: felt252,
    pub total_supply: u256,
    pub legacy_storage_sentinel_hash: felt252,
    pub registry_state_hash: felt252,
    pub formula_configs_root: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrPrePauseTokenState {
    pub mmr_token: ContractAddress,
    pub token_class_hash: felt252,
    pub token_storage_layout_hash: felt252,
    pub token_bridge_init_hash: felt252,
    pub factory_tuple_hash: felt252,
    pub total_supply: u256,
    pub token_role_state_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrRelevantBalanceSlot {
    pub slot_index: u32,
    pub player: ContractAddress,
    pub storage_key: felt252,
    pub scaled_value: u256,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrAuthorityMember {
    pub member_index: u16,
    pub member: ContractAddress,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrAuthorityRole {
    pub role_index: u16,
    pub role_id: felt252,
    pub admin_role_id: felt252,
    pub member_count: u16,
    pub members_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrAuthorityCapability {
    pub capability_index: u16,
    pub capability_id: felt252,
    pub capability_kind: u8,
    pub selector: felt252,
    pub controller: ContractAddress,
    pub route_hash: felt252,
    pub enabled: bool,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrTokenAuthorityProjection {
    pub mmr_token: ContractAddress,
    pub token_class_hash: felt252,
    pub token_storage_layout_hash: felt252,
    pub authority_schema_hash: felt252,
    pub role_count: u16,
    pub roles_hash: felt252,
    pub capability_count: u16,
    pub capabilities_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LegacyMmrFinalTokenState {
    pub finalized_state_root_anchor_hash: felt252,
    pub mmr_token: ContractAddress,
    pub token_class_hash: felt252,
    pub token_storage_layout_hash: felt252,
    pub token_migration_init_hash: felt252,
    pub token_contract_storage_root: felt252,
    pub factory_tuple_hash: felt252,
    pub total_supply: u256,
    pub token_mutation_sequence: u64,
    pub token_mutation_accumulator: felt252,
    pub relevant_balance_slot_count: u32,
    pub relevant_balance_slots_root: felt252,
    pub token_authority_state_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct MMRJob {
    pub sequence: u64,
    pub deployment_id: DeploymentId,
    pub game_id: GameId,
    pub ranking_id: felt252,
    pub participant_count: u16,
    pub module_binding: MmrModuleBinding,
    pub module_aux_hash: felt252,
    pub funding_scope_id: felt252,
    pub funding_job_id: felt252,
    pub state: u8,
    pub snapshot_cursor: u16,
    pub snapshot_commitment: felt252,
    pub plan_root: felt252,
    pub update_cursor: u16,
    pub applied_updates_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct FinalizedStarknetHeader {
    pub chain_id: felt252,
    pub block_number: u64,
    pub block_hash: felt252,
    pub parent_hash: felt252,
    pub state_root: felt252,
    pub finalized_l1_block_number: u64,
    pub finalized_l1_block_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct StarknetHeaderSourcePolicy {
    pub chain_id: felt252,
    pub recursive_finality_verifier: ContractAddress,
    pub initial_trusted_header_hash: felt252,
    pub initial_trusted_block_number: u64,
    pub hardened_piltover_l1: felt252,
    pub piltover_storage_layout_hash: felt252,
    pub max_finality_proof_felts: u16,
    pub max_storage_proof_felts: u16,
}

#[derive(Drop, Serde)]
pub enum CancelledSlotRelayResult {
    Applied: (MessageId, u64),
    AlreadyApplied: (MessageId, u64),
}

#[derive(Drop, Serde)]
pub struct AppliedIngressResult {
    pub activation: IngressActivation,
    pub batch_id: BatchId,
    pub appended_liability_count: u8,
    pub appended_liabilities_hash: felt252,
    pub economic_effect_hash: felt252,
}

#[derive(Drop, Serde)]
pub enum GameIngressDispatchResult {
    Applied: AppliedIngressResult,
    RejectedFinal: IngressRejectionReceipt,
}

#[derive(Drop, Serde)]
pub struct GameForcedExitProgress {
    pub exit_id: felt252,
    pub game_id: GameId,
    pub phase: u8,
    pub family_cursor: u16,
    pub item_cursor: u64,
    pub appended_liability_count: u32,
    pub liabilities_hash: felt252,
    pub terminal: bool,
}

#[derive(Drop, Serde)]
pub struct PlayerBindingRequest {
    pub ingress_id: IngressId,
    pub recipient_l1: ContractAddress,
    pub player_l2: ContractAddress,
    pub binding_nonce: u64,
}

#[derive(Drop, Serde)]
pub struct ResourceDepositMessage {
    pub ingress_id: IngressId,
    pub game_id: GameId,
    pub asset_id: u32,
    pub backing_pool_id: felt252,
    pub gross_amount: u256,
    pub token_decimals: u8,
    pub player_l2: ContractAddress,
    pub recipient_l1: ContractAddress,
    pub target_structure_id: felt252,
    pub client_fee_recipient: ContractAddress,
}

#[derive(Drop, Serde)]
pub struct ScarceDepositMessage {
    pub ingress_id: IngressId,
    pub game_id: GameId,
    pub asset_id: u32,
    pub backing_pool_id: felt252,
    pub purpose: felt252,
    pub gross_amount: u256,
    pub player_l2: ContractAddress,
    pub recipient_l1: ContractAddress,
    pub target_id: felt252,
}

#[derive(Drop, Serde)]
pub struct EntitlementDepositMessage {
    pub ingress_id: IngressId,
    pub entitlement_kind: u8,
    pub token_id: u256,
    pub player_l2: ContractAddress,
    pub recipient_l1: ContractAddress,
    pub game_id: GameId,
    pub metadata_fields: Span<felt252>,
    pub metadata_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct TempCredentialMessage {
    pub ingress_id: IngressId,
    pub credential_kind: u8,
    pub collection_id: u32,
    pub token_id: u256,
    pub player_l2: ContractAddress,
    pub recipient_l1: ContractAddress,
    pub game_id: GameId,
    pub attributes_raw: u128,
    pub metadata_hash: felt252,
    pub lock_policy_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct BlitzEntryMessage {
    pub ingress_id: IngressId,
    pub game_id: GameId,
    pub collection_id: felt252,
    pub token_id: u256,
    pub player_l2: ContractAddress,
    pub payer_l1: ContractAddress,
    pub recipient_l1: ContractAddress,
    pub payment_asset_id: u32,
    pub payment_backing_pool_id: felt252,
    pub gross_fee: u256,
    pub fee_purpose: felt252,
    pub lock_policy_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct FundingGrantMessage {
    pub ingress_id: IngressId,
    pub asset_mode: u8,
    pub asset_id: u32,
    pub backing_pool_id: felt252,
    pub purpose: felt252,
    pub amount_or_quota: u256,
    pub game_id: GameId,
    pub funder_l1: ContractAddress,
    pub refund_recipient_l1: ContractAddress,
    pub refund_policy_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct ForcedExitMessage {
    pub request_id: felt252,
    pub player_l2: ContractAddress,
    pub recipient_l1: ContractAddress,
    pub request_l1_block: u64,
    pub deadline: u64,
    pub binding_nonce: u64,
}

#[derive(Drop, Serde)]
pub struct IngressCloseMessage {
    pub cutoff_transport_nonce: u64,
    pub evidence_kind: u16,
    pub evidence_hash: felt252,
    pub requested_at_l1: u64,
}

#[derive(Drop, Serde)]
pub struct GameFreezeMessage {
    pub freeze_id: felt252,
    pub freeze_scope: u8,
    pub target_game_id: GameId,
    pub cutoff_transport_nonce: u64,
    pub target_economic_timestamp: u64,
    pub evidence_kind: u16,
    pub evidence_hash: felt252,
    pub requested_at_l1: u64,
}

#[derive(Drop, Serde)]
pub struct FinalizationBarrierMessage {
    pub barrier_id: felt252,
    pub forced_exit_cutoff_transport_nonce: u64,
    pub expected_registered_game_count: u8,
    pub requested_at_l1: u64,
}

#[derive(Drop, Serde)]
pub struct SeriesAdvanceAck {
    pub series_id: felt252,
    pub game_number: u32,
    pub game_id: GameId,
    pub result_hash: felt252,
    pub accumulator_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct GameRegistration {
    pub game_id: GameId,
    pub world: ContractAddress,
    pub game_config_hash: felt252,
    pub class_bundle_hash: felt252,
    pub schema_bundle_hash: felt252,
    pub emitters_hash: felt252,
    pub capacity_count: u8,
    pub capacity_hash: felt252,
    pub series_id: felt252,
    pub game_number: u32,
    pub predecessor_result_hash: felt252,
    pub series_accumulator_seed_hash: felt252,
    pub registration_outbox_nonce: u64,
}

#[derive(Drop, Serde)]
pub struct SettlementRootMessage {
    pub batch_id: BatchId,
    pub previous_batch_hash: felt252,
    pub leaf_count: u8,
    pub root: felt252,
    pub asset_totals_hash: felt252,
    pub ingress_activation_count: u8,
    pub ingress_activations_hash: felt252,
    pub nft_reservation_count: u8,
    pub nft_reservations_hash: felt252,
    pub deployment_refund_count: u8,
    pub deployment_refunds_hash: felt252,
    pub lot_share_promotion_count: u16,
    pub lot_share_promotions_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct SeriesResult {
    pub series_id: felt252,
    pub predecessor_hash: felt252,
    pub game_id: GameId,
    pub result_hash: felt252,
    pub valid_result: bool,
    pub completed_at: u64,
    pub accumulator: Span<felt252>,
    pub accumulator_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct PlayerBindingAckAux {
    pub source_message_id: MessageId,
    pub ingress_id: IngressId,
    pub binding_nonce: u64,
}

#[derive(Drop, Serde)]
pub struct ForcedExitCompletedAux {
    pub source_message_id: MessageId,
    pub request_id: felt252,
    pub liabilities_hash: felt252,
    pub completion_batch_id: BatchId,
}

#[derive(Drop, Serde)]
pub struct ResourcePayoutAux {
    pub source_position_id: felt252,
    pub generation: u64,
    pub gross_amount: u256,
    pub loss_amount: u256,
    pub fee_breakdown_hash: felt252,
    pub conversion_policy_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct ScarcePayoutAux {
    pub source_position_id: felt252,
    pub generation: u64,
    pub purpose: felt252,
    pub fee_breakdown_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct LpCompositePayoutAux {
    pub lp_position_id: felt252,
    pub generation: u64,
    pub pool_id: felt252,
    pub shares_burned: u256,
    pub reserve_snapshot_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct FungibleOutcomePayoutAux {
    pub purpose: felt252,
    pub source_result_hash: felt252,
    pub rank_or_share: u256,
}

#[derive(Drop, Serde)]
pub struct OutcomeNftPayoutAux {
    pub outcome_kind: u16,
    pub source_entity_id: felt252,
    pub source_nonce: u64,
    pub attributes_raw: u128,
    pub attributes_hash: felt252,
    pub metadata_hash: felt252,
}

#[derive(Drop, Serde)]
pub struct TempCredentialReleaseAux {
    pub ingress_id: IngressId,
    pub collection_id: u32,
    pub token_id: u256,
    pub release_reason: u16,
}

#[derive(Drop, Serde)]
pub struct FeeDistributionPayoutAux {
    pub source_ingress_or_withdrawal: felt252,
    pub fee_kind: u16,
    pub configured_bps: u16,
}
