kind = "DojoModel"
class_hash = "0x557d178675bc40519e1b34058bb68386bae215a7c958231ccf686adb7235134"
original_class_hash = "0x557d178675bc40519e1b34058bb68386bae215a7c958231ccf686adb7235134"
abi = "manifests/dev/base/abis/models/eternum-Quest-18cf370a.json"
tag = "eternum-Quest"
qualified_path = "eternum::models::quest::quest"
manifest_name = "eternum-Quest-18cf370a"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "completed"
type = "bool"
key = false
