kind = "DojoModel"
class_hash = "0x8170b0403934978312896ce301f6a75ac4c125ebafcc385bd9c5ce40911e06"
original_class_hash = "0x8170b0403934978312896ce301f6a75ac4c125ebafcc385bd9c5ce40911e06"
abi = "manifests/dev/base/abis/models/eternum-RealmLevelConfig-2e254b9a.json"
tag = "eternum-RealmLevelConfig"
qualified_path = "eternum::models::config::realm_level_config"
manifest_name = "eternum-RealmLevelConfig-2e254b9a"

[[members]]
name = "level"
type = "u8"
key = true

[[members]]
name = "required_resources_id"
type = "ID"
key = false

[[members]]
name = "required_resource_count"
type = "u8"
key = false
