kind = "DojoModel"
class_hash = "0x5c87fcaac3db2f0f4bb317415cb01fde2ed30dd229e58b2c89ebd6b2f2f12a4"
original_class_hash = "0x5c87fcaac3db2f0f4bb317415cb01fde2ed30dd229e58b2c89ebd6b2f2f12a4"
abi = "manifests/dev/base/abis/models/eternum-Protectee-6e671952.json"
tag = "eternum-Protectee"
qualified_path = "eternum::models::combat::protectee"
manifest_name = "eternum-Protectee-6e671952"

[[members]]
name = "army_id"
type = "ID"
key = true

[[members]]
name = "protectee_id"
type = "ID"
key = false
