kind = "DojoModel"
class_hash = "0x1e6362bbbf40dd73530f12a69d00eafe3903d0505de5a09a783351c2d5fbaf2"
original_class_hash = "0x1e6362bbbf40dd73530f12a69d00eafe3903d0505de5a09a783351c2d5fbaf2"
abi = "manifests/dev/base/abis/models/eternum-SettleRealmData-40a37d8d.json"
tag = "eternum-SettleRealmData"
qualified_path = "eternum::models::event::settle_realm_data"
manifest_name = "eternum-SettleRealmData-40a37d8d"

[[members]]
name = "id"
type = "ID"
key = true

[[members]]
name = "event_id"
type = "EventType"
key = true

[[members]]
name = "entity_id"
type = "ID"
key = false

[[members]]
name = "owner_address"
type = "ContractAddress"
key = false

[[members]]
name = "owner_name"
type = "felt252"
key = false

[[members]]
name = "realm_name"
type = "felt252"
key = false

[[members]]
name = "produced_resources"
type = "u128"
key = false

[[members]]
name = "cities"
type = "u8"
key = false

[[members]]
name = "harbors"
type = "u8"
key = false

[[members]]
name = "rivers"
type = "u8"
key = false

[[members]]
name = "regions"
type = "u8"
key = false

[[members]]
name = "wonder"
type = "u8"
key = false

[[members]]
name = "order"
type = "u8"
key = false

[[members]]
name = "x"
type = "u32"
key = false

[[members]]
name = "y"
type = "u32"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
