kind = "DojoModel"
class_hash = "0x5e599733e0a1ba3cc2e38a6435fd362c2ebfd1f04a1566591e394ebc90cca60"
original_class_hash = "0x5e599733e0a1ba3cc2e38a6435fd362c2ebfd1f04a1566591e394ebc90cca60"
abi = "manifests/dev/base/abis/models/eternum-Structure-1ccc0e57.json"
tag = "eternum-Structure"
qualified_path = "eternum::models::structure::structure"
manifest_name = "eternum-Structure-1ccc0e57"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "category"
type = "StructureCategory"
key = false

[[members]]
name = "created_at"
type = "u64"
key = false
