kind = "DojoModel"
class_hash = "0x1e7cb5d3ce359c15b4a45d6ddc0b655f8db583ae5a4885d345191213bd229aa"
original_class_hash = "0x1e7cb5d3ce359c15b4a45d6ddc0b655f8db583ae5a4885d345191213bd229aa"
abi = "manifests/dev/base/abis/models/eternum-Epoch-4f756c33.json"
tag = "eternum-Epoch"
qualified_path = "eternum::models::hyperstructure::epoch"
manifest_name = "eternum-Epoch-4f756c33"

[[members]]
name = "hyperstructure_entity_id"
type = "ID"
key = true

[[members]]
name = "index"
type = "u16"
key = true

[[members]]
name = "start_timestamp"
type = "u64"
key = false

[[members]]
name = "owners"
type = "Span<(ContractAddress, u16)>"
key = false
