kind = "DojoModel"
class_hash = "0x1967e023056669a5680986f608704b95d9199eae082ac9ba67a384c9fd0baa6"
original_class_hash = "0x1967e023056669a5680986f608704b95d9199eae082ac9ba67a384c9fd0baa6"
abi = "manifests/dev/base/abis/models/eternum-BattleClaimData-51826fa8.json"
tag = "eternum-BattleClaimData"
qualified_path = "eternum::models::event::battle_claim_data"
manifest_name = "eternum-BattleClaimData-51826fa8"

[[members]]
name = "id"
type = "ID"
key = true

[[members]]
name = "event_id"
type = "EventType"
key = true

[[members]]
name = "structure_entity_id"
type = "ID"
key = false

[[members]]
name = "claimer"
type = "ContractAddress"
key = false

[[members]]
name = "claimer_name"
type = "felt252"
key = false

[[members]]
name = "claimer_army_entity_id"
type = "ID"
key = false

[[members]]
name = "previous_owner"
type = "ContractAddress"
key = false

[[members]]
name = "x"
type = "u32"
key = false

[[members]]
name = "y"
type = "u32"
key = false

[[members]]
name = "structure_type"
type = "StructureCategory"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
