kind = "DojoModel"
class_hash = "0x2bc68767e24a949812e3fe1e79c2f42249148b057ff27ad57aa2e693ede8685"
original_class_hash = "0x2bc68767e24a949812e3fe1e79c2f42249148b057ff27ad57aa2e693ede8685"
abi = "manifests/dev/base/abis/models/eternum-BuildingCategoryPopConfig-5804f847.json"
tag = "eternum-BuildingCategoryPopConfig"
qualified_path = "eternum::models::config::building_category_pop_config"
manifest_name = "eternum-BuildingCategoryPopConfig-5804f847"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "building_category"
type = "BuildingCategory"
key = true

[[members]]
name = "population"
type = "u32"
key = false

[[members]]
name = "capacity"
type = "u32"
key = false
