kind = "DojoModel"
class_hash = "0x338d3e6593d7cdd1088edd18bbd44f38598d465f533dac605135b7e6cd754e1"
original_class_hash = "0x338d3e6593d7cdd1088edd18bbd44f38598d465f533dac605135b7e6cd754e1"
abi = "manifests/dev/base/abis/models/eternum-Hyperstructure-767c75e3.json"
tag = "eternum-Hyperstructure"
qualified_path = "eternum::models::hyperstructure::hyperstructure"
manifest_name = "eternum-Hyperstructure-767c75e3"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "current_epoch"
type = "u16"
key = false

[[members]]
name = "completed"
type = "bool"
key = false

[[members]]
name = "last_updated_by"
type = "ContractAddress"
key = false

[[members]]
name = "last_updated_timestamp"
type = "u64"
key = false

[[members]]
name = "access"
type = "Access"
key = false
