kind = "DojoModel"
class_hash = "0x70a12fcb57b41160181aa0d794c982868d727dc3bae3fcbda4ccf9ccd60fd60"
original_class_hash = "0x70a12fcb57b41160181aa0d794c982868d727dc3bae3fcbda4ccf9ccd60fd60"
abi = "manifests/dev/base/abis/models/eternum-Orders-4423b5ef.json"
tag = "eternum-Orders"
qualified_path = "eternum::models::order::orders"
manifest_name = "eternum-Orders-4423b5ef"

[[members]]
name = "order_id"
type = "ID"
key = true

[[members]]
name = "hyperstructure_count"
type = "u32"
key = false
