kind = "DojoModel"
class_hash = "0x2220d491d661ebb5dfaed6e3602c9791b289bd728fe7c2f909d48fd2a9b0604"
original_class_hash = "0x2220d491d661ebb5dfaed6e3602c9791b289bd728fe7c2f909d48fd2a9b0604"
abi = "manifests/dev/base/abis/models/eternum-QuantityTracker-1889ed7d.json"
tag = "eternum-QuantityTracker"
qualified_path = "eternum::models::quantity::quantity_tracker"
manifest_name = "eternum-QuantityTracker-1889ed7d"

[[members]]
name = "entity_id"
type = "felt252"
key = true

[[members]]
name = "count"
type = "u128"
key = false
