kind = "DojoModel"
class_hash = "0x11dbb3e191286eb3ddd6b59a5c6558e3e6234713e361ccccc8b155a44a0a625"
original_class_hash = "0x11dbb3e191286eb3ddd6b59a5c6558e3e6234713e361ccccc8b155a44a0a625"
abi = "manifests/dev/base/abis/models/eternum-MapConfig-369135d8.json"
tag = "eternum-MapConfig"
qualified_path = "eternum::models::config::map_config"
manifest_name = "eternum-MapConfig-369135d8"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "reward_resource_amount"
type = "u128"
key = false

[[members]]
name = "shards_mines_fail_probability"
type = "u128"
key = false
