kind = "DojoModel"
class_hash = "0x2e25a336ed189f0829ae5258f1e1f5aff096d2062701866f14b708189f8d144"
original_class_hash = "0x2e25a336ed189f0829ae5258f1e1f5aff096d2062701866f14b708189f8d144"
abi = "manifests/dev/base/abis/models/eternum-GuildWhitelist-54f9b15d.json"
tag = "eternum-GuildWhitelist"
qualified_path = "eternum::models::guild::guild_whitelist"
manifest_name = "eternum-GuildWhitelist-54f9b15d"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "guild_entity_id"
type = "ID"
key = true

[[members]]
name = "is_whitelisted"
type = "bool"
key = false
