kind = "DojoModel"
class_hash = "0x45656207de5a881cc24e8422f388168c9ae35d0a48f05bf6f6cceb011a90040"
original_class_hash = "0x45656207de5a881cc24e8422f388168c9ae35d0a48f05bf6f6cceb011a90040"
abi = "manifests/dev/base/abis/models/eternum-AcceptOrder-e6bad9d6.json"
tag = "eternum-AcceptOrder"
qualified_path = "eternum::systems::trade::contracts::trade_systems::trade_systems::accept_order"
manifest_name = "eternum-AcceptOrder-e6bad9d6"

[[members]]
name = "taker_id"
type = "ID"
key = true

[[members]]
name = "maker_id"
type = "ID"
key = true

[[members]]
name = "id"
type = "ID"
key = true

[[members]]
name = "trade_id"
type = "ID"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
