kind = "DojoModel"
class_hash = "0x2a63759152575e9a36473ace95c2a4407a060071a1a7f359436cfd8a1c5d779"
original_class_hash = "0x2a63759152575e9a36473ace95c2a4407a060071a1a7f359436cfd8a1c5d779"
abi = "manifests/dev/base/abis/models/eternum-HyperstructureContribution-3716a74e.json"
tag = "eternum-HyperstructureContribution"
qualified_path = "eternum::systems::hyperstructure::contracts::hyperstructure_systems::hyperstructure_contribution"
manifest_name = "eternum-HyperstructureContribution-3716a74e"

[[members]]
name = "id"
type = "ID"
key = true

[[members]]
name = "hyperstructure_entity_id"
type = "ID"
key = true

[[members]]
name = "contributor_entity_id"
type = "ID"
key = false

[[members]]
name = "contributions"
type = "Span<(u8, u128)>"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
