kind = "DojoModel"
class_hash = "0x29172dacb3dd362cc20767c3781b4c196c8b6b2b8573dfc5fa7a5b87e4d6bdd"
original_class_hash = "0x29172dacb3dd362cc20767c3781b4c196c8b6b2b8573dfc5fa7a5b87e4d6bdd"
abi = "manifests/dev/base/abis/models/eternum-RealmMaxLevelConfig-33033093.json"
tag = "eternum-RealmMaxLevelConfig"
qualified_path = "eternum::models::config::realm_max_level_config"
manifest_name = "eternum-RealmMaxLevelConfig-33033093"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "max_level"
type = "u8"
key = false
