kind = "DojoModel"
class_hash = "0x58c085d9137ca94e280411982fc7a7893c95fec43105b3c440ccf4327e9a7b3"
original_class_hash = "0x58c085d9137ca94e280411982fc7a7893c95fec43105b3c440ccf4327e9a7b3"
abi = "manifests/dev/base/abis/models/eternum-Season-1cbb8463.json"
tag = "eternum-Season"
qualified_path = "eternum::models::season::season"
manifest_name = "eternum-Season-1cbb8463"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "is_over"
type = "bool"
key = false
