kind = "DojoModel"
class_hash = "0x140edfbf70a998c4b6cefc9a637deeabefee1b2dfe581767a57a1bc7de564e7"
original_class_hash = "0x140edfbf70a998c4b6cefc9a637deeabefee1b2dfe581767a57a1bc7de564e7"
abi = "manifests/dev/base/abis/models/eternum-TravelStaminaCostConfig-3e06f929.json"
tag = "eternum-TravelStaminaCostConfig"
qualified_path = "eternum::models::config::travel_stamina_cost_config"
manifest_name = "eternum-TravelStaminaCostConfig-3e06f929"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "travel_type"
type = "u8"
key = true

[[members]]
name = "cost"
type = "u16"
key = false
