kind = "DojoModel"
class_hash = "0x623d07477446edc29388ecc016245bdefd89fdeb26dd4b57629d7ce046ecb51"
original_class_hash = "0x623d07477446edc29388ecc016245bdefd89fdeb26dd4b57629d7ce046ecb51"
abi = "manifests/dev/base/abis/models/eternum-EntityOwner-23cb1be3.json"
tag = "eternum-EntityOwner"
qualified_path = "eternum::models::owner::entity_owner"
manifest_name = "eternum-EntityOwner-23cb1be3"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "entity_owner_id"
type = "ID"
key = false
