kind = "DojoModel"
class_hash = "0x218edc3b30f31d235b93dd8d77bed9fe5522bd24a3ec7b501614f27855961e7"
original_class_hash = "0x218edc3b30f31d235b93dd8d77bed9fe5522bd24a3ec7b501614f27855961e7"
abi = "manifests/dev/base/abis/models/eternum-QuestConfig-2d5813dd.json"
tag = "eternum-QuestConfig"
qualified_path = "eternum::models::config::quest_config"
manifest_name = "eternum-QuestConfig-2d5813dd"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "production_material_multiplier"
type = "u16"
key = false
