kind = "DojoModel"
class_hash = "0x75686d0233619fb7526ac898b30dced192717fe4dbec5ca0ede59e679044156"
original_class_hash = "0x75686d0233619fb7526ac898b30dced192717fe4dbec5ca0ede59e679044156"
abi = "manifests/dev/base/abis/models/eternum-ResourceBridgeWhitelistConfig-3e87baae.json"
tag = "eternum-ResourceBridgeWhitelistConfig"
qualified_path = "eternum::models::config::resource_bridge_whitelist_config"
manifest_name = "eternum-ResourceBridgeWhitelistConfig-3e87baae"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = false
