kind = "DojoModel"
class_hash = "0x7a807fb79d3d7c5a5cf5fefd71ccfe07fed35bf000d2ca5fea788ca48aa52ec"
original_class_hash = "0x7a807fb79d3d7c5a5cf5fefd71ccfe07fed35bf000d2ca5fea788ca48aa52ec"
abi = "manifests/dev/base/abis/models/eternum-SettlementConfig-2830060d.json"
tag = "eternum-SettlementConfig"
qualified_path = "eternum::models::config::settlement_config"
manifest_name = "eternum-SettlementConfig-2830060d"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "angle_scaled"
type = "u128"
key = false

[[members]]
name = "center"
type = "u32"
key = false

[[members]]
name = "min_scaling_factor_scaled"
type = "u128"
key = false

[[members]]
name = "radius"
type = "u32"
key = false

[[members]]
name = "min_distance"
type = "u32"
key = false

[[members]]
name = "max_distance"
type = "u32"
key = false

[[members]]
name = "min_angle_increase"
type = "u64"
key = false

[[members]]
name = "max_angle_increase"
type = "u64"
key = false
