kind = "DojoModel"
class_hash = "0x385ea6b1356d7244904ca73c73d6f0ab12fce89262ef4cc933d2473f0b79540"
original_class_hash = "0x385ea6b1356d7244904ca73c73d6f0ab12fce89262ef4cc933d2473f0b79540"
abi = "manifests/dev/base/abis/models/eternum-ResourceCost-11ae7f37.json"
tag = "eternum-ResourceCost"
qualified_path = "eternum::models::resources::resource_cost"
manifest_name = "eternum-ResourceCost-11ae7f37"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = false

[[members]]
name = "amount"
type = "u128"
key = false
