kind = "DojoModel"
class_hash = "0x5bc4211276776ca351b922ea98afbfa59a1e5f58f6532266c2c33dc9407cd91"
original_class_hash = "0x5bc4211276776ca351b922ea98afbfa59a1e5f58f6532266c2c33dc9407cd91"
abi = "manifests/dev/base/abis/models/eternum-TravelFoodCostConfig-61ee69b5.json"
tag = "eternum-TravelFoodCostConfig"
qualified_path = "eternum::models::config::travel_food_cost_config"
manifest_name = "eternum-TravelFoodCostConfig-61ee69b5"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "unit_type"
type = "u8"
key = true

[[members]]
name = "explore_wheat_burn_amount"
type = "u128"
key = false

[[members]]
name = "explore_fish_burn_amount"
type = "u128"
key = false

[[members]]
name = "travel_wheat_burn_amount"
type = "u128"
key = false

[[members]]
name = "travel_fish_burn_amount"
type = "u128"
key = false
