kind = "DojoModel"
class_hash = "0x1d90651d732aa0ceae9a29d5e7a1ae9989c3251e845e6d2a620e64bccc51672"
original_class_hash = "0x1d90651d732aa0ceae9a29d5e7a1ae9989c3251e845e6d2a620e64bccc51672"
abi = "manifests/dev/base/abis/models/eternum-HyperstructureConfig-4dbe3083.json"
tag = "eternum-HyperstructureConfig"
qualified_path = "eternum::models::config::hyperstructure_config"
manifest_name = "eternum-HyperstructureConfig-4dbe3083"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "time_between_shares_change"
type = "u64"
key = false

[[members]]
name = "points_per_cycle"
type = "u128"
key = false

[[members]]
name = "points_for_win"
type = "u128"
key = false

[[members]]
name = "points_on_completion"
type = "u128"
key = false
