kind = "DojoModel"
class_hash = "0x146c13acba6a6e1a29289118ecab85721f682fcbda423a42900b7eedbf2f220"
original_class_hash = "0x146c13acba6a6e1a29289118ecab85721f682fcbda423a42900b7eedbf2f220"
abi = "manifests/dev/base/abis/models/eternum-StaminaConfig-b6eb17a7.json"
tag = "eternum-StaminaConfig"
qualified_path = "eternum::models::config::stamina_config"
manifest_name = "eternum-StaminaConfig-b6eb17a7"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "unit_type"
type = "u8"
key = true

[[members]]
name = "max_stamina"
type = "u16"
key = false
