kind = "DojoModel"
class_hash = "0x237660871af08d763a54aeccaa32e51b48964161a4b3f3378811f3ef80bab1e"
original_class_hash = "0x237660871af08d763a54aeccaa32e51b48964161a4b3f3378811f3ef80bab1e"
abi = "manifests/dev/base/abis/models/eternum-BuildingGeneralConfig-268eab05.json"
tag = "eternum-BuildingGeneralConfig"
qualified_path = "eternum::models::config::building_general_config"
manifest_name = "eternum-BuildingGeneralConfig-268eab05"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "base_cost_percent_increase"
type = "u16"
key = false
