kind = "DojoModel"
class_hash = "0x4d01df1c91f9d1d0a346d78c1704472e3fdb0e8545d0c756883fefb59f45ba8"
original_class_hash = "0x4d01df1c91f9d1d0a346d78c1704472e3fdb0e8545d0c756883fefb59f45ba8"
abi = "manifests/dev/base/abis/models/eternum-Bank-522579aa.json"
tag = "eternum-Bank"
qualified_path = "eternum::models::bank::bank::bank"
manifest_name = "eternum-Bank-522579aa"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "owner_fee_num"
type = "u128"
key = false

[[members]]
name = "owner_fee_denom"
type = "u128"
key = false

[[members]]
name = "owner_bridge_fee_dpt_percent"
type = "u16"
key = false

[[members]]
name = "owner_bridge_fee_wtdr_percent"
type = "u16"
key = false

[[members]]
name = "exists"
type = "bool"
key = false
