kind = "DojoModel"
class_hash = "0x5ad780711bc43d85052654d4e16f3d5570193f6f5782f9586498280a3b89034"
original_class_hash = "0x5ad780711bc43d85052654d4e16f3d5570193f6f5782f9586498280a3b89034"
abi = "manifests/dev/base/abis/models/eternum-AddressName-48fbe026.json"
tag = "eternum-AddressName"
qualified_path = "eternum::models::name::address_name"
manifest_name = "eternum-AddressName-48fbe026"

[[members]]
name = "address"
type = "felt252"
key = true

[[members]]
name = "name"
type = "felt252"
key = false
