kind = "DojoModel"
class_hash = "0x3c386d7cfcd041771f3c6d33090470f44544c144d991db506a19030e5ea3e05"
original_class_hash = "0x3c386d7cfcd041771f3c6d33090470f44544c144d991db506a19030e5ea3e05"
abi = "manifests/dev/base/abis/models/eternum-HyperstructureResourceConfig-34106fab.json"
tag = "eternum-HyperstructureResourceConfig"
qualified_path = "eternum::models::config::hyperstructure_resource_config"
manifest_name = "eternum-HyperstructureResourceConfig-34106fab"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = true

[[members]]
name = "amount_for_completion"
type = "u128"
key = false
