kind = "DojoModel"
class_hash = "0x60b36f17aaa0fb71dc0447628271b540ed030ded7ddf02492946e408b56570b"
original_class_hash = "0x60b36f17aaa0fb71dc0447628271b540ed030ded7ddf02492946e408b56570b"
abi = "manifests/dev/base/abis/models/eternum-SeasonConfig-54d48f16.json"
tag = "eternum-SeasonConfig"
qualified_path = "eternum::models::config::season_config"
manifest_name = "eternum-SeasonConfig-54d48f16"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "season_pass_address"
type = "ContractAddress"
key = false

[[members]]
name = "realms_address"
type = "ContractAddress"
key = false

[[members]]
name = "lords_address"
type = "ContractAddress"
key = false
