kind = "DojoModel"
class_hash = "0x156d3465e59d43f281eb13a991f9ff4ba846e1411dd66accd5629544517e1bc"
original_class_hash = "0x156d3465e59d43f281eb13a991f9ff4ba846e1411dd66accd5629544517e1bc"
abi = "manifests/dev/base/abis/models/eternum-EternumEvent-109355df.json"
tag = "eternum-EternumEvent"
qualified_path = "eternum::models::event::eternum_event"
manifest_name = "eternum-EternumEvent-109355df"

[[members]]
name = "id"
type = "ID"
key = true

[[members]]
name = "event_id"
type = "EventType"
key = true

[[members]]
name = "timestamp"
type = "u64"
key = false
