# Realms dev appchain (AWS, chain id WP_REALMS_DEV) — see docs/plans/appchain-phase-1.md
[namespace]
default = "s2_blitz"

[lib_versions]
"s2_blitz-combat_library" = "0_1_14"
"s2_blitz-raid_library" = "0_1_0"
"s2_blitz-rng_library" = "0_1_16"
"s2_blitz-biome_library" = "0_1_13"
"s2_blitz-structure_creation_library" = "0_1_18"


[env]
rpc_url = "http://Realms-Alb16-vyiZTcVBQthr-325094656.us-east-1.elb.amazonaws.com"

[world]
seed = "s2_blitz_aws_1"
name = "Realms: Eternum"
description = "Rule the Hex"
cover_uri = "file://assets/bg.webp"
website = "https://alpha-eternum.realms.world/"

[writers]
"s2_blitz" = [
    "s2_blitz-agent_discovery_systems",
    "s2_blitz-alt_movement_systems",
    "s2_blitz-artificer_systems",
    "s2_blitz-blitz_realm_systems",
    "s2_blitz-camp_discovery_systems",
    "s2_blitz-guild_systems",
    "s2_blitz-hyperstructure_create_systems",
    "s2_blitz-hyperstructure_discovery_systems",
    "s2_blitz-hyperstructure_systems",
    "s2_blitz-mmr_systems",
    "s2_blitz-name_systems",
    "s2_blitz-ownership_systems",
    "s2_blitz-point_systems",
    "s2_blitz-prize_distribution_systems",
    "s2_blitz-production_systems",
    "s2_blitz-realm_internal_systems",
    "s2_blitz-registrar_systems",
    "s2_blitz-relic_chest_discovery_systems",
    "s2_blitz-relic_systems",
    "s2_blitz-resource_systems",
    "s2_blitz-structure_systems",
    "s2_blitz-troop_battle_systems",
    "s2_blitz-troop_management_systems",
    "s2_blitz-troop_movement_systems",
    "s2_blitz-troop_movement_util_systems",
]
