# Game world on the shared Realms appchain.
[namespace]
default = "s2"

[lib_versions]
"s2-combat_library" = "0_1_14"
"s2-raid_library" = "0_1_0"
"s2-rng_library" = "0_1_16"
"s2-biome_library" = "0_1_13"
"s2-structure_creation_library" = "0_1_18"

[env]
rpc_url = "http://Realms-Alb16-vyiZTcVBQthr-325094656.us-east-1.elb.amazonaws.com"

[world]
seed = "s2_eternum_1"
name = "Realms: Eternum"
description = "Persistent Realms seasons"
cover_uri = "file://assets/bg.webp"
website = "https://alpha-eternum.realms.world/"

[writers]
"s2" = [
    "s2-agent_discovery_systems",
    "s2-alt_movement_systems",
    "s2-artificer_systems",
    "s2-blitz_realm_systems",
    "s2-camp_discovery_systems",
    "s2-guild_systems",
    "s2-hyperstructure_create_systems",
    "s2-hyperstructure_discovery_systems",
    "s2-hyperstructure_systems",
    "s2-mmr_systems",
    "s2-name_systems",
    "s2-ownership_systems",
    "s2-point_systems",
    "s2-prize_distribution_systems",
    "s2-production_systems",
    "s2-realm_internal_systems",
    "s2-registrar_systems",
    "s2-relic_chest_discovery_systems",
    "s2-relic_systems",
    "s2-resource_systems",
    "s2-structure_systems",
    "s2-troop_battle_systems",
    "s2-troop_management_systems",
    "s2-troop_movement_systems",
    "s2-troop_movement_util_systems",
]
