[namespace]
default = "s1_eternum"

[env]
account_address = "0x01BFC84464f990C09Cc0e5D64D18F54c3469fD5c467398BF31293051bAde1C39"
private_key = "0x075362a844768f31c8058ce31aec3dd7751686440b4f220f410ae0c9bf042e60"
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"

[world]
seed = "eternum-sepolia-quest.2"
name = "Eternum Sepolia"
description = "Rule the Hex"
cover_uri = "file://assets/bg.webp"
website = "https://eternum.realms.world/"

[writers]
"s1_eternum" = [
    "s1_eternum-bank_systems",
    "s1_eternum-structure_systems",
    "s1_eternum-production_systems",
    "s1_eternum-config_systems",
    "s1_eternum-dev_resource_systems",
    "s1_eternum-guild_systems",
    "s1_eternum-hyperstructure_systems",
    "s1_eternum-liquidity_systems",
    "s1_eternum-name_systems",
    "s1_eternum-ownership_systems",
    "s1_eternum-realm_systems",
	"s1_eternum-realm_internal_systems",
    "s1_eternum-resource_bridge_systems",
    "s1_eternum-resource_systems",
    "s1_eternum-swap_systems",
    "s1_eternum-trade_systems",
    "s1_eternum-troop_management_systems",
	"s1_eternum-troop_battle_systems",
	"s1_eternum-troop_raid_systems",
    "s1_eternum-troop_movement_systems",
    "s1_eternum-troop_movement_util_systems",
    "s1_eternum-agent_discovery_systems",
    "s1_eternum-hyperstructure_discovery_systems",
    "s1_eternum-mine_discovery_systems",
	"s1_eternum-season_systems",
	"s1_eternum-village_systems",
	"s1_eternum-quest_systems"
]