[namespace]
default = "s1_eternum"

[env]
## local
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
rpc_url = "https://api.cartridge.gg/x/slot-real-cave/katana"

[world]
seed = "s1_eternum"
name = "Realms: Eternum"
description = "Rule the Hex"
cover_uri = "file://assets/bg.webp"
website = "https://alpha-eternum.realms.world/"

[writers]
"s1_eternum" = [
	"s1_eternum-bank_systems",
	"s1_eternum-structure_systems",
	"s1_eternum-production_systems",
	"s1_eternum-config_systems",
	"s1_eternum-dev_resource_systems",
	"s1_eternum-guild_systems",
	"s1_eternum-hyperstructure_systems",
	"s1_eternum-liquidity_systems",
	"s1_eternum-name_systems",
	"s1_eternum-ownership_systems",
	"s1_eternum-realm_systems",
	"s1_eternum-resource_bridge_systems",
	"s1_eternum-resource_systems",
	"s1_eternum-swap_systems",
	"s1_eternum-trade_systems",
	"s1_eternum-troop_management_systems",
	"s1_eternum-troop_battle_systems",
	"s1_eternum-troop_raid_systems",
    "s1_eternum-troop_movement_systems",
    "s1_eternum-troop_movement_util_systems",
	"s1_eternum-season_systems",
	"s1_eternum-village_systems",
    "s1_eternum-quest_systems"
]

# Adjust according to slot config
[init_call_args]
"s1_eternum-quest_systems" = [
    # --- game_list: Array<QuestGame> ---
    "0x2", # N: Total number of games = 2

    # --- QuestGame[0] ---
    "0x12345", # game_address for Game 1
    "0x3",              # M_1: Number of levels for Game 1 = 3

    # LevelConfig[0] for Game 1
    "0x64", # target_score = 100 (hex)
    "0x1",  # settings_id = 1
    "14400", # time_limit = 4hrs

    # LevelConfig[1] for Game 1
    "0xfa", # target_score = 250 (hex)
    "0x2",  # settings_id = 2
    "14400", # time_limit = 4hrs

    # LevelConfig[2] for Game 1
    "0x1f4",# target_score = 500 (hex)
    "0x3",  # settings_id = 3
    "14400", # time_limit = 4hrs

    # --- QuestGame[1] ---
    "0x123456", # game_address for Game 2
    "0x1",              # M_2: Number of levels for Game 2 = 1
    # LevelConfig[0] for Game 2
    "0x32", # target_score = 50 (hex)
    "0xa",   # settings_id = 10 (hex)
    "14400", # time_limit = 4hrs
]