# Please be mindful that changing the content of this file will impact the Eternum Launcher app

rpc = "http://127.0.0.1:5050"

world_address = "0x51ee71bcf98cdcba52e97f0b98294e99e0c94fa79dade5b004703cf48231b74"

db_dir = "torii-local"

[indexing]
events_chunk_size = 1024  # Size of events page to fetch
blocks_chunk_size = 10240 # Blocks to process before DB commit

pending = true # Enable indexing pending blocks

polling_interval = 500 # Polling interval in milliseconds

max_concurrent_tasks = 100 # Maximum concurrent indexing tasks

transactions = true

contracts = [
      "erc721:0x7dd66b571624e0f306ecb241de88fd16d8c22982d97cf82e5832dab851675bf",
      "erc721:0x1178358da69dc2aa9e1754804de02c240d1cdc2eaa0ff86c8ecf74219225d15",
      "erc20:0x4d019ffb00bf80d98147738bc2c08af7c33cf9c9c737d1ea76e3bf64e3f3db0",
]

namespaces = ["s1_eternum"]

world_block = 0

[sql]
all_model_indices = false
model_indices = [] # TODO(tedison): add model indices, for now there's NO indices in the database
historical = ["s1_eternum-TrophyCreation", "s1_eternum-TrophyProgression"]
cache_size = -500_000 # 512MB of cache size, we can tune this up if needed. This should account for between 30%-80% of the RAM of the slot instance.
page_size = 32_768

[server]
http_cors_origins = ["*"]

[events]
raw = false
