# Please be mindful that changing the content of this file will impact the Eternum Launcher app

rpc = "https://api.cartridge.gg/x/starknet/sepolia"

world_address = "0x7113b2a40ebedb0f0508bfdfc86ae574bab7bb4e84ce38564edad4f777ab7d8"

db_dir = "torii-sepolia"

[indexing]
events_chunk_size = 1024  # Size of events page to fetch
blocks_chunk_size = 10240 # Blocks to process before DB commit

pending = true # Enable indexing pending blocks

polling_interval = 500 # Polling interval in milliseconds

max_concurrent_tasks = 100 # Maximum concurrent indexing tasks

transactions = true

contracts = [
    "erc721:0x4430e9e7b6ad7fbc1b40d85c8166880bd0811f37af3293ba8d19d8052b01db",
    "erc721:0x571531ea5ab11e9fb0f1589139c72c93f474dd774cfda1be361be09ae8d5120",
	"erc721:0x41daa0003c33c8e45b6ead4dec35dc02970413f970f8155ccaf5cfe8286b74e",
    "erc20:0x2e1704aa180dd8094625bc1424ddde8461357ee86618ade4e1429104c38dd43",
]

namespaces = ["s1_eternum"]

world_block = 0

[sql]
all_model_indices = false
model_indices = [
	{ model_tag = "s1_eternum-ResourceList", fields = ["amount"]},
	{ model_tag = "s1_eternum-ExplorerTroops", fields = ["owner", "coord.x", "coord.y"]},
	{ model_tag = "s1_eternum-Structure", fields = ["category", "base.coord_x", "base.coord_y", "metadata.villages_count", "metadata.realm_id", "owner"]},
	{ model_tag = "s1_eternum-Tile", fields = ["col", "row"] },
]
historical = ["s1_eternum-TrophyProgression"]
cache_size = -500_000 # 512MB of cache size, we can tune this up if needed. This should account for between 30%-80% of the RAM of the slot instance.
page_size = 32_768

[server]
http_cors_origins = ["*"]

[events]
raw = false
