# db_dir = "./torii-db"

[indexing]

events_chunk_size = 1024 # Size of events page to fetch
blocks_chunk_size = 10240 # Blocks to process before DB commit
pending = true # Enable indexing pending blocks
polling_interval = 500 # Polling interval in milliseconds
max_concurrent_tasks = 100 # Maximum concurrent indexing tasks
world_block = 0
contracts = [
      "erc721:0x1a9987eb1be35180f1dbe9218625ff646770e5dc4787634cfe2f186d0a0d6aa",
      "erc721:0x39affcb9aac0e66136c2975cd6be79df73ea1da6e0e7b6f5b6b04c0646bd334",
      "erc20:0x2ec84dee27696005b64602713e09fdd22c9a5b6ffe4132f6e4a5ce3dd5119c4",
]

[events]
raw = false

[sql]
historical = ["s1_eternum-TrophyCreation", "s1_eternum-TrophyProgression"]
