# Please be mindful that changing the content of this file will impact the Eternum Launcher app

rpc = "https://api.cartridge.gg/x/starknet/mainnet"

world_address = "0x0009dd5e66cfa83f893c2a70b9ea5221e2df18aaf52a111fe9003264f948c7aa"

db_dir = "torii-mainnet"

[indexing]
events_chunk_size = 1024  # Size of events page to fetch
blocks_chunk_size = 10240 # Blocks to process before DB commit

pending = true # Enable indexing pending blocks

polling_interval = 500 # Polling interval in milliseconds

max_concurrent_tasks = 100 # Maximum concurrent indexing tasks

transactions = true

contracts = [
	"erc721:0x057675b9c0bd62b096a2e15502a37b290fa766ead21c33eda42993e48a714b80",
	"erc721:0x07ae27a31bb6526e3de9cf02f081f6ce0615ac12a6d7b85ee58b8ad7947a2809",
	"erc20:0x0124aeb495b947201f5fac96fd1138e326ad86195b98df6dec9009158a533b49",
]

namespaces = ["s1_eternum"]

world_block = 940000

[sql]
all_model_indices = false
model_indices = [
	{ model_tag = "s1_eternum-ResourceList", fields = ["amount"]},
	{ model_tag = "s1_eternum-ExplorerTroops", fields = ["owner"]},
]
historical = ["s1_eternum-TrophyCreation", "s1_eternum-TrophyProgression"]
cache_size = -78_125_000 # 10GB of cache size, we can tune this up if needed. This should account for between 30%-80% of the RAM of the slot instance. 10GB is 50% of an insane slot instance's RAM.
page_size = 32_768

[server]
http_cors_origins = ["*"]

[events]
raw = false