# Please be mindful that changing the content of this file will impact the Eternum Launcher app

rpc = "https://api.cartridge.gg/x/starknet/sepolia"

world_address = "0x395bcaaecad6257cdedb4defc6392f61bc6c03e18b5434657c1229f0bb54f18"

db_dir = "torii-sepolia"

[indexing]
events_chunk_size = 1024  # Size of events page to fetch
blocks_chunk_size = 10240 # Blocks to process before DB commit

pending = true # Enable indexing pending blocks

polling_interval = 500 # Polling interval in milliseconds

max_concurrent_tasks = 100 # Maximum concurrent indexing tasks

transactions = true

contracts = [
    "erc721:0x4c65504c7e7df16928cc1e8e476e6f8ea6e4f56cdef7f6b51eac014c19c1fd2",
    "erc721:0x1948e239f559bcbdf9388938a3c46bc79f52bcba7c4d5c9732568cb8eb6a53d",
    "erc20:0x43da677785217130c6c9d82cea88ca19e098387d664774986ccdcc6162611bd",
]

namespaces = ["s1_eternum"]

world_block = 0

[sql]
all_model_indices = false
model_indices = [
	{ model_tag = "s1_eternum-ResourceList", fields = ["amount"]},
	{ model_tag = "s1_eternum-ExplorerTroops", fields = ["owner", "coord.x", "coord.y"]},
	{ model_tag = "s1_eternum-Structure", fields = ["category", "base.coord_x", "base.coord_y", "metadata.villages_count", "metadata.realm_id", "owner"]},
	{ model_tag = "s1_eternum-Tile", fields = ["col", "row"] },
]
historical = ["s1_eternum-TrophyCreation", "s1_eternum-TrophyProgression"]
cache_size = -78_125_000 # 10GB of cache size, we can tune this up if needed. This should account for between 30%-80% of the RAM of the slot instance. 10GB is 50% of an insane slot instance's RAM.
page_size = 32_768

[server]
http_cors_origins = ["*"]

[events]
raw = false