/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollectionRouteImport } from './routes/$collection'
import { Route as TradeCollectionRouteRouteImport } from './routes/trade/$collection/route'

const MintLazyRouteImport = createFileRoute('/mint')()
const DataLazyRouteImport = createFileRoute('/data')()
const IndexLazyRouteImport = createFileRoute('/')()
const TradeIndexLazyRouteImport = createFileRoute('/trade/')()
const TradeActivityLazyRouteImport = createFileRoute('/trade/activity')()
const TradeCollectionIndexLazyRouteImport = createFileRoute(
  '/trade/$collection/',
)()
const TradeCollectionActivityLazyRouteImport = createFileRoute(
  '/trade/$collection/activity',
)()
const TradeCollectionTokenIdLazyRouteImport = createFileRoute(
  '/trade/$collection/$tokenId',
)()

const MintLazyRoute = MintLazyRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/mint.lazy').then((d) => d.Route))
const DataLazyRoute = DataLazyRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/data.lazy').then((d) => d.Route))
const CollectionRoute = CollectionRouteImport.update({
  id: '/$collection',
  path: '/$collection',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/$collection.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TradeIndexLazyRoute = TradeIndexLazyRouteImport.update({
  id: '/trade/',
  path: '/trade/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/trade/index.lazy').then((d) => d.Route))
const TradeActivityLazyRoute = TradeActivityLazyRouteImport.update({
  id: '/trade/activity',
  path: '/trade/activity',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/trade/activity.lazy').then((d) => d.Route),
)
const TradeCollectionRouteRoute = TradeCollectionRouteRouteImport.update({
  id: '/trade/$collection',
  path: '/trade/$collection',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeCollectionIndexLazyRoute =
  TradeCollectionIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TradeCollectionRouteRoute,
  } as any).lazy(() =>
    import('./routes/trade/$collection/index.lazy').then((d) => d.Route),
  )
const TradeCollectionActivityLazyRoute =
  TradeCollectionActivityLazyRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => TradeCollectionRouteRoute,
  } as any).lazy(() =>
    import('./routes/trade/$collection/activity.lazy').then((d) => d.Route),
  )
const TradeCollectionTokenIdLazyRoute =
  TradeCollectionTokenIdLazyRouteImport.update({
    id: '/$tokenId',
    path: '/$tokenId',
    getParentRoute: () => TradeCollectionRouteRoute,
  } as any).lazy(() =>
    import('./routes/trade/$collection/$tokenId.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$collection': typeof CollectionRoute
  '/data': typeof DataLazyRoute
  '/mint': typeof MintLazyRoute
  '/trade/$collection': typeof TradeCollectionRouteRouteWithChildren
  '/trade/activity': typeof TradeActivityLazyRoute
  '/trade': typeof TradeIndexLazyRoute
  '/trade/$collection/$tokenId': typeof TradeCollectionTokenIdLazyRoute
  '/trade/$collection/activity': typeof TradeCollectionActivityLazyRoute
  '/trade/$collection/': typeof TradeCollectionIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$collection': typeof CollectionRoute
  '/data': typeof DataLazyRoute
  '/mint': typeof MintLazyRoute
  '/trade/activity': typeof TradeActivityLazyRoute
  '/trade': typeof TradeIndexLazyRoute
  '/trade/$collection/$tokenId': typeof TradeCollectionTokenIdLazyRoute
  '/trade/$collection/activity': typeof TradeCollectionActivityLazyRoute
  '/trade/$collection': typeof TradeCollectionIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/$collection': typeof CollectionRoute
  '/data': typeof DataLazyRoute
  '/mint': typeof MintLazyRoute
  '/trade/$collection': typeof TradeCollectionRouteRouteWithChildren
  '/trade/activity': typeof TradeActivityLazyRoute
  '/trade/': typeof TradeIndexLazyRoute
  '/trade/$collection/$tokenId': typeof TradeCollectionTokenIdLazyRoute
  '/trade/$collection/activity': typeof TradeCollectionActivityLazyRoute
  '/trade/$collection/': typeof TradeCollectionIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$collection'
    | '/data'
    | '/mint'
    | '/trade/$collection'
    | '/trade/activity'
    | '/trade'
    | '/trade/$collection/$tokenId'
    | '/trade/$collection/activity'
    | '/trade/$collection/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$collection'
    | '/data'
    | '/mint'
    | '/trade/activity'
    | '/trade'
    | '/trade/$collection/$tokenId'
    | '/trade/$collection/activity'
    | '/trade/$collection'
  id:
    | '__root__'
    | '/'
    | '/$collection'
    | '/data'
    | '/mint'
    | '/trade/$collection'
    | '/trade/activity'
    | '/trade/'
    | '/trade/$collection/$tokenId'
    | '/trade/$collection/activity'
    | '/trade/$collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CollectionRoute: typeof CollectionRoute
  DataLazyRoute: typeof DataLazyRoute
  MintLazyRoute: typeof MintLazyRoute
  TradeCollectionRouteRoute: typeof TradeCollectionRouteRouteWithChildren
  TradeActivityLazyRoute: typeof TradeActivityLazyRoute
  TradeIndexLazyRoute: typeof TradeIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mint': {
      id: '/mint'
      path: '/mint'
      fullPath: '/mint'
      preLoaderRoute: typeof MintLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$collection': {
      id: '/$collection'
      path: '/$collection'
      fullPath: '/$collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/': {
      id: '/trade/'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/activity': {
      id: '/trade/activity'
      path: '/trade/activity'
      fullPath: '/trade/activity'
      preLoaderRoute: typeof TradeActivityLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$collection': {
      id: '/trade/$collection'
      path: '/trade/$collection'
      fullPath: '/trade/$collection'
      preLoaderRoute: typeof TradeCollectionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$collection/': {
      id: '/trade/$collection/'
      path: '/'
      fullPath: '/trade/$collection/'
      preLoaderRoute: typeof TradeCollectionIndexLazyRouteImport
      parentRoute: typeof TradeCollectionRouteRoute
    }
    '/trade/$collection/activity': {
      id: '/trade/$collection/activity'
      path: '/activity'
      fullPath: '/trade/$collection/activity'
      preLoaderRoute: typeof TradeCollectionActivityLazyRouteImport
      parentRoute: typeof TradeCollectionRouteRoute
    }
    '/trade/$collection/$tokenId': {
      id: '/trade/$collection/$tokenId'
      path: '/$tokenId'
      fullPath: '/trade/$collection/$tokenId'
      preLoaderRoute: typeof TradeCollectionTokenIdLazyRouteImport
      parentRoute: typeof TradeCollectionRouteRoute
    }
  }
}

interface TradeCollectionRouteRouteChildren {
  TradeCollectionTokenIdLazyRoute: typeof TradeCollectionTokenIdLazyRoute
  TradeCollectionActivityLazyRoute: typeof TradeCollectionActivityLazyRoute
  TradeCollectionIndexLazyRoute: typeof TradeCollectionIndexLazyRoute
}

const TradeCollectionRouteRouteChildren: TradeCollectionRouteRouteChildren = {
  TradeCollectionTokenIdLazyRoute: TradeCollectionTokenIdLazyRoute,
  TradeCollectionActivityLazyRoute: TradeCollectionActivityLazyRoute,
  TradeCollectionIndexLazyRoute: TradeCollectionIndexLazyRoute,
}

const TradeCollectionRouteRouteWithChildren =
  TradeCollectionRouteRoute._addFileChildren(TradeCollectionRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CollectionRoute: CollectionRoute,
  DataLazyRoute: DataLazyRoute,
  MintLazyRoute: MintLazyRoute,
  TradeCollectionRouteRoute: TradeCollectionRouteRouteWithChildren,
  TradeActivityLazyRoute: TradeActivityLazyRoute,
  TradeIndexLazyRoute: TradeIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
