const defaultTheme = require("tailwindcss/defaultTheme");
const colors = require("tailwindcss/colors");

/** @type {import('tailwindcss').Config} */
export default {
  presets: [require("../../default.js")],
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "sm:col-span-1",
    "sm:col-span-2",
    "sm:col-span-3",
    "sm:col-span-4",
    "sm:col-span-5",
    "sm:col-span-6",
    "sm:col-span-7",
    "sm:col-span-8",
    "sm:col-span-9",
    "sm:col-span-10",
    "sm:col-span-11",
    "sm:col-span-12",
    "md:col-span-1",
    "md:col-span-2",
    "md:col-span-3",
    "md:col-span-4",
    "md:col-span-5",
    "md:col-span-6",
    "md:col-span-7",
    "md:col-span-8",
    "md:col-span-9",
    "md:col-span-10",
    "md:col-span-11",
    "md:col-span-12",
    "lg:col-span-1",
    "lg:col-span-2",
    "lg:col-span-3",
    "lg:col-span-4",
    "lg:col-span-5",
    "lg:col-span-6",
    "lg:col-span-7",
    "lg:col-span-8",
    "lg:col-span-9",
    "lg:col-span-10",
    "lg:col-span-11",
    "lg:col-span-12",
    "xl:col-span-1",
    "xl:col-span-2",
    "xl:col-span-3",
    "xl:col-span-4",
    "xl:col-span-5",
    "xl:col-span-6",
    "xl:col-span-7",
    "xl:col-span-8",
    "xl:col-span-9",
    "xl:col-span-10",
    "xl:col-span-11",
    "xl:col-span-12",
    "sm:row-span-1",
    "sm:row-span-2",
    "sm:row-span-3",
    "sm:row-span-4",
    "sm:row-span-5",
    "sm:row-span-6",
    "md:row-span-1",
    "md:row-span-2",
    "md:row-span-3",
    "md:row-span-4",
    "md:row-span-5",
    "md:row-span-6",
    "lg:row-span-1",
    "lg:row-span-2",
    "lg:row-span-3",
    "lg:row-span-4",
    "lg:row-span-5",
    "lg:row-span-6",
    "xl:row-span-1",
    "xl:row-span-2",
    "xl:row-span-3",
    "xl:row-span-4",
    "xl:row-span-5",
    "xl:row-span-6",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "dark-wood": "url(/images/textures/dark-wood.png)",
      },
      fontFamily: {
        sans: ["Goudy Bookletter 1911", ...defaultTheme.fontFamily.sans],
        heading: ["Cinzel", ...defaultTheme.fontFamily.sans],
        number: ["Anonymous Pro", ...defaultTheme.fontFamily.mono],
      },
      fontSize: {
        xxs: ".625rem",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      animation: {
        border: "border 4s linear infinite",
      },
      keyframes: {
        border: {
          to: { "--border-angle": "360deg" },
        },
      },
      colors: {
        // Add only the specific colors used in the components
        white: colors.white,
        black: colors.black,
        gray: {
          100: colors.gray[100],
          200: colors.gray[200],
          300: colors.gray[300],
          400: colors.gray[400],
          500: colors.gray[500],
          600: colors.gray[600],
          700: colors.gray[700],
          800: colors.gray[800],
          900: colors.gray[900],
        },
        slate: {
          600: "#6b5b47", // Medium warm brown-gray
          700: "#5a4a38", // Dark warm brown-gray  
          800: "#4a3a2a", // Very dark warm brown
          900: "#3a2a1c", // Almost black warm brown
        },
        blue: {
          500: colors.blue[500],
          600: colors.blue[600],
        },
        green: {
          500: colors.green[500],
          600: colors.green[600],
        },
        purple: {
          500: colors.purple[500],
          600: colors.purple[600],
        },
        orange: {
          500: colors.orange[500],
        },
        red: {
          500: colors.red[500],
        },
        yellow: {
          600: colors.yellow[600],
        },
        // Custom color for chest title
        "chest-gold": "#dfaa54",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        transparent: "transparent",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        rarity: {
          common: "#848484",
          uncommon: "#6cc95e",
          rare: "#56c8da",
          epic: "#ba37d4",
          legendary: "#e9b062",
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
