from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Sequence

try:
    from .git_utils import Commit
    from .issues import IssueAlert
    from .summary import ModelDigest
except ImportError:  # pragma: no cover - fallback for script execution
    from git_utils import Commit  # type: ignore
    from issues import IssueAlert  # type: ignore
    from summary import ModelDigest  # type: ignore


def _format_issue_links(alert: IssueAlert) -> str:
    links: list[str] = []
    for issue in alert.issues:
        label = f"#{issue.number}"
        if issue.url:
            label = f"[{label}]({issue.url})"
        if issue.title:
            label = f"{label} – {issue.title}"
        links.append(label)
    return "<br>".join(links)


def build_markdown(
    branch: str,
    digest: ModelDigest,
    commits: Sequence[Commit],
    *,
    issue_alerts: Sequence[IssueAlert] | None = None,
) -> str:
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []
    lines.append(f"# Daily Engineering Digest – {branch}")
    lines.append("")
    lines.append(f"_Generated on {generated_at}_")
    lines.append("")

    if digest.overview:
        lines.append("## Highlights")
        for item in digest.overview:
            lines.append(f"- {item}")
        lines.append("")

    if digest.authors:
        lines.append("## Contributor Spotlight")
        lines.append("| Author | Summary | Commits |")
        lines.append("| --- | --- | --- |")
        for author in digest.authors:
            commits_joined = "<br>".join(author.commits) if author.commits else "—"
            summary = author.summary or "—"
            lines.append(f"| {author.name} | {summary} | {commits_joined} |")
        lines.append("")

    if issue_alerts:
        lines.append("## Assigned Issues")
        lines.append("| Assignee | Issues |")
        lines.append("| --- | --- |")
        for alert in issue_alerts:
            issue_links = _format_issue_links(alert) or "—"
            assignee_label = f"{alert.github_login} ({alert.discord_mention})"
            lines.append(f"| {assignee_label} | {issue_links} |")
        lines.append("")

    if digest.callouts:
        lines.append("## Callouts")
        for item in digest.callouts:
            lines.append(f"- {item}")
        lines.append("")

    if commits:
        lines.append("## Commit Log")
        for commit in commits:
            lines.append(
                f"- `{commit.short_sha}` ({commit.author}, {commit.authored_at.strftime('%Y-%m-%d %H:%M')}) – {commit.title}"
            )
            if commit.files:
                files_preview = ", ".join(commit.files[:6])
                lines.append(f"  - Files: {files_preview}")
            if commit.body:
                first_line = commit.body.splitlines()[0].strip()
                if first_line:
                    lines.append(f"  - Notes: {first_line}")
        lines.append("")

    lines.append("---")
    lines.append(
        "Generated by `.github/commit_digest` using OpenAI summarization and posted to Discord."
    )
    return "\n".join(lines)


def write_markdown(content: str, output_directory: Path, *, filename: str | None = None) -> Path:
    output_directory.mkdir(parents=True, exist_ok=True)
    if not filename:
        filename = f"daily-digest-{datetime.utcnow().strftime('%Y%m%d')}.md"
    destination = output_directory / filename
    destination.write_text(content, encoding="utf-8")
    return destination


__all__ = [
    "build_markdown",
    "write_markdown",
]
