"""Generate the immutable gameplay traits from the bundled 8,000 realm metadata records."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "packages/core/src/data/full-realms.json"
MAPPINGS = ROOT / "contracts/l3/game/src/models/realm.cairo"
TARGET = ROOT / "contracts/l3/game/src/systems/utils/realm_metadata.cairo"


def reference_mapping(name):
    section = MAPPINGS.read_text().split(f"fn {name}_mapping(", 1)[1].split("\n    fn ", 1)[0]
    return {label: int(number) for number, label in re.findall(r'(\d+) => "([^"\n]+)"', section)}


def generate():
    realms = json.loads(SOURCE.read_text())
    assert set(realms) == {str(i) for i in range(1, 8001)}, "Expected all 8000 canonical realms"
    resources = reference_mapping("resource")
    orders = reference_mapping("order")
    wonders = reference_mapping("wonder")
    packed = []
    for realm_id in range(1, 8001):
        attributes = realms[str(realm_id)]["attributes"]
        mask = sum(1 << (resources[a["value"]] - 1) for a in attributes if a["trait_type"] == "Resource")
        order = next(orders[a["value"]] for a in attributes if a["trait_type"] == "Order")
        wonder = next((wonders[a["value"]] for a in attributes if a["trait_type"] == "Wonder (translated)"), 1)
        assert mask > 0 and mask < (1 << 22) and 1 <= order <= 16 and 1 <= wonder <= 63
        packed.append(mask | ((order - 1) << 22) | (wonder << 26))
    chunks = [sum(value << (32 * offset) for offset, value in enumerate(packed[index:index + 7])) for index in range(0, len(packed), 7)]
    for index, expected in enumerate(packed):
        assert (chunks[index // 7] >> (32 * (index % 7))) & 0xffffffff == expected
    literals = ",\n".join(f"    0x{value:x}" for value in chunks)
    return f"""// Generated by scripts/generate-realm-metadata.py from packages/core/src/data/full-realms.json.
// Seven 32-bit records per felt: 22 resource bits, four Order bits, six wonder bits.
use alexandria_math::BitShift;

const REALM_TRAITS: [felt252; {len(chunks)}] = [
{literals},
];

pub fn realm_attributes(realm_id: u32) -> (u8, u8, Array<u8>) {{
    assert!(realm_id >= 1 && realm_id <= 8000, "Eternum: invalid canonical realm id");
    let index = realm_id - 1;
    let chunk: u256 = (*REALM_TRAITS.span().at(index / 7)).into();
    let traits = BitShift::shr(chunk, ((index % 7) * 32).into()) & 0xffffffff;
    let order: u8 = ((BitShift::shr(traits, 22) & 15) + 1).try_into().unwrap();
    let wonder: u8 = BitShift::shr(traits, 26).try_into().unwrap();
    let mut mask = traits & 0x3fffff;
    let mut resources = array![];
    for resource in 1..23_u8 {{
        if mask & 1 == 1 {{ resources.append(resource); }}
        mask = BitShift::shr(mask, 1);
    }}
    (wonder, order, resources)
}}

#[cfg(test)]
mod tests {{
    use super::realm_attributes;
    #[test]
    fn stolsli_has_its_canonical_traits() {{
        let (wonder, order, resources) = realm_attributes(1);
        assert!(wonder == 1 && order == 1 && resources == array![1, 2], "Stolsli metadata changed");
    }}
    #[test]
    fn eternal_orchard_keeps_its_wonder_and_order() {{
        let (wonder, order, resources) = realm_attributes(87);
        assert!(wonder == 2 && order == 5 && resources == array![2], "Orchard metadata changed");
    }}
    #[test]
    fn packed_chunk_boundaries_have_playable_traits() {{
        for realm_id in array![1_u32, 7, 8, 87, 7994, 7995, 8000] {{
            let (wonder, order, resources) = realm_attributes(realm_id);
            assert!(wonder >= 1 && wonder <= 51 && order >= 1 && order <= 16 && !resources.is_empty(), "invalid realm traits");
        }}
    }}
}}
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        # Cairo formatting may split whitespace differently; the token stream must match.
        normalize = lambda text: re.sub(r",(?=[)\]])", "", re.sub(r"\s+", "", text))
        assert normalize(TARGET.read_text()) == normalize(generated), "Regenerate canonical realm metadata"
    else:
        TARGET.write_text(generated)
