"""Generate the immutable gameplay traits from the bundled 8,000 realm metadata records."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "packages/core/src/data/full-realms.json"
TARGET = ROOT / "contracts/l3/game/src/systems/utils/realm_metadata.cairo"


# Canonical realm NFT IDs. These differ from the game resource IDs.
RESOURCE_IDS = {
    "Stone": 1,
    "Coal": 2,
    "Wood": 3,
    "Copper": 4,
    "Ironwood": 5,
    "Obsidian": 6,
    "Gold": 7,
    "Silver": 8,
    "Mithral": 9,
    "Alchemical Silver": 10,
    "Cold Iron": 11,
    "Deep Crystal": 12,
    "Ruby": 13,
    "Diamonds": 14,
    "Hartwood": 15,
    "Ignium": 16,
    "Twilight Quartz": 17,
    "True Ice": 18,
    "Adamantine": 19,
    "Sapphire": 20,
    "Ethereal Silica": 21,
    "Dragonhide": 22
}

ORDER_IDS = {
    "The Order of Giants": 1,
    "The Order of Perfection": 2,
    "The Order of Rage": 3,
    "The Order of the Fox": 4,
    "The Order of the Twins": 5,
    "The Order of Fury": 6,
    "The Order of Reflection": 7,
    "The Order of Detection": 8,
    "The Order of Skill": 9,
    "The Order of Brilliance": 10,
    "The Order of Protection": 11,
    "The Order of Power": 12,
    "The Order of Titans": 13,
    "The Order of Vitriol": 14,
    "The Order of Anger": 15,
    "The Order of Enlightenment": 16
}

WONDER_IDS = {
    "None": 1,
    "The Eternal Orchard": 2,
    "The Glowing Geyser": 3,
    "The Pearl Summit": 4,
    "The Pearl River": 5,
    "Altar Of Divine Will": 6,
    "The Fading Yew": 7,
    "Pantheon Of Chaos": 8,
    "The Ancient Lagoon": 9,
    "The Exalted Basin": 10,
    "The Amaranthine Rock": 11,
    "The Pale Pillar": 12,
    "The Mythic Trees": 13,
    "Sanctum Of The Oracle": 14,
    "The Ancestral Willow": 15,
    "The Pale Vertex": 16,
    "Cathedral Of Agony": 17,
    "The Omen Graves": 18,
    "The Crying Oak": 19,
    "The Perpetual Ridge": 20,
    "The Sanctified Fjord": 21,
    "Altar Of Perfection": 22,
    "The Argent Catacombs": 23,
    "The Mirror Grotto": 24,
    "The Mother Grove": 25,
    "The Dark Mountain": 26,
    "The Origin Oasis": 27,
    "The Cerulean Reliquary": 28,
    "Sanctum Of Purpose": 29,
    "Altar Of The Void": 30,
    "Pagoda Of Fortune": 31,
    "The Weeping Willow": 32,
    "Synagogue Of Collapse": 33,
    "Mosque Of Mercy": 34,
    "The Perpetual Fjord": 35,
    "The Ethereal Isle": 36,
    "The Azure Lake": 37,
    "The Celestial Vertex": 38,
    "The Exalted Maple": 39,
    "The Oracle Pool": 40,
    "Infinity Spire": 41,
    "The Exalted Geyser": 42,
    "The Glowing Pinnacle": 43,
    "The Ancestral Trees": 44,
    "The Immortal Hot Spring": 45,
    "The Pure Stone": 46,
    "The Cerulean Chamber": 47,
    "Sanctuary Of The Ancients": 48,
    "The Solemn Catacombs": 49,
    "The Devout Summit": 50,
    "Sky Mast": 51
}

def generate():
    realms = json.loads(SOURCE.read_text())
    assert set(realms) == {str(i) for i in range(1, 8001)}, "Expected all 8000 canonical realms"
    resources = RESOURCE_IDS
    orders = ORDER_IDS
    wonders = WONDER_IDS
    packed = []
    for realm_id in range(1, 8001):
        attributes = realms[str(realm_id)]["attributes"]
        mask = sum(1 << (resources[a["value"]] - 1) for a in attributes if a["trait_type"] == "Resource")
        order = next(orders[a["value"]] for a in attributes if a["trait_type"] == "Order")
        wonder = next((wonders[a["value"]] for a in attributes if a["trait_type"] == "Wonder (translated)"), 1)
        assert mask > 0 and mask < (1 << 22) and 1 <= order <= 16 and 1 <= wonder <= 63
        packed.append(mask | ((order - 1) << 22) | (wonder << 26))
    chunks = [sum(value << (32 * offset) for offset, value in enumerate(packed[index:index + 7])) for index in range(0, len(packed), 7)]
    for index, expected in enumerate(packed):
        assert (chunks[index // 7] >> (32 * (index % 7))) & 0xffffffff == expected
    literals = ",\n".join(f"    0x{value:x}" for value in chunks)
    return f"""// Generated by scripts/generate-realm-metadata.py from packages/core/src/data/full-realms.json.
// Seven 32-bit records per felt: 22 resource bits, four Order bits, six wonder bits.
use alexandria_math::BitShift;

const REALM_TRAITS: [felt252; {len(chunks)}] = [
{literals},
];

pub fn realm_attributes(realm_id: u32) -> (u8, u8, Array<u8>) {{
    assert!(realm_id >= 1 && realm_id <= 8000, "Eternum: invalid canonical realm id");
    let index = realm_id - 1;
    let chunk: u256 = (*REALM_TRAITS.span().at(index / 7)).into();
    let traits = BitShift::shr(chunk, ((index % 7) * 32).into()) & 0xffffffff;
    let order: u8 = ((BitShift::shr(traits, 22) & 15) + 1).try_into().unwrap();
    let wonder: u8 = BitShift::shr(traits, 26).try_into().unwrap();
    let mut mask = traits & 0x3fffff;
    let mut resources = array![];
    for resource in 1..23_u8 {{
        if mask & 1 == 1 {{ resources.append(resource); }}
        mask = BitShift::shr(mask, 1);
    }}
    (wonder, order, resources)
}}

#[cfg(test)]
mod tests {{
    use super::realm_attributes;
    #[test]
    fn stolsli_has_its_canonical_traits() {{
        let (wonder, order, resources) = realm_attributes(1);
        assert!(wonder == 1 && order == 1 && resources == array![1, 2], "Stolsli metadata changed");
    }}
    #[test]
    fn eternal_orchard_keeps_its_wonder_and_order() {{
        let (wonder, order, resources) = realm_attributes(87);
        assert!(wonder == 2 && order == 5 && resources == array![2], "Orchard metadata changed");
    }}
    #[test]
    fn packed_chunk_boundaries_have_playable_traits() {{
        for realm_id in array![1_u32, 7, 8, 87, 7994, 7995, 8000] {{
            let (wonder, order, resources) = realm_attributes(realm_id);
            assert!(wonder >= 1 && wonder <= 51 && order >= 1 && order <= 16 && !resources.is_empty(), "invalid realm traits");
        }}
    }}
}}
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        # Cairo formatting may split whitespace differently; the token stream must match.
        normalize = lambda text: re.sub(r",(?=[)\]])", "", re.sub(r"\s+", "", text))
        assert normalize(TARGET.read_text()) == normalize(generated), "Regenerate canonical realm metadata"
    else:
        TARGET.write_text(generated)
