import { ResourcesIds } from "@bibliothecadao/types";

export const RESOURCE_BALANCE_COLUMNS = [
  ["STONE_BALANCE", ResourcesIds.Stone, "Stone"],
  ["COAL_BALANCE", ResourcesIds.Coal, "Coal"],
  ["WOOD_BALANCE", ResourcesIds.Wood, "Wood"],
  ["COPPER_BALANCE", ResourcesIds.Copper, "Copper"],
  ["IRONWOOD_BALANCE", ResourcesIds.Ironwood, "Ironwood"],
  ["OBSIDIAN_BALANCE", ResourcesIds.Obsidian, "Obsidian"],
  ["GOLD_BALANCE", ResourcesIds.Gold, "Gold"],
  ["SILVER_BALANCE", ResourcesIds.Silver, "Silver"],
  ["MITHRAL_BALANCE", ResourcesIds.Mithral, "Mithral"],
  ["ALCHEMICAL_SILVER_BALANCE", ResourcesIds.AlchemicalSilver, "Alchemical Silver"],
  ["COLD_IRON_BALANCE", ResourcesIds.ColdIron, "Cold Iron"],
  ["DEEP_CRYSTAL_BALANCE", ResourcesIds.DeepCrystal, "Deep Crystal"],
  ["RUBY_BALANCE", ResourcesIds.Ruby, "Ruby"],
  ["DIAMONDS_BALANCE", ResourcesIds.Diamonds, "Diamonds"],
  ["HARTWOOD_BALANCE", ResourcesIds.Hartwood, "Hartwood"],
  ["IGNIUM_BALANCE", ResourcesIds.Ignium, "Ignium"],
  ["TWILIGHT_QUARTZ_BALANCE", ResourcesIds.TwilightQuartz, "Twilight Quartz"],
  ["TRUE_ICE_BALANCE", ResourcesIds.TrueIce, "True Ice"],
  ["ADAMANTINE_BALANCE", ResourcesIds.Adamantine, "Adamantine"],
  ["SAPPHIRE_BALANCE", ResourcesIds.Sapphire, "Sapphire"],
  ["ETHEREAL_SILICA_BALANCE", ResourcesIds.EtherealSilica, "Ethereal Silica"],
  ["DRAGONHIDE_BALANCE", ResourcesIds.Dragonhide, "Dragonhide"],
  ["LABOR_BALANCE", ResourcesIds.Labor, "Labor"],
  ["EARTHEN_SHARD_BALANCE", ResourcesIds.AncientFragment, "Ancient Fragment"],
  ["DONKEY_BALANCE", ResourcesIds.Donkey, "Donkey"],
  ["WHEAT_BALANCE", ResourcesIds.Wheat, "Wheat"],
  ["FISH_BALANCE", ResourcesIds.Fish, "Fish"],
  ["LORDS_BALANCE", ResourcesIds.Lords, "Lords"],
  ["ESSENCE_BALANCE", ResourcesIds.Essence, "Essence"],
  ["RESEARCH_BALANCE", ResourcesIds.Research, "Research"],
].map(([column, resourceId, name]) => ({ column: String(column), resourceId: Number(resourceId), name: String(name) }));
