// Generated from schema/command-routes.mjs and production logic ABIs.
use starknet::storage::StoragePointerReadAccess;

#[derive(Copy, Drop)]
pub struct CommandRoute {
    pub logic: u8,
    pub selector: felt252,
    pub items_offset: Option<u32>,
    pub batch: bool,
}

pub const SETTLE_BLITZ_ROSTER: u32 = 7;

pub const COMMAND_ROUTES: [CommandRoute; 71] = [
    CommandRoute { logic: 6, selector: selector!("create_explorer"), items_offset: None, batch: false },
    CommandRoute { logic: 16, selector: selector!("explore"), items_offset: None, batch: false },
    CommandRoute { logic: 12, selector: selector!("battle"), items_offset: Some(2), batch: false },
    CommandRoute { logic: 16, selector: selector!("move_explorer"), items_offset: Some(1), batch: false },
    CommandRoute { logic: 16, selector: selector!("toggle_alternate"), items_offset: None, batch: false },
    CommandRoute { logic: 5, selector: selector!("transfer_structure_ownership"), items_offset: None, batch: false },
    CommandRoute { logic: 3, selector: selector!("level_up"), items_offset: None, batch: false },
    CommandRoute { logic: 7, selector: selector!("settle_blitz_roster"), items_offset: None, batch: true },
    CommandRoute { logic: 5, selector: selector!("activate_realm_economy"), items_offset: None, batch: false },
    CommandRoute { logic: 5, selector: selector!("create_reserved_hyperstructure"), items_offset: None, batch: false },
    CommandRoute { logic: 7, selector: selector!("settle_season"), items_offset: None, batch: false },
    CommandRoute { logic: 7, selector: selector!("settle_village"), items_offset: None, batch: false },
    CommandRoute { logic: 5, selector: selector!("receive_village_army"), items_offset: None, batch: false },
    CommandRoute { logic: 8, selector: selector!("burn_structure_resources"), items_offset: Some(1), batch: false },
    CommandRoute { logic: 8, selector: selector!("transfer_explorer_resources"), items_offset: Some(2), batch: false },
    CommandRoute {
        logic: 8, selector: selector!("transfer_structure_resources_to_explorer"), items_offset: Some(2), batch: false,
    },
    CommandRoute { logic: 8, selector: selector!("offload_arrival"), items_offset: None, batch: false },
    CommandRoute { logic: 8, selector: selector!("send_resources"), items_offset: Some(2), batch: false },
    CommandRoute {
        logic: 8, selector: selector!("transfer_explorer_resources_to_structure"), items_offset: Some(2), batch: false,
    },
    CommandRoute {
        logic: 4, selector: selector!("burn_labor_for_resource_production"), items_offset: None, batch: false,
    },
    CommandRoute {
        logic: 4, selector: selector!("burn_resource_for_resource_production"), items_offset: None, batch: false,
    },
    CommandRoute { logic: 3, selector: selector!("create_building"), items_offset: None, batch: false },
    CommandRoute { logic: 3, selector: selector!("destroy_building"), items_offset: None, batch: false },
    CommandRoute { logic: 3, selector: selector!("pause_building_production"), items_offset: None, batch: false },
    CommandRoute { logic: 3, selector: selector!("resume_building_production"), items_offset: None, batch: false },
    CommandRoute { logic: 10, selector: selector!("contribute_bitcoin_labor"), items_offset: None, batch: false },
    CommandRoute { logic: 10, selector: selector!("close_bitcoin_phase"), items_offset: None, batch: false },
    CommandRoute { logic: 10, selector: selector!("bind_bitcoin_phase"), items_offset: None, batch: false },
    CommandRoute { logic: 10, selector: selector!("claim_bitcoin_phase"), items_offset: Some(1), batch: true },
    CommandRoute { logic: 12, selector: selector!("battle_guard"), items_offset: None, batch: false },
    CommandRoute { logic: 9, selector: selector!("create_trade_order"), items_offset: None, batch: false },
    CommandRoute { logic: 9, selector: selector!("accept_trade_order"), items_offset: None, batch: false },
    CommandRoute { logic: 9, selector: selector!("cancel_trade_order"), items_offset: None, batch: false },
    CommandRoute { logic: 9, selector: selector!("create_banks"), items_offset: Some(0), batch: false },
    CommandRoute { logic: 9, selector: selector!("buy_from_bank"), items_offset: None, batch: false },
    CommandRoute { logic: 9, selector: selector!("sell_to_bank"), items_offset: None, batch: false },
    CommandRoute { logic: 9, selector: selector!("add_bank_liquidity"), items_offset: None, batch: false },
    CommandRoute { logic: 9, selector: selector!("remove_bank_liquidity"), items_offset: None, batch: false },
    CommandRoute { logic: 9, selector: selector!("initialize_hyperstructure"), items_offset: None, batch: false },
    CommandRoute { logic: 9, selector: selector!("contribute_hyperstructure"), items_offset: Some(2), batch: false },
    CommandRoute {
        logic: 9, selector: selector!("allocate_hyperstructure_shares"), items_offset: Some(1), batch: false,
    },
    CommandRoute { logic: 9, selector: selector!("set_construction_access"), items_offset: None, batch: false },
    CommandRoute { logic: 15, selector: selector!("open_relic_chest"), items_offset: None, batch: false },
    CommandRoute { logic: 15, selector: selector!("apply_relic"), items_offset: None, batch: false },
    CommandRoute { logic: 0, selector: selector!("close_season"), items_offset: None, batch: true },
    CommandRoute { logic: 10, selector: selector!("pledge_faith"), items_offset: None, batch: false },
    CommandRoute { logic: 10, selector: selector!("remove_faith"), items_offset: None, batch: false },
    CommandRoute { logic: 10, selector: selector!("update_wonder_ownership"), items_offset: None, batch: false },
    CommandRoute { logic: 10, selector: selector!("update_faithful_ownership"), items_offset: None, batch: false },
    CommandRoute { logic: 10, selector: selector!("claim_wonder_points"), items_offset: None, batch: false },
    CommandRoute { logic: 10, selector: selector!("claim_player_faith_points"), items_offset: None, batch: false },
    CommandRoute { logic: 10, selector: selector!("record_blitz_results"), items_offset: Some(1), batch: true },
    CommandRoute { logic: 15, selector: selector!("craft_relic"), items_offset: None, batch: false },
    CommandRoute { logic: 5, selector: selector!("create_guild"), items_offset: None, batch: false },
    CommandRoute { logic: 5, selector: selector!("join_guild"), items_offset: None, batch: false },
    CommandRoute { logic: 5, selector: selector!("leave_guild"), items_offset: None, batch: false },
    CommandRoute { logic: 5, selector: selector!("set_guild_whitelist"), items_offset: None, batch: false },
    CommandRoute { logic: 5, selector: selector!("remove_guild_member"), items_offset: None, batch: false },
    CommandRoute { logic: 0, selector: selector!("mark_game_settled"), items_offset: None, batch: true },
    CommandRoute { logic: 6, selector: selector!("manage_troops"), items_offset: None, batch: false },
    CommandRoute { logic: 12, selector: selector!("guard_attack"), items_offset: None, batch: false },
    CommandRoute { logic: 13, selector: selector!("raid"), items_offset: Some(2), batch: false },
    CommandRoute { logic: 14, selector: selector!("deposit_resource"), items_offset: None, batch: false },
    CommandRoute { logic: 14, selector: selector!("withdraw_resource"), items_offset: None, batch: false },
    CommandRoute { logic: 5, selector: selector!("provision_and_upgrade_realm"), items_offset: None, batch: false },
    CommandRoute { logic: 5, selector: selector!("set_entity_name"), items_offset: None, batch: false },
    CommandRoute { logic: 16, selector: selector!("enter_depth"), items_offset: None, batch: false },
    CommandRoute { logic: 3, selector: selector!("research"), items_offset: None, batch: false },
    CommandRoute { logic: 15, selector: selector!("choose_attribute"), items_offset: None, batch: false },
    CommandRoute { logic: 3, selector: selector!("upgrade_building"), items_offset: None, batch: false },
    CommandRoute { logic: 15, selector: selector!("interact_site"), items_offset: None, batch: false },
];

pub fn logic_class(
    classes: starknet::storage::StoragePointer<games_storage::release::LogicClasses>, index: u8,
) -> starknet::ClassHash {
    match index {
        0 => classes.season.read(),
        1 => classes.map.read(),
        2 => classes.placement.read(),
        3 => classes.construction.read(),
        4 => classes.production.read(),
        5 => classes.structures.read(),
        6 => classes.troops.read(),
        7 => classes.settlement.read(),
        8 => classes.resources.read(),
        9 => classes.economy.read(),
        10 => classes.prizes.read(),
        11 => classes.registry.read(),
        12 => classes.combat.read(),
        13 => classes.raid.read(),
        14 => classes.bridge.read(),
        15 => classes.relics.read(),
        16 => classes.movement.read(),
        _ => panic!("unknown command logic"),
    }
}

// Tests construct typed actions; production forwards their existing Cairo wire fields.
#[cfg(test)]
#[derive(Copy, Drop, Serde, Debug, PartialEq)]
pub enum Command {
    CreateExplorer: crate::commands::CreateExplorer,
    Explore: crate::commands::Explore,
    Battle: crate::combat_actions::AttackExplorer,
    Move: crate::commands::Move,
    ToggleAlternate: crate::commands::ToggleAlternate,
    TransferStructureOwnership: crate::ownership::TransferOwnership,
    LevelUp: core::integer::u32,
    SettleBlitzRoster,
    ProvisionRealm: core::integer::u32,
    CreateReservedHyperstructure: crate::troops::Coord,
    SettleSeason: crate::realms::SettleSeason,
    SettleVillage: crate::village::SettleVillage,
    ReceiveVillageArmy: core::integer::u32,
    BurnStructureResources: crate::resources::ResourceBurn,
    TransferExplorerResources: crate::resources::ResourceTransfer,
    TransferStructureResourcesToExplorer: crate::resources::ResourceTransfer,
    OffloadArrival: crate::arrivals::OffloadArrival,
    SendResources: crate::resources::ResourceTransfer,
    TransferExplorerResourcesToStructure: crate::resources::ResourceTransfer,
    BurnLaborForResourceProduction: crate::production::RefillProduction,
    BurnResourceForResourceProduction: crate::production::RefillProduction,
    CreateBuilding: crate::buildings::CreateBuilding,
    DestroyBuilding: crate::buildings::ChangeBuilding,
    PauseBuildingProduction: crate::buildings::ChangeBuilding,
    ResumeBuildingProduction: crate::buildings::ChangeBuilding,
    ContributeBitcoinLabor: crate::bitcoin::ContributeLabor,
    CloseBitcoinPhase: core::integer::u64,
    BindBitcoinPhase: core::integer::u64,
    ClaimBitcoinPhase: crate::bitcoin::ClaimPhase,
    BattleGuard: crate::commands::Battle,
    CreateTradeOrder: crate::trade::CreateOrder,
    AcceptTradeOrder: crate::trade::AcceptOrder,
    CancelTradeOrder: core::integer::u32,
    CreateBanks: core::array::Span<crate::market::BankPlacement>,
    BuyFromBank: crate::market::Swap,
    SellToBank: crate::market::Swap,
    AddBankLiquidity: crate::market::AddLiquidity,
    RemoveBankLiquidity: crate::market::RemoveLiquidity,
    InitializeHyperstructure: core::integer::u32,
    ContributeHyperstructure: crate::hyperstructures::Contribution,
    AllocateHyperstructureShares: crate::hyperstructures::AllocateShares,
    SetConstructionAccess: crate::hyperstructures::SetConstructionAccess,
    OpenRelicChest: crate::relics::OpenChest,
    ApplyRelic: crate::relics::ApplyRelic,
    CloseSeason,
    PledgeFaith: crate::faith::Pledge,
    RemoveFaith: core::integer::u32,
    UpdateWonderOwnership: core::integer::u32,
    UpdateFaithfulOwnership: core::integer::u32,
    ClaimWonderPoints: core::integer::u32,
    ClaimPlayerFaithPoints: crate::faith::ClaimPlayer,
    RecordBlitzResults: crate::blitz_results::RecordBlitzResults,
    CraftRelic: core::integer::u32,
    CreateGuild: crate::guilds::CreateGuild,
    JoinGuild: crate::guilds::JoinGuild,
    LeaveGuild,
    SetGuildWhitelist: crate::guilds::SetWhitelist,
    RemoveGuildMember: starknet::contract_address::ContractAddress,
    MarkGameSettled,
    ManageTroops: crate::troop_management::ManageTroops,
    GuardAttack: crate::combat_actions::GuardAttack,
    Raid: crate::combat_actions::Raid,
    DepositResource: crate::bridge::Deposit,
    WithdrawResource: crate::bridge::Withdraw,
    ProvisionAndUpgradeRealm: core::integer::u32,
    SetEntityName: crate::names::SetEntityName,
    EnterDepth: crate::commands::EnterDepth,
    Research: crate::research::Research,
    ChooseAttribute: crate::progression::ChooseAttribute,
    UpgradeBuilding: crate::buildings::ChangeBuilding,
    InteractSite: crate::relics::InteractSite,
}
