[package]
cairo-version = "=2.10.1"
name = "marketplace"
version = "1.0.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.10.1"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v1.0.0" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.5.0" }

[[target.starknet-contract]]
casm = true
build-external-contracts = [
	"dojo::world::world_contract::world",
]

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[profile.local]

[profile.slot]

[profile.sepolia]

[profile.mainnet]
