kind = "DojoModel"
class_hash = "0x79e412a179637857fcb1eb1b95328946c0533fcdf98e174ef8e16639408c474"
original_class_hash = "0x79e412a179637857fcb1eb1b95328946c0533fcdf98e174ef8e16639408c474"
abi = "manifests/prod/base/abis/models/eternum-PopulationConfig-8cead3bb.json"
tag = "eternum-PopulationConfig"
qualified_path = "eternum::models::config::population_config"
manifest_name = "eternum-PopulationConfig-8cead3bb"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "base_population"
type = "u32"
key = false
