kind = "DojoModel"
class_hash = "0x276d64103df4cef7e0f9bd59fb406fd8acc35c99c278f33becefc0dcc640e31"
original_class_hash = "0x276d64103df4cef7e0f9bd59fb406fd8acc35c99c278f33becefc0dcc640e31"
abi = "manifests/prod/base/abis/models/eternum-Stamina-64093ed8.json"
tag = "eternum-Stamina"
qualified_path = "eternum::models::stamina::stamina"
manifest_name = "eternum-Stamina-64093ed8"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "amount"
type = "u16"
key = false

[[members]]
name = "last_refill_tick"
type = "u64"
key = false
