kind = "DojoModel"
class_hash = "0x1e40d5fceb2966b7f2fb3cbf724e91b32d0b29847634a5202dbda33a765140e"
original_class_hash = "0x1e40d5fceb2966b7f2fb3cbf724e91b32d0b29847634a5202dbda33a765140e"
abi = "manifests/prod/base/abis/models/eternum-ProductionConfig-58cf51ed.json"
tag = "eternum-ProductionConfig"
qualified_path = "eternum::models::config::production_config"
manifest_name = "eternum-ProductionConfig-58cf51ed"

[[members]]
name = "resource_type"
type = "u8"
key = true

[[members]]
name = "amount"
type = "u128"
key = false

[[members]]
name = "input_count"
type = "u128"
key = false

[[members]]
name = "output_count"
type = "u128"
key = false
