kind = "DojoModel"
class_hash = "0x433b3deede71441ae49a12cd83d74bf70ba716f02cb16b38ff6bff09abbfb12"
original_class_hash = "0x433b3deede71441ae49a12cd83d74bf70ba716f02cb16b38ff6bff09abbfb12"
abi = "manifests/prod/base/abis/models/eternum-AcceptPartialOrder-33e6b6b9.json"
tag = "eternum-AcceptPartialOrder"
qualified_path = "eternum::systems::trade::contracts::trade_systems::trade_systems::accept_partial_order"
manifest_name = "eternum-AcceptPartialOrder-33e6b6b9"

[[members]]
name = "taker_id"
type = "ID"
key = true

[[members]]
name = "maker_id"
type = "ID"
key = true

[[members]]
name = "trade_id"
type = "ID"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
