kind = "DojoModel"
class_hash = "0x445564fbb2d245eb339ace1dc691215f63de43fb79c8b3b1d205e9a2478200c"
original_class_hash = "0x445564fbb2d245eb339ace1dc691215f63de43fb79c8b3b1d205e9a2478200c"
abi = "manifests/prod/base/abis/models/eternum-LevelingConfig-1c0257fd.json"
tag = "eternum-LevelingConfig"
qualified_path = "eternum::models::config::leveling_config"
manifest_name = "eternum-LevelingConfig-1c0257fd"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "decay_interval"
type = "u64"
key = false

[[members]]
name = "max_level"
type = "u64"
key = false

[[members]]
name = "decay_scaled"
type = "u128"
key = false

[[members]]
name = "cost_percentage_scaled"
type = "u128"
key = false

[[members]]
name = "base_multiplier"
type = "u128"
key = false

[[members]]
name = "wheat_base_amount"
type = "u128"
key = false

[[members]]
name = "fish_base_amount"
type = "u128"
key = false

[[members]]
name = "resource_1_cost_id"
type = "ID"
key = false

[[members]]
name = "resource_1_cost_count"
type = "u32"
key = false

[[members]]
name = "resource_2_cost_id"
type = "ID"
key = false

[[members]]
name = "resource_2_cost_count"
type = "u32"
key = false

[[members]]
name = "resource_3_cost_id"
type = "ID"
key = false

[[members]]
name = "resource_3_cost_count"
type = "u32"
key = false
