kind = "DojoModel"
class_hash = "0x62fdb411ae9adc999e69d2fa0996e053aec218901458e3fa24e476c364a1062"
original_class_hash = "0x62fdb411ae9adc999e69d2fa0996e053aec218901458e3fa24e476c364a1062"
abi = "manifests/prod/base/abis/models/eternum-ResourceTransferLock-6a7c4096.json"
tag = "eternum-ResourceTransferLock"
qualified_path = "eternum::models::resources::resource_transfer_lock"
manifest_name = "eternum-ResourceTransferLock-6a7c4096"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "start_at"
type = "u64"
key = false

[[members]]
name = "release_at"
type = "u64"
key = false
