kind = "DojoModel"
class_hash = "0x1a9134ee493ab5847c1fdedb9fd2f7a8aa01cb51cdd82362b44ac696aca219f"
original_class_hash = "0x1a9134ee493ab5847c1fdedb9fd2f7a8aa01cb51cdd82362b44ac696aca219f"
abi = "manifests/prod/base/abis/models/eternum-BuildingQuantityv2-31cdaf07.json"
tag = "eternum-BuildingQuantityv2"
qualified_path = "eternum::models::buildings::building_quantityv_2"
manifest_name = "eternum-BuildingQuantityv2-31cdaf07"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "category"
type = "BuildingCategory"
key = true

[[members]]
name = "value"
type = "u8"
key = false
