kind = "DojoModel"
class_hash = "0x4fb0e45454b977241a287145a928a6245aa37bd160eb69f3a588aaa81d95a77"
original_class_hash = "0x4fb0e45454b977241a287145a928a6245aa37bd160eb69f3a588aaa81d95a77"
abi = "manifests/prod/base/abis/models/eternum-BattleLeaveData-3082a68c.json"
tag = "eternum-BattleLeaveData"
qualified_path = "eternum::models::event::battle_leave_data"
manifest_name = "eternum-BattleLeaveData-3082a68c"

[[members]]
name = "id"
type = "ID"
key = true

[[members]]
name = "event_id"
type = "EventType"
key = true

[[members]]
name = "battle_entity_id"
type = "ID"
key = false

[[members]]
name = "leaver"
type = "ContractAddress"
key = false

[[members]]
name = "leaver_name"
type = "felt252"
key = false

[[members]]
name = "leaver_army_entity_id"
type = "ID"
key = false

[[members]]
name = "leaver_side"
type = "BattleSide"
key = false

[[members]]
name = "duration_left"
type = "u64"
key = false

[[members]]
name = "x"
type = "u32"
key = false

[[members]]
name = "y"
type = "u32"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
