kind = "DojoModel"
class_hash = "0x420273f5f48cfbe450360eced03117cbdbc57795fad3c6d3b1db94b53f5e9a5"
original_class_hash = "0x420273f5f48cfbe450360eced03117cbdbc57795fad3c6d3b1db94b53f5e9a5"
abi = "manifests/prod/base/abis/models/eternum-Transfer-aad2d49c.json"
tag = "eternum-Transfer"
qualified_path = "eternum::systems::resources::contracts::resource_systems::transfer"
manifest_name = "eternum-Transfer-aad2d49c"

[[members]]
name = "recipient_entity_id"
type = "ID"
key = true

[[members]]
name = "sending_realm_id"
type = "ID"
key = true

[[members]]
name = "sender_entity_id"
type = "ID"
key = false

[[members]]
name = "resources"
type = "Span<(u8, u128)>"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
