kind = "DojoModel"
class_hash = "0x7c7bd97140dd00fd070bf37847d9d1271ca2e0988eec3de0a710bf1913f4392"
original_class_hash = "0x7c7bd97140dd00fd070bf37847d9d1271ca2e0988eec3de0a710bf1913f4392"
abi = "manifests/prod/base/abis/models/eternum-BuildingConfig-2050f944.json"
tag = "eternum-BuildingConfig"
qualified_path = "eternum::models::config::building_config"
manifest_name = "eternum-BuildingConfig-2050f944"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "category"
type = "BuildingCategory"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = true

[[members]]
name = "resource_cost_id"
type = "ID"
key = false

[[members]]
name = "resource_cost_count"
type = "u32"
key = false
