kind = "DojoModel"
class_hash = "0x3f305b12152e28290cdfa49e261b491fd9b35a97bb08e84d466d473d3f02ca9"
original_class_hash = "0x3f305b12152e28290cdfa49e261b491fd9b35a97bb08e84d466d473d3f02ca9"
abi = "manifests/prod/base/abis/models/eternum-EntityMetadata-72b04193.json"
tag = "eternum-EntityMetadata"
qualified_path = "eternum::models::metadata::entity_metadata"
manifest_name = "eternum-EntityMetadata-72b04193"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "entity_type"
type = "u32"
key = false
