kind = "DojoModel"
class_hash = "0x57c20dd8d15b5011efc41b6115aa55268505fdc6a5be23d948acd6abc84fe6e"
original_class_hash = "0x57c20dd8d15b5011efc41b6115aa55268505fdc6a5be23d948acd6abc84fe6e"
abi = "manifests/prod/base/abis/models/eternum-EntityName-8c850fbe.json"
tag = "eternum-EntityName"
qualified_path = "eternum::models::name::entity_name"
manifest_name = "eternum-EntityName-8c850fbe"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "name"
type = "felt252"
key = false
