kind = "DojoModel"
class_hash = "0x182c4a5ea3b8ff80e27dbb7460c584f18c7b13dccb4f35146497cbb76d9ef5"
original_class_hash = "0x182c4a5ea3b8ff80e27dbb7460c584f18c7b13dccb4f35146497cbb76d9ef5"
abi = "manifests/prod/base/abis/models/eternum-MercenariesConfig-4c7248d4.json"
tag = "eternum-MercenariesConfig"
qualified_path = "eternum::models::config::mercenaries_config"
manifest_name = "eternum-MercenariesConfig-4c7248d4"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "troops"
type = "Troops"
key = false

[[members]]
name = "rewards"
type = "Span<(u8, u128)>"
key = false
