kind = "DojoModel"
class_hash = "0x300f8ebbd1c764b0da865d21cd1af3719282fb55ecd9b4555af1e794e23048"
original_class_hash = "0x300f8ebbd1c764b0da865d21cd1af3719282fb55ecd9b4555af1e794e23048"
abi = "manifests/prod/base/abis/models/eternum-HyperstructureFinished-4b0440d5.json"
tag = "eternum-HyperstructureFinished"
qualified_path = "eternum::systems::hyperstructure::contracts::hyperstructure_systems::hyperstructure_finished"
manifest_name = "eternum-HyperstructureFinished-4b0440d5"

[[members]]
name = "id"
type = "ID"
key = true

[[members]]
name = "hyperstructure_entity_id"
type = "ID"
key = true

[[members]]
name = "contributor_entity_id"
type = "ID"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
