kind = "DojoModel"
class_hash = "0x55330c894f2b7c9016228aabf1a70c357ff0ae89be4523da7dfd397264fde9"
original_class_hash = "0x55330c894f2b7c9016228aabf1a70c357ff0ae89be4523da7dfd397264fde9"
abi = "manifests/prod/base/abis/models/eternum-CreateOrder-55ffed6f.json"
tag = "eternum-CreateOrder"
qualified_path = "eternum::systems::trade::contracts::trade_systems::trade_systems::create_order"
manifest_name = "eternum-CreateOrder-55ffed6f"

[[members]]
name = "taker_id"
type = "ID"
key = true

[[members]]
name = "maker_id"
type = "ID"
key = true

[[members]]
name = "trade_id"
type = "ID"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
