kind = "DojoModel"
class_hash = "0x13aeb486814696b3fa2c797a319b066d5395a53e4d60c956e23fb212636bbd0"
original_class_hash = "0x13aeb486814696b3fa2c797a319b066d5395a53e4d60c956e23fb212636bbd0"
abi = "manifests/prod/base/abis/models/eternum-Building-a3631d0a.json"
tag = "eternum-Building"
qualified_path = "eternum::models::buildings::building"
manifest_name = "eternum-Building-a3631d0a"

[[members]]
name = "outer_col"
type = "u32"
key = true

[[members]]
name = "outer_row"
type = "u32"
key = true

[[members]]
name = "inner_col"
type = "u32"
key = true

[[members]]
name = "inner_row"
type = "u32"
key = true

[[members]]
name = "category"
type = "BuildingCategory"
key = false

[[members]]
name = "produced_resource_type"
type = "u8"
key = false

[[members]]
name = "bonus_percent"
type = "u32"
key = false

[[members]]
name = "entity_id"
type = "ID"
key = false

[[members]]
name = "outer_entity_id"
type = "ID"
key = false

[[members]]
name = "paused"
type = "bool"
key = false
