kind = "DojoModel"
class_hash = "0x5888324fcb35eeeee69a7f61bb64e842b618be87d98933a69f41f6986a8825a"
original_class_hash = "0x5888324fcb35eeeee69a7f61bb64e842b618be87d98933a69f41f6986a8825a"
abi = "manifests/prod/base/abis/models/eternum-Production-30841685.json"
tag = "eternum-Production"
qualified_path = "eternum::models::production::production"
manifest_name = "eternum-Production-30841685"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = true

[[members]]
name = "building_count"
type = "u8"
key = false

[[members]]
name = "production_rate"
type = "u128"
key = false

[[members]]
name = "consumption_rate"
type = "u128"
key = false

[[members]]
name = "last_updated_tick"
type = "u64"
key = false

[[members]]
name = "input_finish_tick"
type = "u64"
key = false
