kind = "DojoModel"
class_hash = "0xffca9a6feca863c8005123467925e7edebe279a70670528b71e972d31afa24"
original_class_hash = "0xffca9a6feca863c8005123467925e7edebe279a70670528b71e972d31afa24"
abi = "manifests/prod/base/abis/models/eternum-CancelOrder-29fe0e8f.json"
tag = "eternum-CancelOrder"
qualified_path = "eternum::systems::trade::contracts::trade_systems::trade_systems::cancel_order"
manifest_name = "eternum-CancelOrder-29fe0e8f"

[[members]]
name = "taker_id"
type = "ID"
key = true

[[members]]
name = "maker_id"
type = "ID"
key = true

[[members]]
name = "trade_id"
type = "ID"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
