kind = "DojoModel"
class_hash = "0x21feb9182e649a2b9b5db5cd0e7c1af7520ff6d314415fe53fe8c28a430ddab"
original_class_hash = "0x21feb9182e649a2b9b5db5cd0e7c1af7520ff6d314415fe53fe8c28a430ddab"
abi = "manifests/prod/base/abis/models/eternum-Tile-5dfdf226.json"
tag = "eternum-Tile"
qualified_path = "eternum::models::map::tile"
manifest_name = "eternum-Tile-5dfdf226"

[[members]]
name = "col"
type = "u32"
key = true

[[members]]
name = "row"
type = "u32"
key = true

[[members]]
name = "explored_by_id"
type = "ID"
key = false

[[members]]
name = "explored_at"
type = "u64"
key = false

[[members]]
name = "biome"
type = "Biome"
key = false
