kind = "DojoModel"
class_hash = "0x590aa9c91d3f0211072cdf79aed8466143db269f213d11d28cefb2ab22bcb6"
original_class_hash = "0x590aa9c91d3f0211072cdf79aed8466143db269f213d11d28cefb2ab22bcb6"
abi = "manifests/prod/base/abis/models/eternum-HyperstructureCoOwnersChange-73c7a6d4.json"
tag = "eternum-HyperstructureCoOwnersChange"
qualified_path = "eternum::systems::hyperstructure::contracts::hyperstructure_systems::hyperstructure_co_owners_change"
manifest_name = "eternum-HyperstructureCoOwnersChange-73c7a6d4"

[[members]]
name = "id"
type = "ID"
key = true

[[members]]
name = "hyperstructure_entity_id"
type = "ID"
key = true

[[members]]
name = "co_owners"
type = "Span<(ContractAddress, u16)>"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
