kind = "DojoModel"
class_hash = "0x3cb4e8e2d6bcd98f0d1bfbc7d8c06364033fde0dbba8ec1d459f10e8d63f79f"
original_class_hash = "0x3cb4e8e2d6bcd98f0d1bfbc7d8c06364033fde0dbba8ec1d459f10e8d63f79f"
abi = "manifests/prod/base/abis/models/eternum-HasClaimedStartingResources-636eaec7.json"
tag = "eternum-HasClaimedStartingResources"
qualified_path = "eternum::models::config::has_claimed_starting_resources"
manifest_name = "eternum-HasClaimedStartingResources-636eaec7"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "claimed"
type = "bool"
key = false
