kind = "DojoModel"
class_hash = "0x52bcea2d0f21b18ccae2ae44fc190323441aa6c3a2f16ea19de835df54afef8"
original_class_hash = "0x52bcea2d0f21b18ccae2ae44fc190323441aa6c3a2f16ea19de835df54afef8"
abi = "manifests/prod/base/abis/models/eternum-Realm-68a0f35d.json"
tag = "eternum-Realm"
qualified_path = "eternum::models::realm::realm"
manifest_name = "eternum-Realm-68a0f35d"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "realm_id"
type = "ID"
key = false

[[members]]
name = "resource_types_packed"
type = "u128"
key = false

[[members]]
name = "resource_types_count"
type = "u8"
key = false

[[members]]
name = "cities"
type = "u8"
key = false

[[members]]
name = "harbors"
type = "u8"
key = false

[[members]]
name = "rivers"
type = "u8"
key = false

[[members]]
name = "regions"
type = "u8"
key = false

[[members]]
name = "wonder"
type = "u8"
key = false

[[members]]
name = "order"
type = "u8"
key = false
