kind = "DojoModel"
class_hash = "0x29fcad2b856b3b162583a94026de4f32151c67b267f666423fd2e61bb3850f5"
original_class_hash = "0x29fcad2b856b3b162583a94026de4f32151c67b267f666423fd2e61bb3850f5"
abi = "manifests/prod/base/abis/models/eternum-Bank-522579aa.json"
tag = "eternum-Bank"
qualified_path = "eternum::models::bank::bank::bank"
manifest_name = "eternum-Bank-522579aa"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "owner_fee_num"
type = "u128"
key = false

[[members]]
name = "owner_fee_denom"
type = "u128"
key = false

[[members]]
name = "exists"
type = "bool"
key = false
