kind = "DojoModel"
class_hash = "0x2e75cf512a3c4de702aa94604d01298a27cc5a289d7d80d9020f7bf38f3a464"
original_class_hash = "0x2e75cf512a3c4de702aa94604d01298a27cc5a289d7d80d9020f7bf38f3a464"
abi = "manifests/prod/base/abis/models/eternum-ProductionOutput-3fcdac94.json"
tag = "eternum-ProductionOutput"
qualified_path = "eternum::models::production::production_output"
manifest_name = "eternum-ProductionOutput-3fcdac94"

[[members]]
name = "input_resource_type"
type = "u8"
key = true

[[members]]
name = "index"
type = "u8"
key = true

[[members]]
name = "output_resource_type"
type = "u8"
key = false
