kind = "DojoModel"
class_hash = "0x16f999d580e5134ce0dc4105ad69827bc186404c13f8474e264aab5127ac05d"
original_class_hash = "0x16f999d580e5134ce0dc4105ad69827bc186404c13f8474e264aab5127ac05d"
abi = "manifests/prod/base/abis/models/eternum-Battle-20295758.json"
tag = "eternum-Battle"
qualified_path = "eternum::models::combat::battle"
manifest_name = "eternum-Battle-20295758"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "attack_army"
type = "BattleArmy"
key = false

[[members]]
name = "attack_army_lifetime"
type = "BattleArmy"
key = false

[[members]]
name = "defence_army"
type = "BattleArmy"
key = false

[[members]]
name = "defence_army_lifetime"
type = "BattleArmy"
key = false

[[members]]
name = "attackers_resources_escrow_id"
type = "ID"
key = false

[[members]]
name = "defenders_resources_escrow_id"
type = "ID"
key = false

[[members]]
name = "attack_army_health"
type = "BattleHealth"
key = false

[[members]]
name = "defence_army_health"
type = "BattleHealth"
key = false

[[members]]
name = "attack_delta"
type = "u64"
key = false

[[members]]
name = "defence_delta"
type = "u64"
key = false

[[members]]
name = "last_updated"
type = "u64"
key = false

[[members]]
name = "duration_left"
type = "u64"
key = false

[[members]]
name = "start_at"
type = "u64"
key = false
