kind = "DojoModel"
class_hash = "0x4e65c6d4cd616d04441980af72f0eebf87edf0eae22911869bfd08510637539"
original_class_hash = "0x4e65c6d4cd616d04441980af72f0eebf87edf0eae22911869bfd08510637539"
abi = "manifests/prod/base/abis/models/eternum-HyperstructureUpdate-7602bcc6.json"
tag = "eternum-HyperstructureUpdate"
qualified_path = "eternum::models::hyperstructure::hyperstructure_update"
manifest_name = "eternum-HyperstructureUpdate-7602bcc6"

[[members]]
name = "hyperstructure_entity_id"
type = "ID"
key = true

[[members]]
name = "last_updated_timestamp"
type = "u64"
key = false

[[members]]
name = "last_updated_by"
type = "ContractAddress"
key = false
