kind = "DojoModel"
class_hash = "0xcb632c126afe3b481f00c96970daa4b09c7233e0d1cbbef4ae83dd0fb81e30"
original_class_hash = "0xcb632c126afe3b481f00c96970daa4b09c7233e0d1cbbef4ae83dd0fb81e30"
abi = "manifests/prod/base/abis/models/eternum-Owner-7395b328.json"
tag = "eternum-Owner"
qualified_path = "eternum::models::owner::owner"
manifest_name = "eternum-Owner-7395b328"

[[members]]
name = "entity_id"
type = "ID"
key = true

[[members]]
name = "address"
type = "ContractAddress"
key = false
