kind = "DojoModel"
class_hash = "0x550b3483853493973ac9b27fe77018b328cd3345f676f0e9f5ca642bfdd9bae"
original_class_hash = "0x550b3483853493973ac9b27fe77018b328cd3345f676f0e9f5ca642bfdd9bae"
abi = "manifests/prod/base/abis/models/eternum-ForeignKey-42013ea4.json"
tag = "eternum-ForeignKey"
qualified_path = "eternum::models::metadata::foreign_key"
manifest_name = "eternum-ForeignKey-42013ea4"

[[members]]
name = "foreign_key"
type = "felt252"
key = true

[[members]]
name = "entity_id"
type = "ID"
key = false
