kind = "DojoModel"
class_hash = "0x108235218feb79c91ab2d962b97a2e6c032129bbfd125d210942e5c282025ee"
original_class_hash = "0x108235218feb79c91ab2d962b97a2e6c032129bbfd125d210942e5c282025ee"
abi = "manifests/prod/base/abis/models/eternum-Progress-87eb8002.json"
tag = "eternum-Progress"
qualified_path = "eternum::models::hyperstructure::progress"
manifest_name = "eternum-Progress-87eb8002"

[[members]]
name = "hyperstructure_entity_id"
type = "ID"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = true

[[members]]
name = "amount"
type = "u128"
key = false
