kind = "DojoModel"
class_hash = "0xf29c778e8da6c709dfedd1b4bd853e75c281f43025e7edae3936b157397fda"
original_class_hash = "0xf29c778e8da6c709dfedd1b4bd853e75c281f43025e7edae3936b157397fda"
abi = "manifests/prod/base/abis/models/eternum-BattleConfig-60902e8b.json"
tag = "eternum-BattleConfig"
qualified_path = "eternum::models::config::battle_config"
manifest_name = "eternum-BattleConfig-60902e8b"

[[members]]
name = "config_id"
type = "ID"
key = true

[[members]]
name = "battle_grace_tick_count"
type = "u8"
key = false

[[members]]
name = "battle_delay_seconds"
type = "u64"
key = false
