name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun link
      - name: Install dependencies
        run: bun install
      - name: Run Prettier
        run: bun x prettier --check .
