name: test ammv2

on:
  workflow_call:

jobs:
  test-ammv2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: contracts/l2/ammv2/.tool-versions
          scarb-lock: contracts/l2/ammv2/Scarb.lock
      - uses: ./.github/actions/fetch-cairo-dependencies
        with:
          working-directory: contracts/l2/ammv2
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: contracts/l2/ammv2/.tool-versions
      - run: scarb build
        working-directory: contracts/l2/ammv2
      - run: snforge test
        working-directory: contracts/l2/ammv2
