name: test season pass

on:
  workflow_call:

jobs:
  test-season-pass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: contracts/l2/season_pass/.tool-versions
          scarb-lock: contracts/l2/season_pass/Scarb.lock
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: contracts/l2/season_pass/.tool-versions
      - run: scarb build
        working-directory: contracts/l2/season_pass
      - run: snforge test
        working-directory: contracts/l2/season_pass
