name: test collectibles

on:
  pull_request:
    paths-ignore:
      - "contracts/common/**"
      - "contracts/l3/game/**"
      - "contracts/l2/season_pass/**"
      - "contracts/l2/village_pass/**"
      - "contracts/utils/**"
      - "client/**"
      - "**/manifest.json"
      - "config/**"
      - ".github/**"
      - "pnpm-lock.yaml"

env:
  SCARB_VERSION: v2.9.2

jobs:
  test-collectibles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: contracts/l2/collectibles/.tool-versions
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: contracts/l2/collectibles/.tool-versions
      - run: scarb build
        working-directory: contracts/l2/collectibles
      - run: snforge test
        working-directory: contracts/l2/collectibles
