name: test collectibles

on:
  workflow_call:

jobs:
  test-collectibles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: contracts/l2/collectibles/.tool-versions
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: contracts/l2/collectibles/.tool-versions
      - run: scarb build
        working-directory: contracts/l2/collectibles
      - run: snforge test
        working-directory: contracts/l2/collectibles
