kind = "DojoContract"
class_hash = "0x57dfc52135f972fc5cbcdd2067dfc0a3156c70074710586b1ae99ab81750236"
original_class_hash = "0x57dfc52135f972fc5cbcdd2067dfc0a3156c70074710586b1ae99ab81750236"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-trade_systems-7f6765dd.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-trade_systems"
systems = [
    "accept_order",
    "accept_partial_order",
    "cancel_order",
]
manifest_name = "eternum-trade_systems-7f6765dd"
