kind = "DojoContract"
class_hash = "0x26d85963ab8f1a7ee1478203dd5ef7215b768de8d1194a71b2ccb6013f20c3c"
original_class_hash = "0x26d85963ab8f1a7ee1478203dd5ef7215b768de8d1194a71b2ccb6013f20c3c"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-battle_systems-318da24f.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-battle_systems"
systems = [
    "battle_force_start",
    "battle_join",
    "battle_leave",
    "battle_claim",
]
manifest_name = "eternum-battle_systems-318da24f"
