kind = "DojoContract"
class_hash = "0x14c2245e92aed54625f5f5d719442ed6b715d69d196a119ecab1a21edeaff87"
original_class_hash = "0x14c2245e92aed54625f5f5d719442ed6b715d69d196a119ecab1a21edeaff87"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-dev_resource_systems-9f04ac8a.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-dev_resource_systems"
systems = ["mint"]
manifest_name = "eternum-dev_resource_systems-9f04ac8a"
