kind = "DojoContract"
class_hash = "0x3f239f4e48138e744ea7f1d62f74658c29c248fee550315b18d8043b8cf7f92"
original_class_hash = "0x3f239f4e48138e744ea7f1d62f74658c29c248fee550315b18d8043b8cf7f92"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-liquidity_systems-337d668f.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-liquidity_systems"
systems = ["add"]
manifest_name = "eternum-liquidity_systems-337d668f"
