kind = "DojoContract"
class_hash = "0x723f7c78237d9041a0509b4559b2a80f53222da42d7cbc234bb0f294fb35e6e"
original_class_hash = "0x723f7c78237d9041a0509b4559b2a80f53222da42d7cbc234bb0f294fb35e6e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-donkey_systems-4851519d.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-donkey_systems"
systems = []
manifest_name = "eternum-donkey_systems-4851519d"
