kind = "DojoContract"
class_hash = "0x4141f454f41ab7535443ed8c9a440a657c586d92c313c13fc4045206e8c7bdd"
original_class_hash = "0x4141f454f41ab7535443ed8c9a440a657c586d92c313c13fc4045206e8c7bdd"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-guild_systems-38e127d4.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-guild_systems"
systems = [
    "join_guild",
    "whitelist_player",
    "leave_guild",
    "transfer_guild_ownership",
    "remove_guild_member",
    "remove_player_from_whitelist",
]
manifest_name = "eternum-guild_systems-38e127d4"
