kind = "DojoContract"
class_hash = "0x39f665b33e9f0988d9ecdb5018533b6ba255964a0bac3605462c089cec6b086"
original_class_hash = "0x39f665b33e9f0988d9ecdb5018533b6ba255964a0bac3605462c089cec6b086"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-config_systems-5f8c7cdc.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-config_systems"
systems = [
    "set_world_config",
    "set_season_config",
    "set_quest_config",
    "set_quest_reward_config",
    "set_map_config",
    "set_capacity_config",
    "set_travel_stamina_cost_config",
    "set_weight_config",
    "set_battle_config",
    "set_tick_config",
    "set_stamina_config",
    "set_travel_food_cost_config",
    "set_stamina_refill_config",
    "set_leveling_config",
    "set_production_config",
    "set_speed_config",
    "set_hyperstructure_config",
    "set_bank_config",
    "set_troop_config",
    "set_building_category_pop_config",
    "set_population_config",
    "set_building_general_config",
    "set_building_config",
    "set_mercenaries_config",
    "set_resource_bridge_config",
    "set_resource_bridge_fee_split_config",
    "set_resource_bridge_whitelist_config",
    "set_realm_max_level_config",
    "set_realm_level_config",
    "set_settlement_config",
]
manifest_name = "eternum-config_systems-5f8c7cdc"
