kind = "DojoContract"
class_hash = "0x3e1b39b8ec54856fe7f324de91f1497b059326fa6a8a902465d16d7888fb968"
original_class_hash = "0x3e1b39b8ec54856fe7f324de91f1497b059326fa6a8a902465d16d7888fb968"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-ownership_systems-61566ab9.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-ownership_systems"
systems = ["transfer_ownership"]
manifest_name = "eternum-ownership_systems-61566ab9"
