kind = "DojoContract"
class_hash = "0x41505f85600ae686e9c47e4044d80dfaebb3d65998f613f6a3ff0108e8fa6b5"
original_class_hash = "0x41505f85600ae686e9c47e4044d80dfaebb3d65998f613f6a3ff0108e8fa6b5"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-bank_systems-85030190.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-bank_systems"
systems = [
    "change_owner_amm_fee",
    "change_owner_bridge_fee",
]
manifest_name = "eternum-bank_systems-85030190"
