kind = "DojoContract"
class_hash = "0x7c66c8b6ae4773a0f67ee07afd97b8672f445b261f588b699cda3c3a771119a"
original_class_hash = "0x7c66c8b6ae4773a0f67ee07afd97b8672f445b261f588b699cda3c3a771119a"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-hyperstructure_systems-3660009a.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-hyperstructure_systems"
systems = [
    "contribute_to_construction",
    "set_co_owners",
    "set_access",
    "end_game",
]
manifest_name = "eternum-hyperstructure_systems-3660009a"
