kind = "DojoContract"
class_hash = "0x5472b39def0d27f5b1eb625fa319b1705bff4f8385f180840d10717af39ec75"
original_class_hash = "0x5472b39def0d27f5b1eb625fa319b1705bff4f8385f180840d10717af39ec75"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-realm_systems-2b08f0da.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-realm_systems"
systems = [
    "upgrade_level",
    "quest_claim",
]
manifest_name = "eternum-realm_systems-2b08f0da"
