kind = "DojoContract"
class_hash = "0x63f13e710b56d89c12aa9643cfc96303c09d6f0d7df478f03c073255853a223"
original_class_hash = "0x63f13e710b56d89c12aa9643cfc96303c09d6f0d7df478f03c073255853a223"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-swap_systems-216e8d44.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-swap_systems"
systems = []
manifest_name = "eternum-swap_systems-216e8d44"
