kind = "DojoContract"
class_hash = "0x7dbc0c17379efbf2afd76a8435db8e72e7b7b47e9725c104c42ac7f5e0d2530"
original_class_hash = "0x7dbc0c17379efbf2afd76a8435db8e72e7b7b47e9725c104c42ac7f5e0d2530"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-resource_systems-59b73d5a.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-resource_systems"
systems = [
    "approve",
    "send",
    "pickup",
]
manifest_name = "eternum-resource_systems-59b73d5a"
