kind = "DojoContract"
class_hash = "0x7670d553d597cbcfed65734cd1a8edbc369cf60fb82669017373fbdf80cc7a8"
original_class_hash = "0x7670d553d597cbcfed65734cd1a8edbc369cf60fb82669017373fbdf80cc7a8"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-travel_systems-4ec72d4c.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-travel_systems"
systems = [
    "travel",
    "travel_hex",
]
manifest_name = "eternum-travel_systems-4ec72d4c"
