kind = "DojoContract"
class_hash = "0x2bc82ea3a9baeed31a7dd96fb1b8efc97f5c03afbce3c5db72a0540af22d4e"
original_class_hash = "0x2bc82ea3a9baeed31a7dd96fb1b8efc97f5c03afbce3c5db72a0540af22d4e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/eternum-resource_bridge_systems-5ff4c52e.json"
reads = []
writes = []
init_calldata = []
tag = "eternum-resource_bridge_systems"
systems = [
    "deposit_initial",
    "deposit",
    "start_withdraw",
    "finish_withdraw",
]
manifest_name = "eternum-resource_bridge_systems-5ff4c52e"
