// Ordered routes replace the Command discriminants and dispatch match. Payload types come from production ABIs.
export const commandRoutes = [
  { name: "CreateExplorer", logic: "troops", entrypoint: "create_explorer" },
  { name: "Explore", logic: "movement", entrypoint: "explore" },
  { name: "Battle", logic: "combat", entrypoint: "battle", items: "steal_resources" },
  { name: "Move", logic: "movement", entrypoint: "move_explorer", items: "directions" },
  { name: "ToggleAlternate", logic: "movement", entrypoint: "toggle_alternate" },
  { name: "TransferStructureOwnership", logic: "structures", entrypoint: "transfer_structure_ownership" },
  { name: "LevelUp", logic: "construction", entrypoint: "level_up" },
  { name: "SettleBlitzRoster", logic: "settlement", entrypoint: "settle_blitz_roster", batch: true },
  { name: "ProvisionRealm", logic: "structures", entrypoint: "activate_realm_economy" },
  { name: "CreateReservedHyperstructure", logic: "structures", entrypoint: "create_reserved_hyperstructure" },
  { name: "SettleSeason", logic: "settlement", entrypoint: "settle_season" },
  { name: "SettleVillage", logic: "settlement", entrypoint: "settle_village" },
  { name: "ReceiveVillageArmy", logic: "structures", entrypoint: "receive_village_army" },
  { name: "BurnStructureResources", logic: "resources", entrypoint: "burn_structure_resources", items: "resources" },
  {
    name: "TransferExplorerResources",
    logic: "resources",
    entrypoint: "transfer_explorer_resources",
    items: "resources",
  },
  {
    name: "TransferStructureResourcesToExplorer",
    logic: "resources",
    entrypoint: "transfer_structure_resources_to_explorer",
    items: "resources",
  },
  { name: "OffloadArrival", logic: "resources", entrypoint: "offload_arrival" },
  { name: "SendResources", logic: "resources", entrypoint: "send_resources", items: "resources" },
  {
    name: "TransferExplorerResourcesToStructure",
    logic: "resources",
    entrypoint: "transfer_explorer_resources_to_structure",
    items: "resources",
  },
  { name: "BurnLaborForResourceProduction", logic: "production", entrypoint: "burn_labor_for_resource_production" },
  {
    name: "BurnResourceForResourceProduction",
    logic: "production",
    entrypoint: "burn_resource_for_resource_production",
  },
  { name: "CreateBuilding", logic: "construction", entrypoint: "create_building" },
  { name: "DestroyBuilding", logic: "construction", entrypoint: "destroy_building" },
  { name: "PauseBuildingProduction", logic: "construction", entrypoint: "pause_building_production" },
  { name: "ResumeBuildingProduction", logic: "construction", entrypoint: "resume_building_production" },
  { name: "ContributeBitcoinLabor", logic: "prizes", entrypoint: "contribute_bitcoin_labor" },
  { name: "CloseBitcoinPhase", logic: "prizes", entrypoint: "close_bitcoin_phase" },
  { name: "BindBitcoinPhase", logic: "prizes", entrypoint: "bind_bitcoin_phase" },
  { name: "ClaimBitcoinPhase", logic: "prizes", entrypoint: "claim_bitcoin_phase", items: "mine_ids", batch: true },
  { name: "BattleGuard", logic: "combat", entrypoint: "battle_guard" },
  { name: "CreateTradeOrder", logic: "economy", entrypoint: "create_trade_order" },
  { name: "AcceptTradeOrder", logic: "economy", entrypoint: "accept_trade_order" },
  { name: "CancelTradeOrder", logic: "economy", entrypoint: "cancel_trade_order" },
  { name: "CreateBanks", logic: "economy", entrypoint: "create_banks", items: "." },
  { name: "BuyFromBank", logic: "economy", entrypoint: "buy_from_bank" },
  { name: "SellToBank", logic: "economy", entrypoint: "sell_to_bank" },
  { name: "AddBankLiquidity", logic: "economy", entrypoint: "add_bank_liquidity" },
  { name: "RemoveBankLiquidity", logic: "economy", entrypoint: "remove_bank_liquidity" },
  { name: "InitializeHyperstructure", logic: "economy", entrypoint: "initialize_hyperstructure" },
  { name: "ContributeHyperstructure", logic: "economy", entrypoint: "contribute_hyperstructure", items: "resources" },
  {
    name: "AllocateHyperstructureShares",
    logic: "economy",
    entrypoint: "allocate_hyperstructure_shares",
    items: "shareholders",
  },
  { name: "SetConstructionAccess", logic: "economy", entrypoint: "set_construction_access" },
  { name: "OpenRelicChest", logic: "relics", entrypoint: "open_relic_chest" },
  { name: "ApplyRelic", logic: "relics", entrypoint: "apply_relic" },
  { name: "CloseSeason", logic: "season", entrypoint: "close_season", batch: true },
  { name: "PledgeFaith", logic: "prizes", entrypoint: "pledge_faith" },
  { name: "RemoveFaith", logic: "prizes", entrypoint: "remove_faith" },
  { name: "UpdateWonderOwnership", logic: "prizes", entrypoint: "update_wonder_ownership" },
  { name: "UpdateFaithfulOwnership", logic: "prizes", entrypoint: "update_faithful_ownership" },
  { name: "ClaimWonderPoints", logic: "prizes", entrypoint: "claim_wonder_points" },
  { name: "ClaimPlayerFaithPoints", logic: "prizes", entrypoint: "claim_player_faith_points" },
  { name: "RecordBlitzResults", logic: "prizes", entrypoint: "record_blitz_results", items: "players", batch: true },
  { name: "CraftRelic", logic: "relics", entrypoint: "craft_relic" },
  { name: "CreateGuild", logic: "structures", entrypoint: "create_guild" },
  { name: "JoinGuild", logic: "structures", entrypoint: "join_guild" },
  { name: "LeaveGuild", logic: "structures", entrypoint: "leave_guild" },
  { name: "SetGuildWhitelist", logic: "structures", entrypoint: "set_guild_whitelist" },
  { name: "RemoveGuildMember", logic: "structures", entrypoint: "remove_guild_member" },
  { name: "MarkGameSettled", logic: "season", entrypoint: "mark_game_settled", batch: true },
  { name: "ManageTroops", logic: "troops", entrypoint: "manage_troops" },
  { name: "GuardAttack", logic: "combat", entrypoint: "guard_attack" },
  { name: "Raid", logic: "raid", entrypoint: "raid", items: "steal_resources" },
  { name: "DepositResource", logic: "bridge", entrypoint: "deposit_resource" },
  { name: "WithdrawResource", logic: "bridge", entrypoint: "withdraw_resource" },
  { name: "ProvisionAndUpgradeRealm", logic: "structures", entrypoint: "provision_and_upgrade_realm" },
  { name: "SetEntityName", logic: "structures", entrypoint: "set_entity_name" },
  { name: "EnterDepth", logic: "movement", entrypoint: "enter_depth" },
  { name: "Research", logic: "construction", entrypoint: "research" },
  { name: "ChooseAttribute", logic: "relics", entrypoint: "choose_attribute" },
  { name: "UpgradeBuilding", logic: "construction", entrypoint: "upgrade_building" },
  { name: "InteractSite", logic: "relics", entrypoint: "interact_site" },
];
