// Generated from the compiled Command ABI. Run the native schema generator to update.
import type { BigNumberish } from "starknet";
export interface NativeCommandPayloads {
  CreateExplorer: { readonly structure_id: BigNumberish; readonly category: BigNumberish; readonly tier: BigNumberish; readonly amount: BigNumberish; readonly direction: BigNumberish };
  Explore: { readonly explorer_id: BigNumberish; readonly direction: BigNumberish };
  Battle: { readonly attacker_id: BigNumberish; readonly defender_id: BigNumberish; readonly steal_resources: readonly ({ readonly resource_type: BigNumberish; readonly amount: BigNumberish })[] };
  Move: { readonly explorer_id: BigNumberish; readonly directions: readonly (BigNumberish)[] };
  ToggleAlternate: { readonly explorer_id: BigNumberish; readonly spire_direction: BigNumberish };
  TransferStructureOwnership: { readonly entity_id: BigNumberish; readonly new_owner: BigNumberish };
  SetAddressName: { readonly owned_structure_id: BigNumberish; readonly name: BigNumberish };
  LevelUp: BigNumberish;
  SettleBlitzRoster: undefined;
  ProvisionRealm: BigNumberish;
  CreateReservedHyperstructure: { readonly alt: boolean; readonly x: BigNumberish; readonly y: BigNumberish };
  SettleSeason: { readonly name: BigNumberish; readonly selected_realm: { readonly kind: "Some"; readonly value: BigNumberish } | { readonly kind: "None"; readonly value: undefined } };
  SettleVillage: { readonly pass_id: BigNumberish; readonly connected_realm_entity_id: BigNumberish };
  ReceiveVillageArmy: BigNumberish;
  ApproveResources: { readonly owner_entity_id: BigNumberish; readonly approved_entity_id: BigNumberish; readonly resources: readonly ({ readonly resource_type: BigNumberish; readonly amount: BigNumberish })[] };
  BurnStructureResources: { readonly entity_id: BigNumberish; readonly resources: readonly ({ readonly resource_type: BigNumberish; readonly amount: BigNumberish })[] };
  RegularizeResourceWeights: readonly (BigNumberish)[];
  BurnExplorerResources: { readonly entity_id: BigNumberish; readonly resources: readonly ({ readonly resource_type: BigNumberish; readonly amount: BigNumberish })[] };
  TransferExplorerResources: { readonly from_entity_id: BigNumberish; readonly to_entity_id: BigNumberish; readonly resources: readonly ({ readonly resource_type: BigNumberish; readonly amount: BigNumberish })[] };
  TransferStructureResourcesToExplorer: { readonly from_entity_id: BigNumberish; readonly to_entity_id: BigNumberish; readonly resources: readonly ({ readonly resource_type: BigNumberish; readonly amount: BigNumberish })[] };
  OffloadArrival: { readonly entity_id: BigNumberish; readonly day: BigNumberish; readonly slot: BigNumberish; readonly resource_count: BigNumberish };
  SendResources: { readonly from_entity_id: BigNumberish; readonly to_entity_id: BigNumberish; readonly resources: readonly ({ readonly resource_type: BigNumberish; readonly amount: BigNumberish })[] };
  PickupResources: { readonly from_entity_id: BigNumberish; readonly to_entity_id: BigNumberish; readonly resources: readonly ({ readonly resource_type: BigNumberish; readonly amount: BigNumberish })[] };
  TransferExplorerResourcesToStructure: { readonly from_entity_id: BigNumberish; readonly to_entity_id: BigNumberish; readonly resources: readonly ({ readonly resource_type: BigNumberish; readonly amount: BigNumberish })[] };
  BurnResourceForLaborProduction: { readonly structure_id: BigNumberish; readonly resource_types: readonly (BigNumberish)[]; readonly amounts: readonly (BigNumberish)[] };
  BurnLaborForResourceProduction: { readonly structure_id: BigNumberish; readonly resource_types: readonly (BigNumberish)[]; readonly amounts: readonly (BigNumberish)[] };
  BurnResourceForResourceProduction: { readonly structure_id: BigNumberish; readonly resource_types: readonly (BigNumberish)[]; readonly amounts: readonly (BigNumberish)[] };
  CreateBuilding: { readonly structure_id: BigNumberish; readonly directions: readonly (BigNumberish)[]; readonly category: BigNumberish; readonly use_simple: boolean };
  DestroyBuilding: { readonly structure_id: BigNumberish; readonly coord: { readonly alt: boolean; readonly x: BigNumberish; readonly y: BigNumberish } };
  PauseBuildingProduction: { readonly structure_id: BigNumberish; readonly coord: { readonly alt: boolean; readonly x: BigNumberish; readonly y: BigNumberish } };
  ResumeBuildingProduction: { readonly structure_id: BigNumberish; readonly coord: { readonly alt: boolean; readonly x: BigNumberish; readonly y: BigNumberish } };
  ContributeBitcoinLabor: { readonly structure_id: BigNumberish; readonly amount: BigNumberish };
  CloseBitcoinPhase: BigNumberish;
  BindBitcoinPhase: BigNumberish;
  ClaimBitcoinPhase: { readonly phase: BigNumberish; readonly mine_ids: readonly (BigNumberish)[] };
  BattleGuard: { readonly attacker_id: BigNumberish; readonly defender_id: BigNumberish };
  CreateTradeOrder: { readonly maker_id: BigNumberish; readonly taker_id: BigNumberish; readonly offered_resource: BigNumberish; readonly requested_resource: BigNumberish; readonly offered_per_lot: BigNumberish; readonly requested_per_lot: BigNumberish; readonly lots: BigNumberish; readonly expires_at: BigNumberish };
  AcceptTradeOrder: { readonly trade_id: BigNumberish; readonly taker_id: BigNumberish; readonly lots: BigNumberish };
  CancelTradeOrder: BigNumberish;
  CreateBanks: readonly ({ readonly name: BigNumberish; readonly coord: { readonly alt: boolean; readonly x: BigNumberish; readonly y: BigNumberish } })[];
  BuyFromBank: { readonly bank_id: BigNumberish; readonly structure_id: BigNumberish; readonly resource_type: BigNumberish; readonly amount: BigNumberish };
  SellToBank: { readonly bank_id: BigNumberish; readonly structure_id: BigNumberish; readonly resource_type: BigNumberish; readonly amount: BigNumberish };
  AddBankLiquidity: { readonly bank_id: BigNumberish; readonly structure_id: BigNumberish; readonly resource_type: BigNumberish; readonly resource_amount: BigNumberish; readonly lords_amount: BigNumberish };
  RemoveBankLiquidity: { readonly bank_id: BigNumberish; readonly structure_id: BigNumberish; readonly resource_type: BigNumberish; readonly shares: BigNumberish };
  InitializeHyperstructure: BigNumberish;
  ContributeHyperstructure: { readonly hyperstructure_id: BigNumberish; readonly from_structure_id: BigNumberish; readonly resources: readonly ({ readonly resource_type: BigNumberish; readonly amount: BigNumberish })[] };
  AllocateHyperstructureShares: { readonly hyperstructure_id: BigNumberish; readonly shareholders: readonly ({ readonly player: BigNumberish; readonly bps: BigNumberish })[] };
  SetConstructionAccess: { readonly hyperstructure_id: BigNumberish; readonly access: { readonly kind: "Public"; readonly value: undefined } | { readonly kind: "Private"; readonly value: undefined } | { readonly kind: "GuildOnly"; readonly value: undefined } };
  OpenRelicChest: { readonly explorer_id: BigNumberish; readonly coord: { readonly alt: boolean; readonly x: BigNumberish; readonly y: BigNumberish } };
  ApplyRelic: { readonly entity_id: BigNumberish; readonly relic_id: BigNumberish; readonly recipient: { readonly kind: "Explorer"; readonly value: undefined } | { readonly kind: "StructureProduction"; readonly value: undefined } | { readonly kind: "StructureGuard"; readonly value: undefined } };
  CloseSeason: undefined;
  PledgeFaith: { readonly structure_id: BigNumberish; readonly wonder_id: BigNumberish };
  RemoveFaith: BigNumberish;
  UpdateWonderOwnership: BigNumberish;
  UpdateFaithfulOwnership: BigNumberish;
  ClaimWonderPoints: BigNumberish;
  ClaimPlayerFaithPoints: { readonly player: BigNumberish; readonly wonder_id: BigNumberish };
  SetFaithBlacklist: { readonly wonder_id: BigNumberish; readonly blocked_id: BigNumberish; readonly blocked: boolean };
  FundFaithPrizes: BigNumberish;
  DistributeFaithPrizes: undefined;
  ClaimFaithPrize: { readonly player: BigNumberish; readonly wonder_id: BigNumberish };
  RecordBlitzResults: { readonly start: BigNumberish; readonly players: readonly ({ readonly player: BigNumberish; readonly points: BigNumberish; readonly rank: BigNumberish })[] };
  CraftRelic: BigNumberish;
  CreateGuild: { readonly owned_structure_id: BigNumberish; readonly public: boolean; readonly name: BigNumberish };
  JoinGuild: { readonly owned_structure_id: BigNumberish; readonly guild_id: BigNumberish };
  LeaveGuild: undefined;
  SetGuildWhitelist: { readonly player: BigNumberish; readonly owned_structure_id: BigNumberish; readonly allowed: boolean };
  RemoveGuildMember: BigNumberish;
  MintDevelopmentResources: { readonly entity_id: BigNumberish; readonly resources: readonly ({ readonly resource_type: BigNumberish; readonly amount: BigNumberish })[] };
  MarkGameSettled: undefined;
  ManageTroops: { readonly kind: "RecruitGuard"; readonly value: { readonly guard: { readonly structure_id: BigNumberish; readonly slot: BigNumberish }; readonly category: { readonly kind: "Knight"; readonly value: undefined } | { readonly kind: "Paladin"; readonly value: undefined } | { readonly kind: "Crossbowman"; readonly value: undefined }; readonly tier: { readonly kind: "T1"; readonly value: undefined } | { readonly kind: "T2"; readonly value: undefined } | { readonly kind: "T3"; readonly value: undefined }; readonly amount: BigNumberish } } | { readonly kind: "RemoveGuard"; readonly value: { readonly structure_id: BigNumberish; readonly slot: BigNumberish } } | { readonly kind: "RecruitExplorer"; readonly value: { readonly explorer_id: BigNumberish; readonly amount: BigNumberish } } | { readonly kind: "RemoveExplorer"; readonly value: BigNumberish } | { readonly kind: "Transfer"; readonly value: { readonly source: { readonly kind: "Explorer"; readonly value: BigNumberish } | { readonly kind: "Guard"; readonly value: { readonly structure_id: BigNumberish; readonly slot: BigNumberish } }; readonly target: { readonly kind: "Explorer"; readonly value: BigNumberish } | { readonly kind: "Guard"; readonly value: { readonly structure_id: BigNumberish; readonly slot: BigNumberish } }; readonly amount: BigNumberish } };
  GuardAttack: { readonly guard: { readonly structure_id: BigNumberish; readonly slot: BigNumberish }; readonly explorer_id: BigNumberish };
  Raid: { readonly explorer_id: BigNumberish; readonly structure_id: BigNumberish; readonly steal_resources: readonly ({ readonly resource_type: BigNumberish; readonly amount: BigNumberish })[] };
  DepositResource: { readonly structure_id: BigNumberish; readonly resource_type: BigNumberish; readonly amount: BigNumberish; readonly client_fee_recipient: BigNumberish };
  WithdrawResource: { readonly structure_id: BigNumberish; readonly recipient: BigNumberish; readonly resource_type: BigNumberish; readonly amount: BigNumberish; readonly client_fee_recipient: BigNumberish };
  ProvisionAndUpgradeRealm: BigNumberish;
  SetEntityName: { readonly entity_id: BigNumberish; readonly name: BigNumberish };
}
export type NativeCommand = { [K in keyof NativeCommandPayloads]: { kind: K; value: NativeCommandPayloads[K] } }[keyof NativeCommandPayloads];
